// Builds ../waiting-on-client-nudge.yml from the PowerShell in this folder.
// Each step's script is: the _shared/psa.ps1 block, the src/psa-extra.ps1 block, the src/common.ps1 block,
// then the step's own file. This script fills the src/ blocks; _shared/inject.js fills the _shared block.
// Usage: node build.js          write the .yml
//        node build.js --check  exit 1 if the .yml is out of date
// Edit the .ps1 files here, never the script inside the .yml.
const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync } = require('child_process');
let y;
try { y = require('js-yaml'); } catch { y = require(process.env.JS_YAML_PATH); }

const NAME = 'Waiting-on-Client Nudge';
const FILE = 'waiting-on-client-nudge.yml';
const STEPS = [
  { id: 'node-find', name: 'Find tickets in Waiting', src: '1-find.ps1', testInput: '{"preview": true}' },
  { id: 'node-remind', name: 'Send reminders', src: '2-remind.ps1' },
  { id: 'node-close', name: 'Close with notice', src: '3-close.ps1' },
  { id: 'node-notes', name: 'Internal note per action', src: '4-notes.ps1' },
];
const SRC_BLOCKS = ['psa-extra.ps1', 'common.ps1'];

const here = __dirname;
const root = path.join(here, '..');
const read = (p) => fs.readFileSync(p, 'utf8').replace(/\r\n/g, '\n').trimEnd();
const check = process.argv.includes('--check');

// --dump: print the shipped .yml's PowerShell steps as JSON ([{ id, script }]) for test.ps1.
if (process.argv.includes('--dump')) {
  const wf0 = y.load(fs.readFileSync(path.join(root, FILE), 'utf8'));
  const steps = wf0.definition.activities.filter((a) => a.type === 'powershell-script').map((a) => ({ id: a.id, script: a.properties.script }));
  process.stdout.write(JSON.stringify(steps));
  process.exit(0);
}

function stepScript(step) {
  const lines = [
    '# >>> _shared/psa.ps1 (generated by _shared/inject.js; edit the source, not this block)',
    '# <<< _shared/psa.ps1',
  ];
  for (const b of SRC_BLOCKS) {
    lines.push(`# >>> src/${b} (generated by src/build.js; edit the source, not this block)`, ...read(path.join(here, b)).split('\n'), `# <<< src/${b}`);
  }
  lines.push(...read(path.join(here, step.src)).split('\n'));
  const bad = lines.findIndex((l) => /[ \t]+$/.test(l) || l.includes('\t'));
  if (bad >= 0) throw new Error(`${step.src}: trailing whitespace or a tab in the assembled script (line ${bad + 1}); YAML would quote the block`);
  return lines.join('\n') + '\n';
}

const activities = [{ id: 'start', name: 'Start', type: 'start', position: { x: 100, y: 120 }, properties: { webhookEnabled: false } }];
STEPS.forEach((s, i) => {
  const props = { script: stepScript(s), timeoutSeconds: 900, retryCount: 0, parameters: [], aiExtensions: [] };
  if (s.testInput) props.testInput = s.testInput;
  activities.push({ id: s.id, name: s.name, type: 'powershell-script', position: { x: 280 + i * 180, y: 120 }, properties: props });
});
activities.push({ id: 'end', name: 'End', type: 'end', position: { x: 280 + STEPS.length * 180, y: 120 } });
const ids = ['start', ...STEPS.map((s) => s.id), 'end'];
const connections = ids.slice(1).map((t, i) => ({ source: ids[i], target: t, sourceHandle: null }));
const wf = { automationsWorkflow: 1, name: NAME, definition: { schemaVersion: 1, activities, connections, startActivityId: 'start' } };

// Write to a temp folder, let inject.js fill the _shared block there, then compare or copy.
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'wocn-'));
const tmpFile = path.join(tmp, FILE);
fs.writeFileSync(tmpFile, y.dump(wf, { lineWidth: -1, noRefs: true }));
execFileSync(process.execPath, [path.join(root, '..', '_shared', 'inject.js'), tmp], { stdio: ['ignore', 'ignore', 'inherit'] });
const next = fs.readFileSync(tmpFile, 'utf8');
fs.rmSync(tmp, { recursive: true, force: true });
const parsed = y.load(next);
if (parsed.definition.activities.length !== STEPS.length + 2) throw new Error('unexpected activity count after parsing');
for (const a of parsed.definition.activities.filter((x) => x.type === 'powershell-script')) {
  if (!a.properties.script.includes('function Connect-Psa')) throw new Error(`${a.id}: _shared/psa.ps1 was not injected`);
}

const target = path.join(root, FILE);
const was = fs.existsSync(target) ? fs.readFileSync(target, 'utf8').replace(/\r\n/g, '\n') : '';
if (check) {
  console.log(`${FILE}: ${next === was ? 'current' : 'OUT OF DATE (run node build.js)'}`);
  process.exit(next === was ? 0 : 1);
}
fs.writeFileSync(target, next);
console.log(`${FILE}: ${next === was ? 'current' : 'written'} (${next.length} bytes, ${STEPS.length} steps)`);
