# === STEP: Post QBR-prep card ===
# Edit this file, then run: node qbr-data-pack/src/build.js
# The only write in this workflow: one internal CloudRadial Planner card on this company's board, subject
# "QBR prep: <quarter>", stable key qbr-data-pack:<year>-Q<n>. A re-run in the same quarter updates that card
# instead of adding another. With preview: true it works out the card and writes nothing.
# The card only holds this one company's numbers, gathered by the earlier steps.
# Secrets: CloudRadial-BaseUrl, CloudRadial-PublicKey, CloudRadial-PrivateKey.
# >>> _shared/cloudradial.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/cloudradial.ps1

$in = Get-NodeInput
function Get-QbrProp { param($o, [string]$n) if ($null -eq $o) { return $null }; if ($o -is [System.Collections.IDictionary]) { if ($o.Contains($n)) { return $o[$n] }; return $null }; $p = $o.PSObject.Properties[$n]; if ($p) { return $p.Value }; return $null }
function Enc { param($s) return [System.Net.WebUtility]::HtmlEncode([string]$s) }
$ci = [System.Globalization.CultureInfo]::InvariantCulture
$warnings = New-Object System.Collections.ArrayList
foreach ($w in @(Get-QbrProp $in 'warnings')) { if ($w) { $null = $warnings.Add([string]$w) } }

function Stop-QbrCard {
    param([string]$Why)
    Set-NodeOutput ([ordered]@{ status = 'error'; message = $Why; public_note = ''; internal_note = $Why; ticket_id = ''; actions = @(); warnings = @($warnings) })
    throw $Why
}
# "1 device" / "3 devices"
function Get-QbrCount { param($n, [string]$One, [string]$Many) if ([int]$n -eq 1) { return "1 $One" }; return "$n $Many" }
function Get-QbrNum { param($v) if ($null -eq $v -or [string]$v -eq '') { return 'not available' }; return [string]$v }
function ConvertTo-QbrUtc { param($v) if ($null -eq $v) { return $null }; if ($v -is [datetime]) { if ($v.Kind -eq [DateTimeKind]::Unspecified) { return [datetime]::SpecifyKind($v, [DateTimeKind]::Utc) }; return $v.ToUniversalTime() }; if ($v -is [datetimeoffset]) { return $v.UtcDateTime }; $d = [datetime]::MinValue; if ([string]$v -and [datetime]::TryParse([string]$v, [System.Globalization.CultureInfo]::InvariantCulture, [System.Globalization.DateTimeStyles]'AdjustToUniversal,AssumeUniversal', [ref]$d)) { return $d }; return $null }
function Get-QbrDay { param($v) $d = ConvertTo-QbrUtc $v; if ($null -ne $d) { return $d.ToString('d MMM yyyy', $ci) }; return [string]$v }
function Add-QbrTable {
    param($Sb, [string]$Caption, [string[]]$Head, [object[]]$Rows)
    $null = $Sb.Append("<p><strong>$(Enc $Caption)</strong></p><table><thead><tr>")
    foreach ($h in $Head) { $null = $Sb.Append("<th>$(Enc $h)</th>") }
    $null = $Sb.Append('</tr></thead><tbody>')
    foreach ($r in $Rows) { $null = $Sb.Append('<tr>'); foreach ($c in @($r)) { $null = $Sb.Append("<td>$(Enc $c)</td>") }; $null = $Sb.Append('</tr>') }
    $null = $Sb.Append('</tbody></table>')
}

$companyId = [int](Get-QbrProp $in 'companyId')
$companyName = [string](Get-QbrProp $in 'companyName')
if ($companyId -le 0) { Stop-QbrCard 'The earlier steps did not say which company this is for, so no card was written.' }
$preview = [bool](Get-QbrProp $in 'preview')
$days = [int](Get-QbrProp $in 'quarter_days'); if ($days -le 0) { $days = 90 }
$quarterLabel = [string](Get-QbrProp $in 'quarterLabel')
$CardKey = "qbr-data-pack:$([string](Get-QbrProp $in 'quarterKey'))"
$CardSubject = "QBR prep: $quarterLabel"
$dev = Get-QbrProp $in 'devices'
$tix = Get-QbrProp $in 'tickets'
$lic = Get-QbrProp $in 'licences'
$dom = Get-QbrProp $in 'domains'
$cert = Get-QbrProp $in 'certificates'
$plan = Get-QbrProp $in 'planner'
$runAtDate = ConvertTo-QbrUtc (Get-QbrProp $in 'runAt'); if ($null -eq $runAtDate) { $runAtDate = (Get-Date).ToUniversalTime() }
$runAt = $runAtDate.ToString('yyyy-MM-dd HH:mm', $ci) + ' UTC'
$to = Get-QbrDay $runAtDate
$from = if ($null -ne $tix) { Get-QbrDay (Get-QbrProp $tix 'currentFrom') } else { '' }
if (-not $from) { $from = $runAtDate.AddDays(-$days).ToString('d MMM yyyy', $ci) }

$sb = New-Object System.Text.StringBuilder
$headline = New-Object System.Collections.ArrayList
$null = $sb.Append("<p>This CloudRadial Planner card gathers the numbers for $(Enc $companyName)'s quarterly business review ($(Enc $quarterLabel)). It covers the $days days from $(Enc $from) to $(Enc $to). Nothing was changed in any system to build it.</p>")

# ---- devices ----
$devSentence = ''
if ($null -ne $dev -and [bool](Get-QbrProp $dev 'available')) {
    $total = [int](Get-QbrProp $dev 'total')
    if ($total -eq 0) { $devSentence = "No managed devices are recorded for $(Enc $companyName) in CloudRadial." }
    else {
        $age = Get-QbrProp $dev 'age'; $war = Get-QbrProp $dev 'warranty'; $os = Get-QbrProp $dev 'os'
        $old = [int](Get-QbrProp $age '5 to 7 years') + [int](Get-QbrProp $age '7 years or more'); $veryOld = [int](Get-QbrProp $age '7 years or more')
        $parts = @("$(Enc $companyName) has $(Get-QbrCount $total 'managed device' 'managed devices'): $(Get-QbrCount (Get-QbrProp $dev 'workstations') 'workstation' 'workstations'), $(Get-QbrCount (Get-QbrProp $dev 'servers') 'server' 'servers') and $(Get-QbrCount (Get-QbrProp $dev 'virtual') 'virtual machine' 'virtual machines').")
        if ($old) { $parts += "$(Get-QbrCount $old 'device is' 'devices are') 5 or more years old$(if ($veryOld) { ", $veryOld of them 7 or more" })." }
        $exp = [int](Get-QbrProp $war 'expired'); $soon = [int](Get-QbrProp $war 'expiring')
        if ($exp -or $soon) { $parts += "The warranty has expired on $(Get-QbrCount $exp 'device' 'devices'), and $(Get-QbrCount $soon 'more ends' 'more end') within 90 days." }
        $uns = [int](Get-QbrProp $os 'unsupported'); if ($uns) { $parts += "$(Get-QbrCount $uns 'device runs' 'devices run') an operating system that no longer gets security updates." }
        $rep = [int](Get-QbrProp $dev 'replace'); if ($rep) { $parts += "By the Endpoint LifeCycle Manager rules, $(Get-QbrCount $rep 'workstation is' 'workstations are') due for replacement." }
        $stale = [int](Get-QbrProp $dev 'stale'); if ($stale) { $parts += "$(Get-QbrCount $stale 'device has' 'devices have') not checked in for 30 days." }
        $devSentence = $parts -join ' '
        $null = $headline.Add((Get-QbrCount $total 'device' 'devices') + $(if ($old) { " ($old aged 5 years or more)" } else { '' }))
    }
}
else { $devSentence = "Device data was not available: $(Enc (Get-QbrProp $dev 'reason'))" }
$null = $sb.Append("<p>$devSentence</p>")

# ---- tickets ----
function Get-QbrTrend {
    param($cur, $prev)
    if ($null -eq $prev -or $null -eq $cur) { return '' }
    $c = [int]$cur; $p = [int]$prev
    if ($p -eq 0) { if ($c -eq 0) { return ', the same as the previous period' }; return ', compared with none in the previous period' }
    if ($c -eq $p) { return ", the same as the $p in the previous period" }
    $pct = [int][Math]::Round([Math]::Abs($c - $p) * 100.0 / $p)
    return ", $(if ($c -gt $p) { 'up' } else { 'down' }) $pct% from $p in the previous period"
}
$tixAvailable = ($null -ne $tix -and [bool](Get-QbrProp $tix 'available'))
if ($tixAvailable) {
    $oc = Get-QbrProp $tix 'openedCurrent'; $op = Get-QbrProp $tix 'openedPrevious'; $cc = Get-QbrProp $tix 'closedCurrent'; $cp = Get-QbrProp $tix 'closedPrevious'; $on = Get-QbrProp $tix 'openNow'
    $label = [string](Get-QbrProp $tix 'categoryLabel'); $cats = @(Get-QbrProp $tix 'categories' | Where-Object { $null -ne $_ })
    $s = "In $(Enc (Get-QbrProp $tix 'psaName')), $(if ($null -ne $oc) { Get-QbrCount $oc 'ticket was' 'tickets were' } else { 'the number of tickets' }) opened in the last $days days$(Get-QbrTrend $oc $op)"
    $s += ", and $(if ($null -ne $cc) { "$cc were closed" } else { 'the closed count is not available' })$(Get-QbrTrend $cc $cp)."
    if ($null -ne $on) { $s += " $(Get-QbrCount $on 'ticket is' 'tickets are') open now." }
    if ($cats.Count) { $s += " The most common $(Enc $label) was $(Enc (Get-QbrProp $cats[0] 'name')) ($(Get-QbrCount (Get-QbrProp $cats[0] 'count') 'ticket' 'tickets'))." }
    $null = $sb.Append("<p>$s</p>")
    if ($null -ne $oc) { $null = $headline.Add("$(Get-QbrCount $oc 'ticket' 'tickets') opened in $days days") }
}
else { $why = [string](Get-QbrProp $tix 'reason'); if (-not $why) { $why = 'Ticket trends from the PSA are not available.' }; $null = $sb.Append("<p>$(Enc $why)</p>") }

# ---- licences ----
$licAvailable = ($null -ne $lic -and [bool](Get-QbrProp $lic 'available'))
$skus = @()
if ($licAvailable) {
    $skus = @(Get-QbrProp $lic 'skus' | Where-Object { $null -ne $_ })
    $pur = [int](Get-QbrProp $lic 'purchased'); $asg = [int](Get-QbrProp $lic 'assigned'); $un = [Math]::Max(0, $pur - $asg)
    if (-not $skus.Count) { $null = $sb.Append('<p>Microsoft 365 shows no paid licences for this tenant.</p>') }
    else {
        $s = "Microsoft 365 has $(Get-QbrCount $pur 'paid licence' 'paid licences') across $(Get-QbrCount $skus.Count 'subscription' 'subscriptions'), with $asg assigned and $un unassigned."
        $most = @($skus | Sort-Object @{ Expression = { [int](Get-QbrProp $_ 'unassigned') }; Descending = $true }) | Select-Object -First 1
        if ([int](Get-QbrProp $most 'unassigned') -gt 0) { $s += " The most unassigned is $(Enc (Get-QbrProp $most 'name')), with $(Get-QbrProp $most 'unassigned') of $(Get-QbrProp $most 'purchased') not in use." }
        $null = $sb.Append("<p>$s</p>")
        if ($un) { $null = $headline.Add("$(Get-QbrCount $un 'unassigned licence' 'unassigned licences')") }
    }
}
else { $why = [string](Get-QbrProp $lic 'reason'); if (-not $why) { $why = 'Microsoft 365 licence usage is not included.' }; $null = $sb.Append("<p>$(Enc $why)</p>") }

# ---- domains and certificates ----
$domItems = @(); $certItems = @()
$expParts = @()
if ($null -ne $dom -and [bool](Get-QbrProp $dom 'available')) {
    $domItems = @(Get-QbrProp $dom 'items' | Where-Object { $null -ne $_ })
    $expParts += $(if ($domItems.Count) { "$(Get-QbrCount $domItems.Count 'domain has' 'domains have') expired or will expire within 60 days" } else { 'no domains expire within 60 days' })
}
else { $expParts += 'domain expiry dates were not available' }
if ($null -ne $cert -and [bool](Get-QbrProp $cert 'available')) {
    $certItems = @(Get-QbrProp $cert 'items' | Where-Object { $null -ne $_ })
    $expParts += $(if ($certItems.Count) { "$(Get-QbrCount $certItems.Count 'certificate has' 'certificates have') expired or will expire within 30 days" } else { 'no certificates expire within 30 days' })
}
else { $expParts += 'certificate expiry dates were not available' }
$es = ($expParts -join ', and ')
$null = $sb.Append("<p>$($es.Substring(0, 1).ToUpperInvariant())$($es.Substring(1)).")
if ($null -ne $plan -and [bool](Get-QbrProp $plan 'available')) { $po = [int](Get-QbrProp $plan 'open'); $null = $sb.Append(" There $(if ($po -eq 1) { 'is 1 other open card' } else { "are $po other open cards" }) on this Planner board.") }
$null = $sb.Append('</p>')
if ($domItems.Count + $certItems.Count) { $null = $headline.Add("$(Get-QbrCount ($domItems.Count + $certItems.Count) 'domain or certificate' 'domains or certificates') expiring soon") }

# ---- tables ----
if ($null -ne $dev -and [bool](Get-QbrProp $dev 'available') -and [int](Get-QbrProp $dev 'total') -gt 0) {
    $age = Get-QbrProp $dev 'age'; $war = Get-QbrProp $dev 'warranty'; $os = Get-QbrProp $dev 'os'
    $rows = @(foreach ($k in @('Under 3 years', '3 to 5 years', '5 to 7 years', '7 years or more', 'Unknown')) { , @($k, [string][int](Get-QbrProp $age $k)) })
    Add-QbrTable $sb 'Physical devices by age' @('Age', 'Devices') $rows
    if ([int](Get-QbrProp $dev 'ageEstimated')) { $null = $sb.Append("<p>$(Get-QbrCount (Get-QbrProp $dev 'ageEstimated') 'age is' 'ages are') estimated from the BIOS or processor date.</p>") }
    $rows = @(foreach ($k in @(@('Expired', 'expired'), @('Ends within 90 days', 'expiring'), @('Active', 'active'), @('No date on file', 'unknown'))) { , @($k[0], [string][int](Get-QbrProp $war $k[1])) })
    Add-QbrTable $sb 'Warranty (physical devices)' @('Warranty', 'Devices') $rows
    $rows = @(foreach ($k in @(@('Supported', 'supported'), @('No longer gets security updates', 'unsupported'), @('Version unknown', 'unknown'), @('Not Windows or macOS', 'other'))) { , @($k[0], [string][int](Get-QbrProp $os $k[1])) })
    Add-QbrTable $sb 'Operating system' @('Support', 'Devices') $rows
    $soonList = @(Get-QbrProp $dev 'warrantySoon' | Where-Object { $null -ne $_ })
    if ($soonList.Count) {
        Add-QbrTable $sb 'Warranties ending within 90 days' @('Device', 'Warranty ends') @($soonList | Select-Object -First 10 | ForEach-Object { , @([string](Get-QbrProp $_ 'name'), [string](Get-QbrProp $_ 'ends')) })
        if ($soonList.Count -gt 10) { $null = $sb.Append("<p>$($soonList.Count - 10) more are in the workflow run output.</p>") }
    }
}
if ($tixAvailable) {
    $rows = @(@(, @('Opened', (Get-QbrNum $oc), (Get-QbrNum $op))) + @(, @('Closed', (Get-QbrNum $cc), (Get-QbrNum $cp))) + @(, @('Open now', (Get-QbrNum $on), '')))
    Add-QbrTable $sb 'Tickets' @('Measure', "Last $days days", "Previous $days days") $rows
    if ($cats.Count) {
        $lbl = [string](Get-QbrProp $tix 'categoryLabel')
        Add-QbrTable $sb "Tickets opened this period, top 5 by $lbl" @(($lbl.Substring(0, 1).ToUpperInvariant() + $lbl.Substring(1)), 'Tickets') @($cats | ForEach-Object { , @([string](Get-QbrProp $_ 'name'), [string](Get-QbrProp $_ 'count')) })
    }
    foreach ($n in @(Get-QbrProp $tix 'notes' | Where-Object { $_ })) { $null = $sb.Append("<p>$(Enc $n)</p>") }
}
if ($licAvailable -and $skus.Count) {
    Add-QbrTable $sb 'Microsoft 365 licences' @('Licence', 'Purchased', 'Assigned', 'Unassigned') @($skus | Select-Object -First 15 | ForEach-Object { , @([string](Get-QbrProp $_ 'name'), [string](Get-QbrProp $_ 'purchased'), [string](Get-QbrProp $_ 'assigned'), [string](Get-QbrProp $_ 'unassigned')) })
    if ($skus.Count -gt 15) { $null = $sb.Append("<p>$($skus.Count - 15) more subscriptions are in the workflow run output.</p>") }
}
if ($domItems.Count + $certItems.Count) {
    $rows = @(@($domItems | ForEach-Object { , @('Domain', [string](Get-QbrProp $_ 'name'), [string](Get-QbrProp $_ 'expires'), $(if ([int](Get-QbrProp $_ 'daysLeft') -lt 0) { 'Expired' } else { [string](Get-QbrProp $_ 'daysLeft') })) }) + @($certItems | ForEach-Object { , @('Certificate', [string](Get-QbrProp $_ 'name'), [string](Get-QbrProp $_ 'expires'), $(if ([int](Get-QbrProp $_ 'daysLeft') -lt 0) { 'Expired' } else { [string](Get-QbrProp $_ 'daysLeft') })) }))
    Add-QbrTable $sb 'Expiring domains and certificates' @('Type', 'Name', 'Expires', 'Days left') $rows
}
# Section reasons are already said in their own paragraph; any other warning goes at the end as a note.
$shown = @(foreach ($sec in @($dev, $tix, $lic, $dom, $cert, $plan)) { [string](Get-QbrProp $sec 'reason') })
$cardNotes = @($warnings | Where-Object { $_ -and $shown -notcontains $_ })
foreach ($w in $cardNotes) { $null = $sb.Append("<p>Note: $(Enc $w)</p>") }
$null = $sb.Append("<p>This card is prepared by the QBR Data Pack automation and updated in place if it runs again this quarter.</p>")

$summary = "Numbers for the $quarterLabel review: $(if ($headline.Count) { ($headline -join ', ') } else { 'see the card for details' })."
$psaLine = if ($tixAvailable) { "$([string](Get-QbrProp $tix 'psaName')) company $([string](Get-QbrProp $tix 'psaCompanyId')) (matched by $([string](Get-QbrProp $tix 'matchedBy')))" } else { 'not used' }
$m365Line = if ($licAvailable) { "tenant $([string](Get-QbrProp $lic 'tenantId')) (matched by $([string](Get-QbrProp $lic 'matchedBy')))" } else { 'not used' }
$internal = "Internal: CloudRadial company $companyId (chosen by $([string](Get-QbrProp $in 'companyVia'))). PSA: $psaLine. Microsoft 365: $m365Line. Gathered $runAt over $days days. Marker: $CardKey."

# ---- the card ----
try { $null = Connect-Cr } catch { Stop-QbrCard ([string]$_.Exception.Message) }
$cards = @()
try { $cards = @(Get-CrAll "/v2/odata/product?`$filter=companyId eq $companyId" | Where-Object { $null -ne $_ -and [int](Get-QbrProp $_ 'companyId') -eq $companyId }) }
catch { Stop-QbrCard "Couldn't read the Planner cards for $($companyName): $($_.Exception.Message)" }
$fields = [ordered]@{ body = $sb.ToString(); summary = $summary; notes = $internal; status = 0; priority = 0 }
$r = $null
try { $r = Set-CrPlannerCard -CompanyId $companyId -Subject $CardSubject -Key $CardKey -Existing $cards -Fields $fields -Preview:$preview }
catch { Stop-QbrCard "Couldn't write the Planner card for $($companyName): $($_.Exception.Message)" }
if ($r.optionalFieldsDropped) { $null = $warnings.Add('This portal did not accept the internal notes field, so the card was written without it.') }

$verb = switch ($r.action) { 'created' { 'added to' } 'updated' { 'updated on' } 'would-create' { 'would be added to' } default { 'would be updated on' } }
$msg = if ($preview) { "Preview only: the CloudRadial Planner card '$CardSubject' $verb $companyName's board when this runs without preview. $summary Nothing was changed." }
else { "The CloudRadial Planner card '$CardSubject' was $verb $companyName's board for the vCIO. $summary Nothing else was changed." }

Set-NodeOutput ([ordered]@{
        status        = $(if ($preview) { 'pending_confirmation' } else { 'success' })
        message       = $msg
        public_note   = ''
        internal_note = $internal
        ticket_id     = ''
        actions       = @("Planner card $($r.action)")
        warnings      = @($warnings)
        companyId     = $companyId
        companyName   = $companyName
        quarterLabel  = $quarterLabel
        cardAction    = $r.action
        productId     = [string]$r.productId
        cardSubject   = $CardSubject
        cardBody      = $sb.ToString()
        devices       = $dev
        tickets       = $tix
        licences      = $lic
        domains       = $dom
        certificates  = $cert
        planner       = $plan
    })
