# === STEP: Read CloudRadial data ===
# Edit this file, then run: node qbr-data-pack/src/build.js
# Read-only. Works out which CloudRadial company this run is for, then reads that company's endpoints,
# Planner cards, domains and certificates. Device age, warranty and operating system use the same rules as
# Endpoint LifeCycle Manager (endpoint-lifecycle-manager/src/elm.ps1).
# Every list is filtered to the one company, and filtered again here, so no other client's data is carried on.
# Secrets: CloudRadial-BaseUrl, CloudRadial-PublicKey, CloudRadial-PrivateKey, optional CloudRadial-CompanyId.
# >>> _shared/cloudradial.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/cloudradial.ps1

$in = Get-NodeInput
function Get-QbrProp { param($o, [string]$n) if ($null -eq $o) { return $null }; if ($o -is [System.Collections.IDictionary]) { if ($o.Contains($n)) { return $o[$n] }; return $null }; $p = $o.PSObject.Properties[$n]; if ($p) { return $p.Value }; return $null }
function Copy-QbrInput { param($o) $h = [ordered]@{}; if ($o -is [System.Collections.IDictionary]) { foreach ($k in $o.Keys) { $h[[string]$k] = $o[$k] } } elseif ($null -ne $o) { foreach ($p in $o.PSObject.Properties) { $h[$p.Name] = $p.Value } }; return $h }
$out = Copy-QbrInput $in
$warnings = New-Object System.Collections.ArrayList
foreach ($w in @(Get-QbrProp $in 'warnings')) { if ($w) { $null = $warnings.Add([string]$w) } }

function Stop-QbrCr {
    param([string]$Why)
    Set-NodeOutput ([ordered]@{ status = 'error'; message = $Why; public_note = ''; internal_note = $Why; ticket_id = ''; actions = @(); warnings = @($warnings) })
    throw $Why
}

$ci = [System.Globalization.CultureInfo]::InvariantCulture
$runDate = (Get-Date).ToUniversalTime()
function ConvertTo-QbrUtc { param($v) if ($null -eq $v) { return $null }; if ($v -is [datetime]) { if ($v.Kind -eq [DateTimeKind]::Unspecified) { return [datetime]::SpecifyKind($v, [DateTimeKind]::Utc) }; return $v.ToUniversalTime() }; if ($v -is [datetimeoffset]) { return $v.UtcDateTime }; $d = [datetime]::MinValue; if ([string]$v -and [datetime]::TryParse([string]$v, [System.Globalization.CultureInfo]::InvariantCulture, [System.Globalization.DateTimeStyles]'AdjustToUniversal,AssumeUniversal', [ref]$d)) { return $d }; return $null }
$tmp = ConvertTo-QbrUtc (Get-QbrProp $in 'runAt'); if ($null -ne $tmp) { $runDate = $tmp }
function ConvertTo-QbrDate { param($v) $d = [datetime]::MinValue; if ($null -ne $v -and [string]$v -and [datetime]::TryParse([string]$v, $ci, [System.Globalization.DateTimeStyles]'AdjustToUniversal,AssumeUniversal', [ref]$d)) { if ($d.Year -gt 1900) { return $d } }; return $null }
function Format-QbrDate { param([datetime]$d) return $d.ToString('d MMM yyyy', $ci) }

try { $null = Connect-Cr } catch { Stop-QbrCr ([string]$_.Exception.Message) }

# ---- which company: the run's company_id, then the CloudRadial-CompanyId secret ----
$companyId = [int](Get-QbrProp $in 'company_id')
$how = 'company_id input'
if ($companyId -le 0) {
    $sec = [string](Get-CrSecret 'CloudRadial-CompanyId')
    if ($sec.Trim() -match '^\d+$' -and [int]$sec.Trim() -gt 0) { $companyId = [int]$sec.Trim(); $how = 'CloudRadial-CompanyId secret' }
}
if ($companyId -le 0) {
    $why = 'No company was given. Set company_id on the run, or add the CloudRadial-CompanyId secret to this runner''s Key Vault.'
    Set-NodeOutput ([ordered]@{ status = 'rejected'; message = $why; public_note = ''; internal_note = $why; ticket_id = ''; actions = @(); warnings = @($warnings) })
    throw $why
}
$company = $null
try { $company = @(Get-CrAll "/v2/odata/company?`$filter=companyId eq $companyId") | Where-Object { [int](Get-QbrProp $_ 'companyId') -eq $companyId } | Select-Object -First 1 }
catch { Stop-QbrCr "Couldn't read CloudRadial company $($companyId): $($_.Exception.Message)" }
if ($null -eq $company) { Stop-QbrCr "CloudRadial company $companyId (from the $how) was not found. Check the company number and run again." }
$companyName = [string](Get-QbrProp $company 'name'); if (-not $companyName) { $companyName = "company $companyId" }
$out.companyId = $companyId
$out.companyName = $companyName
$out.companyVia = $how
$out.psaKey = [string](Get-QbrProp $company 'psaKey')
$out.psaIdentifier = [string](Get-QbrProp $company 'psaIdentifier')
$tenantFields = @('tenantId', 'companyTenantId', 'officeTenantId', 'm365TenantId', 'azureTenantId', 'microsoftTenantId')
$coTenant = ''; foreach ($f in $tenantFields) { $v = [string](Get-QbrProp $company $f); if ($v -match '^[0-9a-fA-F-]{36}$') { $coTenant = $v.ToLowerInvariant(); break } }
$out.companyTenantId = $coTenant

# ---- device rules (same as Endpoint LifeCycle Manager) ----
function Get-QbrAge {
    param($ep)
    foreach ($f in @('manufacturedDate', 'biosDate', 'cpuDate')) { $d = ConvertTo-QbrDate (Get-QbrProp $ep $f); if ($d) { return @{ years = [math]::Round(($runDate - $d).TotalDays / 365.25, 1); estimated = ($f -ne 'manufacturedDate') } } }
    return $null
}
function Get-QbrWarranty {
    param($ep)
    $d = ConvertTo-QbrDate (Get-QbrProp $ep 'expirationDate')
    if (-not $d) { return @{ status = 'unknown'; date = $null } }
    if ($d -lt $runDate) { return @{ status = 'expired'; date = $d } }
    if ($d -le $runDate.AddDays(90)) { return @{ status = 'expiring'; date = $d } }
    return @{ status = 'active'; date = $d }
}
function Get-QbrOsType { param([string]$os) if ($os -match '(?i)windows') { 'windows' } elseif ($os -match '(?i)mac\s?os|os x') { 'macos' } else { 'other' } }
function Get-QbrOsSupport {
    param([string]$os, [string]$type)
    if ($type -eq 'windows') { if ($os -match '(?i)windows\s*11') { return 'supported' }; if ($os -match '(?i)windows\s*(10|8|7|xp|vista)') { return 'unsupported' }; return 'unknown' }
    if ($type -eq 'macos') { if ($os -match '(?i)mac\s?os[^\d]*(\d+)') { if ([int]$Matches[1] -ge 14) { return 'supported' }; return 'unsupported' }; return 'unknown' }
    return 'other'
}
function Get-QbrRamGb { param($ep) $b = 0.0; if ([double]::TryParse([string](Get-QbrProp $ep 'memory'), [System.Globalization.NumberStyles]::Float, $ci, [ref]$b) -and $b -gt 0) { return [math]::Round($b / 1073741824, 1) }; return $null }

# ---- endpoints ----
$dev = [ordered]@{
    available = $true; reason = ''; total = 0; workstations = 0; servers = 0; virtual = 0
    age = [ordered]@{ 'Under 3 years' = 0; '3 to 5 years' = 0; '5 to 7 years' = 0; '7 years or more' = 0; 'Unknown' = 0 }
    ageEstimated = 0
    warranty = [ordered]@{ expired = 0; expiring = 0; active = 0; unknown = 0 }
    os = [ordered]@{ supported = 0; unsupported = 0; unknown = 0; other = 0 }
    replace = 0; stale = 0; warrantySoon = @()
}
try {
    $eps = @(Get-CrAll "/v2/odata/endpoint?`$filter=companyId eq $companyId" | Where-Object { $null -ne $_ -and [int](Get-QbrProp $_ 'companyId') -eq $companyId })
    $soon = New-Object System.Collections.ArrayList
    foreach ($ep in $eps) {
        $dev.total++
        $isServer = [bool](Get-QbrProp $ep 'isServer'); $isVirtual = [bool](Get-QbrProp $ep 'isVirtual')
        if ($isVirtual) { $dev.virtual++ } elseif ($isServer) { $dev.servers++ } else { $dev.workstations++ }
        $os = [string](Get-QbrProp $ep 'os'); $type = Get-QbrOsType $os; $sup = Get-QbrOsSupport $os $type
        $dev.os[$sup]++
        $seen = ConvertTo-QbrDate (Get-QbrProp $ep 'lastCheckIn'); if ($seen -and $seen -lt $runDate.AddDays(-30)) { $dev.stale++ }
        if ($isVirtual) { continue }   # age and warranty mean nothing for a virtual machine
        $a = Get-QbrAge $ep
        $bucket = if ($null -eq $a) { 'Unknown' } elseif ($a.years -ge 7) { '7 years or more' } elseif ($a.years -ge 5) { '5 to 7 years' } elseif ($a.years -ge 3) { '3 to 5 years' } else { 'Under 3 years' }
        $dev.age[$bucket]++
        if ($null -ne $a -and $a.estimated) { $dev.ageEstimated++ }
        $war = Get-QbrWarranty $ep
        $dev.warranty[$war.status]++
        if ($war.status -eq 'expiring') { $null = $soon.Add(@{ name = [string](Get-QbrProp $ep 'name'); date = $war.date }) }
        # Endpoint LifeCycle Manager's "Replace" rule for a workstation.
        $ram = Get-QbrRamGb $ep
        $w11 = ([string](Get-QbrProp $ep 'windows11Readiness')) -match '(?i)installed|ready|capable'
        if (-not $isServer -and $type -ne 'other' -and (($null -ne $a -and $a.years -ge 5) -or ($sup -eq 'unsupported' -and -not $w11) -or ($null -ne $ram -and $ram -lt 4))) { $dev.replace++ }
    }
    $dev.warrantySoon = @($soon | Sort-Object { $_.date } | ForEach-Object { @{ name = $_.name; ends = (Format-QbrDate $_.date) } })
}
catch {
    $dev.available = $false; $dev.reason = "Couldn't read the endpoints: $($_.Exception.Message)"
    $null = $warnings.Add($dev.reason)
}
$out.devices = $dev

# ---- Planner cards already on the board (open ones, not counting QBR cards) ----
$plan = [ordered]@{ available = $true; reason = ''; open = 0; total = 0 }
try {
    $cards = @(Get-CrAll "/v2/odata/product?`$filter=companyId eq $companyId" | Where-Object { $null -ne $_ -and [int](Get-QbrProp $_ 'companyId') -eq $companyId -and -not [bool](Get-QbrProp $_ 'isDeleted') })
    $cards = @($cards | Where-Object { -not ([string](Get-QbrProp $_ 'body')).Contains('qbr-data-pack') })
    $plan.total = $cards.Count
    $plan.open = @($cards | Where-Object { [string](Get-QbrProp $_ 'status') -notmatch '^(?i)(40|50|60|completed|client_declined|archive)$' }).Count
}
catch { $plan.available = $false; $plan.reason = "Couldn't read the Planner cards: $($_.Exception.Message)"; $null = $warnings.Add($plan.reason) }
$out.planner = $plan

# ---- domains (60 days) and certificates (30 days) ----
function Get-QbrExpiring {
    param([object[]]$Rows, [string]$DateField, [int]$Window, [string[]]$NameFields)
    $list = New-Object System.Collections.ArrayList; $total = 0
    foreach ($r in $Rows) {
        $total++
        $d = ConvertTo-QbrDate (Get-QbrProp $r $DateField); if (-not $d) { continue }
        if ($d -gt $runDate.AddDays($Window)) { continue }
        $name = ''; foreach ($f in $NameFields) { $name = [string](Get-QbrProp $r $f); if ($name) { break } }
        $left = [int][math]::Floor(($d - $runDate).TotalDays)
        $null = $list.Add([ordered]@{ name = $name; expires = (Format-QbrDate $d); daysLeft = $left; status = $(if ($left -lt 0) { 'expired' } else { 'expiring' }) })
    }
    return @{ total = $total; items = @($list | Sort-Object { $_.daysLeft }) }
}
$dom = [ordered]@{ available = $true; reason = ''; window = 60; total = 0; items = @() }
$domainNames = @()
try {
    $rows = @(Get-CrAll "/v2/odata/domain?`$filter=companyId eq $companyId" | Where-Object { $null -ne $_ -and [int](Get-QbrProp $_ 'companyId') -eq $companyId -and -not [bool](Get-QbrProp $_ 'isDeleted') })
    $domainNames = @($rows | ForEach-Object { ([string](Get-QbrProp $_ 'name')).Trim().ToLowerInvariant() } | Where-Object { $_ })
    $e = Get-QbrExpiring $rows 'dateExpires' 60 @('name'); $dom.total = $e.total; $dom.items = $e.items
}
catch { $dom.available = $false; $dom.reason = "Couldn't read the domains: $($_.Exception.Message)"; $null = $warnings.Add($dom.reason) }
$cert = [ordered]@{ available = $true; reason = ''; window = 30; total = 0; items = @() }
try {
    $rows = @(Get-CrAll "/v2/odata/certificate?`$filter=companyId eq $companyId" | Where-Object { $null -ne $_ -and [int](Get-QbrProp $_ 'companyId') -eq $companyId -and -not [bool](Get-QbrProp $_ 'isDeleted') })
    $e = Get-QbrExpiring $rows 'expirationDate' 30 @('name', 'subject', 'url'); $cert.total = $e.total; $cert.items = $e.items
}
catch { $cert.available = $false; $cert.reason = "Couldn't read the certificates: $($_.Exception.Message)"; $null = $warnings.Add($cert.reason) }
$out.domains = $dom
$out.certificates = $cert
$out.domainNames = $domainNames
$out.warnings = @($warnings)
$out.status = 'ok'
Set-NodeOutput $out
