# === STEP: Read Microsoft 365 licences ===
# Edit this file, then run: node qbr-data-pack/src/build.js
# Optional and read-only (GET calls only). Reads the tenant's subscriptions: licences purchased and assigned per SKU.
# Skipped with a note when the runner has no Microsoft 365 secrets, when the app lacks Organization.Read.All,
# or when the tenant can't be confirmed as this client's (so another client's licences never reach this card).
# Graph application permission: Organization.Read.All (or Directory.Read.All).
# Secrets: M365-TenantId, M365-ClientId, M365-ClientSecret (the Entra-* and Graph-* names work too).
# >>> _shared/graph.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/graph.ps1

$in = Get-NodeInput
function Get-QbrProp { param($o, [string]$n) if ($null -eq $o) { return $null }; if ($o -is [System.Collections.IDictionary]) { if ($o.Contains($n)) { return $o[$n] }; return $null }; $p = $o.PSObject.Properties[$n]; if ($p) { return $p.Value }; return $null }
function Copy-QbrInput { param($o) $h = [ordered]@{}; if ($o -is [System.Collections.IDictionary]) { foreach ($k in $o.Keys) { $h[[string]$k] = $o[$k] } } elseif ($null -ne $o) { foreach ($p in $o.PSObject.Properties) { $h[$p.Name] = $p.Value } }; return $h }
$out = Copy-QbrInput $in
$warnings = New-Object System.Collections.ArrayList
foreach ($w in @(Get-QbrProp $in 'warnings')) { if ($w) { $null = $warnings.Add([string]$w) } }
$lic = [ordered]@{ available = $false; reason = ''; tenantId = ''; tenantName = ''; matchedBy = ''; skus = @(); purchased = 0; assigned = 0 }
function Close-QbrStep { $out.licences = $lic; $out.warnings = @($warnings); Set-NodeOutput $out }
function Skip-QbrM365 { param([string]$Why) $lic.reason = $Why; $null = $warnings.Add($Why); Close-QbrStep }

# Friendly names for common SKUs (part numbers otherwise).
$QbrSkuNames = @{
    'O365_BUSINESS_ESSENTIALS' = 'Microsoft 365 Business Basic'; 'O365_BUSINESS_PREMIUM' = 'Microsoft 365 Business Standard'; 'SPB' = 'Microsoft 365 Business Premium'
    'O365_BUSINESS' = 'Microsoft 365 Apps for business'; 'OFFICESUBSCRIPTION' = 'Microsoft 365 Apps for enterprise'; 'STANDARDPACK' = 'Office 365 E1'
    'ENTERPRISEPACK' = 'Office 365 E3'; 'ENTERPRISEPREMIUM' = 'Office 365 E5'; 'SPE_E3' = 'Microsoft 365 E3'; 'SPE_E5' = 'Microsoft 365 E5'; 'SPE_F1' = 'Microsoft 365 F3'
    'DESKLESSPACK' = 'Office 365 F3'; 'EXCHANGESTANDARD' = 'Exchange Online (Plan 1)'; 'EXCHANGEENTERPRISE' = 'Exchange Online (Plan 2)'; 'EXCHANGEDESKLESS' = 'Exchange Online Kiosk'
    'EXCHANGEARCHIVE_ADDON' = 'Exchange Online Archiving'; 'POWER_BI_PRO' = 'Power BI Pro'; 'PBI_PREMIUM_PER_USER' = 'Power BI Premium Per User'
    'PROJECTPROFESSIONAL' = 'Project Plan 3'; 'PROJECT_P1' = 'Project Plan 1'; 'VISIOCLIENT' = 'Visio Plan 2'; 'VISIOONLINE_PLAN1' = 'Visio Plan 1'
    'EMS' = 'Enterprise Mobility + Security E3'; 'EMSPREMIUM' = 'Enterprise Mobility + Security E5'; 'AAD_PREMIUM' = 'Microsoft Entra ID P1'; 'AAD_PREMIUM_P2' = 'Microsoft Entra ID P2'
    'INTUNE_A' = 'Microsoft Intune Plan 1'; 'ATP_ENTERPRISE' = 'Microsoft Defender for Office 365 (Plan 1)'; 'THREAT_INTELLIGENCE' = 'Microsoft Defender for Office 365 (Plan 2)'
    'MCOEV' = 'Teams Phone Standard'; 'MCOMEETADV' = 'Microsoft 365 Audio Conferencing'; 'MICROSOFT_TEAMS_ENTERPRISE_NEW' = 'Microsoft Teams Enterprise'; 'MICROSOFT_365_COPILOT' = 'Microsoft 365 Copilot'
}
function Test-QbrFreeSku { param([string]$Part) $u = $Part.ToUpperInvariant(); if (@('FLOW_FREE', 'POWER_BI_STANDARD', 'TEAMS_EXPLORATORY', 'TEAMS_FREE', 'STREAM', 'WINDOWS_STORE', 'RIGHTSMANAGEMENT_ADHOC', 'MICROSOFT_BUSINESS_CENTER', 'MCOPSTNC', 'PHONESYSTEM_VIRTUALUSER', 'MEETING_ROOM_FREE', 'APPS_FREE') -contains $u) { return $true }; return ($u -match '(_FREE$|^FREE_|_VIRAL|VIRAL_|_TRIAL|TRIAL_|_IW_SKU$|_IW$|EXPLORATORY)') }

# ---- sign in (optional) ----
$hasAny = $false
foreach ($n in @('M365-TenantId', 'M365-TenantID', 'Entra-TenantID', 'Graph-TenantId', 'M365-ClientId', 'M365-ClientID', 'Entra-ClientID', 'Graph-ClientId')) { if (Get-GraphSecret @($n)) { $hasAny = $true; break } }
if (-not $hasAny) { Skip-QbrM365 'Microsoft 365 is not connected on this runner (no M365-TenantId or M365-ClientId secret), so licence usage was left out.'; return }
$conn = $null
try { $conn = Connect-Graph } catch { Skip-QbrM365 "Couldn't sign in to Microsoft 365, so licence usage was left out: $($_.Exception.Message)"; return }
$lic.tenantId = [string]$conn.TenantId

# ---- confirm the tenant belongs to this client ----
$org = $null
try { $org = @(Get-QbrProp (Invoke-Graph -Method GET -Path '/v1.0/organization?$select=id,displayName,verifiedDomains' -Permission 'Organization.Read.All') 'value') | Select-Object -First 1 }
catch {
    if ($GraphState.LastStatus -eq 403) { Skip-QbrM365 'Microsoft Graph refused to read the organization. Grant the app registration the Organization.Read.All application permission, with admin consent, to include licence usage.'; return }
    Skip-QbrM365 "Couldn't read the Microsoft 365 organization, so licence usage was left out: $($_.Exception.Message)"; return
}
$lic.tenantName = [string](Get-QbrProp $org 'displayName')
$verified = @(@(Get-QbrProp $org 'verifiedDomains') | ForEach-Object { ([string](Get-QbrProp $_ 'name')).Trim().ToLowerInvariant() } | Where-Object { $_ })
$crDomains = @(@(Get-QbrProp $in 'domainNames') | ForEach-Object { ([string]$_).Trim().ToLowerInvariant() } | Where-Object { $_ })
$coTenant = [string](Get-QbrProp $in 'companyTenantId')
$companyName = [string](Get-QbrProp $in 'companyName')
$shared = @($crDomains | Where-Object { $verified -contains $_ })
if ($coTenant -and $coTenant -eq $lic.tenantId.ToLowerInvariant()) { $lic.matchedBy = 'the tenant id on the CloudRadial company' }
elseif ($coTenant) { Skip-QbrM365 "The Microsoft 365 tenant on this runner ($($lic.tenantName)) is not the one linked to $companyName in CloudRadial, so licence usage was left out."; return }
elseif ($shared.Count) { $lic.matchedBy = "the domain $($shared[0]), which is on both the CloudRadial company and the tenant" }
elseif (-not $crDomains.Count -and [string](Get-QbrProp $in 'companyVia') -eq 'CloudRadial-CompanyId secret') { $lic.matchedBy = 'the CloudRadial-CompanyId secret on this runner (the company has no domains in CloudRadial to compare)' }
else { Skip-QbrM365 "Couldn't confirm that the Microsoft 365 tenant on this runner ($($lic.tenantName)) belongs to $companyName, because none of its verified domains are on the company in CloudRadial, so licence usage was left out."; return }

# ---- subscriptions ----
$skus = @()
try { $skus = @(Get-GraphAll -Path '/v1.0/subscribedSkus' -Permission 'Organization.Read.All (or Directory.Read.All)') }
catch {
    if ($GraphState.LastStatus -eq 403) { Skip-QbrM365 'Microsoft Graph refused to list the tenant''s subscriptions. Grant the app registration the Organization.Read.All application permission, with admin consent, to include licence usage.'; return }
    Skip-QbrM365 "Couldn't read the Microsoft 365 subscriptions, so licence usage was left out: $($_.Exception.Message)"; return
}
$rows = New-Object System.Collections.ArrayList
foreach ($s in $skus) {
    $part = [string](Get-QbrProp $s 'skuPartNumber'); if (-not $part) { continue }
    $applies = [string](Get-QbrProp $s 'appliesTo')
    if ((Test-QbrFreeSku $part) -or ($applies -and $applies -ne 'User')) { continue }
    $pre = Get-QbrProp $s 'prepaidUnits'
    $enabled = [int](Get-QbrProp $pre 'enabled'); $warning = [int](Get-QbrProp $pre 'warning'); $suspended = [int](Get-QbrProp $pre 'suspended')
    $used = [int](Get-QbrProp $s 'consumedUnits')
    if ($enabled -le 0 -and $used -le 0) { continue }
    $u = $part.ToUpperInvariant()
    $name = if ($QbrSkuNames.ContainsKey($u)) { $QbrSkuNames[$u] } else { $part }
    $null = $rows.Add([ordered]@{ sku = $part; name = $name; purchased = $enabled; assigned = $used; unassigned = [Math]::Max(0, $enabled - $used); warning = $warning; suspended = $suspended })
}
$lic.skus = @($rows | Sort-Object @{ Expression = { $_.purchased }; Descending = $true }, @{ Expression = { $_.name }; Descending = $false })
$lic.purchased = [int](@($rows | ForEach-Object { $_.purchased }) | Measure-Object -Sum).Sum
$lic.assigned = [int](@($rows | ForEach-Object { $_.assigned }) | Measure-Object -Sum).Sum
$lic.available = $true
Close-QbrStep
