// Builds ../risky-signin-response.yml from the step scripts in this folder, then pastes the shared
// libraries into it with ../../_shared/inject.js.
// Usage: node build.js                 rewrite the .yml
//        node build.js --check         exit 1 if the .yml is out of date
//        node build.js --extract <dir>  write each step's finished script to <dir>/<node-id>.ps1 (used by test.ps1)
// Edit the .ps1 files here, never the .yml.
// Needs js-yaml: set JS_YAML_PATH (or NODE_PATH) to an existing copy, or npm install in automationai/_shared.
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

// Returns js-yaml and sets JS_YAML_PATH so inject.js uses the same copy.
function loadYaml() {
  const tries = [process.env.JS_YAML_PATH, 'js-yaml', path.join(__dirname, '..', '..', '_shared', 'node_modules', 'js-yaml')].filter(Boolean);
  for (const t of tries) {
    try { const p = require.resolve(t); const y = require(p); process.env.JS_YAML_PATH = p; return y; } catch { /* next */ }
  }
  throw new Error('js-yaml not found. Set JS_YAML_PATH, or run npm install in automationai/_shared.');
}

const here = __dirname;
const folder = path.join(here, '..');
const out = path.join(folder, 'risky-signin-response.yml');
const inject = path.join(here, '..', '..', '_shared', 'inject.js');

const steps = [
  { id: 'node-inputs', name: 'Read inputs', file: 'read-inputs.ps1', libs: [], timeout: 120,
    testInput: { min_risk: 'high', preview: true, notify_manager: true, confirm: false, block_upns: '', company_id: '', psa: '', psa_company_id: '' } },
  { id: 'node-find', name: 'Find risky users', file: 'find-risky.ps1', libs: ['graph.ps1'], timeout: 600 },
  { id: 'node-respond', name: 'Respond to new risky users', file: 'respond.ps1', libs: ['graph.ps1', 'psa.ps1', 'psa-tickets.ps1', 'cloudradial.ps1'], timeout: 900 },
  { id: 'node-block', name: 'Block confirmed accounts', file: 'block.ps1', libs: ['graph.ps1', 'plan.ps1', 'psa.ps1'], timeout: 600 },
  { id: 'node-summary', name: 'Summarize', file: 'summarize.ps1', libs: [], timeout: 120 },
];

const marker = (lib) => [`# >>> _shared/${lib} (generated by _shared/inject.js; edit the source, not this block)`, `# <<< _shared/${lib}`];
const ind = (lines, n) => lines.map((l) => (l ? ' '.repeat(n) + l : ''));

function render() {
  const L = [];
  L.push('automationsWorkflow: 1');
  L.push('name: Risky Sign-in Response');
  L.push("description: 'Hourly check for users Microsoft Entra ID Protection has at high risk. For each new one it opens a high-priority PSA ticket (critical for admins) with the risk detail only in an internal note, signs the user out everywhere, requires a password change at next sign-in and emails their manager a short notice. It never blocks an account unless rerun with confirm true and block_upns, and only while the account is still at risk. Needs Entra ID P2.'");
  L.push('definition:');
  L.push('  schemaVersion: 1');
  L.push('  activities:');
  L.push('  - id: start', '    name: Start', '    type: start', '    position:', '      x: 100', '      y: 200', '    properties:',
    '      # Manual run or hourly Routine: the first step reads Get-NodeInput, so the webhook stays off.',
    '      webhookEnabled: false');
  steps.forEach((s, i) => {
    const src = fs.readFileSync(path.join(here, s.file), 'utf8').replace(/\r\n/g, '\n').trimEnd().split('\n');
    const body = [];
    for (const lib of s.libs) body.push(...marker(lib));
    if (s.libs.length) body.push('');
    body.push(...src);
    L.push(`  - id: ${s.id}`, `    name: ${s.name}`, '    type: powershell-script', '    position:', `      x: ${280 + i * 200}`, '      y: 200', '    properties:');
    L.push('      script: |-', ...ind(body, 8));
    L.push(`      timeoutSeconds: ${s.timeout}`, '      retryCount: 0', '      parameters: []', '      aiExtensions: []');
    if (s.testInput) L.push('      testInput: |-', ...ind(JSON.stringify(s.testInput, null, 2).split('\n'), 8));
  });
  L.push('  - id: end', '    name: End', '    type: end', '    position:', `      x: ${280 + steps.length * 200}`, '      y: 200');
  L.push('  connections:');
  const ids = ['start', ...steps.map((s) => s.id), 'end'];
  for (let i = 0; i < ids.length - 1; i++) L.push(`  - source: ${ids[i]}`, `    target: ${ids[i + 1]}`, '    sourceHandle: null');
  L.push('  startActivityId: start', '');
  return L.join('\n');
}

function main(argv) {
  const y = loadYaml();
  const ex = argv.indexOf('--extract');
  if (ex >= 0) {
    const dir = argv[ex + 1];
    if (!dir) throw new Error('--extract needs a folder');
    fs.mkdirSync(dir, { recursive: true });
    const doc = y.load(fs.readFileSync(out, 'utf8'));
    for (const a of doc.definition.activities) {
      if (a.type === 'powershell-script') fs.writeFileSync(path.join(dir, `${a.id}.ps1`), a.properties.script);
    }
    console.log(`Extracted ${doc.definition.activities.filter((a) => a.type === 'powershell-script').length} steps to ${dir}`);
    return 0;
  }
  const check = argv.includes('--check');
  // Render with empty marker blocks, fill them in a temp copy, and compare with (or replace) the real file.
  const tmpDir = fs.mkdtempSync(path.join(require('os').tmpdir(), 'rsr-'));
  const tmp = path.join(tmpDir, 'risky-signin-response.yml');
  fs.writeFileSync(tmp, render());
  execFileSync(process.execPath, [inject, tmpDir], { stdio: 'pipe', env: process.env });
  const next = fs.readFileSync(tmp, 'utf8');
  fs.rmSync(tmpDir, { recursive: true, force: true });
  const doc = y.load(next);
  const scripts = doc.definition.activities.filter((a) => a.type === 'powershell-script');
  if (scripts.length !== steps.length) throw new Error('Wrong number of steps after build');
  const was = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : '';
  const same = was === next;
  console.log(`risky-signin-response.yml: ${scripts.length} steps${same ? ' current' : check ? ' OUT OF DATE' : ' written'}`);
  if (!same && !check) fs.writeFileSync(out, next);
  return !same && check ? 1 : 0;
}

if (require.main === module) {
  try { process.exit(main(process.argv.slice(2))); } catch (e) { console.error(e.message); process.exit(2); }
}
