// Builds ../time-entry-review.yml from the step scripts in this folder, then pastes the shared libraries
// (psa.ps1, psa-tickets.ps1, postmark.ps1) with ../../_shared/inject.js.
// Usage: node build.js                  rewrite the .yml
//        node build.js --check          exit 1 if the .yml is out of date
//        node build.js --extract <dir>  write each step's finished script to <dir>/<node-id>.ps1 (used by test.ps1)
// Edit the .ps1 files here, never the .yml.
// Needs js-yaml: set JS_YAML_PATH (or NODE_PATH) to an existing copy, or npm install in _shared.
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const NAME = 'time-entry-review';
const TITLE = 'Time Entry Review';
const DESCRIPTION = 'Daily, read-only review of the tickets closed yesterday in any of six PSAs: flags tickets closed with no time logged, time entries with short notes, and time entries with no billable setting, then emails a plain table to the service manager through Postmark. Never changes a ticket.';
const START_COMMENT = 'Manual run or daily Routine: the first step reads Get-NodeInput, so the webhook stays off.';
const steps = [
  { id: 'node-inputs', name: 'Read inputs', file: 'read-inputs.ps1', libs: [], timeout: 120,
    testInput: { date: '', timezone: '', min_note_chars: 20, check_billable: true, to: '', company_id: '', zendesk_time_field_id: '', max_tickets: 500, psa: '' } },
  { id: 'node-find', name: 'Find closed tickets', file: 'find-tickets.ps1', libs: ['psa.ps1', 'psa-tickets.ps1'], timeout: 600 },
  { id: 'node-review', name: 'Review time entries', file: 'review-time.ps1', libs: ['psa.ps1', 'psa-tickets.ps1'], timeout: 1800 },
  { id: 'node-send', name: 'Email the service manager', file: 'send-report.ps1', libs: ['postmark.ps1'], timeout: 300 },
];

// Returns js-yaml and sets JS_YAML_PATH so inject.js uses the same copy.
function loadYaml() {
  const tries = [process.env.JS_YAML_PATH, 'js-yaml', path.join(__dirname, '..', '..', '_shared', 'node_modules', 'js-yaml')].filter(Boolean);
  for (const t of tries) {
    try { const p = require.resolve(t); const y = require(p); process.env.JS_YAML_PATH = p; return y; } catch { /* next */ }
  }
  throw new Error('js-yaml not found. Set JS_YAML_PATH, or run npm install in _shared.');
}

const here = __dirname;
const folder = path.join(here, '..');
const out = path.join(folder, `${NAME}.yml`);
const inject = path.join(here, '..', '..', '_shared', 'inject.js');

const sharedMarker = (lib) => [`# >>> _shared/${lib} (generated by _shared/inject.js; edit the source, not this block)`, `# <<< _shared/${lib}`];
const readLines = (f) => fs.readFileSync(path.join(here, f), 'utf8').replace(/\r\n/g, '\n').trimEnd().split('\n');
const ind = (lines, n) => lines.map((l) => (l ? ' '.repeat(n) + l : ''));
const q = (s) => `'${String(s).replace(/'/g, "''")}'`;

function render() {
  const L = [];
  L.push('automationsWorkflow: 1');
  L.push(`name: ${TITLE}`);
  L.push(`description: ${q(DESCRIPTION)}`);
  L.push('definition:');
  L.push('  schemaVersion: 1');
  L.push('  activities:');
  L.push('  - id: start', '    name: Start', '    type: start', '    position:', '      x: 100', '      y: 200', '    properties:',
    `      # ${START_COMMENT}`, '      webhookEnabled: false');
  steps.forEach((s, i) => {
    const body = [];
    for (const lib of s.libs) body.push(...sharedMarker(lib));
    if (s.libs.length) body.push('');
    body.push(...readLines(s.file));
    L.push(`  - id: ${s.id}`, `    name: ${s.name}`, '    type: powershell-script', '    position:', `      x: ${280 + i * 200}`, '      y: 200', '    properties:');
    L.push('      script: |-', ...ind(body, 8));
    L.push(`      timeoutSeconds: ${s.timeout}`, '      retryCount: 0', '      parameters: []', '      aiExtensions: []');
    if (s.testInput) L.push('      testInput: |-', ...ind(JSON.stringify(s.testInput, null, 2).split('\n'), 8));
  });
  L.push('  - id: end', '    name: End', '    type: end', '    position:', `      x: ${280 + steps.length * 200}`, '      y: 200');
  L.push('  connections:');
  const ids = ['start', ...steps.map((s) => s.id), 'end'];
  for (let i = 0; i < ids.length - 1; i++) L.push(`  - source: ${ids[i]}`, `    target: ${ids[i + 1]}`, '    sourceHandle: null');
  L.push('  startActivityId: start', '');
  return L.join('\n');
}

function main(argv) {
  const y = loadYaml();
  const ex = argv.indexOf('--extract');
  if (ex >= 0) {
    const dir = argv[ex + 1];
    if (!dir) throw new Error('--extract needs a folder');
    fs.mkdirSync(dir, { recursive: true });
    const doc = y.load(fs.readFileSync(out, 'utf8'));
    const scripts = doc.definition.activities.filter((a) => a.type === 'powershell-script');
    for (const a of scripts) fs.writeFileSync(path.join(dir, `${a.id}.ps1`), a.properties.script);
    console.log(`Extracted ${scripts.length} steps to ${dir}`);
    return 0;
  }
  const check = argv.includes('--check');
  // Render with empty shared blocks, fill them in a temp copy, and compare with (or replace) the real file.
  const tmpDir = fs.mkdtempSync(path.join(require('os').tmpdir(), `${NAME}-`));
  const tmp = path.join(tmpDir, `${NAME}.yml`);
  fs.writeFileSync(tmp, render());
  execFileSync(process.execPath, [inject, tmpDir], { stdio: 'pipe', env: process.env });
  const next = fs.readFileSync(tmp, 'utf8');
  fs.rmSync(tmpDir, { recursive: true, force: true });
  const doc = y.load(next);
  const scripts = doc.definition.activities.filter((a) => a.type === 'powershell-script');
  if (scripts.length !== steps.length) throw new Error('Wrong number of steps after build');
  if (doc.automationsWorkflow !== 1 || doc.definition.startActivityId !== 'start') throw new Error('Workflow header is wrong after build');
  // Compare without line endings, so a CRLF checkout still counts as current.
  const was = fs.existsSync(out) ? fs.readFileSync(out, 'utf8').replace(/\r\n/g, '\n') : '';
  const same = was === next;
  console.log(`${NAME}.yml: ${scripts.length} steps${same ? ' current' : check ? ' OUT OF DATE' : ' written'}`);
  if (!same && !check) fs.writeFileSync(out, next);
  return !same && check ? 1 : 0;
}

if (require.main === module) {
  try { process.exit(main(process.argv.slice(2))); } catch (e) { console.error(e.message); process.exit(2); }
}
