// Builds post-close-feedback.yml from the step sources in this folder, then pastes the shared
// libraries into it (_shared/inject.js).
// Usage: node build.js          rewrite the .yml
//        node build.js --check  exit 1 if the .yml is out of date
// Edit parse.ps1, survey.ps1, route.ps1 and step.ps1 (or the shared files in _shared), never the .yml.
// Needs js-yaml: set JS_YAML_PATH (or NODE_PATH) to an existing copy, or npm install in _shared.
const fs = require('fs');
const path = require('path');
const { injectText } = require('../../_shared/inject.js');

function loadYaml() {
  try { return require('js-yaml'); } catch { /* fall through */ }
  if (process.env.JS_YAML_PATH) return require(process.env.JS_YAML_PATH);
  throw new Error('js-yaml not found. Set JS_YAML_PATH, or npm install in _shared.');
}

const here = __dirname;
const name = 'post-close-feedback';
const out = path.join(here, '..', `${name}.yml`);
const read = (f) => fs.readFileSync(path.join(here, f), 'utf8').replace(/\r\n/g, '\n').trimEnd();
const block = (text, indent) => text.split('\n').map((l) => (l ? indent + l : '')).join('\n');
const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
// Shared libraries are marked for inject.js; this folder's own helpers are pasted here with the same marker pattern.
const shared = (lib) => `# >>> _shared/${lib} (generated by _shared/inject.js; edit the source, not this block)\n# <<< _shared/${lib}`;
const local = (f) => `# >>> src/${f} (generated by src/build.js; edit the source, not this block)\n${read(f)}\n# <<< src/${f}`;
const script = (libs, locals, body) => [...libs.map(shared), ...locals.map(local), read(body)].join('\n');

const testInput = JSON.stringify({
  mode: 'survey',
  ticketId: '1001',
  contactEmail: 'megan.bowen@contoso.com',
  status: 'Closed',
  feedback_url: 'https://feedback.example.com/csat?ticket={ticketId}&score={score}',
  score: '',
  comment: '',
  service_manager_email: '',
  preview: true,
}, null, 2);

function psStep({ id, name: n, x, body, params, test }) {
  let s = `  - id: ${id}
    name: ${n}
    type: powershell-script
    position:
      x: ${x}
      y: 80
    properties:
      script: |-
${block(body, '        ')}
      timeoutSeconds: 300
      retryCount: 0
`;
  if (params && params.length) s += '      parameters:\n' + params.map(([p, e]) => `      - name: ${p}\n        expression: ${q(e)}\n`).join('');
  else s += '      parameters: []\n';
  s += '      aiExtensions: []\n';
  if (test) s += `      testInput: |-\n${block(test, '        ')}\n`;
  return s;
}

const steps = [
  { id: 'parse', name: 'Read the request', body: script(['psa.ps1'], ['step.ps1'], 'parse.ps1'), params: [['trigger', '{{ nodes.trigger.output }}']], test: testInput },
  { id: 'survey', name: 'Send the survey', body: script(['psa.ps1'], ['step.ps1'], 'survey.ps1') },
  { id: 'route', name: 'Route low scores to the service manager', body: script(['psa.ps1', 'cloudradial.ps1', 'postmark.ps1'], ['step.ps1'], 'route.ps1') },
];

let x = 280;
const chain = ['start', ...steps.map((s) => s.id), 'end'];
const yml = `automationsWorkflow: 1
name: Post-Close Feedback
description: When a ticket closes, send the requester a one-question satisfaction survey as a public note, once
  per ticket, skipping tickets closed as duplicate or spam. When the answer comes back (mode score), note it on
  the ticket and email the service manager about low scores. Reporting companion is feedback-csat-report.
definition:
  schemaVersion: 1
  activities:
  - id: start
    name: Start
    type: start
    position:
      x: 100
      y: 80
    properties:
      # Enable the webhook in Properties after import; AutomationAI issues the URL and secret.
      webhookEnabled: false
${steps.map((s) => { const r = psStep({ ...s, x }); x += 180; return r; }).join('')}  - id: end
    name: End
    type: end
    position:
      x: ${x}
      y: 80
  connections:
${chain.slice(0, -1).map((src, i) => `  - source: ${src}\n    target: ${chain[i + 1]}\n    sourceHandle: null\n`).join('')}  startActivityId: start
`;

const y = loadYaml();
const { text } = injectText(yml, `${name}.yml`, new Map());
const doc = y.load(text);
// Guard rails: the shape every workflow must have.
if (doc.automationsWorkflow !== 1) throw new Error('automationsWorkflow marker missing');
const acts = doc.definition.activities;
if (acts.find((a) => a.id === 'start').properties.webhookEnabled !== false) throw new Error('webhook must ship disabled');
if (acts.some((a) => a.properties && a.properties.model)) throw new Error('model must be blank');
if (/\{\{\s*input\./.test(text)) throw new Error('use nodes.<id>.output bindings, never input.*');
if (/—/.test(text)) throw new Error('no em dashes');
const ids = new Set(acts.map((a) => a.id));
for (const c of doc.definition.connections) if (!ids.has(c.source) || !ids.has(c.target)) throw new Error(`bad connection ${c.source} -> ${c.target}`);

const check = process.argv.includes('--check');
const was = fs.existsSync(out) ? fs.readFileSync(out, 'utf8').replace(/\r\n/g, '\n') : '';
if (text === was) { console.log(`${name}.yml: current`); process.exit(0); }
if (check) { console.log(`${name}.yml: OUT OF DATE (run node src/build.js)`); process.exit(1); }
fs.writeFileSync(out, text);
console.log(`${name}.yml: written`);
