// Builds ../user-offboarding.yml from the scripts in this folder, with the _shared libraries pasted in by _shared/inject.js.
// Usage: node build.js          rewrite the generated file
//        node build.js --check  exit 1 if the generated file is out of date
// Edit the .ps1 files here (or the library in _shared), never the generated .yml.
// Needs js-yaml: npm install in _shared, or set JS_YAML_PATH.
const fs = require('fs');
const path = require('path');
let y;
try { y = require('js-yaml'); } catch { try { y = require(path.join(__dirname, '..', '..', '_shared', 'node_modules', 'js-yaml')); } catch { y = require(process.env.JS_YAML_PATH); } }
const { injectText } = require(path.join(__dirname, '..', '..', '_shared', 'inject.js'));

const here = __dirname;
const root = path.join(here, '..');
const check = process.argv.includes('--check');
const read = (f) => fs.readFileSync(path.join(here, f), 'utf8').replace(/\r\n/g, '\n').trimEnd() + '\n';
const lib = (name) => `# >>> _shared/${name} (generated by _shared/inject.js; edit the source, not this block)\n# <<< _shared/${name}\n`;

const preamble = (title, lines) =>
  ['# =====================================================================', `#  Offboard a Departing Employee - ${title}`, ...lines.map((l) => `#  ${l}`),
   '#  Generated from user-offboarding/src. Edit the source, then run build.js.',
   '# =====================================================================', "$ErrorActionPreference = 'Stop'", 'Set-StrictMode -Version Latest', ''].join('\n') + '\n';

const readScript = preamble('Read the user and plan the offboarding', [
  'Writes nothing. Reads the user, admin roles, groups, licences, manager, direct reports and devices from Microsoft Graph,',
  'and the mailbox from Exchange Online when the runner can reach it.',
  'Secrets: M365-TenantId, M365-ClientId, M365-ClientSecret; optional MicrosoftExchange-* (see README) and CloudRadial-CompanyId.',
]) + lib('graph.ps1') + lib('exchange.ps1') + '\n# ---------- this step ----------\n' + read('read.ps1');

const applyScript = preamble('Preview or offboard, then report', [
  'Changes Microsoft 365 and Exchange Online only when confirm is true. Adds an internal note to ticket_id,',
  'writes the completion report to the company\'s Report Archive "Offboarding" (admins only) and a generic public note.',
  'Secrets: M365-*, optional MicrosoftExchange-*, PSA-Type and the PSA\'s own secrets, CloudRadial-BaseUrl/PublicKey/PrivateKey.',
]) + lib('plan.ps1') + lib('graph.ps1') + lib('psa.ps1') + lib('cloudradial.ps1') + lib('exchange.ps1') + '\n# ---------- this step ----------\n' + read('apply.ps1');

const testInput = {
  upn: 'sam.doe@contoso.com',
  forward_to_manager: 'true',
  forward_to: '',
  keep_licenses_days: '0',
  confirm: 'false',
  allow_admin: 'false',
  mailbox_already_shared: 'false',
  requester_email: 'alex.kim@contoso.com',
  psa: 'connectwise',
  ticket_id: '12345',
  company_id: '42',
  company_tenant_id: '',
};

const wf = {
  automationsWorkflow: 1,
  name: 'Offboard a Departing Employee',
  description:
    'Offboards a departing Microsoft 365 user: blocks sign-in, resets the password to a random value, signs them out everywhere, ' +
    'removes their cloud groups, converts the mailbox to shared, hides it from the address list, optionally forwards mail, then removes licences. ' +
    'Preview only until confirm is true. Refuses admin accounts and self-offboarding. Writes an internal ticket note and an admin-only completion report.',
  definition: {
    schemaVersion: 1,
    activities: [
      { id: 'start', name: 'Start', type: 'start', position: { x: 80, y: 120 }, properties: { webhookEnabled: false } },
      {
        id: 'node-read', name: 'Read the user and plan the offboarding', type: 'powershell-script', position: { x: 320, y: 120 },
        properties: {
          script: readScript, timeoutSeconds: 300, retryCount: 0, parameters: [], aiExtensions: [],
          testInput: JSON.stringify(testInput, null, 2),
        },
      },
      {
        id: 'node-apply', name: 'Preview or offboard, then report', type: 'powershell-script', position: { x: 580, y: 120 },
        properties: {
          script: applyScript, timeoutSeconds: 900, retryCount: 0,
          parameters: [{ name: 'prep', expression: '{{ nodes.node-read.output }}' }],
          aiExtensions: [],
        },
      },
      { id: 'end', name: 'End', type: 'end', position: { x: 820, y: 120 } },
    ],
    connections: [
      { source: 'start', target: 'node-read', sourceHandle: null },
      { source: 'node-read', target: 'node-apply', sourceHandle: null },
      { source: 'node-apply', target: 'end', sourceHandle: null },
    ],
    startActivityId: 'start',
  },
};

const header = [
  '# CloudRadial AutomationAI - Offboard a Departing Employee (Microsoft 365 and Exchange Online).',
  '# Generated by src/build.js. Edit the scripts in src/, not this file.',
  '# Import on Workflows -> Import. See README.md for secrets, permissions and inputs.',
].join('\n');
const dumped = header + '\n' + y.dump(wf, { lineWidth: -1, noRefs: true });
const { text, blocks } = injectText(dumped, 'user-offboarding.yml', new Map());
if (blocks.length !== 7) throw new Error(`expected 7 _shared blocks, got ${blocks.length}`);
const back = y.load(text);
JSON.parse(back.definition.activities.find((a) => a.id === 'node-read').properties.testInput);
if (back.definition.activities[0].properties.webhookEnabled !== false) throw new Error('webhook must ship off');
for (const a of back.definition.activities) {
  if (!a.properties || !a.properties.script) continue;
  if (!a.properties.script.includes('function Get-GraphUser')) throw new Error(`${a.id}: graph.ps1 not injected`);
  if (new RegExp('[' + String.fromCharCode(0x2013, 0x2014) + ']').test(a.properties.script)) throw new Error(`${a.id}: contains an en or em dash`);
}

const p = path.join(root, 'user-offboarding.yml');
const was = fs.existsSync(p) ? fs.readFileSync(p, 'utf8').replace(/\r\n/g, '\n') : null;
const changed = was !== text;
console.log(`user-offboarding.yml: ${changed ? (check ? 'OUT OF DATE' : 'updated') : 'current'} (${text.length} bytes)`);
if (changed) {
  if (check) process.exit(1);
  fs.writeFileSync(p, text);
}
