# === NODE: Clear the MFA methods and record it ===
# Runs only when every check passed. Removes every registered sign-in method except the password
# (an existing Temporary Access Pass is removed too), signs the user out everywhere, and, when
# issue_tap is true, creates a one-time Temporary Access Pass (60 minutes) for a technician to relay.
# dry_run=true lists what would be removed and changes nothing anywhere (no Graph writes, no ticket note).
# The method detail and any Temporary Access Pass go ONLY in the internal ticket note (and internal_note).
# The public note is generic and never lists methods. A rejected request from the previous step is
# recorded here too, as an internal note on the ticket.
# >>> _shared/graph.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/graph.ps1
# >>> _shared/psa.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/psa.ps1
$ErrorActionPreference = 'Stop'

function Read-MfaState { $in = Get-NodeInput; $s = [ordered]@{}; if ($null -ne $in) { if ($in -is [System.Collections.IDictionary]) { foreach ($k in @($in.Keys)) { $s[[string]$k] = $in[$k] } } else { foreach ($p in $in.PSObject.Properties) { $s[$p.Name] = $p.Value } } }; return $s }
function Get-MfaProp { param($o, [string]$n) if ($null -eq $o) { return $null }; if ($o -is [System.Collections.IDictionary]) { if ($o.Contains($n)) { return $o[$n] }; return $null }; $p = $o.PSObject.Properties[$n]; if ($p) { return $p.Value }; return $null }
function Get-MfaList { param($S, [string]$Key) if (-not $S.Contains($Key)) { return @() }; return @(@($S[$Key]) | Where-Object { $null -ne $_ -and [string]$_ -ne '' }) }
function Get-MfaMasked {
    param([string]$Value, [string]$Kind)
    if (-not $Value) { return '' }
    if ($Kind -eq 'phone') { $d = ($Value -replace '\D', ''); if ($d.Length -ge 4) { return "ending $($d.Substring($d.Length - 4))" }; return 'number hidden' }
    if ($Kind -eq 'email' -and $Value -match '^(.)[^@]*(@.+)$') { return "$($Matches[1])***$($Matches[2])" }
    return $Value
}
# The step's own warnings first, then the ones _shared/psa.ps1 recorded in $PsaState.Warnings (a priority it
# couldn't set, a write answered with a redirect), each once and in its own words.
function Get-MfaWarnings {
    param($Own)
    $all = New-Object System.Collections.ArrayList
    foreach ($w in @(@($Own) + @($PsaState.Warnings))) { $t = [string]$w; if ($t -and -not $all.Contains($t)) { $null = $all.Add($t) } }
    return @($all)
}
# A plain description of one sign-in method for the internal note. Phone numbers and email addresses are masked.
function Get-MfaLabel {
    param($M)
    $t = ([string](Get-MfaProp $M '@odata.type')) -replace '^#?microsoft\.graph\.', ''
    $dn = [string](Get-MfaProp $M 'displayName')
    switch ($t) {
        'microsoftAuthenticatorAuthenticationMethod' { return "Microsoft Authenticator app$(if ($dn) { " on $dn" })" }
        'phoneAuthenticationMethod' { return "Phone ($([string](Get-MfaProp $M 'phoneType')), $(Get-MfaMasked ([string](Get-MfaProp $M 'phoneNumber')) 'phone'))" }
        'fido2AuthenticationMethod' { $mdl = [string](Get-MfaProp $M 'model'); return "Security key or passkey$(if ($dn) { " '$dn'" })$(if ($mdl) { " ($mdl)" })" }
        'emailAuthenticationMethod' { return "Email address $(Get-MfaMasked ([string](Get-MfaProp $M 'emailAddress')) 'email')" }
        'softwareOathAuthenticationMethod' { return 'Authenticator app code (software OATH token)' }
        'windowsHelloForBusinessAuthenticationMethod' { return "Windows Hello for Business$(if ($dn) { " on $dn" })" }
        'temporaryAccessPassAuthenticationMethod' { return 'Existing Temporary Access Pass' }
        'platformCredentialAuthenticationMethod' { return "Platform credential (macOS)$(if ($dn) { " on $dn" })" }
        default { return "$t$(if ($dn) { " '$dn'" })" }
    }
}

$state = Read-MfaState
$status = [string]$state['status']
if (@('incomplete', 'error', 'success', 'pending_confirmation') -contains $status) { $state['warnings'] = @(Get-MfaWarnings (Get-MfaList $state 'warnings')); Set-NodeOutput $state; return }
$dryRun = [bool]$state['dry_run']
$ticketId = [string]$state['ticket_id']
$upn = [string]$state['upn']; $userId = [string]$state['user_id']
$submitter = [string]$state['submittedByUpn']; if (-not $submitter) { $submitter = [string]$state['userOfficeId'] }
$actions = @(Get-MfaList $state 'actions'); $warnings = @(Get-MfaList $state 'warnings')
$when = (Get-Date).ToUniversalTime().ToString('yyyy-MM-dd HH:mm') + ' UTC'
$out = [ordered]@{
    status = $status; message = ''; public_note = ''; internal_note = ''; chatReply = ''
    ticket_id = $ticketId; user_id = $userId; upn = $upn; dry_run = $dryRun
    category = $(if ($state.Contains('category')) { [string]$state['category'] } else { '' })
    methods_found = 0; methods_removed = 0; methods_not_removed = 0
    sessions_revoked = $false; tap_issued = $false; note_written = $false
    actions = @(); warnings = @()
    audit = [ordered]@{ requestedBy = $submitter; submitterSource = [string]$state['submitter_source']; target = $upn; evaluatedAt = $when }
}
$stop = @{ done = $false; category = 'graph-error' }
trap {
    if (-not $stop.done) {
        $stop.done = $true
        $m = [string]$_.Exception.Message
        $out.status = 'error'; $out.category = $stop.category; $out.message = $m
        $out.public_note = 'Something went wrong while resetting your sign-in methods. A technician will follow up shortly.'; $out.chatReply = $out.public_note
        $out.internal_note = "MFA reset for $upn failed: $m"; $out.actions = $actions; $out.warnings = @(Get-MfaWarnings $warnings)
        Set-NodeOutput $out
    }
    break
}

# Retry guard. The internal note ends with [mfa-reset: <ticket id>] (a rejected request with
# [mfa-reset-request: <ticket id>]). The marker holds only the ticket id: never the account, and never
# the Temporary Access Pass. Before anything changes, the ticket's notes are read; when the reset's
# marker is already there (ServiceAI Retry, or the same request run twice), nothing is removed, no
# new pass is created (which would replace the one a technician is relaying) and no note is added.
$ticketPsa = @{ ok = $false; marker = '' }
if ($ticketId) { $ticketPsa.marker = $(if ($status -eq 'rejected') { "mfa-reset-request: $ticketId" } else { "mfa-reset: $ticketId" }) }
if (-not $dryRun -and $ticketId) {
    try {
        $psa = Get-PsaType ([string]$state['psa'])
        if (-not $psa) { $warnings += 'No PSA is set up (PSA-Type secret), so the internal note is only in this run''s output.' }
        else {
            $null = Connect-Psa -Psa $psa
            $companyId = [string]$state['psaCompanyId']
            $ticketPsa.ok = $true
            if ($companyId) {
                $tk = Get-PsaTicket -Id $ticketId
                if ($tk.companyId -and [string]$tk.companyId -ne $companyId) { $ticketPsa.ok = $false; $warnings += "Ticket $ticketId belongs to another company in $(Get-PsaName), so no note was written to it. The internal note is only in this run's output." }
            }
        }
    }
    catch { $ticketPsa.ok = $false; $warnings += "The internal note could not be written to ticket $($ticketId): $($_.Exception.Message)" }
}
if ($status -ne 'rejected' -and -not $dryRun -and $ticketPsa.ok) {
    $stop.category = 'psa-error'
    try { $seen = Test-PsaNoteMarker -Id $ticketId -Marker $ticketPsa.marker }
    catch { throw "The notes on ticket $ticketId couldn't be read, so nothing was changed. (This check stops a retried run from resetting twice.) $($_.Exception.Message)" }
    $stop.category = 'graph-error'
    if ($seen) {
        $out.status = 'success'; $out.category = 'already-done'
        $out.message = "The MFA reset for ticket $ticketId was already done, so nothing was changed again and no note was added."
        $out.public_note = 'Your MFA reset has already been done. If you still cannot sign in, contact the service desk.'; $out.chatReply = $out.public_note
        $out.internal_note = "MFA reset for ticket $ticketId was already recorded on the ticket. This rerun changed nothing."
        $actions += "The reset was already recorded on ticket $ticketId, so this run changed nothing"
        $out.actions = $actions; $out.warnings = @(Get-MfaWarnings $warnings)
        Set-NodeOutput $out
        return
    }
}

$noteLines = New-Object System.Collections.Generic.List[string]
if ($status -eq 'rejected') {
    $out.message = [string]$state['message']; $out.public_note = [string]$state['public_note']; $out.chatReply = $out.public_note
    $noteLines.Add([string]$state['internal_note'])
    $noteLines.Add("Requested by: $submitter  |  Ticket: $ticketId  |  $when")
}
else {
    $null = Connect-Graph
    $all = @(Get-GraphAuthMethods -UserId $userId)
    $supported = @('microsoftAuthenticatorAuthenticationMethod', 'phoneAuthenticationMethod', 'fido2AuthenticationMethod', 'emailAuthenticationMethod', 'softwareOathAuthenticationMethod', 'windowsHelloForBusinessAuthenticationMethod', 'temporaryAccessPassAuthenticationMethod', 'platformCredentialAuthenticationMethod')
    $toRemove = @(); $cannot = @()
    foreach ($m in $all) {
        $t = ([string](Get-MfaProp $m '@odata.type')) -replace '^#?microsoft\.graph\.', ''
        if ($t -eq 'passwordAuthenticationMethod') { continue }
        if ($supported -contains $t) { $toRemove += $m } else { $cannot += $m }
    }
    $out.methods_found = $toRemove.Count + $cannot.Count
    $removed = @(); $failed = @()
    $tapLines = @()
    $revoke = [bool]$state['revokeSessions']
    $issueTap = [bool]$state['issue_tap']

    if ($dryRun) {
        $out.status = 'pending_confirmation'
        $out.message = "Dry run: every check passed for $upn. $($toRemove.Count) sign-in method(s) would be removed. Nothing was changed and no ticket note was written. Run again with dry_run=false to reset."
        $out.public_note = 'Test run only: no changes were made to your sign-in methods.'; $out.chatReply = $out.public_note
        $noteLines.Add("DRY RUN: MFA reset for $upn. Every check passed. Nothing was changed.")
        $noteLines.Add("Requested by: $submitter  |  Ticket: $ticketId  |  $when")
        $noteLines.Add(''); $noteLines.Add("Would remove ($($toRemove.Count)):")
        foreach ($m in $toRemove) { $noteLines.Add(" - $(Get-MfaLabel $m)") }
        if (-not $toRemove.Count) { $noteLines.Add(' - nothing (only the password is registered)') }
        if ($revoke -and $toRemove.Count) { $noteLines.Add('Would sign the user out of every session.') }
        if ($issueTap) { $noteLines.Add('Would create a one-time Temporary Access Pass (60 minutes) for a technician to relay.') }
        $actions += "Dry run: listed $($toRemove.Count) sign-in method(s) that would be removed"
    }
    else {
        # Pass 1, then retry what failed once: Graph can refuse to remove the default method while others remain.
        $pending = @($toRemove)
        for ($pass = 1; $pass -le 2 -and $pending.Count; $pass++) {
            $next = @()
            foreach ($m in $pending) {
                try { Remove-GraphAuthMethod -UserId $userId -Method $m; $removed += $m }
                catch {
                    if ($GraphState.LastStatus -eq 403) { throw }
                    if ($pass -eq 2) { $failed += [pscustomobject]@{ m = $m; why = [string]$_.Exception.Message } } else { $next += $m }
                }
            }
            $pending = $next
        }
        $out.methods_removed = $removed.Count
        if ($removed.Count) { $actions += "Removed $($removed.Count) sign-in method(s)" }
        if ($revoke -and $removed.Count) {
            try { Revoke-GraphSessions -UserId $userId; $out.sessions_revoked = $true; $actions += 'Signed the user out of every session' }
            catch { $warnings += "The user was not signed out of their sessions: $($_.Exception.Message)" }
        }
        if ($issueTap) {
            try {
                $tap = Invoke-Graph -Method POST -Path "/v1.0/users/$userId/authentication/temporaryAccessPassMethods" -Body @{ isUsableOnce = $true; lifetimeInMinutes = 60 } -Permission 'UserAuthenticationMethod.ReadWrite.All'
                $code = [string](Get-MfaProp $tap 'temporaryAccessPass')
                if (-not $code) { throw 'Graph created no pass value.' }
                $start = [string](Get-MfaProp $tap 'startDateTime'); $life = [string](Get-MfaProp $tap 'lifetimeInMinutes'); $once = [string](Get-MfaProp $tap 'isUsableOnce')
                $out.tap_issued = $true
                $actions += 'Created a one-time Temporary Access Pass (in the internal note only)'
                $onceText = $(if ($once -match '(?i)^true$') { 'It works for one sign-in only.' } else { 'It can be used more than once until it expires.' })
                $tapLines = @('', "Temporary Access Pass: $code", "Valid for $life minutes from $start. $onceText",'Relay it ONLY after verifying the user by a callback to a number already on file. Never send it by email or in the public note.')
            }
            catch {
                $why = [string]$_.Exception.Message
                if ($GraphState.LastStatus -eq 400 -or $why -match '(?i)policy') { $warnings += "No Temporary Access Pass was created. Turn on the Temporary Access Pass policy (Entra admin center > Protection > Authentication methods > Policies) and allow one-time passes of 60 minutes. Graph said: $why" }
                else { $warnings += "No Temporary Access Pass was created: $why" }
            }
        }
        $out.methods_not_removed = $failed.Count + $cannot.Count
        if ($failed.Count -or $cannot.Count -or -not ($out.sessions_revoked -or -not $revoke -or -not $removed.Count)) { $out.status = 'incomplete' } else { $out.status = 'success' }

        $noteLines.Add("MFA reset for $upn ($($out.status)). Self-service request verified against the portal sign-in.")
        $noteLines.Add("Requested by: $submitter  |  Ticket: $ticketId  |  $when")
        $noteLines.Add(''); $noteLines.Add("Removed ($($removed.Count)):")
        foreach ($m in $removed) { $noteLines.Add(" - $(Get-MfaLabel $m)") }
        if (-not $toRemove.Count) { $noteLines.Add(' - nothing (only the password was registered)') }
        if ($failed.Count -or $cannot.Count) {
            $noteLines.Add(''); $noteLines.Add('NOT removed, please remove by hand (Entra admin center > Users > the user > Authentication methods):')
            foreach ($f in $failed) { $noteLines.Add(" - $(Get-MfaLabel $f.m): $($f.why)") }
            foreach ($m in $cannot) { $noteLines.Add(" - $(Get-MfaLabel $m): this workflow can't remove this kind of method") }
        }
        $noteLines.Add('The password was not changed.')
        foreach ($l in $tapLines) { $noteLines.Add($l) }

        if ($out.status -eq 'success') {
            $pub = "Your multi-factor authentication (MFA) has been reset. The next time you sign in, you'll be asked to set up your sign-in methods again$(if ($out.sessions_revoked) { ', and you have been signed out of your other sessions' })."
            if ($out.tap_issued) { $pub += ' A technician will contact you with a one-time sign-in code.' }
            if (-not $toRemove.Count) { $pub = "Your account had no MFA sign-in methods to reset. The next time you sign in, you'll be asked to set them up if your organization requires it." }
            $pub += ' If you did not request this, contact the service desk immediately.'
        }
        else { $pub = 'We started resetting your sign-in methods, but a technician needs to finish the job. They will reach out shortly.' }
        $out.public_note = $pub; $out.chatReply = $pub
        $out.message = $(if ($out.status -eq 'success') { "MFA reset for $upn completed." } else { "MFA reset for $upn needs a technician: some methods were not removed or the user was not signed out. See the internal note." })
    }
}
$warnings = @(Get-MfaWarnings $warnings)
if ($warnings.Count) { $noteLines.Add(''); $noteLines.Add('Warnings:'); foreach ($w in $warnings) { $noteLines.Add(" - $w") } }
if ($actions.Count) { $noteLines.Add(''); $noteLines.Add('Checks and actions:'); foreach ($a in $actions) { $noteLines.Add(" - $a") } }
$out.internal_note = $noteLines -join "`n"

# Internal note on the ticket, through the six-PSA adapter. A dry run writes nothing.
if ($dryRun) { }
elseif (-not $ticketId) { $warnings += 'No ticket id was sent, so the internal note is only in this run''s output.' }
elseif ($ticketPsa.ok) {
    # Written last, after every change, so a run that failed part way is retried in full.
    try {
        $r = Add-PsaNote -Id $ticketId -Text $out.internal_note -Title 'MFA reset' -Marker $ticketPsa.marker
        if ($r -eq 'already-present') { $actions += "The internal note was already on ticket $ticketId, so it was not added again" }
        else { $out.note_written = $true; $actions += "Added the internal note to ticket $ticketId in $(Get-PsaName)" }
    }
    catch { $warnings += "The internal note could not be written to ticket $($ticketId): $($_.Exception.Message)" }
}
$out.actions = $actions; $out.warnings = @(Get-MfaWarnings $warnings)
Set-NodeOutput $out
