# === NODE: Check the requester and the account (fail closed) ===
# Gates, in order. Any one that fails ends the reset with status rejected; the next step records why
# in the internal ticket note. Nothing is changed in this step.
#   1. Tenant: a companyTenantId sent by the portal must be the tenant this runner's app signs in to.
#   2. Ownership: the TRUSTED submitter must be the target account. When @UserOfficeId is sent, only an
#      exact object-id match passes (a mismatch is refused). Only when it is blank does @UserEmail
#      have to match the target's UPN, mail or an SMTP proxy address.
#   3. Disabled: a disabled account is not reset (possible offboarding or a hold).
#   4. Privileged: the target holds no Entra directory role, directly, through a role-assignable
#      group, or as a PIM-eligible assignment. Admins go through a technician.
#   5. Risk: an at-risk or compromised user (Identity Protection) is not reset. Skipped with a
#      warning when the tenant or the app can't read risk.
# A missing Graph permission stops the step with a sentence naming it.
# >>> _shared/graph.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/graph.ps1
$ErrorActionPreference = 'Stop'

function Read-MfaState { $in = Get-NodeInput; $s = [ordered]@{}; if ($null -ne $in) { if ($in -is [System.Collections.IDictionary]) { foreach ($k in @($in.Keys)) { $s[[string]$k] = $in[$k] } } else { foreach ($p in $in.PSObject.Properties) { $s[$p.Name] = $p.Value } } }; return $s }
function Test-MfaTerminal { param($S) return (@('incomplete', 'rejected', 'error', 'success', 'pending_confirmation') -contains [string]$S['status']) }
function Get-MfaProp { param($o, [string]$n) if ($null -eq $o) { return $null }; if ($o -is [System.Collections.IDictionary]) { if ($o.Contains($n)) { return $o[$n] }; return $null }; $p = $o.PSObject.Properties[$n]; if ($p) { return $p.Value }; return $null }
function Add-MfaList { param($S, [string]$Key, [string]$Text) $S[$Key] = @(@($S[$Key]) | Where-Object { $null -ne $_ -and [string]$_ -ne '' }) + $Text }
$GenericHold = 'We could not reset your sign-in methods automatically. A technician is reviewing your request and will reach out shortly.'
function Deny-Mfa {
    param($S, [string]$Category, [string]$Internal, [string]$Public = $GenericHold)
    $S['status'] = 'rejected'; $S['category'] = $Category
    $S['message'] = $Public; $S['public_note'] = $Public; $S['chatReply'] = $Public
    $S['internal_note'] = $Internal
    Set-NodeOutput $S
}

$state = Read-MfaState
if (Test-MfaTerminal $state) { Set-NodeOutput $state; return }
$stop = @{ done = $false }
trap {
    if (-not $stop.done) {
        $stop.done = $true
        $m = [string]$_.Exception.Message
        $state['status'] = 'error'; $state['category'] = 'graph-error'
        $state['message'] = $m
        $state['public_note'] = 'Something went wrong while checking your request. A technician will follow up shortly.'
        $state['chatReply'] = $state['public_note']
        $state['internal_note'] = "MFA reset stopped while checking the account. Nothing was changed. $m"
        Set-NodeOutput $state
    }
    break
}

$conn = Connect-Graph
$runnerTenant = [string]$conn.TenantId
$state['graphTenantId'] = $runnerTenant

# 1. Tenant scope (before any user lookup).
$companyTenantId = [string]$state['companyTenantId']
if ($companyTenantId -match '^[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}$' -and $companyTenantId.Trim().ToLowerInvariant() -ne $runnerTenant.Trim().ToLowerInvariant()) {
    Deny-Mfa $state 'tenant-scope' "MFA reset rejected: the request came from Microsoft 365 tenant $companyTenantId, but this runner's app signs in to tenant $runnerTenant. Cross-tenant reset blocked. Nothing was changed."
    return
}

# Resolve the target.
$target = [string]$state['upn']
$user = Get-GraphUser -Id $target -Select 'id,userPrincipalName,displayName,mail,proxyAddresses,accountEnabled'
if ($null -eq $user) {
    Deny-Mfa $state 'resolution' "MFA reset rejected: no account '$target' was found in tenant $runnerTenant. Nothing was changed." 'We could not find that account. A technician will follow up shortly.'
    return
}
$userId = [string](Get-MfaProp $user 'id'); $upn = [string](Get-MfaProp $user 'userPrincipalName')
$state['user_id'] = $userId; $state['upn'] = $upn; $state['displayName'] = [string](Get-MfaProp $user 'displayName')

# 2. Ownership. Only the portal's verified identity counts; a form answer can't stand in for it.
$submitter = [string]$state['submittedByUpn']; $officeId = [string]$state['userOfficeId']
if (-not $submitter -and -not $officeId) {
    Deny-Mfa $state 'identity-unverified' "MFA reset rejected: the portal sent no verified submitter (@UserEmail or @UserOfficeId), so ownership of $upn could not be checked. Nothing was changed." 'We could not verify your identity for this request. A technician will follow up shortly.'
    return
}
$isOwner = $false; $how = ''
# Stricter than Password Reset: when the portal sent an object id, only an exact id match passes.
# The email match is used only when no object id was sent.
if ($officeId) {
    if ($officeId.Trim().ToLowerInvariant() -eq $userId.Trim().ToLowerInvariant()) { $isOwner = $true; $how = 'Entra object id' }
}
elseif ($submitter) {
    $ids = New-Object System.Collections.Generic.List[string]
    $ids.Add($upn); $mail = [string](Get-MfaProp $user 'mail'); if ($mail) { $ids.Add($mail) }
    foreach ($pa in @(Get-MfaProp $user 'proxyAddresses')) { if ([string]$pa -match '^(?i)smtp:(.+)$') { $ids.Add($Matches[1]) } }
    $sn = $submitter.Trim().ToLowerInvariant()
    foreach ($i in $ids) { if ($i.Trim().ToLowerInvariant() -eq $sn) { $isOwner = $true; $how = 'email address'; break } }
}
if (-not $isOwner) {
    Deny-Mfa $state 'identity-mismatch' "MFA reset DENIED: submitter '$(if ($submitter) { $submitter } else { $officeId })'$(if ($officeId) { " (Entra object id $officeId, account object id $userId)" }) asked to reset the sign-in methods of '$upn', a different account. Possible misuse; please review. Nothing was changed." 'You can only reset the sign-in methods on your own account. If someone else needs a reset, please contact the service desk.'
    return
}
Add-MfaList $state 'actions' "Verified the requester owns the account (matched on $how)"

# 3. Disabled account.
if (-not [bool](Get-MfaProp $user 'accountEnabled')) {
    Deny-Mfa $state 'disabled' "MFA reset rejected: $upn is disabled. Confirm whether that is intentional (offboarding or a hold) before resetting anything. Nothing was changed."
    return
}

# 4. Privileged roles: direct, through a role-assignable group, and PIM-eligible.
$perm = 'RoleManagement.Read.Directory'
$roleIds = New-Object System.Collections.Generic.List[string]
foreach ($a in @(Get-GraphAll -Path "/v1.0/roleManagement/directory/roleAssignments?`$filter=principalId eq '$userId'" -Permission $perm)) { $roleIds.Add([string](Get-MfaProp $a 'roleDefinitionId')) }
$roleHow = 'directly'
if (-not $roleIds.Count) {
    # Unverified: beta transitiveRoleAssignments (needs ConsistencyLevel: eventual and $count). It includes roles held through role-assignable groups.
    try {
        $t = Invoke-Graph -Method GET -Path "/beta/roleManagement/directory/transitiveRoleAssignments?`$count=true&`$filter=principalId eq '$userId'" -Permission $perm -Headers @{ ConsistencyLevel = 'eventual' }
        foreach ($a in @(Get-MfaProp $t 'value')) { if ($null -ne $a) { $roleIds.Add([string](Get-MfaProp $a 'roleDefinitionId')) } }
        $roleHow = 'through a role-assignable group'
    }
    catch {
        if ($GraphState.LastStatus -eq 403) { throw }
        throw "Could not check whether $upn holds an admin role through a group, so the reset was stopped to be safe. Graph said: $($_.Exception.Message)"
    }
}
if (-not $roleIds.Count) {
    try {
        foreach ($a in @(Get-GraphAll -Path "/v1.0/roleManagement/directory/roleEligibilityScheduleInstances?`$filter=principalId eq '$userId'" -Permission $perm)) { $roleIds.Add([string](Get-MfaProp $a 'roleDefinitionId')) }
        $roleHow = 'as an eligible (PIM) assignment'
    }
    catch {
        if ($GraphState.LastStatus -eq 403) { throw }
        # A tenant without Entra ID P2 has no PIM, so it has no eligible assignments to find.
        if ($_.Exception.Message -match '(?i)licen|premium|P2') { Add-MfaList $state 'warnings' 'Eligible (PIM) admin roles were not checked: the tenant has no Entra ID P2 licence, so there are none.' }
        else { throw "Could not check eligible (PIM) admin roles for $upn, so the reset was stopped to be safe. Graph said: $($_.Exception.Message)" }
    }
}
if ($roleIds.Count) {
    $names = @()
    foreach ($rid in @($roleIds | Select-Object -Unique)) {
        $n = $rid
        try { $d = Invoke-Graph -Method GET -Path "/v1.0/roleManagement/directory/roleDefinitions/$rid`?`$select=displayName" -Permission $perm; $dn = [string](Get-MfaProp $d 'displayName'); if ($dn) { $n = $dn } } catch { }
        $names += $n
    }
    Deny-Mfa $state 'privilege' "MFA reset rejected: $upn holds an Entra admin role $roleHow ($($names -join ', ')). Admin accounts must be reset by a technician after verifying identity, not by self-service. Nothing was changed."
    return
}
Add-MfaList $state 'actions' 'Confirmed the account holds no admin role'

# 5. Identity Protection risk (best effort).
$risky = $null; $riskRead = $true
try { $risky = Get-GraphRiskyUsers -UserId $userId } catch { $riskRead = $false; Add-MfaList $state 'warnings' "The user's sign-in risk was not checked (it needs the IdentityRiskyUser.Read.All permission and Entra ID P2): $($_.Exception.Message)" }
if ($null -ne $risky) {
    $rl = [string](Get-MfaProp $risky 'riskLevel'); $rs = [string](Get-MfaProp $risky 'riskState')
    if ($rs -eq 'atRisk' -or $rs -eq 'confirmedCompromised' -or $rl -eq 'high') {
        Deny-Mfa $state 'risk' "MFA reset rejected: $upn is flagged in Identity Protection (risk level $rl, state $rs). Clearing MFA on an account that may be compromised would let an attacker enroll their own device. Investigate first. Nothing was changed."
        return
    }
}
if ($riskRead) { Add-MfaList $state 'actions' 'Confirmed the account is not flagged as at risk' }

Set-NodeOutput $state
