// Builds ../shared-mailbox-dl.yml from the scripts in this folder, with the _shared libraries pasted in by _shared/inject.js.
// Usage: node build.js          rewrite the generated file
//        node build.js --check  exit 1 if the generated file is out of date
// Edit the .ps1 files here (or the library in _shared), never the generated .yml.
// Needs js-yaml: npm install in automationai/_shared, or set JS_YAML_PATH.
const fs = require('fs');
const path = require('path');
let y;
try { y = require('js-yaml'); } catch { try { y = require(path.join(__dirname, '..', '..', '_shared', 'node_modules', 'js-yaml')); } catch { y = require(process.env.JS_YAML_PATH); } }
const { injectText } = require(path.join(__dirname, '..', '..', '_shared', 'inject.js'));

const here = __dirname;
const root = path.join(here, '..');
const check = process.argv.includes('--check');
const read = (f) => fs.readFileSync(path.join(here, f), 'utf8').replace(/\r\n/g, '\n').trimEnd() + '\n';
const lib = (name) => `# >>> _shared/${name} (generated by _shared/inject.js; edit the source, not this block)\n# <<< _shared/${name}\n`;

const preamble = (title, lines) =>
  ['# =====================================================================', `#  Create a Shared Mailbox or Distribution List - ${title}`, ...lines.map((l) => `#  ${l}`),
   '#  Generated from automationai/shared-mailbox-dl/src. Edit the source, then run build.js.',
   '# =====================================================================', "$ErrorActionPreference = 'Stop'", 'Set-StrictMode -Version Latest', ''].join('\n') + '\n';

const readScript = preamble('Check the request and plan it', [
  'Writes nothing. Checks the address is free and every member exists (Microsoft Graph and Exchange Online),',
  "and whether a technician must confirm (someone outside the requester's department, or more than 25 members).",
  'Secrets: M365-TenantId, M365-ClientId, M365-ClientSecret; MicrosoftExchange-* (see README).',
]) + lib('graph.ps1') + lib('exchange.ps1') + '\n# ---------- this step ----------\n' + read('read.ps1');

const applyScript = preamble('Create it, or hold it for confirmation, then reply on the ticket', [
  'Creates the shared mailbox or distribution list in Exchange Online unless preview is true, or the request',
  'needs confirmation and confirm is false. Adds an internal note with the plan or result to ticket_id, and a',
  "public note with the new address when it was created. Secrets: MicrosoftExchange-*, PSA-Type and the PSA's own secrets.",
]) + lib('plan.ps1') + lib('psa.ps1') + lib('exchange.ps1') + '\n# ---------- this step ----------\n' + read('apply.ps1');

const testInput = {
  kind: 'shared_mailbox',
  display_name: 'Contoso Sales Team',
  alias: '',
  domain: '',
  members: 'alex.kim@contoso.com, sam.doe@contoso.com',
  send_as: 'sam.doe@contoso.com',
  requester_email: 'alex.kim@contoso.com',
  external_allowed: 'false',
  confirm: 'false',
  preview: 'true',
  psa: 'connectwise',
  ticket_id: '12345',
  company_tenant_id: '',
};

const wf = {
  automationsWorkflow: 1,
  name: 'Create a Shared Mailbox or Distribution List',
  description:
    'Creates a Microsoft 365 shared mailbox or distribution list with the requested name and members, makes the requester an owner, ' +
    "and grants send-as where asked. Checks the address is free and every member exists. Holds the request for a technician's confirmation " +
    "when a member is outside the requester's department or there are more than 25 members. Replies on the PSA ticket with the new address.",
  definition: {
    schemaVersion: 1,
    activities: [
      { id: 'start', name: 'Start', type: 'start', position: { x: 80, y: 120 }, properties: { webhookEnabled: false } },
      {
        id: 'node-read', name: 'Check the request and plan it', type: 'powershell-script', position: { x: 320, y: 120 },
        properties: {
          script: readScript, timeoutSeconds: 300, retryCount: 0, parameters: [], aiExtensions: [],
          testInput: JSON.stringify(testInput, null, 2),
        },
      },
      {
        id: 'node-apply', name: 'Create it, or hold it for confirmation, then reply on the ticket', type: 'powershell-script', position: { x: 580, y: 120 },
        properties: {
          script: applyScript, timeoutSeconds: 900, retryCount: 0,
          parameters: [{ name: 'prep', expression: '{{ nodes.node-read.output }}' }],
          aiExtensions: [],
        },
      },
      { id: 'end', name: 'End', type: 'end', position: { x: 820, y: 120 } },
    ],
    connections: [
      { source: 'start', target: 'node-read', sourceHandle: null },
      { source: 'node-read', target: 'node-apply', sourceHandle: null },
      { source: 'node-apply', target: 'end', sourceHandle: null },
    ],
    startActivityId: 'start',
  },
};

const header = [
  '# CloudRadial AutomationAI - Create a Shared Mailbox or Distribution List (Microsoft 365 and Exchange Online).',
  '# Generated by src/build.js. Edit the scripts in src/, not this file.',
  '# Import on Workflows -> Import. See README.md for secrets, permissions and inputs.',
].join('\n');
const dumped = header + '\n' + y.dump(wf, { lineWidth: -1, noRefs: true });
const { text, blocks } = injectText(dumped, 'shared-mailbox-dl.yml', new Map());
if (blocks.length !== 5) throw new Error(`expected 5 _shared blocks, got ${blocks.length}`);
const back = y.load(text);
JSON.parse(back.definition.activities.find((a) => a.id === 'node-read').properties.testInput);
if (back.definition.activities[0].properties.webhookEnabled !== false) throw new Error('webhook must ship off');
const need = { 'node-read': ['function Get-GraphUser', 'function Connect-OfExchange'], 'node-apply': ['function Add-PsaNote', 'function Invoke-ChangePlan', 'function Connect-OfExchange'] };
for (const a of back.definition.activities) {
  if (!a.properties || !a.properties.script) continue;
  for (const s of need[a.id]) if (!a.properties.script.includes(s)) throw new Error(`${a.id}: ${s} missing`);
  if (new RegExp('[' + String.fromCharCode(0x2013, 0x2014) + ']').test(a.properties.script)) throw new Error(`${a.id}: contains an en or em dash`);
}

const p = path.join(root, 'shared-mailbox-dl.yml');
const was = fs.existsSync(p) ? fs.readFileSync(p, 'utf8').replace(/\r\n/g, '\n') : null;
const changed = was !== text;
console.log(`shared-mailbox-dl.yml: ${changed ? (check ? 'OUT OF DATE' : 'updated') : 'current'} (${text.length} bytes)`);
if (changed) {
  if (check) process.exit(1);
  fs.writeFileSync(p, text);
}
