// Tests for _shared/inject.js against a throwaway workflow file: inject, --check, indentation,
// CRLF, several libraries in one step (all five libraries), and a missing end marker.
// Usage: node automationai/_shared/tests/test-inject.js   (needs js-yaml, like inject.js)
const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');

const shared = path.join(__dirname, '..');
const inject = path.join(shared, 'inject.js');
let y;
try { y = require('js-yaml'); } catch { y = require(process.env.JS_YAML_PATH); }

let pass = 0;
let fail = 0;
function check(name, ok, detail = '') {
  if (ok) { pass++; console.log(`PASS ${name}`); } else { fail++; console.log(`FAIL ${name} :: ${detail}`); }
}
const run = (dir, ...flags) => spawnSync(process.execPath, [inject, dir, ...flags], { encoding: 'utf8', env: process.env });
const start = (n) => `# >>> _shared/${n} (generated by _shared/inject.js; edit the source, not this block)`;
const end = (n) => `# <<< _shared/${n}`;
const lib = (n) => fs.readFileSync(path.join(shared, n), 'utf8').replace(/\r\n/g, '\n').trimEnd();

const workflow = [
  'kind: automationsWorkflow',
  'definition:',
  '  activities:',
  '    - id: node-step',
  '      properties:',
  '        script: |',
  '          $confirm = $true',
  `          ${start('plan.ps1')}`,
  '          stale line',
  `          ${end('plan.ps1')}`,
  `          ${start('graph.ps1')}`,
  `          ${end('graph.ps1')}`,
  '          Write-Output $confirm',
  '    - id: node-other',
  '      properties:',
  '        script: |-',
  `            ${start('plan.ps1')}`,
  `            ${end('plan.ps1')}`,
  '    - id: node-all',
  '      properties:',
  '        script: |',
  `          ${start('psa.ps1')}`,
  `          ${end('psa.ps1')}`,
  `          ${start('cloudradial.ps1')}`,
  `          ${end('cloudradial.ps1')}`,
  `          ${start('exchange.ps1')}`,
  `          ${end('exchange.ps1')}`,
  '',
].join('\n');

const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'inject-'));
try {
  const f = path.join(dir, 'sample.yml');
  fs.writeFileSync(f, workflow);
  fs.writeFileSync(path.join(dir, 'untouched.yml'), 'kind: automationsAgent\n');

  let r = run(dir, '--check');
  check('--check exits 1 when a block is stale', r.status === 1 && /OUT OF DATE/.test(r.stdout), r.stdout + r.stderr);
  check('--check leaves the file alone', fs.readFileSync(f, 'utf8') === workflow);

  r = run(dir);
  check('inject exits 0 and reports the blocks', r.status === 0 && /sample\.yml: 6 block\(s\) \[plan\.ps1, graph\.ps1, psa\.ps1, cloudradial\.ps1, exchange\.ps1\] updated/.test(r.stdout), r.stdout + r.stderr);
  const doc = y.load(fs.readFileSync(f, 'utf8'));
  const s1 = doc.definition.activities[0].properties.script;
  const s2 = doc.definition.activities[1].properties.script;
  const want1 = ['$confirm = $true', start('plan.ps1'), lib('plan.ps1'), end('plan.ps1'), start('graph.ps1'), lib('graph.ps1'), end('graph.ps1'), 'Write-Output $confirm', ''].join('\n');
  check('the step script holds the library text exactly', s1 === want1, s1.slice(0, 300));
  check('a block at a deeper indent keeps its indent', s2 === [start('plan.ps1'), lib('plan.ps1'), end('plan.ps1')].join('\n'), s2.slice(0, 200));
  const s3 = doc.definition.activities[2].properties.script;
  check('psa.ps1, cloudradial.ps1 and exchange.ps1 survive the YAML round trip', s3 === [start('psa.ps1'), lib('psa.ps1'), end('psa.ps1'), start('cloudradial.ps1'), lib('cloudradial.ps1'), end('cloudradial.ps1'), start('exchange.ps1'), lib('exchange.ps1'), end('exchange.ps1'), ''].join('\n'), s3.slice(0, 200));
  check('a file without markers is not touched', fs.readFileSync(path.join(dir, 'untouched.yml'), 'utf8') === 'kind: automationsAgent\n');

  r = run(dir, '--check');
  check('--check exits 0 once current', r.status === 0 && /current/.test(r.stdout), r.stdout + r.stderr);
  const before = fs.readFileSync(f, 'utf8');
  r = run(dir);
  check('a second inject changes nothing', r.status === 0 && fs.readFileSync(f, 'utf8') === before);

  fs.writeFileSync(f, workflow.replace(/\n/g, '\r\n'));
  r = run(dir);
  check('CRLF files stay CRLF', r.status === 0 && fs.readFileSync(f, 'utf8').includes('\r\n') && !/[^\r]\n/.test(fs.readFileSync(f, 'utf8')), r.stderr);

  const broken = workflow.replace(`          ${end('graph.ps1')}\n`, '');
  fs.writeFileSync(f, broken);
  r = run(dir);
  check('a missing end marker is an error and nothing is written', r.status === 2 && /# <<< _shared\/graph\.ps1/.test(r.stderr) && fs.readFileSync(f, 'utf8') === broken, r.stdout + r.stderr);
  fs.writeFileSync(f, workflow.replace(`          ${end('exchange.ps1')}\n`, ''));
  r = run(dir);
  check('an end marker missing at the end of the file is an error', r.status === 2 && /no "# <<< _shared\/exchange\.ps1"/.test(r.stderr), r.stdout + r.stderr);

  fs.writeFileSync(f, workflow.replace(/plan\.ps1/g, 'nope.ps1'));
  r = run(dir);
  check('an unknown library is an error', r.status === 2 && /_shared\/nope\.ps1 doesn't exist/.test(r.stderr), r.stderr);
} finally {
  fs.rmSync(dir, { recursive: true, force: true });
}
console.log(`${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
