# === Step 1: List breached and near-breach tickets (SLA Breach Report) ===
# Reads every open ticket in the PSA and flags the ones that have breached their SLA, or have used
# near_breach_percent (default 80) of the time allowed. The PSA's own SLA dates are used where it has
# them; otherwise the target is sla_hours_by_priority, measured from when the ticket was created.
# Report only: this step never writes to a ticket. A Routine runs it with no input, so every input has a default.
# >>> _shared/psa.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/psa.ps1
# >>> _shared/psa-tickets.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/psa-tickets.ps1

$run = @{ warnings = (New-Object System.Collections.ArrayList); actions = (New-Object System.Collections.ArrayList) }
function Stop-SlaRun {
    param([string]$Status, [string]$Message, [string]$Detail = '')
    Set-NodeOutput ([ordered]@{ status = $Status; message = $Message; public_note = ''; internal_note = $(if ($Detail) { $Detail } else { $Message }); ticket_id = ''; actions = @($run.actions); warnings = @($run.warnings); counts = @{}; tickets = @(); settings = @{} })
    throw $Message
}

# ---- inputs (a Routine sends none; a manual run may send a JSON object, or {trigger: {...}}) ----
$slaIn = Get-NodeInput
if ($slaIn -is [string]) { $slaIn = $(if ($slaIn.Trim()) { try { $slaIn | ConvertFrom-Json } catch { $null } } else { $null }) }
$slaWrap = Get-PsaProp $slaIn 'trigger'; if ($null -ne $slaWrap) { $slaIn = $slaWrap }
function Get-SlaInput {
    param([string]$Name, $Default)
    $v = Get-PsaProp $slaIn $Name
    if ($null -eq $v) { return $Default }
    if ($v -is [string] -and ([string]::IsNullOrWhiteSpace($v) -or $v.Trim().StartsWith('@'))) { return $Default }
    return $v
}
function ConvertTo-SlaBool { param($v) if ($v -is [bool]) { return $v }; return ([string]$v).Trim() -match '^(?i)(true|yes|1|on)$' }
function ConvertTo-SlaHourMap {
    param($Value, [hashtable]$Default, [string]$Label)
    $m = @{}; foreach ($k in $Default.Keys) { $m[$k] = $Default[$k] }
    if ($null -eq $Value) { return $m }
    if ($Value -is [string]) { try { $Value = $Value | ConvertFrom-Json -AsHashtable } catch { throw "$Label isn't valid JSON. Use an object such as {`"critical`":4,`"high`":8,`"medium`":24,`"low`":72}." } }
    # A list of pairs. (@(@(a, b)) from a pipeline flattens to @(a, b) when there is only one pair.)
    $pairs = New-Object System.Collections.ArrayList
    if ($Value -is [System.Collections.IDictionary]) { foreach ($k0 in @($Value.Keys)) { $null = $pairs.Add(@([string]$k0, $Value[$k0])) } }
    else { foreach ($pp in @($Value.PSObject.Properties)) { $null = $pairs.Add(@($pp.Name, $pp.Value)) } }
    foreach ($p in $pairs) {
        $k = Get-PsaPriorityHint ([string]$p[0])
        $n = 0.0
        if (-not $k -or -not [double]::TryParse([string]$p[1], [Globalization.NumberStyles]::Float, [Globalization.CultureInfo]::InvariantCulture, [ref]$n) -or $n -le 0) { throw "$Label needs a positive number of hours for each of critical, high, medium and low. '$($p[0])' was '$($p[1])'." }
        $m[$k] = $n
    }
    return $m
}

$settings = @{}
try {
    $near = 0.0
    if (-not [double]::TryParse([string](Get-SlaInput 'near_breach_percent' 80), [Globalization.NumberStyles]::Float, [Globalization.CultureInfo]::InvariantCulture, [ref]$near) -or $near -lt 1 -or $near -gt 100) { throw 'near_breach_percent must be a number from 1 to 100.' }
    $hours = ConvertTo-SlaHourMap (Get-SlaInput 'sla_hours_by_priority' $null) @{ critical = 4; high = 8; medium = 24; low = 72 } 'sla_hours_by_priority'
    $maxT = 0; if (-not [int]::TryParse([string](Get-SlaInput 'max_tickets' 500), [ref]$maxT) -or $maxT -lt 1 -or $maxT -gt 5000) { throw 'max_tickets must be a whole number from 1 to 5000.' }
    $usePsaSla = ConvertTo-SlaBool (Get-SlaInput 'use_psa_sla' $true)
    $skipRaw = Get-SlaInput 'skip_statuses' 'waiting,pending,on hold,scheduled'
    $skip = @(@($skipRaw) | ForEach-Object { ([string]$_) -split '[,;]' } | ForEach-Object { $_.Trim().ToLowerInvariant() } | Where-Object { $_ })
    # A Routine sends no input, so the ServiceManager-Email secret is the default recipient.
    $toRaw = Get-SlaInput 'to' ''; if (-not ([string]$toRaw).Trim()) { $toRaw = [string](Get-PsaSecret 'ServiceManager-Email') }
    $to = @(@($toRaw) | ForEach-Object { ([string]$_) -split '[,;]' } | ForEach-Object { $_.Trim() } | Where-Object { $_ })
    foreach ($a in $to) { if ($a -notmatch '^[^@\s]+@[^@\s]+\.[^@\s]+$') { throw "'$a' in to isn't an email address." } }
    $settings = [ordered]@{
        psa = [string](Get-SlaInput 'psa' ''); near_breach_percent = $near; sla_hours_by_priority = $hours; max_tickets = $maxT; use_psa_sla = $usePsaSla
        skip_statuses = $skip; to = @($to); from = [string](Get-SlaInput 'from' ''); message_stream = [string](Get-SlaInput 'message_stream' 'outbound')
        company = [string](@(@('company', 'company_id', 'companyId') | ForEach-Object { Get-SlaInput $_ '' } | Where-Object { ([string]$_).Trim() }) | Select-Object -First 1)
        companyId = ''; companyName = ''
    }
}
catch { Stop-SlaRun 'rejected' "The SLA report didn't run because an input is invalid: $($_.Exception.Message)" }

# ---- read the PSA ----
try { $conn = Connect-Psa (Get-PsaType $settings.psa) }
catch { Stop-SlaRun 'error' "The SLA report couldn't connect to the PSA. $($_.Exception.Message)" }
$psaName = Get-PsaName
# Optional company input: a PSA company id or exact name. Only that company's tickets are read.
try { $co = Resolve-PsaCompanyId $settings.company; $settings.companyId = $co.id; $settings.companyName = $co.name }
catch { Stop-SlaRun 'rejected' "The SLA report didn't run because the company input couldn't be matched: $($_.Exception.Message)" }
$scope = if ($settings.companyName) { " for $($settings.companyName)" } elseif ($settings.companyId) { " for company $($settings.companyId)" } else { '' }
$now = [datetime]::UtcNow
try { $open = @(Find-PsaTickets -Open -CompanyId $settings.companyId -Max $maxT -IncludeSla) }
catch { Stop-SlaRun 'error' "The SLA report couldn't read open tickets from $psaName. $($_.Exception.Message)" }
$null = $run.actions.Add("Read $($open.Count) open tickets$scope from $psaName.")
if ($PsaState.FindTruncated) { $null = $run.warnings.Add("Stopped at max_tickets ($maxT), so some open tickets weren't checked. Raise max_tickets to check them all.") }

$counts = [ordered]@{ open = $open.Count; skipped = 0; breached = 0; nearBreach = 0; psaSla = 0; defaultHours = 0; slaPausedOrMet = 0 }
$flagged = New-Object System.Collections.ArrayList
$slaWarned = @{ done = $false }
foreach ($t in $open) {
    $st = $t.status.ToLowerInvariant()
    if (@($skip | Where-Object { $st.Contains($_) }).Count) { $counts.skipped++; continue }
    $sla = @{ source = 'none'; kind = ''; start = $t.created; target = $null; breached = $null; detail = '' }
    if ($usePsaSla) {
        try { $sla = Get-PsaTicketSla $t }
        catch { if (-not $slaWarned.done) { $slaWarned.done = $true; $null = $run.warnings.Add("Couldn't read $psaName SLA details for some tickets, so they were measured against the default hours. First error: $($_.Exception.Message)") } }
    }
    $prio = if ($t.priorityLevel) { $t.priorityLevel } else { 'medium' }
    if ($sla.source -eq 'psa') {
        $source = 'PSA SLA'; $start = $sla.start; $target = $sla.target; $kind = $sla.kind; $detail = $sla.detail
        if ($null -eq $target -and $sla.breached -ne $true) { $counts.slaPausedOrMet++; continue }
    }
    else {
        if ($null -eq $t.created) { continue }
        $source = 'Default hours'; $start = $t.created; $target = $t.created.AddHours($hours[$prio]); $kind = 'resolve'
        $detail = "Default target of $($hours[$prio]) hours from creation for $prio priority"
    }
    $pct = 100
    if ($null -ne $target -and $null -ne $start) {
        $total = ($target - $start).TotalMinutes
        $pct = if ($total -gt 0) { [int][Math]::Round(100 * ($now - $start).TotalMinutes / $total) } else { 100 }
    }
    $breached = ($null -ne $target -and $now -ge $target) -or ($sla.breached -eq $true)
    if (-not $breached -and $pct -lt $near) { continue }
    if ($breached) { $counts.breached++ } else { $counts.nearBreach++ }
    if ($source -eq 'PSA SLA') { $counts.psaSla++ } else { $counts.defaultHours++ }
    $null = $flagged.Add(@{ t = $t; state = $(if ($breached) { 'breached' } else { 'near' }); pct = $pct; target = $target; kind = $kind; source = $source; detail = $detail; prio = $prio })
}

try { Resolve-PsaTicketNames @($flagged | ForEach-Object { $_.t }) }
catch { $null = $run.warnings.Add("Couldn't look up some company or technician names: $($_.Exception.Message)") }

$rows = @($flagged | ForEach-Object {
        $t = $_.t
        $mins = if ($null -ne $_.target) { [int][Math]::Round(($_.target - $now).TotalMinutes) } else { $null }
        [ordered]@{
            id = $t.id; number = $t.number; summary = $t.summary; company = $t.companyName; technician = $t.assigneeName; queue = $t.queueName
            status = $t.status; priority = $_.prio; priorityLabel = $t.priority; state = $_.state; percentUsed = $_.pct
            targetKind = $_.kind; target = $(if ($null -ne $_.target) { $_.target.ToString('yyyy-MM-ddTHH:mm:ssZ') } else { '' }); minutesLeft = $mins
            slaSource = $_.source; slaDetail = $_.detail; created = $(if ($t.created) { $t.created.ToString('yyyy-MM-ddTHH:mm:ssZ') } else { '' })
        }
    } | Sort-Object @{ e = { $_.company } }, @{ e = { $_.technician } }, @{ e = { if ($_.state -eq 'breached') { 0 } else { 1 } } }, @{ e = { $_.percentUsed }; Descending = $true })

$checked = $open.Count - $counts.skipped
$msg = if (-not $rows.Count) { "No open tickets$scope have breached their SLA or are close to it. $checked open tickets were checked." }
else { "$($counts.breached) open ticket$(if ($counts.breached -ne 1) { 's have' } else { ' has' }) breached SLA and $($counts.nearBreach) $(if ($counts.nearBreach -ne 1) { 'are' } else { 'is' }) close to it ($near% or more of the time used), out of $checked open tickets checked$scope." }
if ($counts.skipped) { $msg += " $($counts.skipped) waiting or scheduled tickets were left out." }

Set-NodeOutput ([ordered]@{
        status = 'success'; message = $msg; public_note = ''; internal_note = $msg; ticket_id = ''
        psa = $conn.Psa; psaName = $psaName; companyId = $settings.companyId; companyName = $settings.companyName; generatedAt = $now.ToString('yyyy-MM-ddTHH:mm:ssZ')
        counts = $counts; tickets = @($rows); settings = $settings
        actions = @($run.actions); warnings = @($run.warnings)
    })
