# === NODE: Note and link ===
# Reads the AI's picks, keeps only ids from the shortlist, and writes one internal note on the ticket
# listing the matches with links. Linking only happens with confirm=true, through the PSA's own
# relation where it has one (HaloPSA parent ticket; Autotask and Zendesk incident of a Problem
# ticket), otherwise cross-reference notes. Nothing is ever merged or closed.
# When the AI answer is missing or unreadable, the ServiceAI picks that passed the checks are used,
# and strong word matches are listed as "possible" but never linked.
# >>> _shared/psa.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/psa.ps1
# >>> _shared/psa-tickets.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/psa-tickets.ps1
# >>> _shared/plan.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/plan.ps1
$ErrorActionPreference = 'Stop'

function Get-Prop { param($o, [string]$n) if ($null -eq $o) { return $null }; if ($o -is [System.Collections.IDictionary]) { if ($o.Contains($n)) { return $o[$n] }; return $null }; $p = $o.PSObject.Properties[$n]; if ($p) { return $p.Value }; return $null }
function Read-Json { param($v) if ($null -eq $v) { return $null }; if ($v -isnot [string]) { return $v }; if (-not $v.Trim()) { return $null }; try { return ($v | ConvertFrom-Json -NoEnumerate) } catch { return $null } }
$stopState = @{ done = $false; ticket = '' }
function Stop-Write {
    param([string]$Status, [string]$Why)
    $stopState.done = $true
    Set-NodeOutput ([ordered]@{ status = $Status; message = $Why; public_note = ''; internal_note = "Related ticket check stopped: $Why"; ticket_id = $stopState.ticket; actions = @(); warnings = @(); chatReply = $Why })
    throw $Why
}
trap { if (-not $stopState.done) { $stopState.done = $true; Set-NodeOutput ([ordered]@{ status = 'error'; message = [string]$_.Exception.Message; public_note = ''; internal_note = "Related ticket check failed while writing to the PSA: $($_.Exception.Message)"; ticket_id = $stopState.ticket; actions = @(); warnings = @(); chatReply = "The related ticket check failed: $($_.Exception.Message)" }) }; break }

$req = Read-Json (Get-NodeInput -Name 'request')
$src = Read-Json (Get-NodeInput -Name 'source')
$cands = @(Read-Json (Get-NodeInput -Name 'candidates') | Where-Object { $null -ne $_ })
$sugg = @(Read-Json (Get-NodeInput -Name 'suggested') | Where-Object { $null -ne $_ })
$aiRaw = Get-NodeInput -Name 'judgment'
if ($null -eq $req -or $null -eq $src) { Stop-Write 'error' 'The ticket details from the first step are missing. Run the workflow from the start.' }
$stopState.ticket = [string](Get-Prop $src 'number')
$warnings = New-Object System.Collections.ArrayList
$actions = New-Object System.Collections.ArrayList
foreach ($w in @(Read-Json (Get-NodeInput -Name 'warnings_json'))) { if ($w) { $null = $warnings.Add([string]$w) } }
foreach ($a in @(Read-Json (Get-NodeInput -Name 'actions_json'))) { if ($a) { $null = $actions.Add([string]$a) } }

$confirm = (Get-Prop $req 'confirm') -eq $true
$addNote = (Get-Prop $req 'addNote') -ne $false
$noteWhenNone = (Get-Prop $req 'noteWhenNone') -eq $true
$minConf = 0.6; try { $minConf = [double](Get-Prop $req 'minConfidence') } catch { }
$srcId = [string](Get-Prop $src 'id'); $srcNum = [string](Get-Prop $src 'number')
$byId = @{}; foreach ($c in $cands) { $byId[[string](Get-Prop $c 'id')] = $c }
$serviceAiReason = [string](Get-Prop $req 'reason')

# ---- the AI's picks, checked against the shortlist ----
$ai = $null; $aiText = [string]$aiRaw
if ($aiRaw -and $aiRaw -isnot [string]) { $ai = $aiRaw }
elseif ($aiText -match '(?s)\{.*\}') { try { $ai = $Matches[0] | ConvertFrom-Json } catch { $ai = $null } }
$matches2 = New-Object System.Collections.ArrayList
$possible = New-Object System.Collections.ArrayList
$by = 'ai'
$hasMatches = $null -ne $ai -and $(if ($ai -is [System.Collections.IDictionary]) { $ai.Contains('matches') } else { $null -ne $ai.PSObject.Properties['matches'] })
if ($hasMatches) {
    foreach ($m in @(Get-Prop $ai 'matches' | Where-Object { $null -ne $_ })) {
        $mid = ([string](Get-Prop $m 'id')).Trim().TrimStart('#')
        $hit = $null
        if ($byId.ContainsKey($mid)) { $hit = $byId[$mid] } else { $hit = @($cands | Where-Object { [string](Get-Prop $_ 'number') -eq $mid }) | Select-Object -First 1 }
        if ($null -eq $hit) { $null = $warnings.Add("The AI named ticket $mid, which was not on the shortlist, so it was ignored."); continue }
        $rel = ([string](Get-Prop $m 'relation')).Trim().ToLowerInvariant(); if (@('duplicate', 'related') -notcontains $rel) { $rel = 'related' }
        $conf = 0.0; try { $conf = [double](Get-Prop $m 'confidence') } catch { $conf = 0.0 }
        if ($conf -lt $minConf) { continue }
        $why = ([string](Get-Prop $m 'reason')).Trim(); if ($why.Length -gt 300) { $why = $why.Substring(0, 300) }
        if (@($matches2 | Where-Object { $_.id -eq [string](Get-Prop $hit 'id') }).Count) { continue }
        $null = $matches2.Add(@{ id = [string](Get-Prop $hit 'id'); number = [string](Get-Prop $hit 'number'); summary = [string](Get-Prop $hit 'summary'); url = [string](Get-Prop $hit 'url'); createdAt = [string](Get-Prop $hit 'createdAt'); relation = $rel; confidence = [Math]::Round($conf, 2); reason = $why; linkable = $true })
    }
}
else {
    $by = 'rules'
    $null = $warnings.Add($(if ($aiText.Trim()) { 'The AI answer could not be read, so only checked ServiceAI picks are linked and word matches are listed as possible.' } else { 'The AI answer was empty, so only checked ServiceAI picks are linked and word matches are listed as possible.' }))
    foreach ($c in $cands) {
        $cid = [string](Get-Prop $c 'id')
        if ((Get-Prop $c 'suggestedByServiceAI') -eq $true) {
            $null = $matches2.Add(@{ id = $cid; number = [string](Get-Prop $c 'number'); summary = [string](Get-Prop $c 'summary'); url = [string](Get-Prop $c 'url'); createdAt = [string](Get-Prop $c 'createdAt'); relation = 'related'; confidence = $null; reason = $(if ($serviceAiReason) { $serviceAiReason } else { 'ServiceAI picked it.' }); linkable = $true })
        }
        elseif ([double](Get-Prop $c 'score') -ge 0.6) {
            $null = $possible.Add(@{ id = $cid; number = [string](Get-Prop $c 'number'); summary = [string](Get-Prop $c 'summary'); url = [string](Get-Prop $c 'url'); reason = "Word match ($(@(Get-Prop $c 'signals') -join '; '))." })
        }
    }
}
# ServiceAI picks that the check did not confirm.
foreach ($s in $sugg) {
    if ((Get-Prop $s 'valid') -eq $true -and -not @($matches2 | Where-Object { $_.id -eq [string](Get-Prop $s 'id') }).Count) {
        $null = $warnings.Add("ServiceAI suggested ticket $(Get-Prop $s 'ref'), but this check did not agree it is the same issue, so it was not linked.")
    }
}

# ---- the plan: relate each match (oldest first). The newer ticket is the child. ----
$conn = $null
$support = @{ relation = 'note' }
$needPsa = ($addNote -and ($matches2.Count -or $possible.Count -or $noteWhenNone)) -or ($confirm -and $matches2.Count)
if ($needPsa -or $matches2.Count) { $conn = Connect-Psa -Psa (Get-PsaType ([string](Get-Prop $req 'psa'))); $support = Get-PsaCapabilities }
$plan = New-ChangePlan "Relate tickets to #$srcNum"
$linkState = @{ sourceHasParent = $false }
$srcCreated = ConvertTo-PsaDate (Get-Prop $src 'createdAt')
$ordered = @($matches2 | Where-Object { $_.linkable } | Sort-Object -Property @{ Expression = { $d = ConvertTo-PsaDate $_.createdAt; if ($d) { $d } else { [datetime]::MinValue } } })
foreach ($m in $ordered) {
    $mCreated = ConvertTo-PsaDate $m.createdAt
    $sourceIsChild = -not ($mCreated -and $srcCreated -and $mCreated -gt $srcCreated)
    $child = if ($sourceIsChild) { $srcId } else { $m.id }; $parent = if ($sourceIsChild) { $m.id } else { $srcId }
    $childNum = if ($sourceIsChild) { $srcNum } else { $m.number }; $parentNum = if ($sourceIsChild) { $m.number } else { $srcNum }
    $notesOnly = ($support.relation -eq 'note') -or ($sourceIsChild -and $linkState.sourceHasParent)
    if ($sourceIsChild -and -not $notesOnly) { $linkState.sourceHasParent = $true }
    $how = if ($notesOnly) { "a cross-reference note on #$($m.number)" } elseif ($support.relation -eq 'native') { "make #$childNum a child of #$parentNum, plus a note on #$($m.number)" } else { "make #$childNum an incident of #$parentNum if #$parentNum is a Problem ticket, plus a note on #$($m.number)" }
    Add-PlannedChange $plan "Relate #$($m.number) to #$srcNum ($how)" { param($ch, $pa, $why, $noteOn, $onlyNotes) Add-PsaTicketRelation -Id $ch -RelatedId $pa -Reason $why -NotesOnly:$onlyNotes -NoteTicketId $noteOn } -Arguments @($child, $parent, $m.reason, $m.id, $notesOnly)
}
$result = Invoke-ChangePlan $plan -Confirm $confirm
$linked = New-Object System.Collections.ArrayList
foreach ($r in @($result.ran)) { $o = $r.output; $null = $linked.Add("$($r.description): $(if ($null -ne $o -and $o -is [System.Collections.IDictionary]) { if ($o.method -eq 'native') { $o.detail } else { 'notes only' } } else { 'done' })") }
if ($result.status -eq 'done') { $null = $actions.Add("Related $($linked.Count) ticket(s) to #$srcNum.") }

# ---- the note ----
function Format-Match { param($m) $u = if ($m.url) { " $($m.url)" } else { '' }; $c = if ($null -ne $m.confidence) { " ($([int]($m.confidence * 100))% confident)" } else { '' }; return "- #$($m.number) `"$($m.summary)`"$($c): $($m.reason)$u" }
$dups = @($matches2 | Where-Object { $_.relation -eq 'duplicate' })
$rels = @($matches2 | Where-Object { $_.relation -eq 'related' })
$lines = New-Object System.Collections.ArrayList
$null = $lines.Add("Related ticket check for #$srcNum ($(if ($by -eq 'ai') { 'AI review of a word-match shortlist' } else { 'word match only; the AI answer was not available' })).")
$null = $lines.Add("Checked $(@($cands).Count) shortlisted open ticket(s) for this company from the last $(Get-Prop $req 'days') day(s).")
if ($dups.Count) { $null = $lines.Add(''); $null = $lines.Add('Possible duplicates:'); foreach ($m in $dups) { $null = $lines.Add((Format-Match $m)) } }
if ($rels.Count) { $null = $lines.Add(''); $null = $lines.Add('Related tickets:'); foreach ($m in $rels) { $null = $lines.Add((Format-Match $m)) } }
if ($possible.Count) { $null = $lines.Add(''); $null = $lines.Add('Possible matches to check by hand (not linked):'); foreach ($m in $possible) { $null = $lines.Add("- #$($m.number) `"$($m.summary)`": $($m.reason)$(if ($m.url) { " $($m.url)" })") } }
if (-not $matches2.Count -and -not $possible.Count) { $null = $lines.Add('No open ticket for this company looks like the same issue.') }
$null = $lines.Add('')
switch ($result.status) {
    'preview' { $null = $lines.Add("Not linked yet. Run the Link Related Tickets action again with confirm set to true to: $(@($result.planned) -join '; ').") }
    'done' { $null = $lines.Add("Linked: $(@($linked) -join '; ').") }
    'failed' { $null = $lines.Add("Linking stopped: $($result.message)") }
}
if ($dups.Count) { $null = $lines.Add('If a duplicate is confirmed, a technician can merge or close one ticket. This check never merges or closes tickets.') }
foreach ($w in $warnings) { $null = $lines.Add("Note: $w") }
$note = ($lines -join "`n").Trim()

# Retry guard: the same ticket, outcome and matches give the same marker, so a retried run adds no second note.
$noteIds = @(@($matches2 | ForEach-Object { $_.id }) + @($possible | ForEach-Object { $_.id }) | Sort-Object -Unique)
$noteMarker = "related ticket check $srcId $($result.status) $(if ($noteIds.Count) { $noteIds -join ',' } else { 'none' })"
$noteWritten = $false
if ($addNote -and ($matches2.Count -or $possible.Count -or $noteWhenNone)) {
    $noteResult = Add-PsaNote -Id $srcId -Text $note -Title 'Related ticket check' -Marker $noteMarker
    $noteWritten = $noteResult -eq 'written'
    $null = $actions.Add($(if ($noteWritten) { "Added an internal note to #$srcNum listing $($matches2.Count + $possible.Count) match(es)." } else { "The internal note on #$srcNum was already there from an earlier run, so it was not added again." }))
}

$status = 'success'
if ($result.status -eq 'preview') { $status = 'pending_confirmation' }
elseif ($result.status -eq 'failed') { $status = 'incomplete' }
$count = $matches2.Count
$message = if (-not $count -and -not $possible.Count) { "No related open tickets were found for #$srcNum." }
elseif ($result.status -eq 'preview') { "Found $count related ticket(s) for #$srcNum. Nothing was linked; send confirm=true to link them." }
elseif ($result.status -eq 'done') { "Found and linked $count related ticket(s) for #$srcNum. Nothing was merged or closed." }
elseif ($result.status -eq 'failed') { "Found $count related ticket(s) for #$srcNum, but linking stopped: $($result.message)" }
else { "Found $($possible.Count) possible match(es) for #$srcNum to check by hand. Nothing was linked." }
$chat = if ($count) { "#$srcNum looks related to $((@($matches2 | ForEach-Object { "#$($_.number) ($($_.relation))" })) -join ', ').$(if ($result.status -eq 'preview') { ' Say yes to link them (confirm=true). Nothing is merged or closed.' } elseif ($result.status -eq 'done') { ' They are linked now.' })" } else { $message }

Set-NodeOutput ([ordered]@{
        status = $status; message = $message; public_note = ''; internal_note = $note
        ticket_id = $srcNum; psa = $(if ($conn) { $conn.Psa } else { [string](Get-Prop $req 'psa') })
        matches = @($matches2 | ForEach-Object { [ordered]@{ id = $_.id; number = $_.number; relation = $_.relation; confidence = $_.confidence; reason = $_.reason; url = $_.url } })
        possible = @($possible | ForEach-Object { [ordered]@{ id = $_.id; number = $_.number; reason = $_.reason; url = $_.url } })
        classified_by = $by; planned = @($result.planned); linked = @($linked); note_written = $noteWritten
        counts = [ordered]@{ candidates = @($cands).Count; matches = $count; possible = $possible.Count; linked = $linked.Count }
        actions = @($actions); warnings = @($warnings); chatReply = $chat
    })
