# === NODE: Post the notice and record it ===
# Builds one plan for every affected company, previews it, and only makes the changes when confirm is true.
#   Banner token: the CloudRadial API has no news, announcement or banner resource, so the notice goes
#     into a company token (default @ServiceStatus) that the portal's home page or banner shows. Broadcast
#     sets it; resolved clears it, but only when it still shows this service.
#   Service Status article: one knowledge base article per company in the "Service Status" category,
#     pinned to the portal front page while the outage is open and unpinned with a resolution when it ends.
#   Email (off unless emailContacts is true): the company's primary contact from the PSA, one email per
#     company through Postmark. Without the Postmark secrets nothing is emailed and the ticket note says so.
#   Problem ticket: an internal note listing what ran, on the ticket in problemTicketId (or ticketId). The note
#     carries a marker built from the mode, service and message, so a retried or repeated run doesn't add it twice.
# A company whose banner and article already show this exact notice is skipped, so a retried run doesn't email twice.
# >>> _shared/plan.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/plan.ps1
# >>> _shared/cloudradial.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/cloudradial.ps1
# >>> _shared/psa.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/psa.ps1
# >>> _shared/psa-tickets.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/psa-tickets.ps1
# >>> _shared/postmark.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/postmark.ps1
$ErrorActionPreference = 'Stop'

function Get-ObState { $in = Get-NodeInput; $s = [ordered]@{}; if ($null -ne $in) { if ($in -is [System.Collections.IDictionary]) { foreach ($k in @($in.Keys)) { $s[[string]$k] = $in[$k] } } else { foreach ($p in $in.PSObject.Properties) { $s[$p.Name] = $p.Value } } }; return $s }
function Get-ObList { param($S, [string]$Key) if (-not $S.Contains($Key)) { return @() }; return @(@($S[$Key]) | Where-Object { $null -ne $_ -and [string]$_ -ne '' }) }
# The step's own warnings first, then the ones _shared/psa.ps1 recorded in $PsaState.Warnings (a priority it
# couldn't set, a write answered with a redirect), each once and in its own words.
function Get-ObWarnings {
    param($Own)
    $all = New-Object System.Collections.ArrayList
    foreach ($w in @(@($Own) + @($PsaState.Warnings))) { $t = [string]$w; if ($t -and -not $all.Contains($t)) { $null = $all.Add($t) } }
    return @($all)
}
function ConvertTo-ObHtml { param([string]$t) return (@(([System.Net.WebUtility]::HtmlEncode($t)) -split "\r?\n\r?\n" | Where-Object { $_.Trim() } | ForEach-Object { '<p>' + ($_.Trim() -replace "\r?\n", '<br>') + '</p>' }) -join '') }

$st = Get-ObState
$status = [string]$st['status']
if ($status -ne 'ok') {
    if (-not [string]$st['chatReply']) { $st['chatReply'] = [string]$st['message'] }
    $st['warnings'] = @(Get-ObWarnings (Get-ObList $st 'warnings'))
    Set-NodeOutput $st; return
}
$warnings = New-Object System.Collections.ArrayList; foreach ($w in @(Get-ObList $st 'warnings')) { $null = $warnings.Add([string]$w) }
$actions = New-Object System.Collections.ArrayList
$mode = [string]$st['mode']; $resolved = $mode -eq 'resolved'
$service = [string]$st['affectedService']; $notice = [string]$st['notice']
$tokenName = [string]$st['bannerToken']; $category = [string]$st['articleCategory']
$confirm = [bool]$st['confirm']; $ticketId = [string]$st['ticket_id']
$postBanner = [bool]$st['postBanner']; $postArticle = [bool]$st['postArticle']; $emailContacts = [bool]$st['emailContacts']
$targets = @(Get-ObList $st 'targets')
$by = [string]$st['requestedBy']; if (-not $by) { $by = 'not identified (map the ServiceAI requester field from received_keys)' }
$now = (Get-Date).ToUniversalTime()
$when = $now.ToString('yyyy-MM-dd HH:mm') + ' UTC'
$subjectBase = "Service status: $service"

# The notice the client sees, the same text for every company (it never names another client).
$bannerValue = if ($resolved) { '' } else { "$($service): $notice" }
if ($bannerValue.Length -gt 1000) { $bannerValue = $bannerValue.Substring(0, 1000) }
$articleSubject = if ($resolved) { "$subjectBase (resolved)" } else { $subjectBase }
$articleBody = if ($resolved) { "<p><strong>Resolved.</strong></p>$(ConvertTo-ObHtml $notice)<p>Resolved $when.</p>" } else { "$(ConvertTo-ObHtml $notice)<p>Posted $when. We will update this page when the issue is resolved.</p>" }
$emailSubject = if ($resolved) { "Resolved: $service" } else { "Service notice: $service" }

$null = Connect-Cr

# PSA: needed for the problem ticket note and for the primary contacts. Optional: without it, both are skipped with a warning.
$psaReady = $false
$psaType = ''
try { $psaType = Get-PsaType ([string]$st['psa']) } catch { $null = $warnings.Add($_.Exception.Message) }
if ($psaType -and ($ticketId -or $emailContacts)) {
    try { $null = Connect-Psa $psaType; $psaReady = $true } catch { $null = $warnings.Add("The PSA isn't connected, so no ticket note or contact lookup was done: $($_.Exception.Message)") }
}
elseif (-not $psaType -and ($ticketId -or $emailContacts)) { $null = $warnings.Add('No PSA is set up (the PSA-Type secret), so no ticket note or contact lookup was done.') }

# Postmark: only when emailContacts is on.
$pm = $null
if ($emailContacts) {
    if (Test-PmConfigured) { $pm = $true }
    else { $null = $warnings.Add('emailContacts is on, but the Postmark-ServerToken and Postmark-FromEmail secrets are not set, so no email was sent. The problem ticket note lists who would have been emailed.') }
}
function Send-ObEmail {
    param([string]$To, [string]$Name, [string]$Subject, [string]$Text)
    $greet = if ($Name) { "Hello $Name," } else { 'Hello,' }
    $body = "$greet`n`n$Text`n`nThank you,`nYour IT support team"
    # Send-PmMail never throws, so a failed send is turned into a throw here to stop the plan like any other failed change.
    $r = Send-PmMail -To $To -Subject $Subject -Text $body -Html (ConvertTo-ObHtml $body)
    if (-not $r.sent) { throw "The email to $To wasn't sent: $($r.reason)" }
    return 'sent'
}

$plan = New-ChangePlan "Outage broadcast: $service ($mode)"
$perCompany = New-Object System.Collections.ArrayList
$recipients = New-Object System.Collections.ArrayList
$unchanged = New-Object System.Collections.ArrayList

# Partner-level default: an empty token, so a company with no outage shows nothing instead of the literal @ServiceStatus.
if (-not $resolved -and $postBanner -and -not [bool]$st['partnerTokenExists']) {
    Add-PlannedChange $plan "Create the partner-level @$tokenName token with an empty value (so portals without an outage show nothing)" { param($n) $null = Invoke-CrApi -Path '/v2/token' -Method POST -Body ([ordered]@{ companyId = 0; token = $n; value = ''; type = 'String' }); 'created' } -Arguments @($tokenName)
}

foreach ($t in $targets) {
    $cid = [int]$t.companyId; $cname = [string]$t.name
    $lines = New-Object System.Collections.ArrayList
    $current = [string]$t.tokenValue
    $aid = [int]$t.articleId
    $already = $true

    if ($postBanner) {
        if ($resolved) {
            if (-not $current) { $null = $lines.Add('banner already clear') }
            elseif ($current.IndexOf($service, [StringComparison]::OrdinalIgnoreCase) -lt 0) { $null = $lines.Add('banner shows a different notice, left alone'); $null = $warnings.Add("$cname's @$tokenName banner shows a different notice, so it was left alone.") }
            else {
                $already = $false
                Add-PlannedChange $plan "$($cname): clear the @$tokenName banner" { param($c, $n) $null = Invoke-CrApi -Path '/v2/token' -Method POST -Body ([ordered]@{ companyId = $c; token = $n; value = ''; type = 'String' }); 'cleared' } -Arguments @($cid, $tokenName)
                $null = $lines.Add('clear the banner')
            }
        }
        elseif ($current -ceq $bannerValue) { $null = $lines.Add('banner already shows this notice') }
        else {
            $already = $false
            if ($current -and $current.IndexOf($service, [StringComparison]::OrdinalIgnoreCase) -lt 0) { $null = $warnings.Add("$cname's @$tokenName banner showed another notice, which this replaces.") }
            Add-PlannedChange $plan "$($cname): set the @$tokenName banner" { param($c, $n, $v) $null = Invoke-CrApi -Path '/v2/token' -Method POST -Body ([ordered]@{ companyId = $c; token = $n; value = $v; type = 'String' }); 'set' } -Arguments @($cid, $tokenName, $bannerValue)
            $null = $lines.Add($(if ($t.tokenExists) { 'update the banner' } else { 'set the banner' }))
        }
    }

    if ($postArticle) {
        $art = [ordered]@{ companyId = $cid; subject = $articleSubject; category = $category; body = $articleBody; author = 'Service desk'; datePublished = $now.ToString('yyyy-MM-ddTHH:mm:ssZ'); isFrontPage = (-not $resolved); isFavorite = (-not $resolved) }
        if ($aid -gt 0) {
            if ($resolved -and ([string]$t.articleSubject).Trim() -ieq $articleSubject) { $null = $lines.Add('article already marked resolved') }
            else {
                $already = $false
                Add-PlannedChange $plan "$($cname): $(if ($resolved) { 'mark the Service Status article resolved and unpin it' } else { 'update the pinned Service Status article' })" { param($id, $b) $null = Invoke-CrApi -Path "/v2/article/$id" -Method PUT -Body $b; "article $id updated" } -Arguments @($aid, $art)
                $null = $lines.Add($(if ($resolved) { 'mark the article resolved' } else { 'update the article' }))
            }
        }
        elseif ($resolved) { $null = $lines.Add('no Service Status article to update') }
        else {
            $already = $false
            Add-PlannedChange $plan "$($cname): publish a Service Status article pinned to the portal front page" { param($b) $r = Invoke-CrApi -Path '/v2/article' -Method POST -Body $b; "article $(Get-CrId $r @('articleId', 'data.articleId', 'id')) created" } -Arguments @($art)
            $null = $lines.Add('publish the article')
        }
    }

    if ($emailContacts) {
        if ($already -and ($postBanner -or $postArticle)) { $null = $lines.Add('no email (this notice was already posted)') }
        elseif (-not $psaReady) { $null = $lines.Add('no email (PSA not connected)') }
        elseif (-not $t.psaKey -or [string]$t.psaKey -eq '0') { $null = $lines.Add('no email (company not linked to a PSA company)'); $null = $warnings.Add("$cname isn't linked to a PSA company, so its primary contact couldn't be found.") }
        else {
            $pc = $null
            try { $pc = Get-PsaPrimaryContact ([string]$t.psaKey) } catch { $null = $warnings.Add("Couldn't read $cname's primary contact: $($_.Exception.Message)") }
            if ($null -eq $pc) { $null = $lines.Add('no email (no primary contact with an email address)') }
            else {
                $null = $recipients.Add("$cname - $(if ($pc.name) { "$($pc.name) " })<$($pc.email)>")
                if ($null -ne $pm) {
                    $already = $false
                    Add-PlannedChange $plan "$($cname): email the primary contact $($pc.email)" { param($to, $nm, $sub, $txt) Send-ObEmail $to $nm $sub $txt } -Arguments @($pc.email, $pc.name, $emailSubject, $notice)
                    $null = $lines.Add("email $($pc.email)")
                }
                else { $null = $lines.Add("would email $($pc.email), but Postmark isn't set up") }
            }
        }
    }
    if ($already) { $null = $unchanged.Add($cname) }
    $null = $perCompany.Add("$cname ($($t.reason)): $(@($lines) -join ', ')")
}

$result = Invoke-ChangePlan $plan -Confirm:$confirm
$n = $targets.Count
$names = (@($targets | ForEach-Object { [string]$_.name }) -join ', ')
$detail = (@($perCompany) | ForEach-Object { "- $_" }) -join "`n"
$verb = if ($resolved) { 'resolution for' } else { 'outage notice for' }
$out = [ordered]@{
    status = ''; message = ''; public_note = ''; internal_note = ''; chatReply = ''; ticket_id = $ticketId
    mode = $mode; affectedService = $service; confirm = $confirm; requestedBy = [string]$st['requestedBy']; triggerSource = [string]$st['triggerSource']
    targetSource = [string]$st['targetSource']; companies = @($targets | ForEach-Object { [ordered]@{ companyId = $_.companyId; name = $_.name; reason = $_.reason } })
    recipients = @($recipients); plan = $result; counts = [ordered]@{ companies = $n; changes = @($result.planned).Count; ran = @($result.ran).Count; unchanged = $unchanged.Count; emails = $recipients.Count }
    note_written = $false; note_marker = ''; received_keys = @(Get-ObList $st 'received_keys'); received_body = $st['received_body']
    actions = @(); warnings = @()
}
$out.public_note = if ($resolved) { "The issue affecting $service has been resolved. Thank you for your patience." } else { "We are aware of an issue affecting $service and are working on it. $notice" }

switch ($result.status) {
    'preview' {
        $out.status = 'pending_confirmation'
        $out.message = "Preview only, nothing was changed. This would post the $verb $service to $n compan$(if ($n -eq 1) { 'y' } else { 'ies' }) ($($result.planned.Count) changes). Run again with confirm set to true to go ahead."
        $out.chatReply = "Here's the preview for $($service): $n compan$(if ($n -eq 1) { 'y' } else { 'ies' }) ($names).$(if ($recipients.Count) { " $($recipients.Count) primary contact(s) would be emailed." }) Nothing has changed yet. Say yes and I'll run it with confirm true."
    }
    'empty' {
        $out.status = 'success'
        $out.message = "Every affected company already shows this $(if ($resolved) { 'resolution' } else { 'notice' }), so nothing needed to change."
        $out.chatReply = $out.message
    }
    'done' {
        $out.status = 'success'
        $out.message = "Posted the $verb $service to $n compan$(if ($n -eq 1) { 'y' } else { 'ies' }): $($result.ran.Count) change$(if ($result.ran.Count -ne 1) { 's' }) made."
        $out.chatReply = "Done. The $verb $service is posted for $names."
    }
    'failed' {
        $out.status = 'error'
        $out.message = $result.message
        $out.chatReply = "The broadcast stopped part way: $($result.failed.description) failed. Check the problem ticket note for what ran."
    }
}
foreach ($r in @($result.ran)) { $null = $actions.Add([ordered]@{ action = $r.description; result = [string]$r.output }) }
if ($null -ne $result.failed) { $null = $actions.Add([ordered]@{ action = $result.failed.description; result = "failed: $($result.failed.error)" }) }

$noteWarnings = @(Get-ObWarnings $warnings)
$noteText = @(
    "Outage broadcast ($mode) for $service, $when."
    "Run by: $by$(if ($st['triggerSource']) { " (via $($st['triggerSource']))" })."
    "Affected companies ($n), from $($st['targetSource']):"
    $detail
    $(if ($recipients.Count) { "Primary contacts$(if ($null -eq $pm) { ' (not emailed, Postmark is not set up)' }): $(@($recipients) -join '; ')" })
    "Client message: $notice"
    "Result: $($result.message)"
    $(if ($noteWarnings.Count) { "Warnings: $($noteWarnings -join ' ')" })
) | Where-Object { $_ }
$out.internal_note = ($noteText -join "`n")

# Retry guard: the same mode, service and client message always give the same marker, so a ServiceAI Retry (or a
# repeated run) finds the note already on the ticket and writes nothing. A failed run has its own marker, so a later
# retry that finishes still records its result.
$sha = [System.Security.Cryptography.SHA256]::Create()
$hash = (-join @($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes("$mode|$($service.Trim().ToLowerInvariant())|$($notice.Trim())")) | Select-Object -First 6 | ForEach-Object { $_.ToString('x2') }))
$sha.Dispose()
$noteMarker = "outage-broadcast $mode $hash$(if ($result.status -eq 'failed') { ' failed' })"
$out.note_marker = $noteMarker

# The problem ticket note is written only when the run was confirmed, so a preview changes nothing anywhere.
if ($confirm -and $ticketId) {
    if ($psaReady) {
        try {
            $nr = Add-PsaNote -Id $ticketId -Text $out.internal_note -Title "Outage broadcast: $service" -Marker $noteMarker
            $out.note_written = ($nr -eq 'written')
            $null = $actions.Add([ordered]@{ action = "Internal note on problem ticket $ticketId"; result = $(if ($nr -eq 'written') { 'written' } else { 'already on the ticket from an earlier run, not written again' }) })
        }
        catch { $null = $warnings.Add("The internal note on ticket $ticketId failed: $($_.Exception.Message)"); $null = $actions.Add([ordered]@{ action = "Internal note on problem ticket $ticketId"; result = "failed: $($_.Exception.Message)" }) }
    }
}
elseif ($confirm -and -not $ticketId) { $null = $warnings.Add('No problemTicketId was sent, so no ticket note was written. The summary is in internal_note.') }

$out.actions = @($actions)
$out.warnings = @(Get-ObWarnings $warnings)
Set-NodeOutput $out
