# === NODE: Post the internal note ===
# Puts the AI summary and the figures from the first step into one internal (technician-only) note
# on the ticket. The figures are copied from the PSA, never from the AI. When the AI answer is empty
# or unusable, a plain summary built from the figures is used instead. addNote=false returns the note
# as a preview and writes nothing. Nothing else in the PSA is changed.
# >>> _shared/psa.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/psa.ps1
# >>> src/psa-extra.ps1 (generated by src/build.js; edit the source, not this block)
# <<< src/psa-extra.ps1
$ErrorActionPreference = 'Stop'

function Get-Prop { param($o, [string]$n) if ($null -eq $o) { return $null }; if ($o -is [System.Collections.IDictionary]) { if ($o.Contains($n)) { return $o[$n] }; return $null }; $p = $o.PSObject.Properties[$n]; if ($p) { return $p.Value }; return $null }
function Read-Json { param($v) if ($null -eq $v) { return $null }; if ($v -isnot [string]) { return $v }; if (-not $v.Trim()) { return $null }; try { return ($v | ConvertFrom-Json -NoEnumerate) } catch { return $null } }
$stopState = @{ done = $false; ticket = '' }
function Stop-Note {
    param([string]$Status, [string]$Why)
    $stopState.done = $true
    Set-NodeOutput ([ordered]@{ status = $Status; message = $Why; public_note = ''; internal_note = "Invoice context stopped: $Why"; ticket_id = $stopState.ticket; actions = @(); warnings = @(); chatReply = $Why })
    throw $Why
}
trap { if (-not $stopState.done) { $stopState.done = $true; Set-NodeOutput ([ordered]@{ status = 'error'; message = [string]$_.Exception.Message; public_note = ''; internal_note = "Invoice context failed while writing the note: $($_.Exception.Message)"; ticket_id = $stopState.ticket; actions = @(); warnings = @(); chatReply = "Invoice context failed: $($_.Exception.Message)" }) }; break }

$req = Read-Json (Get-NodeInput -Name 'request')
$fig = Read-Json (Get-NodeInput -Name 'figures')
$aiRaw = Get-NodeInput -Name 'summary'
if ($null -eq $req -or $null -eq $fig) { Stop-Note 'error' 'The billing figures from the first step are missing. Run the workflow from the start.' }
$stopState.ticket = [string](Get-Prop $req 'ticketId')
$warnings = New-Object System.Collections.ArrayList
$actions = New-Object System.Collections.ArrayList
foreach ($w in @(Read-Json (Get-NodeInput -Name 'warnings_json'))) { if ($w) { $null = $warnings.Add([string]$w) } }
foreach ($a in @(Read-Json (Get-NodeInput -Name 'actions_json'))) { if ($a) { $null = $actions.Add([string]$a) } }

$ticketRef = [string](Get-Prop $req 'ticketId')
$addNote = (Get-Prop $req 'addNote') -ne $false
$period = [string](Get-Prop $fig 'period')
$company = [string](Get-Prop $fig 'companyName'); if (-not $company) { $company = 'this company' }
$psaName = [string](Get-Prop $fig 'psa')
$timeOk = (Get-Prop $fig 'timeAvailable') -eq $true
$agrOk = (Get-Prop $fig 'agreementsAvailable') -eq $true
$inv = Get-Prop $fig 'invoice'
$top = @(Get-Prop $fig 'topTickets' | Where-Object { $null -ne $_ })
$agr = @(Get-Prop $fig 'agreements' | Where-Object { $null -ne $_ })
$hrs = { param($v) ([double]$v).ToString('0.0', [System.Globalization.CultureInfo]::InvariantCulture) }
$money = { param($v) ([double]$v).ToString('#,0.00', [System.Globalization.CultureInfo]::InvariantCulture) }

# ---- the AI summary, or a plain one from the figures ----
$text = ([string]$aiRaw).Trim()
$text = ($text -replace '(?s)^```[a-zA-Z]*\s*', '' -replace '(?s)\s*```$', '').Trim()
$by = 'ai'
if (-not $text -or $text.StartsWith('{') -or $text.StartsWith('[') -or $text.Length -lt 40) {
    $by = 'figures'
    $null = $warnings.Add($(if ($text) { 'The AI summary could not be used, so a plain summary was built from the figures.' } else { 'The AI summary was empty, so a plain summary was built from the figures.' }))
    $s = New-Object System.Collections.ArrayList
    if ($null -ne $inv) { $null = $s.Add("Invoice $(Get-Prop $inv 'number') is dated $(Get-Prop $inv 'date') with a total of $(& $money (Get-Prop $inv 'total')).") }
    if ($timeOk) {
        $null = $s.Add("In $period, $(& $hrs (Get-Prop $fig 'totalHours')) hours were logged on $(Get-Prop $fig 'ticketsWithTime') ticket(s), of which $(& $hrs (Get-Prop $fig 'billableHours')) were billable and $(& $hrs (Get-Prop $fig 'nonBillableHours')) were not.")
        if ($top.Count) { $null = $s.Add("The most time went to $((@($top | Select-Object -First 3 | ForEach-Object { "#$($_.number) ($(& $hrs $_.hours) h)" })) -join ', ').") }
    }
    else { $null = $s.Add("Time entries are not available from $psaName, so hours could not be checked.") }
    $null = $s.Add("$(Get-Prop $fig 'ticketsOpened') ticket(s) were opened in the period.")
    if ($agrOk) { $null = $s.Add($(if ($agr.Count) { "Agreements in effect: $((@($agr | ForEach-Object { $_.name })) -join ', ')." } else { 'No agreement was in effect during the period.' })) }
    $text = $s -join ' '
}
if ($text.Length -gt 2000) { $text = $text.Substring(0, 2000) + '...' }

# ---- the note ----
$lines = New-Object System.Collections.ArrayList
$null = $lines.Add("Invoice context for $company, $period$(if (Get-Prop $req 'invoiceNumber') { ", invoice $(Get-Prop $req 'invoiceNumber')" }). Prepared for the account manager; not sent to the client.")
$null = $lines.Add('')
$null = $lines.Add('Summary:')
$null = $lines.Add($text)
$null = $lines.Add('')
$null = $lines.Add("Figures from $($psaName):")
if ($null -ne $inv) { $null = $lines.Add("- Invoice $(Get-Prop $inv 'number'): dated $(Get-Prop $inv 'date'), total $(& $money (Get-Prop $inv 'total')).") }
$null = $lines.Add("- Tickets opened in the period: $(Get-Prop $fig 'ticketsOpened') ($(Get-Prop $fig 'ticketsOpenedClosed') closed since).")
if ($timeOk) {
    $null = $lines.Add("- Time logged: $(& $hrs (Get-Prop $fig 'totalHours')) h ($(& $hrs (Get-Prop $fig 'billableHours')) h billable, $(& $hrs (Get-Prop $fig 'nonBillableHours')) h not billable) on $(Get-Prop $fig 'ticketsWithTime') ticket(s).")
    $null = $lines.Add("- Time logged against an agreement: $(& $hrs (Get-Prop $fig 'hoursOnAgreements')) h.")
}
else { $null = $lines.Add("- Time entries: not available from $psaName.") }
if ($top.Count) {
    $null = $lines.Add(''); $null = $lines.Add('Tickets with the most time:')
    foreach ($x in $top) { $null = $lines.Add("- #$($x.number) `"$($x.summary)`": $(& $hrs $x.hours) h ($(& $hrs $x.billableHours) h billable), $($x.status).$(if ($x.url) { " $($x.url)" })") }
}
if ($agrOk) {
    $null = $lines.Add(''); $null = $lines.Add('Agreements in effect:')
    if (-not $agr.Count) { $null = $lines.Add('- None.') }
    foreach ($x in $agr) {
        $bits = @(@($x.type, $x.status) | Where-Object { $_ })
        $amt = if ([double]$x.amount -gt 0) { " $(& $money $x.amount)$(if ($x.cycle) { " per $($x.cycle)" })." } else { '' }
        $null = $lines.Add("- $($x.name)$(if ($bits.Count) { " ($($bits -join ', '))" }):$amt$(if ($x.coverage) { " Covers $($x.coverage)." })$(if ($timeOk) { " $(& $hrs $x.hoursLogged) h logged against it." })")
    }
}
else { $null = $lines.Add("- Agreements: not available from $psaName.") }
if ($warnings.Count) { $null = $lines.Add(''); foreach ($w in $warnings) { $null = $lines.Add("Note: $w") } }
$null = $lines.Add('')
$null = $lines.Add("$(if ($by -eq 'ai') { 'The summary was written by AI from the figures above; check the figures before replying.' } else { 'The summary was built from the figures above.' }) Nothing else was changed.")
$note = ($lines -join "`n").Trim()

$written = $false
if ($addNote) {
    $null = Connect-Psa -Psa (Get-PsaType ([string](Get-Prop $req 'psa')))
    $id = Resolve-PsaTicketId $ticketRef
    Add-PsaNote -Id $id -Text $note -Title 'Invoice context'
    $written = $true
    $null = $actions.Add("Added an internal note with the invoice context to ticket $ticketRef.")
}

$hoursLine = if ($timeOk) { "$(& $hrs (Get-Prop $fig 'totalHours')) h logged ($(& $hrs (Get-Prop $fig 'billableHours')) h billable) on $(Get-Prop $fig 'ticketsWithTime') ticket(s)" } else { "time entries aren't available from $psaName" }
$topLine = if ($top.Count) { "; most time on #$($top[0].number) ($(& $hrs $top[0].hours) h)" } else { '' }
$message = if ($written) { "Invoice context for $period added as an internal note on ticket $ticketRef." } else { "Invoice context for $period is ready. Nothing was written (addNote is false)." }
Set-NodeOutput ([ordered]@{
        status = $(if ($written) { 'success' } else { 'pending_confirmation' }); message = $message; public_note = ''; internal_note = $note
        ticket_id = $ticketRef; psa = [string](Get-Prop $req 'psa'); period = $period; summary = $text; summarized_by = $by; note_written = $written
        counts = [ordered]@{ ticketsOpened = Get-Prop $fig 'ticketsOpened'; ticketsWithTime = Get-Prop $fig 'ticketsWithTime'; agreements = $agr.Count; topTickets = $top.Count }
        actions = @($actions); warnings = @($warnings)
        chatReply = "Invoice context for $company, $($period): $hoursLine$topLine.$(if ($written) { " Full summary added as an internal note on #$ticketRef." } else { ' Nothing was written.' })"
    })
