# === NODE: Collect billing records ===
# Reads the request, checks the ticket and its company, works out the billing period (the period
# input, else the invoice's own period where the PSA can look invoices up, else last month), then
# reads that company's tickets, time entries and agreements for the period and adds them up without AI.
# Only this company's records are read, and an invoice that belongs to another company stops the run.
# Accepts a flat {key:value} body (ServiceAI Action, manual run), the CloudRadial
# {Ticket:{...}, Company:{...}} shape, or either one wrapped in {trigger:...}.
# Read-only: this step never writes to the PSA.
# >>> _shared/psa.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/psa.ps1
# >>> _shared/psa-tickets.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/psa-tickets.ps1
$ErrorActionPreference = 'Stop'

function Get-Prop { param($o, [string]$n) if ($null -eq $o) { return $null }; if ($o -is [System.Collections.IDictionary]) { if ($o.Contains($n)) { return $o[$n] }; return $null }; $p = $o.PSObject.Properties[$n]; if ($p) { return $p.Value }; return $null }
$stopState = @{ done = $false }
$warnings = New-Object System.Collections.ArrayList
# The step's own warnings first, then the ones _shared/psa.ps1 recorded in $PsaState.Warnings (a priority it
# couldn't set, a write answered with a redirect), each once and in its own words.
function Get-AllWarnings {
    param($Own)
    $all = New-Object System.Collections.ArrayList
    foreach ($w in @(@($Own) + @($PsaState.Warnings))) { $t = [string]$w; if ($t -and -not $all.Contains($t)) { $null = $all.Add($t) } }
    return @($all)
}
function Stop-Run {
    param([string]$Status, [string]$Why, [string]$TicketId = '')
    $stopState.done = $true
    Set-NodeOutput ([ordered]@{
            status = $Status; message = $Why; public_note = ''
            internal_note = "Invoice context stopped before anything was written: $Why"
            ticket_id = $TicketId; actions = @(); warnings = @(Get-AllWarnings $warnings); chatReply = $Why
        })
    throw $Why
}
trap { if (-not $stopState.done) { $stopState.done = $true; Set-NodeOutput ([ordered]@{ status = 'error'; message = [string]$_.Exception.Message; public_note = ''; internal_note = "Invoice context failed while reading the PSA: $($_.Exception.Message)"; ticket_id = ''; actions = @(); warnings = @(Get-AllWarnings $warnings); chatReply = "Invoice context failed: $($_.Exception.Message)" }) }; break }

$raw = Get-NodeInput
if ($null -eq $raw) { Stop-Run 'incomplete' 'No input was received. Send at least ticketId.' }
if ($raw -is [string]) { try { $raw = $raw | ConvertFrom-Json } catch { Stop-Run 'incomplete' 'The input was text that is not valid JSON.' } }
$wrap = Get-Prop $raw 'trigger'; if ($null -ne $wrap) { $raw = $wrap; if ($raw -is [string]) { try { $raw = $raw | ConvertFrom-Json } catch { Stop-Run 'incomplete' 'The trigger body was text that is not valid JSON.' } } }

$answers = @{}
if ($raw -is [System.Collections.IDictionary]) { foreach ($k in @($raw.Keys)) { $answers[[string]$k] = $raw[$k] } }
else { foreach ($p in $raw.PSObject.Properties) { $answers[$p.Name] = $p.Value } }
$crTicket = Get-Prop $raw 'Ticket'
if ($null -ne $crTicket) {
    foreach ($q in @(Get-Prop $crTicket 'Questions')) { $qid = [string](Get-Prop $q 'Id'); if ($qid) { $answers[$qid] = Get-Prop $q 'Value' } }
    $tid = Get-Prop $crTicket 'TicketId'; if ($null -ne $tid) { $answers['ticketId'] = $tid }
}
$crCompany = Get-Prop $raw 'Company'
if ($null -ne $crCompany) { foreach ($pair in @(@('CompanyName', 'companyName'), @('CompanyPsaId', 'companyId'))) { $v = Get-Prop $crCompany $pair[0]; if ($null -ne $v) { $answers[$pair[1]] = $v } } }
function Get-Field {
    param([string[]]$Names)
    foreach ($n in $Names) {
        if (-not $answers.ContainsKey($n)) { continue }
        $v = $answers[$n]
        if ($null -eq $v -or $v -is [System.Management.Automation.PSCustomObject] -or $v -is [System.Collections.IDictionary]) { continue }
        $s = ([string]$v).Trim()
        if (-not $s -or $s.StartsWith('@') -or $s -match '^\{\{.*\}\}$' -or $s -match '^<[^>]*>$') { continue }
        return $s
    }
    return ''
}
function Get-Flag { param([string[]]$Names, [bool]$Default) $s = (Get-Field $Names).ToLowerInvariant(); if (-not $s) { return $Default }; return (@('true', 'yes', '1', 'y') -contains $s) }
function Get-Int {
    param([string[]]$Names, [int]$Default, [int]$Min, [int]$Max)
    $s = Get-Field $Names; if (-not $s) { return $Default }
    $n = 0; if (-not [int]::TryParse($s, [ref]$n) -or $n -lt $Min -or $n -gt $Max) { Stop-Run 'incomplete' "$($Names[0]) must be a whole number from $Min to $Max; '$s' isn't. Nothing was read." }
    return $n
}

$f = [ordered]@{
    ticketId      = (Get-Field @('ticketId', 'ticket_id', 'TicketId', 'ticketNumber'))
    companyName   = (Get-Field @('companyName', 'company_name', 'CompanyName'))
    companyId     = (Get-Field @('companyId', 'company_id', 'psa_company_id', 'CompanyPsaId'))
    invoiceNumber = (Get-Field @('invoiceNumber', 'invoice_number', 'invoice'))
    period        = (Get-Field @('period', 'billingPeriod', 'month'))
    psa           = (Get-Field @('psa'))
    triggerSource = (Get-Field @('triggerSource', 'trigger_source'))
    maxTickets    = (Get-Int @('maxTickets') 5 1 20)
    lookbackDays  = (Get-Int @('lookbackDays') 60 0 365)
    addNote       = (Get-Flag @('addNote') $true)
    periodStart   = ''; periodEnd = ''; periodLabel = ''; periodSource = ''
}
if (-not $f.ticketId) { Stop-Run 'incomplete' 'ticketId is missing. Send the PSA ticket number of the invoice query. Nothing was read.' }
$f.invoiceNumber = $f.invoiceNumber.TrimStart('#')

# ---- the period from the input: 2026-09, September 2026, or 2026-09-01..2026-09-30 ----
$inv = [System.Globalization.CultureInfo]::InvariantCulture
$pStart = $null; $pEnd = $null
if ($f.period) {
    $p = $f.period.Trim()
    $d1 = [datetime]::MinValue; $d2 = [datetime]::MinValue
    if ($p -match '^(\d{4})-(\d{1,2})$' -and [int]$Matches[2] -ge 1 -and [int]$Matches[2] -le 12) { $pStart = [datetime]::new([int]$Matches[1], [int]$Matches[2], 1, 0, 0, 0, [DateTimeKind]::Utc); $pEnd = $pStart.AddMonths(1) }
    elseif ($p -match '^(\d{4}-\d{2}-\d{2})\s*(?:\.\.|to|/|\s-\s)\s*(\d{4}-\d{2}-\d{2})$' -and [datetime]::TryParseExact($Matches[1], 'yyyy-MM-dd', $inv, [System.Globalization.DateTimeStyles]::AssumeUniversal -bor [System.Globalization.DateTimeStyles]::AdjustToUniversal, [ref]$d1) -and [datetime]::TryParseExact($Matches[2], 'yyyy-MM-dd', $inv, [System.Globalization.DateTimeStyles]::AssumeUniversal -bor [System.Globalization.DateTimeStyles]::AdjustToUniversal, [ref]$d2)) { $pStart = $d1; $pEnd = $d2.AddDays(1) }
    elseif ([datetime]::TryParseExact($p, [string[]]@('MMMM yyyy', 'MMM yyyy', 'MMMM, yyyy', 'yyyy MMMM'), $inv, [System.Globalization.DateTimeStyles]::AssumeUniversal -bor [System.Globalization.DateTimeStyles]::AdjustToUniversal, [ref]$d1)) { $pStart = [datetime]::new($d1.Year, $d1.Month, 1, 0, 0, 0, [DateTimeKind]::Utc); $pEnd = $pStart.AddMonths(1) }
    else { Stop-Run 'incomplete' "The period '$($f.period)' wasn't understood. Send a month such as 2026-09, or a range such as 2026-09-01..2026-09-30. Nothing was read." $f.ticketId }
    if ($pEnd -le $pStart -or ($pEnd - $pStart).TotalDays -gt 366) { Stop-Run 'incomplete' "The period '$($f.period)' must run forward and cover at most a year. Nothing was read." $f.ticketId }
    $f.periodSource = 'input'
}

$actions = New-Object System.Collections.ArrayList

# ---- the ticket and its company ----
$conn = Connect-Psa -Psa (Get-PsaType $f.psa)
$f.psa = $conn.Psa
$psaName = Get-PsaName
$support = Get-PsaCapabilities
$sourceId = ''
try { $sourceId = Resolve-PsaTicketId $f.ticketId } catch { Stop-Run 'incomplete' "Ticket $($f.ticketId) wasn't found in $($psaName): $($_.Exception.Message)" $f.ticketId }
$t = $null
try { $t = Get-PsaTicket -Id $sourceId } catch { Stop-Run 'incomplete' "Ticket $($f.ticketId) couldn't be read from $($psaName): $($_.Exception.Message)" $f.ticketId }
$companyId = [string]$t.companyId
if (Test-PsaBlank $companyId) { Stop-Run 'incomplete' "Ticket $($f.ticketId) has no company in $psaName, so its billing records can't be read. Nothing was read." $f.ticketId }
if ($f.companyId -and $f.companyId -ne $companyId) { Stop-Run 'rejected' "Ticket $($f.ticketId) belongs to a different company than the companyId sent ($($f.companyId)). Nothing was read." $f.ticketId }
if ($f.companyName) {
    $hits = @(Find-PsaCompany -Name $f.companyName)
    if (-not @($hits | Where-Object { $_.id -eq $companyId }).Count) { Stop-Run 'rejected' "Ticket $($f.ticketId) does not belong to '$($f.companyName)' in $psaName. Nothing was read." $f.ticketId }
}
$null = $actions.Add("Read ticket $($f.ticketId) (company $companyId) from $psaName.")

# ---- the invoice, where the PSA can look it up ----
$invoice = $null
if ($f.invoiceNumber) {
    if (-not $support.invoices) { $null = $warnings.Add("$psaName invoices can't be looked up by number here, so invoice $($f.invoiceNumber) was not checked.") }
    else {
        $invoice = Get-PsaInvoice -Number $f.invoiceNumber
        if ($null -eq $invoice) { $null = $warnings.Add("Invoice $($f.invoiceNumber) was not found in $psaName.") }
        elseif ($invoice.companyId -and $invoice.companyId -ne $companyId) { Stop-Run 'rejected' "Invoice $($f.invoiceNumber) does not belong to this ticket's company, so nothing about it was read or posted." $f.ticketId }
        else { $null = $actions.Add("Found invoice $($f.invoiceNumber) in $psaName.") }
    }
}
if (-not $pStart) {
    if ($null -ne $invoice -and $invoice.periodStart -and $invoice.periodEnd) {
        $pStart = $invoice.periodStart; $pEnd = $invoice.periodEnd; $f.periodSource = 'invoice'
        if ($invoice.periodDerived) { $null = $warnings.Add("The invoice has no service period in $psaName, so the calendar month before its date was used. Send period to choose another.") }
    }
    elseif ($f.invoiceNumber) { Stop-Run 'incomplete' "The billing period couldn't be worked out from invoice $($f.invoiceNumber). Send period (for example 2026-09). Nothing was posted." $f.ticketId }
    else {
        $first = [datetime]::new((Get-Date).ToUniversalTime().Year, (Get-Date).ToUniversalTime().Month, 1, 0, 0, 0, [DateTimeKind]::Utc)
        $pStart = $first.AddMonths(-1); $pEnd = $first; $f.periodSource = 'default'
        $null = $warnings.Add('No period or invoice number was given, so last month was used.')
    }
}
$f.periodStart = Format-PsaDate $pStart; $f.periodEnd = Format-PsaDate $pEnd
$isMonth = ($pStart.Day -eq 1 -and $pEnd -eq $pStart.AddMonths(1))
$f.periodLabel = if ($isMonth) { $pStart.ToString('MMMM yyyy', $inv) } else { "$($pStart.ToString('yyyy-MM-dd')) to $($pEnd.AddDays(-1).ToString('yyyy-MM-dd'))" }

# ---- tickets, time and agreements for this company only ----
$tickets = @(Find-PsaTickets -CompanyId $companyId -CreatedAfter $pStart.AddDays(-$f.lookbackDays) -CreatedBefore $pEnd -Max 500 -Order newest)
$byTicket = @{}; foreach ($x in $tickets) { $byTicket[$x.id] = $x }
$inPeriod = @($tickets | Where-Object { $_.created -and $_.created -ge $pStart })
$null = $actions.Add("Read $($tickets.Count) ticket(s) for company $companyId ($($inPeriod.Count) opened in $($f.periodLabel)).")
$timeRead = Get-PsaTimeEntries -CompanyId $companyId -TicketIds @($tickets | ForEach-Object { $_.id }) -After $pStart -Before $pEnd
$timeAvailable = [bool]$timeRead.supported
$time = @($timeRead.entries | Where-Object { $null -ne $_ })
if (-not $timeAvailable) { $null = $warnings.Add("$psaName has no time entries this workflow can read, so time was not read.") }
if ($timeAvailable) { $null = $actions.Add("Read $($time.Count) time entr$(if ($time.Count -eq 1) { 'y' } else { 'ies' }) for $($f.periodLabel).") }
$agreementsRead = Get-PsaAgreements -CompanyId $companyId
$agreementsAvailable = [bool]$agreementsRead.supported
$agreements = @($agreementsRead.agreements | Where-Object { $null -ne $_ })
if (-not $agreementsAvailable) { $null = $warnings.Add("$psaName has no agreements or contracts, so none were read.") }
$inEffect = @($agreements | Where-Object { (-not $_.startDate -or $_.startDate -lt $pEnd) -and (-not $_.endDate -or $_.endDate -ge $pStart) })
if ($agreementsAvailable) { $null = $actions.Add("Read $($agreements.Count) agreement(s); $($inEffect.Count) were in effect during the period.") }

# ---- the figures, added up without AI ----
function Get-Sum { param($Rows, [string]$Key) $s = 0.0; foreach ($x in @($Rows)) { if ($null -ne $x) { $s += [double]$x[$Key] } }; return [Math]::Round($s, 2) }
$totalHours = (Get-Sum @($time) 'hours')
$billHours = (Get-Sum @($time) 'billableHours')
$nonBill = (Get-Sum @($time | Where-Object { -not $_.billable }) 'hours')
$onAgreement = (Get-Sum @($time | Where-Object { $_.agreementId }) 'hours')
$groups = @($time | Where-Object { $_.ticketId } | Group-Object -Property { $_.ticketId })
$top = New-Object System.Collections.ArrayList
foreach ($g in @($groups | Sort-Object -Property @{ Expression = { Get-Sum $_.Group 'hours' } } -Descending | Select-Object -First $f.maxTickets)) {
    $tk = if ($byTicket.ContainsKey($g.Name)) { $byTicket[$g.Name] } else { $null }
    if ($null -eq $tk) {
        try { $rt = Get-PsaTicket -Id $g.Name; if ([string]$rt.companyId -eq $companyId) { $tk = @{ id = $g.Name; number = $g.Name; summary = $rt.summary; status = $rt.status } } } catch { $tk = $null }
    }
    if ($null -eq $tk) { continue }
    $null = $top.Add([ordered]@{
            id = [string]$g.Name; number = [string]$(if ($tk.number) { $tk.number } else { $g.Name }); summary = [string]$tk.summary; status = [string]$tk.status
            hours = ((Get-Sum @($g.Group) 'hours')); billableHours = ((Get-Sum @($g.Group) 'billableHours')); url = (Get-PsaTicketUrl $g.Name)
        })
}
$agreementRows = @(foreach ($a in $inEffect) {
        $h = (Get-Sum @($time | Where-Object { $_.agreementId -eq $a.id }) 'hours')
        [ordered]@{ name = $a.name; type = $a.type; status = $a.status; amount = $a.amount; cycle = $a.cycle; coverage = $a.coverage; hoursLogged = $h
            starts = $(if ($a.startDate) { $a.startDate.ToString('yyyy-MM-dd') } else { '' }); ends = $(if ($a.endDate) { $a.endDate.ToString('yyyy-MM-dd') } else { '' }) }
    })
$figures = [ordered]@{
    psa = $psaName; companyId = $companyId; companyName = $f.companyName; ticket = $f.ticketId; ticketUrl = (Get-PsaTicketUrl $sourceId)
    period = $f.periodLabel; periodStart = $f.periodStart; periodEnd = $f.periodEnd; periodSource = $f.periodSource
    invoice = $(if ($null -ne $invoice) { [ordered]@{ number = $invoice.number; date = $(if ($invoice.date) { $invoice.date.ToString('yyyy-MM-dd') } else { '' }); total = $invoice.total } } else { $null })
    invoiceAsked = $f.invoiceNumber
    ticketsOpened = $inPeriod.Count; ticketsOpenedClosed = @($inPeriod | Where-Object { $_.isClosed }).Count
    timeAvailable = $timeAvailable; timeEntries = $time.Count; totalHours = $totalHours; billableHours = $billHours; nonBillableHours = $nonBill
    hoursOnAgreements = $onAgreement; ticketsWithTime = $groups.Count
    topTickets = @($top); agreementsAvailable = $agreementsAvailable; agreements = @($agreementRows)
}
$warnings = @(Get-AllWarnings $warnings)
# What the AI sees: the figures without ids, links or anything from another company.
$facts = [ordered]@{
    company = $f.companyName; period = $f.periodLabel; periodSource = $f.periodSource
    invoice = $figures.invoice; invoiceAsked = $f.invoiceNumber
    ticketsOpened = $figures.ticketsOpened; ticketsOpenedClosed = $figures.ticketsOpenedClosed
    timeAvailable = $timeAvailable; totalHours = $totalHours; billableHours = $billHours; nonBillableHours = $nonBill; hoursOnAgreements = $onAgreement; ticketsWithTime = $groups.Count
    topTickets = @($top | ForEach-Object { [ordered]@{ ticket = "#$($_.number)"; summary = $_.summary; hours = $_.hours; billableHours = $_.billableHours; status = $_.status } })
    agreementsAvailable = $agreementsAvailable
    agreements = @($agreementRows | ForEach-Object { [ordered]@{ name = $_.name; type = $_.type; status = $_.status; amount = $_.amount; cycle = $_.cycle; coverage = $_.coverage; hoursLogged = $_.hoursLogged } })
    notes = @($warnings)
}

Set-NodeOutput ([ordered]@{
        status = 'ok'
        message = "Collected $($time.Count) time entr$(if ($time.Count -eq 1) { 'y' } else { 'ies' }), $($inPeriod.Count) ticket(s) and $($inEffect.Count) agreement(s) for $($f.periodLabel)."
        request_json = ($f | ConvertTo-Json -Compress)
        figures_json = ($figures | ConvertTo-Json -Depth 6 -Compress)
        facts_json = ($facts | ConvertTo-Json -Depth 6)
        warnings_json = (ConvertTo-Json -InputObject @($warnings) -Compress)
        actions_json = (ConvertTo-Json -InputObject @($actions) -Compress)
    })
