// Pastes the shared PowerShell libraries into an automation's workflow files.
// In any .yml in the folder, the lines between
//   # >>> _shared/<name>.ps1 (generated by _shared/inject.js; edit the source, not this block)
//   # <<< _shared/<name>.ps1
// are replaced with the contents of automationai/_shared/<name>.ps1, indented like the start marker.
// Usage: node automationai/_shared/inject.js <automation-folder>          rewrite the .yml files
//        node automationai/_shared/inject.js <automation-folder> --check  exit 1 if any block is out of date
// Edit the file in _shared, never the block between the markers in a .yml.
// Needs js-yaml: npm install in this folder, or set JS_YAML_PATH (or NODE_PATH) to an existing copy.
const fs = require('fs');
const path = require('path');

function loadYaml() {
  try { return require('js-yaml'); } catch { /* fall through */ }
  if (process.env.JS_YAML_PATH) return require(process.env.JS_YAML_PATH);
  throw new Error('js-yaml not found. Run "npm install" in automationai/_shared, or set JS_YAML_PATH.');
}

const SHARED = __dirname;
const START = /^# >>> _shared\/([A-Za-z0-9._-]+\.ps1) \(generated by _shared\/inject\.js; edit the source, not this block\)$/;
const endFor = (name) => `# <<< _shared/${name}`;

function readLib(name, cache) {
  if (!cache.has(name)) {
    const p = path.join(SHARED, name);
    if (!fs.existsSync(p)) throw new Error(`_shared/${name} doesn't exist`);
    cache.set(name, fs.readFileSync(p, 'utf8').replace(/\r\n/g, '\n').trimEnd().split('\n'));
  }
  return cache.get(name);
}

// Returns { text, blocks } with every marked block refreshed.
function injectText(raw, file, cache) {
  const lines = raw.replace(/\r\n/g, '\n').split('\n');
  const out = [];
  const blocks = [];
  for (let i = 0; i < lines.length; i++) {
    const m = lines[i].trim().match(START);
    if (!m) { out.push(lines[i]); continue; }
    const name = m[1];
    const indent = lines[i].slice(0, lines[i].indexOf('#'));
    let j = i + 1;
    while (j < lines.length && lines[j].trim() !== endFor(name)) {
      if (lines[j].trim().match(START)) throw new Error(`${file}: a new start marker at line ${j + 1} before "${endFor(name)}" (from line ${i + 1})`);
      j++;
    }
    if (j >= lines.length) throw new Error(`${file}: no "${endFor(name)}" after line ${i + 1}`);
    const lib = readLib(name, cache);
    out.push(lines[i], ...lib.map((l) => (l ? indent + l : '')), indent + endFor(name));
    blocks.push(name);
    i = j;
  }
  return { text: out.join('\n'), blocks };
}

function main(argv) {
  const args = argv.filter((a) => !a.startsWith('--'));
  const check = argv.includes('--check');
  if (args.length !== 1) {
    console.error('Usage: node automationai/_shared/inject.js <automation-folder> [--check]');
    return 2;
  }
  const dir = path.resolve(args[0]);
  if (!fs.existsSync(dir) || !fs.statSync(dir).isDirectory()) { console.error(`Not a folder: ${dir}`); return 2; }
  const y = loadYaml();
  const cache = new Map();
  const files = fs.readdirSync(dir).filter((f) => /\.ya?ml$/i.test(f)).sort();
  let stale = false;
  let total = 0;
  for (const f of files) {
    const p = path.join(dir, f);
    const raw = fs.readFileSync(p, 'utf8');
    const { text, blocks } = injectText(raw, f, cache);
    if (!blocks.length) continue;
    total += blocks.length;
    try { y.load(text); } catch (e) { throw new Error(`${f}: no longer parses as YAML after injecting: ${e.message}`); }
    const was = raw.replace(/\r\n/g, '\n');
    const changed = text !== was;
    const names = [...new Set(blocks)].join(', ');
    console.log(`${f}: ${blocks.length} block(s) [${names}]${changed ? (check ? ' OUT OF DATE' : ' updated') : ' current'}`);
    if (changed) {
      if (check) stale = true;
      else fs.writeFileSync(p, raw.includes('\r\n') ? text.replace(/\n/g, '\r\n') : text);
    }
  }
  if (!total) console.log(`No _shared markers in ${dir}.`);
  return stale ? 1 : 0;
}

if (require.main === module) {
  try { process.exit(main(process.argv.slice(2))); } catch (e) { console.error(e.message); process.exit(2); }
}
module.exports = { injectText };
