# === NODE: Find candidate tickets ===
# Reads the request, checks the ticket and its company, lists the company's open tickets from the
# last N days, and scores each one against this ticket without AI: shared words in the summary and
# description, the same contact, and the same device where the PSA records one. The best few go to
# the AI step. Ticket numbers ServiceAI already picked (relatedTicketIds) are checked here: each must
# exist, be open and belong to the same company, or it is dropped with a warning.
# Accepts a flat {key:value} body (ServiceAI Action, manual run), the CloudRadial
# {Ticket:{...}, Company:{...}} shape, or either one wrapped in {trigger:...}.
# Read-only: this step never writes to the PSA.
# >>> _shared/psa.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/psa.ps1
# >>> src/psa-extra.ps1 (generated by src/build.js; edit the source, not this block)
# <<< src/psa-extra.ps1
$ErrorActionPreference = 'Stop'

function Get-Prop { param($o, [string]$n) if ($null -eq $o) { return $null }; if ($o -is [System.Collections.IDictionary]) { if ($o.Contains($n)) { return $o[$n] }; return $null }; $p = $o.PSObject.Properties[$n]; if ($p) { return $p.Value }; return $null }
$stopState = @{ done = $false }
function Stop-Run {
    param([string]$Status, [string]$Why, [string]$TicketId = '')
    $stopState.done = $true
    Set-NodeOutput ([ordered]@{
            status = $Status; message = $Why; public_note = ''
            internal_note = "Related ticket check stopped before anything was written: $Why"
            ticket_id = $TicketId; actions = @(); warnings = @(); chatReply = $Why
        })
    throw $Why
}
trap { if (-not $stopState.done) { $stopState.done = $true; Set-NodeOutput ([ordered]@{ status = 'error'; message = [string]$_.Exception.Message; public_note = ''; internal_note = "Related ticket check failed while reading the PSA: $($_.Exception.Message)"; ticket_id = ''; actions = @(); warnings = @(); chatReply = "The related ticket check failed: $($_.Exception.Message)" }) }; break }

$raw = Get-NodeInput
if ($null -eq $raw) { Stop-Run 'incomplete' 'No input was received. Send at least ticketId.' }
if ($raw -is [string]) { try { $raw = $raw | ConvertFrom-Json } catch { Stop-Run 'incomplete' 'The input was text that is not valid JSON.' } }
$wrap = Get-Prop $raw 'trigger'; if ($null -ne $wrap) { $raw = $wrap; if ($raw -is [string]) { try { $raw = $raw | ConvertFrom-Json } catch { Stop-Run 'incomplete' 'The trigger body was text that is not valid JSON.' } } }

$answers = @{}
if ($raw -is [System.Collections.IDictionary]) { foreach ($k in @($raw.Keys)) { $answers[[string]$k] = $raw[$k] } }
else { foreach ($p in $raw.PSObject.Properties) { $answers[$p.Name] = $p.Value } }
$crTicket = Get-Prop $raw 'Ticket'
if ($null -ne $crTicket) {
    foreach ($q in @(Get-Prop $crTicket 'Questions')) { $qid = [string](Get-Prop $q 'Id'); if ($qid) { $answers[$qid] = Get-Prop $q 'Value' } }
    $tid = Get-Prop $crTicket 'TicketId'; if ($null -ne $tid) { $answers['ticketId'] = $tid }
}
$crCompany = Get-Prop $raw 'Company'
if ($null -ne $crCompany) { foreach ($pair in @(@('CompanyName', 'companyName'), @('CompanyPsaId', 'companyId'))) { $v = Get-Prop $crCompany $pair[0]; if ($null -ne $v) { $answers[$pair[1]] = $v } } }
function Get-Field {
    param([string[]]$Names)
    foreach ($n in $Names) {
        if (-not $answers.ContainsKey($n)) { continue }
        $v = $answers[$n]
        if ($null -eq $v -or $v -is [System.Management.Automation.PSCustomObject] -or $v -is [System.Collections.IDictionary]) { continue }
        if ($v -is [array]) { $v = (@($v) | ForEach-Object { [string]$_ }) -join ',' }
        $s = ([string]$v).Trim()
        if (-not $s -or $s.StartsWith('@') -or $s -match '^\{\{.*\}\}$' -or $s -match '^<[^>]*>$') { continue }
        return $s
    }
    return ''
}
function Get-Flag { param([string[]]$Names, [bool]$Default) $s = (Get-Field $Names).ToLowerInvariant(); if (-not $s) { return $Default }; return (@('true', 'yes', '1', 'y') -contains $s) }
function Get-Int {
    param([string[]]$Names, [int]$Default, [int]$Min, [int]$Max)
    $s = Get-Field $Names; if (-not $s) { return $Default }
    $n = 0; if (-not [int]::TryParse($s, [ref]$n) -or $n -lt $Min -or $n -gt $Max) { Stop-Run 'incomplete' "$($Names[0]) must be a whole number from $Min to $Max; '$s' isn't. Nothing was read." }
    return $n
}

$f = [ordered]@{
    ticketId           = (Get-Field @('ticketId', 'ticket_id', 'TicketId', 'ticketNumber'))
    companyName        = (Get-Field @('companyName', 'company_name', 'CompanyName'))
    companyId          = (Get-Field @('companyId', 'company_id', 'psa_company_id', 'CompanyPsaId'))
    summary            = (Get-Field @('summary', 'subject', 'TicketSubject'))
    initialDescription = (Get-Field @('initialDescription', 'description', 'TicketDescription'))
    relatedTicketIds   = (Get-Field @('relatedTicketIds', 'related_ticket_ids', 'relatedTickets'))
    reason             = (Get-Field @('reason'))
    psa                = (Get-Field @('psa'))
    triggerSource      = (Get-Field @('triggerSource', 'trigger_source'))
    days               = (Get-Int @('days', 'lookbackDays') 7 1 90)
    maxCandidates      = (Get-Int @('maxCandidates') 10 1 25)
    minScore           = 0.25
    minConfidence      = 0.6
    confirm            = (Get-Flag @('confirm', 'approvedToWrite') $false)
    addNote            = (Get-Flag @('addNote') $true)
    noteWhenNone       = (Get-Flag @('noteWhenNone') $false)
}
foreach ($pair in @(@('minScore', 0.25), @('minConfidence', 0.6))) {
    $s = Get-Field @($pair[0])
    if ($s) { $d = 0.0; if (-not [double]::TryParse($s, [System.Globalization.NumberStyles]::Float, [System.Globalization.CultureInfo]::InvariantCulture, [ref]$d) -or $d -lt 0 -or $d -gt 1) { Stop-Run 'incomplete' "$($pair[0]) must be a number from 0 to 1; '$s' isn't. Nothing was read." }; $f[$pair[0]] = $d }
}
if (-not $f.ticketId) { Stop-Run 'incomplete' 'ticketId is missing. Send the PSA ticket number of the ticket to check. Nothing was read.' }

$warnings = New-Object System.Collections.ArrayList
$actions = New-Object System.Collections.ArrayList

# ---- the ticket and its company ----
$conn = Connect-Psa -Psa (Get-PsaType $f.psa)
$f.psa = $conn.Psa
$psaName = Get-PsaName
$sourceId = ''
try { $sourceId = Resolve-PsaTicketId $f.ticketId } catch { Stop-Run 'incomplete' "Ticket $($f.ticketId) wasn't found in $($psaName): $($_.Exception.Message)" $f.ticketId }
$t = $null
try { $t = Get-PsaTicket -Id $sourceId } catch { Stop-Run 'incomplete' "Ticket $($f.ticketId) couldn't be read from $($psaName): $($_.Exception.Message)" $f.ticketId }
$src = ConvertTo-PsaTicketRow $t.raw @(if ($conn.Psa -eq 'autotask') { Get-PsaAtCompleteStatuses })
$src.id = $sourceId; if (-not $src.number) { $src.number = $f.ticketId }
if (-not $src.summary) { $src.summary = $(if ($t.summary) { $t.summary } else { $f.summary }) }
if (-not $src.description) { $src.description = $(if ($t.description) { $t.description } else { $f.initialDescription }) }
$companyId = [string]$t.companyId
if (Test-PsaBlank $companyId) { Stop-Run 'incomplete' "Ticket $($f.ticketId) has no company in $psaName, so related tickets can't be limited to one company. Nothing was read." $f.ticketId }
if ($f.companyId -and $f.companyId -ne $companyId) { Stop-Run 'rejected' "Ticket $($f.ticketId) belongs to a different company than the companyId sent ($($f.companyId)). Nothing was read." $f.ticketId }
if ($f.companyName) {
    $hits = @(Find-PsaCompany -Name $f.companyName)
    if (-not @($hits | Where-Object { $_.id -eq $companyId }).Count) { Stop-Run 'rejected' "Ticket $($f.ticketId) does not belong to '$($f.companyName)' in $psaName. Nothing was read." $f.ticketId }
}
$null = $actions.Add("Read ticket $($f.ticketId) (company $companyId) from $psaName.")

# ---- word overlap, no AI ----
$stopWords = @{}
foreach ($w in @('the', 'and', 'for', 'with', 'are', 'was', 'were', 'has', 'have', 'had', 'can', 'cant', 'cannot', 'from', 'this', 'that', 'these', 'those', 'when', 'our', 'his', 'her', 'its', 'you', 'your', 'they', 'them', 'their', 'please', 'help', 'thanks', 'thank', 'hello', 'regards', 'ticket', 'need', 'needs', 'get', 'getting', 'got', 'any', 'all', 'but', 'not', 'just', 'also', 'into', 'out', 'about', 'there', 'here', 'what', 'which', 'who', 'how', 'why', 'will', 'would', 'could', 'should', 'been', 'being', 'some', 'more', 'than', 'then', 'now', 'today', 'again', 'still', 'issue', 'issues', 'problem', 'problems', 'request', 'via', 'sent', 'from', 'subject', 'email', 'mailto', 'http', 'https', 'www', 'com')) { $stopWords[$w] = $true }
function Get-Words {
    param([string]$Text)
    $set = @{}
    $clean = ([regex]::Replace([string]$Text, '<[^>]+>', ' ')).ToLowerInvariant()
    foreach ($w in [regex]::Split($clean, '[^a-z0-9]+')) {
        if ($w.Length -lt 3 -or $stopWords.ContainsKey($w) -or $w -match '^\d{1,3}$') { continue }
        $k = $w; if ($k.Length -gt 4 -and $k.EndsWith('ing')) { $k = $k.Substring(0, $k.Length - 3) } elseif ($k.Length -gt 3 -and $k.EndsWith('s') -and -not $k.EndsWith('ss')) { $k = $k.Substring(0, $k.Length - 1) }
        $set[$k] = $true
    }
    return $set
}
function Get-Shared { param([hashtable]$A, [hashtable]$B) return @($A.Keys | Where-Object { $B.ContainsKey($_) } | Sort-Object) }
function Get-Brief { param([string]$s, [int]$Max) $x = ([regex]::Replace([string]$s, '<[^>]+>', ' ') -replace '\s+', ' ').Trim(); if ($x.Length -gt $Max) { $x = $x.Substring(0, $Max) + '...' }; return $x }

$srcSum = Get-Words $src.summary
$srcAll = Get-Words "$($src.summary) $(Get-Brief $src.description 2000)"
function Get-Score {
    param($Row, [string[]]$SrcDevices = @())
    $sum = Get-Words $Row.summary
    $all = Get-Words "$($Row.summary) $(Get-Brief $Row.description 2000)"
    $sharedSum = @(Get-Shared $srcSum $sum)
    $sharedAll = @(Get-Shared $srcAll $all)
    $minSum = [Math]::Min($srcSum.Count, $sum.Count)
    $ov = if ($minSum) { $sharedSum.Count / $minSum } else { 0.0 }
    $union = $srcAll.Count + $all.Count - $sharedAll.Count
    $jac = if ($union) { $sharedAll.Count / $union } else { 0.0 }
    $sameContact = (-not (Test-PsaBlank $src.contactId)) -and $src.contactId -eq $Row.contactId
    $sameDevice = @($SrcDevices | Where-Object { @($Row.configIds) -contains $_ }).Count -gt 0
    $score = 0.45 * $ov + 0.35 * [Math]::Min(1.0, 2 * $jac) + $(if ($sameContact) { 0.1 } else { 0 }) + $(if ($sameDevice) { 0.15 } else { 0 })
    $signals = New-Object System.Collections.ArrayList
    if ($sharedAll.Count) { $null = $signals.Add("shared words: $((@($sharedAll) | Select-Object -First 8) -join ', ')") }
    if ($sameContact) { $null = $signals.Add('same contact') }
    if ($sameDevice) { $null = $signals.Add('same device') }
    return @{ score = [Math]::Round([Math]::Min(1.0, $score), 2); signals = @($signals); sameContact = $sameContact; sameDevice = $sameDevice }
}

# ---- the company's open tickets from the last N days ----
$since = (Get-Date).ToUniversalTime().AddDays(-$f.days)
$open = @(Find-PsaTickets -CompanyId $companyId -OpenOnly -Since $since -Max 300 | Where-Object { $_.id -ne $sourceId })
$null = $actions.Add("Listed $($open.Count) other open ticket(s) for company $companyId from the last $($f.days) day(s).")

# ---- ticket numbers ServiceAI already picked ----
$suggested = New-Object System.Collections.ArrayList
$suggestedIds = @{}
if ($f.relatedTicketIds) {
    foreach ($ref in @([regex]::Split($f.relatedTicketIds, '[,;\s]+') | ForEach-Object { $_.Trim().TrimStart('#') } | Where-Object { $_ } | Select-Object -Unique | Select-Object -First 20)) {
        $entry = [ordered]@{ ref = $ref; id = ''; valid = $false; why = '' }
        try {
            $rid = Resolve-PsaTicketId $ref
            $entry.id = $rid
            if ($rid -eq $sourceId) { $entry.why = 'it is this ticket' }
            else {
                $rt = Get-PsaTicket -Id $rid
                $row = ConvertTo-PsaTicketRow $rt.raw @(if ($conn.Psa -eq 'autotask') { Get-PsaAtCompleteStatuses })
                $row.id = $rid
                if (-not $row.summary) { $row.summary = $rt.summary }; if (-not $row.description) { $row.description = $rt.description }
                if ([string]$rt.companyId -ne $companyId) { $entry.why = 'it belongs to a different company' }
                elseif ($row.closed) { $entry.why = 'it is closed' }
                else {
                    $entry.valid = $true; $suggestedIds[$rid] = $true
                    if (-not @($open | Where-Object { $_.id -eq $rid }).Count) { $open = @($open) + @($row) }
                }
            }
        }
        catch { $entry.why = 'it was not found' }
        if (-not $entry.valid) { $null = $warnings.Add("ServiceAI suggested ticket $ref, but it was left out because $($entry.why).") }
        $null = $suggested.Add($entry)
    }
}

# ---- score, shortlist, then fill in details for the shortlist ----
$scored = @(foreach ($row in $open) { $s = Get-Score $row; $row.score = $s.score; $row.signals = $s.signals; $row.sameContact = $s.sameContact; $row.sameDevice = $false; $row })
$short = @($scored | Where-Object { $_.score -ge $f.minScore -or $suggestedIds.ContainsKey($_.id) } | Sort-Object -Property @{ Expression = { if ($suggestedIds.ContainsKey($_.id)) { 1 } else { 0 } } }, @{ Expression = { $_.score } } -Descending | Select-Object -First $f.maxCandidates)
$srcDevices = @(Get-PsaTicketDevices -Id $sourceId -Row $src)
foreach ($row in $short) {
    if (-not $row.description -and $conn.Psa -eq 'connectwise') { try { $row.description = (Get-PsaTicket -Id $row.id).description } catch { } }
    if ($srcDevices.Count) { $row.configIds = @(Get-PsaTicketDevices -Id $row.id -Row $row) }
    $s = Get-Score $row $srcDevices; $row.score = $s.score; $row.signals = $s.signals; $row.sameContact = $s.sameContact; $row.sameDevice = $s.sameDevice
}
$short = @($short | Sort-Object -Property @{ Expression = { $_.score } } -Descending)
$null = $actions.Add("Shortlisted $($short.Count) ticket(s) that share words, a contact or a device with ticket $($f.ticketId).")
foreach ($w in @($PsaExtraState.Warnings)) { $null = $warnings.Add([string]$w) }

$candidates = @(foreach ($row in $short) {
        [ordered]@{
            id = $row.id; number = $row.number; summary = (Get-Brief $row.summary 200); description = (Get-Brief $row.description 500)
            status = $row.status; created = $(if ($row.createdAt) { $row.createdAt.ToString('yyyy-MM-dd HH:mm') + ' UTC' } else { '' })
            createdAt = $(if ($row.createdAt) { Format-PsaDate $row.createdAt } else { '' })
            sameContact = [bool]$row.sameContact; sameDevice = [bool]$row.sameDevice; score = $row.score; signals = @($row.signals)
            suggestedByServiceAI = $suggestedIds.ContainsKey($row.id); url = (Get-PsaTicketUrl $row.id); ticketType = $row.ticketType
        }
    })
$source = [ordered]@{
    id = $sourceId; number = $src.number; summary = (Get-Brief $src.summary 200); description = (Get-Brief $src.description 800)
    companyId = $companyId; companyName = $f.companyName; status = $src.status; url = (Get-PsaTicketUrl $sourceId)
    createdAt = $(if ($src.createdAt) { Format-PsaDate $src.createdAt } else { '' })
}
$facts = [ordered]@{
    ticket = [ordered]@{ id = $source.id; summary = $source.summary; description = $source.description }
    serviceAiReason = $f.reason
    candidates = @($candidates | ForEach-Object { [ordered]@{ id = $_.id; summary = $_.summary; description = $_.description; created = $_.created; sameContact = $_.sameContact; sameDevice = $_.sameDevice; score = $_.score; suggestedByServiceAI = $_.suggestedByServiceAI } })
}

Set-NodeOutput ([ordered]@{
        status = 'ok'
        message = "Found $($candidates.Count) possible match(es) for ticket $($f.ticketId) among $($open.Count) open ticket(s)."
        request_json = ($f | ConvertTo-Json -Compress)
        source_json = ($source | ConvertTo-Json -Compress -Depth 5)
        candidates_json = (ConvertTo-Json -InputObject @($candidates) -Compress -Depth 6)
        suggested_json = (ConvertTo-Json -InputObject @($suggested) -Compress -Depth 5)
        facts_json = ($facts | ConvertTo-Json -Depth 6)
        warnings_json = (ConvertTo-Json -InputObject @($warnings) -Compress)
        actions_json = (ConvertTo-Json -InputObject @($actions) -Compress)
        counts = [ordered]@{ open = $open.Count; candidates = $candidates.Count; suggested = $suggested.Count; suggestedValid = $suggestedIds.Count }
    })
