# === NODE: Check the ticket and the article ===
# Reads only; changes nothing. Decides what the next step does and why.
# Send mode:
#   - the confidence must be at least min_confidence (default 0.75)
#   - the ticket must exist and be open, and must not already have had this article sent (ServiceAI Retry replays requests)
#   - the ticket's company must map to one CloudRadial company (its psaKey), or companyId names it
#   - the article must exist in CloudRadial, belong to that company or be MSP-wide (companyId 0 or mspCompanyId),
#     be published (datePublished set and not in the future), and the link must point at it
#   - the contact must not be a portal user of a different company
# Reply mode:
#   - the ticket must have had a troubleshooting article sent by this workflow (the internal note marker)
#   - the reply must clearly say it's fixed (conservative match); anything else leaves the ticket open
# >>> _shared/cloudradial.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/cloudradial.ps1
# >>> _shared/psa.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/psa.ps1
# >>> src/psa-extra.ps1 (generated by src/build.js; edit the source, not this block)
# <<< src/psa-extra.ps1
$ErrorActionPreference = 'Stop'

function Get-TaState { $in = Get-NodeInput; $s = [ordered]@{}; if ($null -ne $in) { if ($in -is [System.Collections.IDictionary]) { foreach ($k in @($in.Keys)) { $s[[string]$k] = $in[$k] } } else { foreach ($p in $in.PSObject.Properties) { $s[$p.Name] = $p.Value } } }; return $s }
function Get-TaList { param($S, [string]$Key) if (-not $S.Contains($Key)) { return @() }; return @(@($S[$Key]) | Where-Object { $null -ne $_ -and [string]$_ -ne '' }) }
# OData: quote a string value (doubling any single quote in it), and URL-encode a whole filter.
function ConvertTo-TaLiteral { param([string]$s) return "'" + $s.Replace("'", "''") + "'" }
function ConvertTo-TaOData { param([string]$f) return [uri]::EscapeDataString($f) }

# The markers this workflow leaves in its internal notes. Reply mode and retries look for them.
$SentMarker = 'Ref: AAI troubleshooting article sent'
$ClosedMarker = 'Ref: AAI troubleshooting article closed'

# Conservative "is it fixed?" check. Returns @{ fixed; why }. Only a short reply with a clear yes and no
# hedge, negation or question counts. Quoted email history and signatures are ignored.
function Test-TaFixedReply {
    param([string]$Text)
    $keep = New-Object System.Collections.ArrayList
    foreach ($line in @($Text -split "\r?\n")) {
        if ($line -match '^\s*>' -or $line -match '^\s*On .+wrote:\s*$' -or $line -match '^\s*-{2,}\s*Original Message' -or $line -match '^\s*(From|Sent|To|Subject):\s' -or $line -match '^\s*Sent from my ' -or $line -match '^\s*--\s*$' -or $line -match '^\s*_{5,}') { break }
        $null = $keep.Add($line)
    }
    $t = ((@($keep) -join ' ') -replace '\s+', ' ').Trim().ToLowerInvariant()
    $t = $t -replace "[‘’]", "'"
    if (-not $t) { return @{ fixed = $false; why = 'the reply is empty' } }
    if ($t.Length -gt 160) { return @{ fixed = $false; why = 'the reply is too long to read as a simple yes' } }
    if ($t.Contains('?')) { return @{ fixed = $false; why = 'the reply asks a question' } }
    $neg = "\b(not|no|nope|never|still|again|but|however|except|partly|partially|sometimes|until|unless|almost|kind of|kinda|maybe|isn't|isnt|doesn't|doesnt|didn't|didnt|won't|wont|can't|cant|cannot|couldn't|haven't|hasn't|wasn't|aren't|nothing|worse|persists?|keeps|broken|fail(s|ed)?|error|wrong|same)\b"
    if ($t -match $neg) { return @{ fixed = $false; why = "the reply has a hedge or negation ('$($Matches[1])')" } }
    $pos = "\b(fixed|resolved|works now|working now|it works|it's working|that worked|it worked|this worked|worked for me|all good|all set|sorted|solved|did the trick|good to close|ok to close|okay to close|you can close|please close|can be closed)\b"
    if ($t -match $pos) { return @{ fixed = $true; why = "the reply says '$($Matches[1])'" } }
    return @{ fixed = $false; why = 'the reply does not clearly say it is fixed' }
}

$st = Get-TaState
if ([string]$st['status'] -ne 'ok') { Set-NodeOutput $st; return }
$warnings = New-Object System.Collections.ArrayList; foreach ($w in @(Get-TaList $st 'warnings')) { $null = $warnings.Add([string]$w) }
$mode = [string]$st['mode']
$ticketId = [string]$st['ticket_id']
$st['decision'] = ''; $st['reason'] = ''; $st['ticketSummary'] = ''; $st['companyName'] = ''; $st['firstName'] = ''
$st['article'] = $null; $st['notesReadable'] = $false; $st['sentTo'] = ''
function Set-TaDecision {
    param([string]$Decision, [string]$Reason)
    $st['decision'] = $Decision; $st['reason'] = $Reason; $st['warnings'] = @($warnings)
    Set-NodeOutput $st
}

# The PSA is required: the ticket is read and written there.
try { $null = Connect-Psa (Get-PsaType ([string]$st['psa'])) }
catch { $st['status'] = 'error'; $st['message'] = "The PSA isn't connected: $($_.Exception.Message)"; $st['chatReply'] = $st['message']; $st['internal_note'] = $st['message']; Set-NodeOutput $st; return }

$ticket = $null
try { $ticket = Get-PsaTicket $ticketId }
catch {
    $msg = [string]$_.Exception.Message
    if ($msg -match 'HTTP 404') { Set-TaDecision 'no-ticket' "Ticket $ticketId wasn't found in the PSA."; return }
    throw
}
$st['ticketSummary'] = [string]$ticket.summary
$closedNow = ([string]$ticket.status) -match '(?i)clos|complete|resolved|solved'

# Notes: the retry guard and the reply-mode check. $null means this PSA's notes couldn't be read.
$notes = $null
try { $notes = Get-PsaNotes $ticketId } catch { $null = $warnings.Add("The ticket's notes couldn't be read: $($_.Exception.Message)") }
$st['notesReadable'] = ($null -ne $notes)
$sentNote = $null; $closedNote = $false
if ($null -ne $notes) {
    foreach ($n in @($notes)) {
        $tx = [string]$n.text
        if ($tx.Contains($SentMarker)) { $sentNote = $tx }
        if ($tx.Contains($ClosedMarker)) { $closedNote = $true }
    }
}

if ($mode -eq 'reply') {
    if ($closedNote) { Set-TaDecision 'already-closed' 'This workflow already closed the ticket after a confirmed fix.'; return }
    if ($null -eq $notes) { Set-TaDecision 'cannot-confirm' "The ticket's notes couldn't be read, so it isn't clear a troubleshooting article was sent. Left open."; return }
    if (-not $sentNote) { Set-TaDecision 'no-article-sent' 'No troubleshooting article was sent on this ticket by this workflow, so the reply was not acted on.'; return }
    if ($sentNote -match 'to ([^\s()]+@[^\s()]+)\)') { $st['sentTo'] = $Matches[1].ToLowerInvariant() }
    $from = [string]$st['replyFrom']
    if ($from -and $st['sentTo'] -and $from -ne $st['sentTo']) { Set-TaDecision 'not-the-contact' "The reply came from $from, not the contact the article was sent to. Left open."; return }
    if ($closedNow) { Set-TaDecision 'already-closed' "The ticket is already $($ticket.status)."; return }
    $v = Test-TaFixedReply ([string]$st['replyText'])
    if (-not $v.fixed) { Set-TaDecision 'not-clear' "Left open: $($v.why)."; return }
    if (-not [bool]$st['autoClose']) { Set-TaDecision 'fixed-no-autoclose' "The customer confirmed the fix ($($v.why)), but autoClose is off, so a technician should close it."; return }
    Set-TaDecision 'close' "The customer confirmed the fix: $($v.why)."
    return
}

# ---- send mode ----
$score = [double]$st['confidence']; $min = [double]$st['minConfidence']
if ($score -lt $min) { Set-TaDecision 'low-confidence' "The match confidence $score is below the $min threshold, so the article wasn't sent."; return }
if ($closedNow) { Set-TaDecision 'ticket-closed' "The ticket is already $($ticket.status), so nothing was sent."; return }

$null = Connect-Cr
# The CloudRadial company: companyId when given, else the company linked to the ticket's PSA company.
$crId = [int]$st['crCompanyId']
$company = $null
if ($crId -gt 0) { $company = Get-CrProp (Invoke-CrApi "/v2/odata/company?`$filter=$(ConvertTo-TaOData "companyId eq $crId")&`$select=companyId,name,psaKey") 'value' | Select-Object -First 1 }
else {
    $pk = [string]$ticket.companyId
    if ($pk -notmatch '^\d+$') { Set-TaDecision 'no-company' "The ticket's PSA company ('$pk') can't be matched to a CloudRadial company. Send companyId to name it."; return }
    $hits = @(Get-CrAll "/v2/odata/company?`$filter=$(ConvertTo-TaOData "psaKey eq $pk")&`$select=companyId,name,psaKey" | Where-Object { [string](Get-CrProp $_ 'psaKey') -eq $pk })
    if ($hits.Count -gt 1) { Set-TaDecision 'no-company' "More than one CloudRadial company is linked to PSA company $pk, so the right knowledge base isn't clear. Send companyId to name it."; return }
    if ($hits.Count -eq 1) { $company = $hits[0] }
}
if ($null -eq $company) { Set-TaDecision 'no-company' "No CloudRadial company is linked to this ticket's company, so the article couldn't be checked."; return }
$cid = [int](Get-CrProp $company 'companyId')
$st['crCompanyId'] = $cid
$st['companyName'] = [string](Get-CrProp $company 'name')

# The article: by the id in the link when there is one, otherwise by title.
$url = [string]$st['articleUrl']; $title = [string]$st['articleTitle']
$idInUrl = 0
if ($url -match '(?i)/(?:articles?|kb|knowledge(?:base)?)/(\d+)(?:[/?#]|$)' -or $url -match '(?i)[?&](?:articleId|id)=(\d+)(?:&|#|$)') { $idInUrl = [int]$Matches[1] }
$article = $null; $how = ''
if ($idInUrl -gt 0) {
    try { $article = Invoke-CrApi "/v2/article/$idInUrl"; $how = 'id' }
    catch { if ([string]$_.Exception.Message -notmatch 'HTTP 404') { throw } }
    $data = Get-CrProp $article 'data'; if ($null -ne $data) { $article = $data }
}
if ($null -eq $article) {
    $rows = @(Get-CrAll "/v2/odata/article?`$filter=$(ConvertTo-TaOData "subject eq $(ConvertTo-TaLiteral $title)")&`$select=articleId,companyId,subject,datePublished,url,category")
    $mspId = [int]$st['mspCompanyId']
    $mine = @($rows | Where-Object { [int](Get-CrProp $_ 'companyId') -eq $cid })
    $shared = @($rows | Where-Object { $c2 = [int](Get-CrProp $_ 'companyId'); $c2 -eq 0 -or ($mspId -gt 0 -and $c2 -eq $mspId) })
    $article = @($mine + $shared) | Select-Object -First 1
    if ($null -eq $article -and $rows.Count) { Set-TaDecision 'wrong-company' "An article titled '$title' exists, but not in this company's knowledge base or the MSP-wide articles, so it wasn't sent."; return }
    $how = 'title'
}
if ($null -eq $article) { Set-TaDecision 'no-article' "No CloudRadial article titled '$title' was found, so nothing was sent."; return }

$aid = [int](Get-CrProp $article 'articleId')
$acid = [int](Get-CrProp $article 'companyId')
$asubj = ([string](Get-CrProp $article 'subject')).Trim()
$st['article'] = [ordered]@{ articleId = $aid; companyId = $acid; subject = $asubj; url = $url; matchedBy = $how }
$mspId = [int]$st['mspCompanyId']
if ($acid -ne $cid -and $acid -ne 0 -and -not ($mspId -gt 0 -and $acid -eq $mspId)) { Set-TaDecision 'wrong-company' "Article $aid belongs to a different company's knowledge base, so it wasn't sent."; return }
if ($how -eq 'id' -and $asubj -ine $title.Trim() -and $asubj.IndexOf($title.Trim(), [StringComparison]::OrdinalIgnoreCase) -lt 0 -and $title.Trim().IndexOf($asubj, [StringComparison]::OrdinalIgnoreCase) -lt 0) {
    Set-TaDecision 'link-mismatch' "The link points at article $aid ('$asubj'), not '$title', so nothing was sent."; return
}
$pubRaw = [string](Get-CrProp $article 'datePublished')
$pub = [datetime]::MinValue
if (-not $pubRaw -or -not [datetime]::TryParse($pubRaw, [System.Globalization.CultureInfo]::InvariantCulture, [System.Globalization.DateTimeStyles]::AdjustToUniversal, [ref]$pub) -or $pub.Year -lt 2000) { Set-TaDecision 'unpublished' "Article $aid has no publish date, so it isn't visible to the client yet."; return }
if ($pub -gt (Get-Date).ToUniversalTime().AddMinutes(5)) { Set-TaDecision 'unpublished' "Article $aid is scheduled for $($pub.ToString('yyyy-MM-dd')), so it isn't visible to the client yet."; return }
if ($how -eq 'title') {
    $u = [uri]$url
    $host2 = $u.Host.ToLowerInvariant()
    $allowed = @(@($st['allowedLinkHosts']) | Where-Object { $_ } | ForEach-Object { ([string]$_).ToLowerInvariant() })
    $own = [string](Get-CrProp $article 'url')
    $ok = ($own -and $own.TrimEnd('/') -ieq $url.TrimEnd('/')) -or ($url -match "(?i)[/=]$aid(?:[/?#&]|$)") -or ($host2 -eq 'cloudradial.com' -or $host2.EndsWith('.cloudradial.com')) -or ($allowed -contains $host2)
    if (-not $ok) { Set-TaDecision 'link-unverified' "The link's site ($host2) isn't the CloudRadial portal or an allowed host, so it can't be confirmed to open article $aid. Add the portal's host to allowedLinkHosts."; return }
}

# The contact: a portal user of a different company means the ticket and the contact don't belong together.
$email = [string]$st['contactEmail']
$users = @(Get-CrAll "/v2/odata/user?`$filter=$(ConvertTo-TaOData "email eq $(ConvertTo-TaLiteral $email)")&`$select=userId,email,firstName,companyId" | Where-Object { ([string](Get-CrProp $_ 'email')).ToLowerInvariant() -eq $email -and (Get-CrProp $_ 'isDeleted') -ne $true })
$here = @($users | Where-Object { [int](Get-CrProp $_ 'companyId') -eq $cid })
if ($users.Count -and -not $here.Count) { Set-TaDecision 'wrong-contact' "The contact $email is a portal user of a different company, so the article wasn't sent."; return }
if ($here.Count) { $st['firstName'] = [string](Get-CrProp $here[0] 'firstName') }
else { $null = $warnings.Add("$email isn't a portal user of $($st['companyName']); the article was checked against the ticket's company instead.") }

if ($null -eq $notes) { $null = $warnings.Add("The ticket's notes couldn't be read, so a retried request can't be detected.") }
elseif ($sentNote -and $sentNote.Contains("(article $aid,")) { Set-TaDecision 'already-sent' "Article $aid was already sent on this ticket."; return }
elseif ($sentNote) { $null = $warnings.Add('A different troubleshooting article was sent on this ticket before.') }

Set-TaDecision 'send' "Article $aid matched with confidence $score (threshold $min) and is published for $($st['companyName'])."
