// Builds ../role-change-mover.yml and the KB article template from the scripts in this folder,
// with the _shared libraries pasted in by _shared/inject.js.
// Usage: node build.js          rewrite the generated files
//        node build.js --check  exit 1 if a generated file is out of date
// Edit the .ps1 files here (or the library in _shared), never the generated .yml.
// Needs js-yaml: npm install in automationai/_shared, or set JS_YAML_PATH.
const fs = require('fs');
const path = require('path');
let y;
try { y = require('js-yaml'); } catch { try { y = require(path.join(__dirname, '..', '..', '_shared', 'node_modules', 'js-yaml')); } catch { y = require(process.env.JS_YAML_PATH); } }
const { injectText } = require(path.join(__dirname, '..', '..', '_shared', 'inject.js'));

const here = __dirname;
const root = path.join(here, '..');
const check = process.argv.includes('--check');
const read = (f) => fs.readFileSync(path.join(here, f), 'utf8').replace(/\r\n/g, '\n').trimEnd() + '\n';
const lib = (name) => `# >>> _shared/${name} (generated by _shared/inject.js; edit the source, not this block)\n# <<< _shared/${name}\n`;

const preamble = (title, lines) =>
  ['# =====================================================================', `#  Move a User to a New Department - ${title}`, ...lines.map((l) => `#  ${l}`),
   '#  Generated from automationai/role-change-mover/src. Edit the source, then run build.js.',
   '# =====================================================================', "$ErrorActionPreference = 'Stop'", 'Set-StrictMode -Version Latest', ''].join('\n') + '\n';

const readScript = preamble('Read the request, department map and user', [
  'Writes nothing. Reads the department map KB article from CloudRadial and the user, groups and licences from Microsoft Graph.',
  'Secrets: CloudRadial-BaseUrl, CloudRadial-PublicKey, CloudRadial-PrivateKey, DepartmentMap-CompanyId,',
  'optional DepartmentMap-ArticleTitle, and M365-TenantId, M365-ClientId, M365-ClientSecret.',
]) + lib('cloudradial.ps1') + lib('graph.ps1') + read('department-map.ps1') + '\n# ---------- this step ----------\n' + read('read.ps1');

const applyScript = preamble('Preview or apply, then note the ticket', [
  'Changes Microsoft 365 only when confirm is true: group adds and removes, department, title and manager.',
  'Adds an internal note to ticket_id with the plan or the result. Secrets: M365-*, PSA-Type and the PSA\'s own secrets.',
]) + lib('plan.ps1') + lib('graph.ps1') + lib('psa.ps1') + '\n# ---------- this step ----------\n' + read('apply.ps1');

const testInput = {
  upn: 'sam.doe@contoso.com',
  new_department: 'Marketing',
  new_title: 'Marketing Coordinator',
  new_manager_upn: 'alex.kim@contoso.com',
  old_department: '',
  confirm: 'false',
  psa: 'connectwise',
  ticket_id: '12345',
};

const wf = {
  automationsWorkflow: 1,
  name: 'Move a User to a New Department',
  description:
    "When a user changes department, reconciles their Microsoft 365 access from your department map: adds the new department's groups, " +
    "removes the old department's, updates department, title and manager, and flags licence and distribution list changes for a technician. " +
    'Preview only until confirm is true. Adds an internal note to the ticket.',
  definition: {
    schemaVersion: 1,
    activities: [
      { id: 'start', name: 'Start', type: 'start', position: { x: 80, y: 120 }, properties: { webhookEnabled: false } },
      {
        id: 'node-read', name: 'Read the request, department map and user', type: 'powershell-script', position: { x: 320, y: 120 },
        properties: {
          script: readScript, timeoutSeconds: 300, retryCount: 0, parameters: [], aiExtensions: [],
          testInput: JSON.stringify(testInput, null, 2),
        },
      },
      {
        id: 'node-apply', name: 'Preview or apply, then note the ticket', type: 'powershell-script', position: { x: 580, y: 120 },
        properties: {
          script: applyScript, timeoutSeconds: 600, retryCount: 0,
          parameters: [{ name: 'prep', expression: '{{ nodes.node-read.output }}' }],
          aiExtensions: [],
        },
      },
      { id: 'end', name: 'End', type: 'end', position: { x: 820, y: 120 } },
    ],
    connections: [
      { source: 'start', target: 'node-read', sourceHandle: null },
      { source: 'node-read', target: 'node-apply', sourceHandle: null },
      { source: 'node-apply', target: 'end', sourceHandle: null },
    ],
    startActivityId: 'start',
  },
};

const header = [
  '# CloudRadial AutomationAI - Move a User to a New Department (role change, mover).',
  '# Generated by src/build.js. Edit the scripts in src/, not this file.',
  '# Import on Workflows -> Import. See README.md for the department map, secrets and inputs.',
].join('\n');
const dumped = header + '\n' + y.dump(wf, { lineWidth: -1, noRefs: true });
const { text, blocks } = injectText(dumped, 'role-change-mover.yml', new Map());
if (blocks.length !== 5) throw new Error(`expected 5 _shared blocks, got ${blocks.length}`);
const back = y.load(text);
JSON.parse(back.definition.activities.find((a) => a.id === 'node-read').properties.testInput);
if (back.definition.activities[0].properties.webhookEnabled !== false) throw new Error('webhook must ship off');
for (const a of back.definition.activities) if (a.properties && a.properties.script && !a.properties.script.includes('function Get-GraphUser')) throw new Error(`${a.id}: graph.ps1 not injected`);

// The KB article template is the CSV template under a short heading, ready to paste.
const csv = fs.readFileSync(path.join(root, 'department-map-template.csv'), 'utf8').replace(/^﻿/, '').replace(/\r\n/g, '\n').trimEnd() + '\n';
const article = 'Department map for role changes. Columns: department, group (display name or object id), kind (security, distribution or m365), license_sku (optional).\n\n' + csv;

const outputs = [
  [path.join(root, 'role-change-mover.yml'), text],
  [path.join(root, 'kb-articles', 'role-change-department-map.txt'), article],
];
let stale = false;
for (const [p, content] of outputs) {
  const was = fs.existsSync(p) ? fs.readFileSync(p, 'utf8').replace(/\r\n/g, '\n') : null;
  const changed = was !== content;
  console.log(`${path.relative(root, p)}: ${changed ? (check ? 'OUT OF DATE' : 'updated') : 'current'} (${content.length} bytes)`);
  if (changed) {
    if (check) stale = true;
    else { fs.mkdirSync(path.dirname(p), { recursive: true }); fs.writeFileSync(p, content); }
  }
}
if (stale) process.exit(1);
