// Pastes src/psa.ps1 into every PowerShell step of the two workflows that has the PSA markers:
//   # >>> src/psa.ps1 (generated by src/build.js; edit the source, not this block)
//   # <<< src/psa.ps1
// Usage: node build.js          rewrite the .yml files
//        node build.js --check  exit 1 if a .yml is out of date
// Edit psa.ps1 here, never the block between the markers in a .yml.
const fs = require('fs');
const path = require('path');
let y;
try { y = require('js-yaml'); } catch { y = require(process.env.JS_YAML_PATH); }

const here = __dirname;
const root = path.join(here, '..');
const files = ['new-user-onboarding-direct.yml', 'new-user-onboarding.yml'];
const START = '# >>> src/psa.ps1 (generated by src/build.js; edit the source, not this block)';
const END = '# <<< src/psa.ps1';
const psa = fs.readFileSync(path.join(here, 'psa.ps1'), 'utf8').replace(/\r\n/g, '\n').trimEnd().split('\n');
const check = process.argv.includes('--check');
let stale = false;

for (const f of files) {
  const p = path.join(root, f);
  const raw = fs.readFileSync(p, 'utf8');
  const crlf = raw.includes('\r\n');
  const lines = raw.replace(/\r\n/g, '\n').split('\n');
  const out = [];
  let blocks = 0;
  for (let i = 0; i < lines.length; i++) {
    const t = lines[i].trim();
    if (t !== START) { out.push(lines[i]); continue; }
    const indent = lines[i].slice(0, lines[i].indexOf('#'));
    let j = i + 1;
    while (j < lines.length && lines[j].trim() !== END) j++;
    if (j >= lines.length) throw new Error(`${f}: no "${END}" after line ${i + 1}`);
    out.push(lines[i], ...psa.map((l) => (l ? indent + l : '')), lines[j]);
    i = j;
    blocks++;
  }
  const next = out.join('\n');
  y.load(next); // must still parse
  const was = raw.replace(/\r\n/g, '\n');
  console.log(`${f}: ${blocks} PSA block(s)${next === was ? '' : check ? ' OUT OF DATE' : ' updated'}`);
  if (next !== was) {
    if (check) stale = true;
    else fs.writeFileSync(p, crlf ? next.replace(/\n/g, '\r\n') : next);
  }
}
if (stale) process.exit(1);
