# === NODE: Send or close, and note it ===
# Acts on the previous step's decision and writes an internal note for every action:
#   send       a public note (so the PSA emails the contact) with the article link and "Reply 'fixed' and we'll
#              close this ticket", then an internal note carrying the marker reply mode looks for
#   close      closes the ticket, adds a short public note, then an internal note with the closed marker
#   anything else: no client-facing change, and an internal note saying what was decided and why
# Retries are quiet: an article already sent, or a ticket this workflow already closed, writes nothing. Every note
# is also written with Add-PsaNote -Marker, so a ServiceAI Retry that gets past those checks (for example after
# the public note was posted but the internal note failed) still never writes the same note twice. A public note
# shows the client only the opaque "Ref: xxxxxxxx" line Add-PsaNote derives from its marker; the markers reply
# mode reads (Ref: AAI troubleshooting article sent/closed) are only ever in the internal notes.
# dry_run=true writes nothing anywhere and returns the notes it would have written.
# >>> _shared/psa.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/psa.ps1
$ErrorActionPreference = 'Stop'

function Get-TaState { $in = Get-NodeInput; $s = [ordered]@{}; if ($null -ne $in) { if ($in -is [System.Collections.IDictionary]) { foreach ($k in @($in.Keys)) { $s[[string]$k] = $in[$k] } } else { foreach ($p in $in.PSObject.Properties) { $s[$p.Name] = $p.Value } } }; return $s }
function Get-TaList { param($S, [string]$Key) if (-not $S.Contains($Key)) { return @() }; return @(@($S[$Key]) | Where-Object { $null -ne $_ -and [string]$_ -ne '' }) }
function Get-TaHash { param([string]$s) $h = [System.Security.Cryptography.SHA256]::Create(); try { return (-join @($h.ComputeHash([Text.Encoding]::UTF8.GetBytes($s)) | Select-Object -First 6 | ForEach-Object { $_.ToString('x2') })) } finally { $h.Dispose() } }
function Get-TaProp { param($o, [string]$n) if ($null -eq $o) { return $null }; if ($o -is [System.Collections.IDictionary]) { if ($o.Contains($n)) { return $o[$n] }; return $null }; $p = $o.PSObject.Properties[$n]; if ($p) { return $p.Value }; return $null }

$st = Get-TaState
$mode = [string]$st['mode']; $ticketId = [string]$st['ticket_id']
$decision = [string]$st['decision']; $reason = [string]$st['reason']
$dry = [bool]$st['dryRun']
$warnings = New-Object System.Collections.ArrayList; foreach ($w in @(Get-TaList $st 'warnings')) { $null = $warnings.Add([string]$w) }
$actions = New-Object System.Collections.ArrayList
# Adds the shared PSA library's warnings (for example a ConnectWise note redirect) after the step's own.
function Add-TaPsaWarnings { foreach ($w in @($PsaState.Warnings)) { if ($w -and -not $warnings.Contains([string]$w)) { $null = $warnings.Add([string]$w) } } }
$when = (Get-Date).ToUniversalTime().ToString('yyyy-MM-dd HH:mm') + ' UTC'
$art = $st['article']
$aid = [string](Get-TaProp $art 'articleId')
$title = [string]$st['articleTitle']; if (Get-TaProp $art 'subject') { $title = [string](Get-TaProp $art 'subject') }
$url = [string]$st['articleUrl']
$email = [string]$st['contactEmail']

$out = [ordered]@{
    status = [string]$st['status']; message = [string]$st['message']; public_note = ''; internal_note = [string]$st['internal_note']; chatReply = [string]$st['chatReply']
    ticket_id = $ticketId; mode = $mode; decision = $decision; reason = $reason; dry_run = $dry
    confidence = $st['confidence']; min_confidence = $st['minConfidence']; article = $art; company = [string]$st['companyName']
    sent = $false; closed = $false; note_written = $false; triggerSource = [string]$st['triggerSource']; received_keys = @(Get-TaList $st 'received_keys')
    actions = @(); warnings = @()
}
if ($out.status -ne 'ok') {
    if (-not $out.chatReply) { $out.chatReply = $out.message }
    $out.warnings = @($warnings); Set-NodeOutput $out; return
}

$null = Connect-Psa (Get-PsaType ([string]$st['psa']))
function Write-TaNote {
    param([string]$Text, [string]$Title, [string]$Marker, [switch]$Public)
    $kind = if ($Public) { 'Public note' } else { 'Internal note' }
    if ($dry) { $null = $actions.Add([ordered]@{ action = "$kind on ticket $ticketId"; result = 'not written (dry run)' }); return $true }
    try {
        $r = Add-PsaNote -Id $ticketId -Text $Text -Title $Title -Public:$Public -Marker $Marker
        $null = $actions.Add([ordered]@{ action = "$kind on ticket $ticketId"; result = $(if ($r -eq 'already-present') { 'already on the ticket from an earlier run, not written again' } else { 'written' }) })
        return $true
    }
    catch { $null = $warnings.Add("The $($kind.ToLowerInvariant()) on ticket $ticketId failed: $($_.Exception.Message)"); $null = $actions.Add([ordered]@{ action = "$kind on ticket $ticketId"; result = "failed: $($_.Exception.Message)" }); return $false }
}

$quiet = @('already-sent', 'already-closed', 'no-ticket')
switch ($decision) {
    'send' {
        $first = [string]$st['firstName']
        $greet = if ($first) { "Hi $first," } else { 'Hi,' }
        $out.public_note = "$greet while a technician looks at your ticket, this article may help you fix it yourself: $title $url`n`nReply 'fixed' and we'll close this ticket. If it doesn't help, just reply and a technician will carry on."
        $internal = "Troubleshooting article sent to the contact as a public note: '$title' (article $aid) $url. Match confidence $($st['confidence']) (threshold $($st['minConfidence'])). $reason If the contact replies that it's fixed, the reply action closes the ticket.`n$('Ref: AAI troubleshooting article sent') (article $aid, to $email)."
        $out.internal_note = $internal
        $sentOk = Write-TaNote $out.public_note 'Troubleshooting article' -Marker "AAI-TA public sent $aid" -Public
        if ($sentOk) {
            $out.sent = -not $dry
            $out.note_written = Write-TaNote $internal 'Troubleshooting article sent' -Marker "AAI-TA sent $aid"
            $out.status = $(if ($dry) { 'pending_confirmation' } else { 'success' })
            $out.message = $(if ($dry) { "Dry run: would send '$title' to $email on ticket $ticketId. Nothing was written." } else { "Sent '$title' to $email on ticket $ticketId." })
            $out.chatReply = $(if ($dry) { "Dry run: I would send '$title' to the contact." } else { "Sent the troubleshooting article '$title' to the contact. A reply of 'fixed' will close the ticket." })
        }
        else {
            $out.status = 'error'
            $out.message = "The article couldn't be posted to ticket $ticketId."
            $out.chatReply = $out.message
            $null = Write-TaNote "Troubleshooting article '$title' (article $aid) could not be posted as a public note: $(@($warnings)[-1])" 'Troubleshooting article failed' -Marker "AAI-TA send failed $aid"
        }
    }
    'close' {
        $closedAs = ''
        $out.public_note = "Thanks for letting us know it's fixed. We've closed this ticket. Reply here if the problem comes back and we'll reopen it."
        if ($dry) { $closedAs = 'closed (dry run)'; $null = $actions.Add([ordered]@{ action = "Close ticket $ticketId"; result = 'not changed (dry run)' }) }
        else {
            try { $closedAs = Set-PsaStatus -Id $ticketId -State closed; $out.closed = $true; $null = $actions.Add([ordered]@{ action = "Close ticket $ticketId"; result = "status set to $closedAs" }) }
            catch { $null = $warnings.Add("Closing ticket $ticketId failed: $($_.Exception.Message)"); $null = $actions.Add([ordered]@{ action = "Close ticket $ticketId"; result = "failed: $($_.Exception.Message)" }) }
        }
        if ($out.closed -or $dry) {
            $null = Write-TaNote $out.public_note 'Ticket closed' -Marker 'AAI-TA public closed' -Public
            $internal = "Closed after the contact confirmed the troubleshooting article fixed it. $reason Status set to $closedAs.`nRef: AAI troubleshooting article closed."
            $out.internal_note = $internal
            $out.note_written = Write-TaNote $internal 'Closed: customer confirmed fixed' -Marker 'AAI-TA closed'
            $out.status = $(if ($dry) { 'pending_confirmation' } else { 'success' })
            $out.message = $(if ($dry) { "Dry run: would close ticket $ticketId. Nothing was changed." } else { "Closed ticket $ticketId after the customer confirmed the fix." })
        }
        else {
            $out.public_note = ''
            $out.status = 'error'
            $out.message = "The customer confirmed the fix, but ticket $ticketId couldn't be closed."
            $out.internal_note = "The contact confirmed the troubleshooting article fixed it ($reason), but closing the ticket failed: $(@($warnings)[-1]) Please close it by hand."
            $out.note_written = Write-TaNote $out.internal_note 'Close failed' -Marker 'AAI-TA close failed'
        }
        $out.chatReply = $out.message
    }
    default {
        # Every other decision changes nothing the client sees. Retries stay quiet; the rest get an internal note.
        $isSend = $mode -eq 'send'
        $out.status = $(if ($decision -in @('already-sent', 'already-closed', 'not-clear', 'no-article-sent', 'fixed-no-autoclose', 'ticket-closed')) { 'success' } elseif ($decision -in @('no-company', 'cannot-confirm')) { 'incomplete' } else { 'rejected' })
        $out.message = $reason
        $out.chatReply = $(if ($isSend) { "No troubleshooting article was sent: $reason" } else { "The ticket was left as it is: $reason" })
        if ($decision -notin $quiet) {
            $what = if ($isSend) { "Troubleshooting article not sent ('$title', confidence $($st['confidence']))" } else { 'Customer reply checked, ticket not closed' }
            $out.internal_note = "$($what): $reason"
            # The marker follows the note's content, so a retry of the same request is quiet and a new reply gets its own note.
            $out.note_written = Write-TaNote $out.internal_note $(if ($isSend) { 'Troubleshooting article not sent' } else { 'Reply checked' }) -Marker "AAI-TA $decision $(Get-TaHash "$($out.internal_note)|$($st['replyText'])")"
        }
        else { $out.internal_note = "No change: $reason" }
    }
}
Add-TaPsaWarnings
if ($warnings.Count -and $out.internal_note -and -not $out.note_written) { $out.internal_note += " Warnings: $(@($warnings) -join ' ')" }
$out.actions = @($actions)
$out.warnings = @($warnings)
Set-NodeOutput $out
