# === Step 4: Internal note with the reason (Auto-Escalation) ===
# Adds an internal (technician-only) note to each escalated ticket: why it was escalated, what was done,
# and whether the dispatcher was emailed. The note starts with "[Auto-Escalation]", which is how later runs
# know not to escalate the ticket again. Returns the workflow's output contract. Does nothing in preview.
# >>> _shared/psa.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/psa.ps1

function ConvertTo-EscHash {
    param($o)
    $h = [ordered]@{}
    if ($o -is [System.Collections.IDictionary]) { foreach ($k in @($o.Keys)) { $h[[string]$k] = $o[$k] } }
    elseif ($null -ne $o) { foreach ($p in @($o.PSObject.Properties)) { $h[$p.Name] = $p.Value } }
    return $h
}

$prev = ConvertTo-EscHash (Get-NodeInput)
$st = [string](Get-PsaProp $prev 'status')
if ($st -notin @('success', 'pending_confirmation')) { Set-NodeOutput $prev; throw "The previous step didn't finish: $(Get-PsaProp $prev 'message')" }
$settings = Get-PsaProp $prev 'settings'
$marker = [string](Get-PsaProp $settings 'marker'); if (-not $marker) { $marker = '[Auto-Escalation]' }
$escalations = @(@(Get-PsaProp $prev 'escalations') | Where-Object { $null -ne $_ } | ForEach-Object { ConvertTo-EscHash $_ })
$actions = @(@(Get-PsaProp $prev 'actions') | Where-Object { $_ })
$warnings = @(@(Get-PsaProp $prev 'warnings') | Where-Object { $_ })
$preview = (Get-PsaProp $prev 'preview') -eq $true
$emailed = (Get-PsaProp $prev 'dispatcher_emailed') -eq $true
$delivery = [string](Get-PsaProp $prev 'delivery')
$counts = ConvertTo-EscHash (Get-PsaProp $prev 'counts')
$noteFails = 0

if (-not $preview -and $escalations.Count) {
    $connected = $false
    try { $null = Connect-Psa (Get-PsaType ([string](Get-PsaProp $settings 'psa'))); $connected = $true }
    catch { $warnings += "Couldn't connect to the PSA to add the escalation notes: $($_.Exception.Message)" }
    $emailLine = if ($emailed) { 'The dispatcher was emailed.' } else { 'No dispatcher email was sent, so this note is the notification.' }
    foreach ($e in $escalations) {
        $text = "$marker This ticket was escalated automatically. $($e.reason) $($e.outcome) $emailLine".Trim() -replace '\s{2,}', ' '
        if (-not $connected) { $noteFails++; $e.error = (@($e.error, 'The note could not be added.') | Where-Object { $_ }) -join ' '; continue }
        try {
            Add-PsaNote -Id $e.id -Text $text -Title 'Auto-Escalation'
            $e.noted = $true
            $actions += "Ticket $($e.number): added the internal escalation note."
        }
        catch {
            $noteFails++
            $why = [string]$_.Exception.Message
            if ($why -match '\(HTTP 403\)') { $why = "$(Get-PsaName) refused the note (HTTP 403). Give the API user permission to add ticket notes." }
            $e.error = (@($e.error, "The note couldn't be added: $why") | Where-Object { $_ }) -join ' '
            $warnings += "Ticket $($e.number): the escalation note couldn't be added, so the next run may escalate it again. $why"
        }
    }
}

$n = $escalations.Count
$moved = @($escalations | Where-Object { $_.result -in @('reassigned', 'partial') }).Count
$moveFails = @($escalations | Where-Object { $_.result -in @('failed', 'partial') }).Count
if ($preview -or -not $n) {
    $status = [string](Get-PsaProp $prev 'status')
    $message = [string](Get-PsaProp $prev 'message')
}
else {
    $status = if ($moveFails -or $noteFails) { 'incomplete' } else { 'success' }
    $message = "Escalated $n ticket$(if ($n -ne 1) { 's' }): $moved moved up a tier and $($n - $moved) flagged without moving. $delivery"
    if ($moveFails) { $message += " $moveFails could not be moved; see warnings." }
    if ($noteFails) { $message += " $noteFails escalation note$(if ($noteFails -ne 1) { 's' }) could not be added; see warnings." }
}
$lines = @($escalations | ForEach-Object { "Ticket $($_.number) ($($_.company)): $($_.reason) $($_.outcome)".Trim() })
$internal = (@("Auto-Escalation ran against $(Get-PsaProp $prev 'psaName'). $message") + $lines) -join "`n"

Set-NodeOutput ([ordered]@{
        status = $status; message = $message.Trim(); public_note = ''; internal_note = $internal; ticket_id = $(if ($n -eq 1) { [string]$escalations[0].id } else { '' })
        preview = $preview; dispatcher_emailed = $emailed; counts = $counts; escalations = @($escalations)
        actions = @($actions); warnings = @($warnings)
    })
