# === Step 3: Notify the dispatcher (Auto-Escalation) ===
# Sends one email per run to dispatcher_email through Postmark (Send-PmMail), listing every ticket this run
# escalated, why, and what was done. Tickets another run had already escalated are left out, so a retried or
# overlapping run doesn't email the dispatcher about them again. Without a dispatcher_email or the Postmark
# secrets, the internal note on each ticket is the notification. Does nothing in preview or when nothing
# was escalated.
# Secrets (same names as the Postmark extension): Postmark-ServerToken, Postmark-FromEmail, Postmark-ApiUrl (optional).
# >>> _shared/postmark.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/postmark.ps1

function ConvertTo-EscHash {
    param($o)
    $h = [ordered]@{}
    if ($o -is [System.Collections.IDictionary]) { foreach ($k in @($o.Keys)) { $h[[string]$k] = $o[$k] } }
    elseif ($null -ne $o) { foreach ($p in @($o.PSObject.Properties)) { $h[$p.Name] = $p.Value } }
    return $h
}

$prev = ConvertTo-EscHash (Get-NodeInput)
$st = [string](Get-PmProp $prev 'status')
if ($st -notin @('success', 'pending_confirmation')) { Set-NodeOutput $prev; throw "The previous step didn't finish: $(Get-PmProp $prev 'message')" }
$settings = Get-PmProp $prev 'settings'
$escalations = @(@(Get-PmProp $prev 'escalations') | Where-Object { $null -ne $_ })
$actions = @(@(Get-PmProp $prev 'actions') | Where-Object { $_ })
$warnings = @(@(Get-PmProp $prev 'warnings') | Where-Object { $_ })
$preview = (Get-PmProp $prev 'preview') -eq $true
$to = @(@(Get-PmProp $settings 'dispatcher_email') | Where-Object { $_ })
$psaName = [string](Get-PmProp $prev 'psaName')
$report = @($escalations | Where-Object { (Get-PmProp $_ 'result') -ne 'already-escalated' })

$emailed = $false; $delivery = ''
if ($preview) { $delivery = 'Preview: no email was sent.' }
elseif (-not $report.Count) { $delivery = 'Nothing new was escalated, so no email was sent.' }
elseif (-not $to.Count) { $delivery = 'No dispatcher_email was given, so the internal note on each ticket is the dispatcher notification.'; $warnings += $delivery }
else {
    $n = $report.Count
    $moved = @($report | Where-Object { (Get-PmProp $_ 'result') -in @('reassigned', 'partial') }).Count
    $subject = "Auto-Escalation: $n ticket$(if ($n -ne 1) { 's' }) escalated"
    $cell = 'padding:6px 8px;border-bottom:1px solid #e5e7eb;text-align:left;vertical-align:top;'
    $sb = New-Object System.Text.StringBuilder
    $null = $sb.Append('<div style="font-family:Segoe UI,Arial,sans-serif;font-size:14px;color:#111827;">')
    $null = $sb.Append("<p style=`"margin:0 0 12px;`">$n ticket$(if ($n -ne 1) { 's were' } else { ' was' }) escalated in $(ConvertTo-PmHtml $psaName). $moved moved up a tier. Any others were flagged without being moved, and the table says why. Each ticket also has an internal note with the same detail.</p>")
    $null = $sb.Append("<table style=`"border-collapse:collapse;width:100%;`"><tr style=`"background:#f3f4f6;`"><th style=`"$cell`">Ticket</th><th style=`"$cell`">Company</th><th style=`"$cell`">Summary</th><th style=`"$cell`">Priority</th><th style=`"$cell`">Technician</th><th style=`"$cell`">Why</th><th style=`"$cell`">What happened</th></tr>")
    foreach ($e in $report) {
        $prio = [string](Get-PmProp $e 'priorityLabel'); if (-not $prio) { $prio = [string](Get-PmProp $e 'priority') }
        $null = $sb.Append("<tr><td style=`"$cell`">$(ConvertTo-PmHtml ([string](Get-PmProp $e 'number')))</td><td style=`"$cell`">$(ConvertTo-PmHtml ([string](Get-PmProp $e 'company')))</td><td style=`"$cell`">$(ConvertTo-PmHtml ([string](Get-PmProp $e 'summary')))</td><td style=`"$cell`">$(ConvertTo-PmHtml $prio)</td><td style=`"$cell`">$(ConvertTo-PmHtml ([string](Get-PmProp $e 'technician')))</td><td style=`"$cell`">$(ConvertTo-PmHtml ([string](Get-PmProp $e 'reason')))</td><td style=`"$cell`">$(ConvertTo-PmHtml ([string](Get-PmProp $e 'outcome')))</td></tr>")
    }
    $null = $sb.Append('</table><p style="margin:16px 0 0;color:#6b7280;font-size:12px;">Sent by the AutomationAI Auto-Escalation workflow. A ticket is escalated once; the [Auto-Escalation] note stops it being escalated again.</p></div>')
    $text = (@($report | ForEach-Object { "- #$(Get-PmProp $_ 'number') $(Get-PmProp $_ 'company'): $(Get-PmProp $_ 'summary'). $(Get-PmProp $_ 'reason') $(Get-PmProp $_ 'outcome')" })) -join "`n"
    $stream = [string](Get-PmProp $settings 'message_stream'); if (-not $stream) { $stream = 'outbound' }
    $r = Send-PmMail -To $to -Subject $subject -Html $sb.ToString() -Text $text -Tag 'auto-escalation' -Stream $stream -From ([string](Get-PmProp $settings 'from'))
    if ($r.sent) { $emailed = $true; $delivery = "The dispatcher was emailed ($(@($r.to) -join ', '))."; $actions += $delivery }
    elseif (-not $r.configured) { $delivery = "$($r.reason) The internal note on each ticket is the dispatcher notification."; $warnings += $delivery }
    else { $delivery = "The dispatcher email couldn't be sent, so the internal note on each ticket is the notification. $($r.reason)"; $warnings += $delivery }
}

$prev.dispatcher_emailed = $emailed
$prev.delivery = $delivery
$prev.actions = @($actions)
$prev.warnings = @($warnings)
Set-NodeOutput $prev
