# === Step 2: Reassign up a tier (Auto-Escalation) ===
# For each planned escalation with action "reassign": moves the ticket to the mapped queue, board, team or
# group, and/or assigns the mapped user. One tier per run. Does nothing in preview, and nothing for
# "note-only" tickets (no map entry, or someone is actively working them).
# >>> _shared/psa.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/psa.ps1
# >>> src/psa-extra.ps1 (generated by src/build.js; edit the source, not this block)
# <<< src/psa-extra.ps1

function ConvertTo-EscHash {
    param($o)
    $h = [ordered]@{}
    if ($o -is [System.Collections.IDictionary]) { foreach ($k in @($o.Keys)) { $h[[string]$k] = $o[$k] } }
    elseif ($null -ne $o) { foreach ($p in @($o.PSObject.Properties)) { $h[$p.Name] = $p.Value } }
    return $h
}
# A 403 on a write becomes a plain sentence about the API user's permissions.
function Get-EscWriteError {
    param([string]$Message)
    if ($Message -match '\(HTTP 403\)') { return "$(Get-PsaName) refused the change (HTTP 403). Give the API user permission to update service tickets." }
    return $Message
}

$prev = ConvertTo-EscHash (Get-NodeInput)
$st = [string](Get-PsaProp $prev 'status')
if ($st -notin @('success', 'pending_confirmation')) { Set-NodeOutput $prev; throw "The previous step didn't finish: $(Get-PsaProp $prev 'message')" }
$settings = Get-PsaProp $prev 'settings'
$escalations = @(@(Get-PsaProp $prev 'escalations') | Where-Object { $null -ne $_ } | ForEach-Object { ConvertTo-EscHash $_ })
$actions = @(@(Get-PsaProp $prev 'actions') | Where-Object { $_ })
$warnings = @(@(Get-PsaProp $prev 'warnings') | Where-Object { $_ })
$preview = (Get-PsaProp $prev 'preview') -eq $true
$todo = @($escalations | Where-Object { $_.action -eq 'reassign' })

if (-not $preview -and $todo.Count) {
    $connected = $false
    try { $null = Connect-Psa (Get-PsaType ([string](Get-PsaProp $settings 'psa'))); $connected = $true }
    catch { $warnings += "Couldn't connect to the PSA to reassign tickets: $($_.Exception.Message)" }
    foreach ($e in $todo) {
        if (-not $connected) { $e.result = 'failed'; $e.error = 'Could not connect to the PSA.'; $e.outcome = "It couldn't be moved because the PSA connection failed."; continue }
        $done = @(); $failed = @()
        if ($e.toQueue) {
            try { Set-PsaQueue $e.id $e.toQueue; $done += "moved from $($e.queue) to $($e.toQueue)" }
            catch { $failed += "couldn't be moved to $($e.toQueue) ($(Get-EscWriteError ([string]$_.Exception.Message)))" }
        }
        if ($e.toAssignee) {
            try {
                $role = [string]$e.toRole
                if (-not $role) { $role = Get-PsaDefaultRole $e.toAssignee }
                Set-PsaAssignee $e.id $e.toAssignee $role
                $done += "assigned to $($e.toAssignee)"
            }
            catch { $failed += "couldn't be assigned to $($e.toAssignee) ($(Get-EscWriteError ([string]$_.Exception.Message)))" }
        }
        $parts = @(); if ($done.Count) { $parts += "It was $($done -join ' and ')." }; if ($failed.Count) { $parts += "It $($failed -join ' and ')." }
        $e.outcome = $parts -join ' '
        if ($failed.Count) { $e.result = $(if ($done.Count) { 'partial' } else { 'failed' }); $e.error = ($failed -join '; ') ; $warnings += "Ticket $($e.number): $($e.outcome)" }
        else { $e.result = 'reassigned' }
        $actions += "Ticket $($e.number): $($e.outcome)"
    }
}
foreach ($e in @($escalations | Where-Object { $_.action -ne 'reassign' })) { if (-not $preview) { $e.result = 'note-only' }; $e.outcome = $e.whyNotMoved }
foreach ($e in @($escalations | Where-Object { $_.action -eq 'reassign' -and $preview })) {
    $plan = @(); if ($e.toQueue) { $plan += "move it from $($e.queue) to $($e.toQueue)" }; if ($e.toAssignee) { $plan += "assign it to $($e.toAssignee)" }
    $e.outcome = "Would $($plan -join ' and ')."
}

$prev.escalations = @($escalations)
$prev.actions = @($actions)
$prev.warnings = @($warnings)
Set-NodeOutput $prev
