# === Step 2: Mark and reassign up a tier (Auto-Escalation) ===
# For each planned escalation, first writes the internal "[Auto-Escalation]" note (why, and what is about to
# happen) with Add-PsaNote -Marker, and only then moves the ticket for action "reassign": to the mapped
# queue, board, team or group, and/or the mapped user. One tier per run. Does nothing in preview.
# Why the note goes first: the note is the record that the ticket was escalated. Add-PsaNote -Marker checks
# the ticket for it just before writing, so when a run is retried (Action Runs Retry) or two runs overlap,
# a ticket that already carries the note is left alone: it isn't moved again and isn't emailed again.
# If the note can't be written, the ticket isn't moved either (fail closed), because without the note a
# retry couldn't tell the move had happened.
# >>> _shared/psa.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/psa.ps1
# >>> _shared/psa-tickets.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/psa-tickets.ps1
# >>> _shared/postmark.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/postmark.ps1

function ConvertTo-EscHash {
    param($o)
    $h = [ordered]@{}
    if ($o -is [System.Collections.IDictionary]) { foreach ($k in @($o.Keys)) { $h[[string]$k] = $o[$k] } }
    elseif ($null -ne $o) { foreach ($p in @($o.PSObject.Properties)) { $h[$p.Name] = $p.Value } }
    return $h
}
# A 403 on a write becomes a plain sentence about the API user's permissions.
function Get-EscWriteError {
    param([string]$Message, [string]$Need = 'update service tickets')
    if ($Message -match '\(HTTP 403\)') { return "$(Get-PsaName) refused the change (HTTP 403). Give the API user permission to $Need." }
    return $Message
}

$prev = ConvertTo-EscHash (Get-NodeInput)
$st = [string](Get-PsaProp $prev 'status')
if ($st -notin @('success', 'pending_confirmation')) { Set-NodeOutput $prev; throw "The previous step didn't finish: $(Get-PsaProp $prev 'message')" }
$settings = Get-PsaProp $prev 'settings'
$marker = [string](Get-PsaProp $settings 'marker'); if (-not $marker) { $marker = '[Auto-Escalation]' }
$escalations = @(@(Get-PsaProp $prev 'escalations') | Where-Object { $null -ne $_ } | ForEach-Object { ConvertTo-EscHash $_ })
$actions = @(@(Get-PsaProp $prev 'actions') | Where-Object { $_ })
$warnings = @(@(Get-PsaProp $prev 'warnings') | Where-Object { $_ })
$preview = (Get-PsaProp $prev 'preview') -eq $true
# Whether the next step will try to email the dispatcher, so the note can say so.
$emailPlanned = (@(@(Get-PsaProp $settings 'dispatcher_email') | Where-Object { $_ }).Count -gt 0) -and (Test-PmConfigured)

foreach ($e in $escalations) {
    if ($e.action -eq 'reassign') {
        $plan = @(); if ($e.toQueue) { $plan += "move it from $($e.queue) to $($e.toQueue)" }; if ($e.toAssignee) { $plan += "assign it to $($e.toAssignee)" }
        $e.planText = "Auto-Escalation is going to $($plan -join ' and ')."
        if ($preview) { $e.outcome = "Would $($plan -join ' and ')." }
    }
    else {
        $e.planText = $e.whyNotMoved
        if ($preview) { $e.outcome = $e.whyNotMoved }
    }
}

if (-not $preview -and $escalations.Count) {
    $connected = $false
    try { $null = Connect-Psa (Get-PsaType ([string](Get-PsaProp $settings 'psa'))); $connected = $true }
    catch { $warnings += "Couldn't connect to the PSA to escalate tickets: $($_.Exception.Message)" }
    $emailLine = if ($emailPlanned) { 'The dispatcher is being emailed a list of the escalated tickets.' } else { 'No dispatcher email is set up, so this note is the notification.' }
    foreach ($e in $escalations) {
        if (-not $connected) { $e.result = 'failed'; $e.error = 'Could not connect to the PSA.'; $e.outcome = "It wasn't escalated because the PSA connection failed."; continue }

        # 1. The marker note. 'already-present' means another run (or an earlier try of this one) escalated it.
        $text = "$marker This ticket was escalated automatically. $($e.reason) $($e.planText) $emailLine".Trim() -replace '\s{2,}', ' '
        $noteResult = ''
        try { $noteResult = Add-PsaNote -Id $e.id -Text $text -Title 'Auto-Escalation' -Marker $marker }
        catch {
            $why = Get-EscWriteError ([string]$_.Exception.Message) 'add ticket notes'
            $e.result = 'failed'; $e.error = "The escalation note couldn't be added: $why"
            $e.outcome = "It wasn't moved, because the escalation note couldn't be added first."
            $warnings += "Ticket $($e.number): the escalation note couldn't be added, so it wasn't moved. $why"
            continue
        }
        if ($noteResult -eq 'already-present') {
            $e.result = 'already-escalated'; $e.outcome = 'It already has an Auto-Escalation note from another run, so nothing more was done.'
            $actions += "Ticket $($e.number): already escalated by another run; left alone."
            continue
        }
        $e.noted = $true
        $actions += "Ticket $($e.number): added the internal escalation note."
        if ($e.action -ne 'reassign') { $e.result = 'note-only'; $e.outcome = $e.whyNotMoved; continue }

        # 2. The move, only once the note is on the ticket.
        $done = @(); $failed = @()
        if ($e.toQueue) {
            try { Set-PsaQueue $e.id $e.toQueue; $done += "moved from $($e.queue) to $($e.toQueue)" }
            catch { $failed += "couldn't be moved to $($e.toQueue) ($(Get-EscWriteError ([string]$_.Exception.Message)))" }
        }
        if ($e.toAssignee) {
            try {
                $role = [string]$e.toRole
                if (-not $role) { $role = Get-PsaDefaultRole $e.toAssignee }
                Set-PsaAssignee $e.id $e.toAssignee $role
                $done += "assigned to $($e.toAssignee)"
            }
            catch { $failed += "couldn't be assigned to $($e.toAssignee) ($(Get-EscWriteError ([string]$_.Exception.Message)))" }
        }
        $parts = @(); if ($done.Count) { $parts += "It was $($done -join ' and ')." }; if ($failed.Count) { $parts += "It $($failed -join ' and ')." }
        $e.outcome = $parts -join ' '
        if ($failed.Count) { $e.result = $(if ($done.Count) { 'partial' } else { 'failed' }); $e.error = ($failed -join '; '); $warnings += "Ticket $($e.number): $($e.outcome)" }
        else { $e.result = 'reassigned' }
        $actions += "Ticket $($e.number): $($e.outcome)"
    }
}

$prev.escalations = @($escalations)
$prev.email_planned = $emailPlanned
$prev.actions = @($actions)
$prev.warnings = @($warnings)
Set-NodeOutput $prev
