// Builds ../license-reclamation.yml from the step sources in this folder, then pastes the shared
// libraries into it with ../../_shared/inject.js.
// Usage: node build.js          rewrite the .yml
//        node build.js --check  exit 1 if the .yml is out of date
// Edit inputs.ps1, scan.ps1 or card.ps1 here, never the scripts inside the .yml.
// Needs js-yaml: npm install in ../../_shared, or set JS_YAML_PATH to an existing copy.
const fs = require('fs');
const path = require('path');
let y;
try { y = require('js-yaml'); } catch {
  try { y = require(path.join(__dirname, '..', '..', '_shared', 'node_modules', 'js-yaml')); } catch { y = require(process.env.JS_YAML_PATH); }
}
const { injectText } = require(path.join(__dirname, '..', '..', '_shared', 'inject.js'));

const here = __dirname;
const target = path.join(here, '..', 'license-reclamation.yml');
const read = (f) => fs.readFileSync(path.join(here, f), 'utf8').replace(/\r\n/g, '\n').trimEnd() + '\n';

const step = (id, name, x, file, extra = {}) => ({
  id, name, type: 'powershell-script', position: { x, y: 120 },
  properties: { script: read(file), timeoutSeconds: 900, retryCount: 0, parameters: [], aiExtensions: [], ...extra },
});

const wf = {
  automationsWorkflow: 1,
  name: 'Microsoft 365 License Reclamation',
  definition: {
    schemaVersion: 1,
    activities: [
      { id: 'start', name: 'Start', type: 'start', position: { x: 100, y: 120 }, properties: { webhookEnabled: false } },
      step('node-inputs', 'Read inputs', 300, 'inputs.ps1', {
        timeoutSeconds: 60,
        testInput: JSON.stringify({ days: 60, price_overrides: {}, company_id: '', preview: true }, null, 2),
      }),
      step('node-scan', 'Find unused licences', 520, 'scan.ps1'),
      step('node-card', 'Update Planner card', 740, 'card.ps1', { timeoutSeconds: 600 }),
      { id: 'end', name: 'End', type: 'end', position: { x: 960, y: 120 } },
    ],
    connections: [
      { source: 'start', target: 'node-inputs', sourceHandle: null },
      { source: 'node-inputs', target: 'node-scan', sourceHandle: null },
      { source: 'node-scan', target: 'node-card', sourceHandle: null },
      { source: 'node-card', target: 'end', sourceHandle: null },
    ],
    startActivityId: 'start',
  },
};

const header = '# Generated by src/build.js from src/*.ps1 and ../_shared. Edit the sources, not this file.\n';
const dumped = header + y.dump(wf, { lineWidth: -1, noRefs: true });
const { text } = injectText(dumped, 'license-reclamation.yml', new Map());
const parsed = y.load(text);
for (const a of parsed.definition.activities) {
  const s = a.properties && a.properties.script;
  if (s && /# >>> _shared\/\S+\n\s*# <<< _shared/.test(s)) throw new Error(`${a.id}: a shared block is empty after injecting`);
}
const check = process.argv.includes('--check');
const was = fs.existsSync(target) ? fs.readFileSync(target, 'utf8').replace(/\r\n/g, '\n') : '';
if (text === was) { console.log('license-reclamation.yml: current'); process.exit(0); }
if (check) { console.log('license-reclamation.yml: OUT OF DATE (run node src/build.js)'); process.exit(1); }
fs.writeFileSync(target, text);
console.log(`license-reclamation.yml: written (${text.length} bytes)`);
