# === STEP: Update Planner card ===
# Edit this file, then run: node license-reclamation/src/build.js
# Writes the findings to one CloudRadial Planner card on this company's board (stable key license-reclamation),
# updating last month's card instead of adding another. When nothing is reclaimable it updates an existing
# card to say so, and creates nothing. The card is the only thing this workflow writes; no licence is changed.
# Secrets: CloudRadial-BaseUrl, CloudRadial-PublicKey, CloudRadial-PrivateKey, optional CloudRadial-CompanyId.
# >>> _shared/cloudradial.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/cloudradial.ps1

$in = Get-NodeInput
function Enc { param($s) return [System.Net.WebUtility]::HtmlEncode([string]$s) }
function Money { param([double]$v) return '$' + $v.ToString('N2', [System.Globalization.CultureInfo]::InvariantCulture) }
$warnings = New-Object System.Collections.ArrayList
foreach ($w in @(Get-CrProp $in 'warnings')) { if ($w) { $null = $warnings.Add([string]$w) } }

function Stop-LrCard {
    param([string]$Why)
    Set-NodeOutput ([ordered]@{ status = 'error'; message = $Why; public_note = ''; internal_note = $Why; ticket_id = ''; actions = @(); warnings = @($warnings) })
    throw $Why
}

$CardSubject = 'Reclaim unused Microsoft 365 licences'
$CardKey = 'license-reclamation'
$MaxRows = 50
$days = [int](Get-CrProp $in 'days')
$preview = [bool](Get-CrProp $in 'preview')
$tenantId = [string](Get-CrProp $in 'tenantId')
$checkedOn = [string](Get-CrProp $in 'checkedOn')
$users = @(Get-CrProp $in 'users' | Where-Object { $null -ne $_ })
$licenceCount = [int](Get-CrProp $in 'licenceCount')
$saving = [double](Get-CrProp $in 'monthlySaving')
$disabledCount = [int](Get-CrProp $in 'disabledCount')
$unknownSkus = @(Get-CrProp $in 'unknownPriceSkus' | Where-Object { $_ })

try { $null = Connect-Cr } catch { Stop-LrCard ([string]$_.Exception.Message) }

# ---- which CloudRadial company: the run's company_id, then the CloudRadial-CompanyId secret, then the tenant match ----
$tenantFields = @('tenantId', 'companyTenantId', 'officeTenantId', 'm365TenantId', 'azureTenantId', 'microsoftTenantId')
function Get-LrTenantOf { param($co) foreach ($f in $tenantFields) { $v = [string](Get-CrProp $co $f); if ($v -match '^[0-9a-fA-F-]{36}$') { return $v.ToLowerInvariant() } }; return '' }
$companyId = [int](Get-CrProp $in 'company_id')
$how = 'company_id input'
if ($companyId -le 0) {
    $sec = [string](Get-CrSecret 'CloudRadial-CompanyId')
    if ($sec.Trim() -match '^\d+$' -and [int]$sec.Trim() -gt 0) { $companyId = [int]$sec.Trim(); $how = 'CloudRadial-CompanyId secret' }
}
$company = $null
try {
    if ($companyId -gt 0) {
        $company = @(Get-CrAll "/v2/odata/company?`$filter=companyId eq $companyId") | Select-Object -First 1
        if ($null -eq $company) { Stop-LrCard "CloudRadial company $companyId (from the $how) was not found. Check the company number and run again." }
    }
    else {
        $all = @(Get-CrAll '/v2/odata/company')
        $hits = @($all | Where-Object { $tenantId -and (Get-LrTenantOf $_) -eq $tenantId.ToLowerInvariant() })
        if ($hits.Count -eq 1) { $company = $hits[0]; $companyId = [int](Get-CrProp $company 'companyId'); $how = 'Microsoft 365 tenant match' }
        else { Stop-LrCard "Couldn't tell which CloudRadial company Microsoft 365 tenant $tenantId belongs to. Set company_id on the run, or add the CloudRadial-CompanyId secret to this runner's Key Vault." }
    }
}
catch { if ($_.Exception.Message -match "^(CloudRadial company|Couldn't tell)") { throw }; Stop-LrCard "Couldn't read the CloudRadial company: $($_.Exception.Message)" }
$companyName = [string](Get-CrProp $company 'name'); if (-not $companyName) { $companyName = "company $companyId" }

# Never write one tenant's users onto another company's card.
$coTenant = Get-LrTenantOf $company
if ($coTenant -and $tenantId -and $coTenant -ne $tenantId.ToLowerInvariant()) {
    Stop-LrCard "CloudRadial company $companyName ($companyId) is linked to a different Microsoft 365 tenant than the one this runner signs in to ($tenantId), so no card was written. Check company_id and the runner's M365 secrets."
}

# ---- the card ----
$cards = @()
try { $cards = @(Get-CrAll "/v2/odata/product?`$filter=companyId eq $companyId") } catch { Stop-LrCard "Couldn't read the Planner cards for $($companyName): $($_.Exception.Message)" }
$ovUsed = @(Get-CrProp $in 'overridesUsed' | Where-Object { $_ })
$probe = Set-CrPlannerCard -CompanyId $companyId -Subject $CardSubject -Key $CardKey -Existing $cards -Fields @{ body = '' } -Preview
$exists = ($probe.action -eq 'would-update')
$internal = "Internal: CloudRadial company $companyId (chosen by $how), Microsoft 365 tenant $tenantId. Checked on $checkedOn with a $days-day threshold; $([int](Get-CrProp $in 'licensedUsers')) users with a paid licence were checked. Mailbox activity used: $(if ([bool](Get-CrProp $in 'mailboxChecked')) { 'yes' } else { 'no' }). Price overrides: $(if ($ovUsed.Count) { $ovUsed -join ', ' } else { 'none' }). Marker: $CardKey."

if (-not $users.Count) {
    $msg = "Every paid Microsoft 365 licence at $companyName was used in the last $days days, so there is nothing to reclaim."
    if (-not $exists) {
        Set-NodeOutput ([ordered]@{ status = 'success'; message = "$msg No Planner card was needed."; public_note = ''; internal_note = $internal; ticket_id = ''; actions = @(); warnings = @($warnings)
                companyId = $companyId; companyName = $companyName; cardAction = 'none'; productId = ''; licenceCount = 0; monthlySaving = 0; users = @() })
        return
    }
    $body = "<p>This CloudRadial Planner card tracks unused Microsoft 365 licences at $(Enc $companyName).</p><p>As of $(Enc $checkedOn), every paid licence was used in the last $days days, so there is nothing to reclaim this month.</p><p>This card is updated each month by the License Reclamation automation.</p>"
    $fields = [ordered]@{ body = $body; summary = 'No unused Microsoft 365 licences this month.'; notes = $internal; status = 40; priority = -1 }
    $r = Set-CrPlannerCard -CompanyId $companyId -Subject $CardSubject -Key $CardKey -Existing $cards -Fields $fields -Preview:$preview
    $done = if ($preview) { "Preview only: the Planner card would be updated to say so." } else { 'The Planner card was updated to say so.' }
    Set-NodeOutput ([ordered]@{ status = $(if ($preview) { 'pending_confirmation' } else { 'success' }); message = "$msg $done"; public_note = ''; internal_note = $internal; ticket_id = ''
            actions = @("Planner card $($r.action)"); warnings = @($warnings); companyId = $companyId; companyName = $companyName; cardAction = $r.action; productId = [string]$r.productId; licenceCount = 0; monthlySaving = 0; users = @() })
    return
}

$userWord = if ($users.Count -eq 1) { '1 user' } else { "$($users.Count) users" }
$licWord = if ($licenceCount -eq 1) { '1 paid licence' } else { "$licenceCount paid licences" }
$disWord = ''
if ($disabledCount -eq 1) { $disWord = ', including 1 disabled account that still holds a licence' } elseif ($disabledCount -gt 1) { $disWord = ", including $disabledCount disabled accounts that still hold a licence" }
$summary = "$licWord held by $userWord have not been used in $days days, worth an estimated $(Money $saving) a month."

$sb = New-Object System.Text.StringBuilder
$null = $sb.Append("<p>This CloudRadial Planner card lists Microsoft 365 licences at $(Enc $companyName) that look unused. As of $(Enc $checkedOn), $licWord held by $userWord have not been used in the last $days days$disWord.</p>")
$null = $sb.Append("<p>Removing them could save an estimated <strong>$(Money $saving) a month</strong> ($(Money ($saving * 12)) a year). Prices are Microsoft list-price estimates in US dollars, not what this client actually pays.")
if ($unknownSkus.Count) { $null = $sb.Append(" The price of $(Enc ($unknownSkus -join ', ')) is unknown, so $(if ($unknownSkus.Count -eq 1) { 'it is' } else { 'they are' }) not in the total.") }
$null = $sb.Append('</p><p>Nothing has been removed. Review the list with the client, then remove or reassign the licences in the Microsoft 365 admin center.</p>')
$null = $sb.Append('<table><thead><tr><th>User</th><th>Licence</th><th>Last sign-in</th><th>Status</th></tr></thead><tbody>')
foreach ($u in @($users | Select-Object -First $MaxRows)) {
    $lics = @(@(Get-CrProp $u 'licences') | ForEach-Object { $p = Get-CrProp $_ 'price'; "$(Enc (Get-CrProp $_ 'name')) ($(if ($null -ne $p) { Money ([double]$p) } else { 'price unknown' }))" }) -join '<br>'
    $last = [string](Get-CrProp $u 'lastSignIn'); if (-not $last) { $last = 'Never' }
    $st = switch ([string](Get-CrProp $u 'reason')) { 'disabled' { 'Disabled but licensed' } 'never' { 'Never signed in' } default { 'Inactive' } }
    $mb = [string](Get-CrProp $u 'lastMailbox'); if ($mb) { $st = "$st (mailbox last used $mb)" }
    $who = Enc (Get-CrProp $u 'name'); $upn = [string](Get-CrProp $u 'upn'); if ($upn) { $who = "$who<br>$(Enc $upn)" }
    $null = $sb.Append("<tr><td>$who</td><td>$lics</td><td>$(Enc $last)</td><td>$(Enc $st)</td></tr>")
}
$null = $sb.Append('</tbody></table>')
if ($users.Count -gt $MaxRows) { $null = $sb.Append("<p>$($users.Count - $MaxRows) more users are not shown here. The full list is in the workflow run output.</p>") }
$null = $sb.Append('<p>A shared mailbox only needs a licence when it holds more than 50 GB or has an archive, so check those before removing a licence.</p>')
foreach ($w in $warnings) { $null = $sb.Append("<p>Note: $(Enc $w)</p>") }
$null = $sb.Append('<p>This card is updated each month by the License Reclamation automation.</p>')

$fields = [ordered]@{ body = $sb.ToString(); summary = $summary; notes = $internal; status = 0; priority = $(if ($saving -ge 100 -or $disabledCount -gt 0) { 1 } else { 0 }) }
try { $r = Set-CrPlannerCard -CompanyId $companyId -Subject $CardSubject -Key $CardKey -Existing $cards -Fields $fields -Preview:$preview }
catch { Stop-LrCard "Couldn't write the Planner card for $($companyName): $($_.Exception.Message)" }
if ($r.optionalFieldsDropped) { $null = $warnings.Add('This portal did not accept the internal notes field, so the card was written without it.') }

$verb = switch ($r.action) { 'created' { 'added to' } 'updated' { 'updated on' } 'would-create' { 'would be added to' } default { 'would be updated on' } }
$msg = "$summary The CloudRadial Planner card '$CardSubject' was $verb $companyName's board for review. No licence was changed."
if ($preview) { $msg = "Preview only: $summary The CloudRadial Planner card '$CardSubject' $verb $companyName's board when this runs without preview. No licence was changed." }
Set-NodeOutput ([ordered]@{
        status        = $(if ($preview) { 'pending_confirmation' } else { 'success' })
        message       = $msg
        public_note   = ''
        internal_note = $internal
        ticket_id     = ''
        actions       = @("Planner card $($r.action)")
        warnings      = @($warnings)
        companyId     = $companyId
        companyName   = $companyName
        cardAction    = $r.action
        productId     = [string]$r.productId
        licenceCount  = $licenceCount
        monthlySaving = $saving
        users         = $users
    })
