# === STEP: Find unused licences ===
# Edit this file, then run: node license-reclamation/src/build.js
# Read-only. Reads the tenant's subscriptions, every user's licences and last sign-in, and (when allowed)
# mailbox activity, then lists users holding a paid licence they haven't used in the last <days> days.
# Disabled accounts that still hold a paid licence are always listed. Free and trial SKUs are ignored.
# Graph application permissions: Organization.Read.All (or Directory.Read.All), User.Read.All,
# AuditLog.Read.All (needs Entra ID P1). Optional: Reports.Read.All for mailbox activity.
# >>> _shared/graph.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/graph.ps1

$in = Get-NodeInput
$days = [int](Get-GraphProp $in 'days'); if ($days -le 0) { $days = 60 }
$overrides = @{}
$po = Get-GraphProp $in 'price_overrides'
if ($po -is [System.Collections.IDictionary]) { foreach ($k in $po.Keys) { $overrides[([string]$k).ToUpperInvariant()] = [double]$po[$k] } }
elseif ($null -ne $po) { foreach ($p in $po.PSObject.Properties) { $overrides[$p.Name.ToUpperInvariant()] = [double]$p.Value } }
$warnings = New-Object System.Collections.ArrayList

function Stop-LrScan {
    param([string]$Why)
    Set-NodeOutput ([ordered]@{ status = 'error'; message = $Why; public_note = ''; internal_note = $Why; ticket_id = ''; actions = @(); warnings = @($warnings) })
    throw $Why
}

# ---- built-in tables ----
# List prices in USD per user per month, annual commitment, as published by Microsoft. Estimates only:
# partner, CSP and monthly-billing prices differ. price_overrides replaces any of them.
$LrPrices = [ordered]@{
    'O365_BUSINESS_ESSENTIALS' = @{ name = 'Microsoft 365 Business Basic'; price = 6.00 }
    'O365_BUSINESS_PREMIUM'    = @{ name = 'Microsoft 365 Business Standard'; price = 12.50 }
    'SPB'                      = @{ name = 'Microsoft 365 Business Premium'; price = 22.00 }
    'O365_BUSINESS'            = @{ name = 'Microsoft 365 Apps for business'; price = 8.25 }
    'OFFICESUBSCRIPTION'       = @{ name = 'Microsoft 365 Apps for enterprise'; price = 12.00 }
    'STANDARDPACK'             = @{ name = 'Office 365 E1'; price = 10.00 }
    'ENTERPRISEPACK'           = @{ name = 'Office 365 E3'; price = 23.00 }
    'ENTERPRISEPREMIUM'        = @{ name = 'Office 365 E5'; price = 38.00 }
    'SPE_E3'                   = @{ name = 'Microsoft 365 E3'; price = 36.00 }
    'SPE_E5'                   = @{ name = 'Microsoft 365 E5'; price = 57.00 }
    'SPE_F1'                   = @{ name = 'Microsoft 365 F3'; price = 8.00 }
    'DESKLESSPACK'             = @{ name = 'Office 365 F3'; price = 2.25 }
    'EXCHANGESTANDARD'         = @{ name = 'Exchange Online (Plan 1)'; price = 4.00 }
    'EXCHANGEENTERPRISE'       = @{ name = 'Exchange Online (Plan 2)'; price = 8.00 }
    'EXCHANGEDESKLESS'         = @{ name = 'Exchange Online Kiosk'; price = 2.00 }
    'EXCHANGEARCHIVE_ADDON'    = @{ name = 'Exchange Online Archiving'; price = 3.00 }
    'POWER_BI_PRO'             = @{ name = 'Power BI Pro'; price = 14.00 }
    'PBI_PREMIUM_PER_USER'     = @{ name = 'Power BI Premium Per User'; price = 24.00 }
    'PROJECTPROFESSIONAL'      = @{ name = 'Project Plan 3'; price = 30.00 }
    'PROJECT_P1'               = @{ name = 'Project Plan 1'; price = 10.00 }
    'VISIOCLIENT'              = @{ name = 'Visio Plan 2'; price = 15.00 }
    'VISIOONLINE_PLAN1'        = @{ name = 'Visio Plan 1'; price = 5.00 }
    'EMS'                      = @{ name = 'Enterprise Mobility + Security E3'; price = 10.60 }
    'EMSPREMIUM'               = @{ name = 'Enterprise Mobility + Security E5'; price = 16.40 }
    'AAD_PREMIUM'              = @{ name = 'Microsoft Entra ID P1'; price = 6.00 }
    'AAD_PREMIUM_P2'           = @{ name = 'Microsoft Entra ID P2'; price = 9.00 }
    'INTUNE_A'                 = @{ name = 'Microsoft Intune Plan 1'; price = 8.00 }
    'ATP_ENTERPRISE'           = @{ name = 'Microsoft Defender for Office 365 (Plan 1)'; price = 2.00 }
    'THREAT_INTELLIGENCE'      = @{ name = 'Microsoft Defender for Office 365 (Plan 2)'; price = 5.00 }
    'MCOEV'                    = @{ name = 'Teams Phone Standard'; price = 10.00 }
    'MCOMEETADV'               = @{ name = 'Microsoft 365 Audio Conferencing'; price = 4.00 }
    'MICROSOFT_TEAMS_ENTERPRISE_NEW' = @{ name = 'Microsoft Teams Enterprise'; price = 5.25 }
    'MICROSOFT_365_COPILOT'    = @{ name = 'Microsoft 365 Copilot'; price = 30.00 }
}
# Free, trial and self-service SKUs that cost nothing, so they are never listed.
$LrFree = @('FLOW_FREE', 'POWER_BI_STANDARD', 'TEAMS_EXPLORATORY', 'TEAMS_FREE', 'POWERAPPS_VIRAL', 'POWERAPPS_DEV', 'POWERAPPS_INDIVIDUAL_USER',
    'POWER_PAGES_VTRIAL_FOR_MAKERS', 'STREAM', 'WINDOWS_STORE', 'RIGHTSMANAGEMENT_ADHOC', 'CCIBOTS_PRIVPREV_VIRAL', 'MICROSOFT_BUSINESS_CENTER',
    'FORMS_PRO', 'DYN365_ENTERPRISE_P1_IW', 'PROJECT_MADEIRA_PREVIEW_IW_SKU', 'MCOPSTNC', 'PHONESYSTEM_VIRTUALUSER', 'MEETING_ROOM_FREE',
    'MICROSOFT_REMOTE_ASSIST_HOLOLENS', 'POWERAUTOMATE_ATTENDED_RPA_TRIAL', 'VIRTUAL_AGENT_BASE_TRIAL', 'DEVELOPERPACK_E5', 'MCOCAP_FREE', 'APPS_FREE')

function Test-LrFreeSku { param([string]$Part) $u = $Part.ToUpperInvariant(); if ($LrFree -contains $u) { return $true }; return ($u -match '(_FREE$|^FREE_|_VIRAL|VIRAL_|_TRIAL|TRIAL_|_IW_SKU$|_IW$|EXPLORATORY)') }
function ConvertTo-LrDate {
    param($v)
    if ($null -eq $v) { return $null }
    if ($v -is [datetime]) { return $v.ToUniversalTime() }
    if ($v -is [datetimeoffset]) { return $v.UtcDateTime }
    $s = ([string]$v).Trim(); if (-not $s) { return $null }
    $d = [datetime]::MinValue
    if ([datetime]::TryParse($s, [System.Globalization.CultureInfo]::InvariantCulture, [System.Globalization.DateTimeStyles]'AdjustToUniversal,AssumeUniversal', [ref]$d)) { if ($d.Year -le 1601) { return $null }; return $d }
    return $null
}
function Get-LrLatest { param([object[]]$Dates) $m = $null; foreach ($d in $Dates) { if ($null -ne $d -and ($null -eq $m -or $d -gt $m)) { $m = $d } }; return $m }

# ---- Graph ----
try { $conn = Connect-Graph } catch { Stop-LrScan ([string]$_.Exception.Message) }
$tenantId = [string]$conn.TenantId
$now = (Get-Date).ToUniversalTime()
$cutoff = $now.AddDays(-$days)

$skus = @()
try { $skus = @(Get-GraphAll -Path '/v1.0/subscribedSkus' -Permission 'Organization.Read.All (or Directory.Read.All)') }
catch {
    if ($GraphState.LastStatus -eq 403) { Stop-LrScan "Microsoft Graph refused to list the tenant's subscriptions. Grant the app registration the Organization.Read.All (or Directory.Read.All) application permission, with admin consent, then run again." }
    Stop-LrScan "Couldn't read the tenant's Microsoft 365 subscriptions: $($_.Exception.Message)"
}
$skuMap = @{}
foreach ($s in $skus) {
    $sid = [string](Get-GraphProp $s 'skuId'); $part = [string](Get-GraphProp $s 'skuPartNumber')
    if (-not $sid -or -not $part) { continue }
    $applies = [string](Get-GraphProp $s 'appliesTo')
    $u = $part.ToUpperInvariant()
    $free = (Test-LrFreeSku $part) -or ($applies -and $applies -ne 'User')
    $name = $part; $price = $null; $source = 'unknown'
    if ($LrPrices.Contains($u)) { $name = $LrPrices[$u].name; $price = [double]$LrPrices[$u].price; $source = 'list' }
    if ($overrides.ContainsKey($u)) { $price = [double]$overrides[$u]; $source = 'override' }
    $skuMap[$sid.ToLowerInvariant()] = @{ part = $part; name = $name; price = $price; source = $source; free = $free }
}

$sel = 'id,displayName,userPrincipalName,accountEnabled,userType,createdDateTime,assignedLicenses,signInActivity'
$users = @()
try { $users = @(Get-GraphAll -Path "/v1.0/users?`$select=$sel&`$top=120" -Permission 'AuditLog.Read.All (with User.Read.All)') }
catch {
    $msg = [string]$_.Exception.Message
    if ($GraphState.LastStatus -eq 403 -and $msg -match '(?i)premium licen|NonPremium|tenant is B2C') { Stop-LrScan 'Microsoft Graph refused to read last sign-in times because this tenant has no Microsoft Entra ID P1 (or Business Premium) licence. Last sign-in data needs Entra ID P1, so this check cannot run for this tenant.' }
    if ($GraphState.LastStatus -eq 403) { Stop-LrScan 'Microsoft Graph refused to read last sign-in times. Grant the app registration the AuditLog.Read.All application permission (with User.Read.All), with admin consent, then run again.' }
    Stop-LrScan "Couldn't read the tenant's users: $msg"
}

# Mailbox activity (optional). The report is CSV; it names users only when concealed names are turned off.
$mailbox = @{}
$mailboxChecked = $false
try {
    $csv = Invoke-Graph -Method GET -Path "/v1.0/reports/getMailboxUsageDetail(period='D90')" -Permission 'Reports.Read.All'
    if ($csv -is [byte[]]) { $csv = [Text.Encoding]::UTF8.GetString($csv) }
    $rows = @(([string]$csv).TrimStart([char]0xFEFF) | ConvertFrom-Csv)
    $named = @($rows | Where-Object { ([string](Get-GraphProp $_ 'User Principal Name')) -like '*@*' })
    if ($rows.Count -and -not $named.Count) {
        $null = $warnings.Add('Mailbox activity was not used because Microsoft 365 reports hide user names in this tenant. To include it, turn off "Display concealed user, group, and site names in all reports" in the Microsoft 365 admin center under Settings > Org settings > Reports.')
    }
    else {
        foreach ($r in $named) {
            $upn = ([string](Get-GraphProp $r 'User Principal Name')).ToLowerInvariant()
            $mailbox[$upn] = ConvertTo-LrDate (Get-GraphProp $r 'Last Activity Date')
        }
        $mailboxChecked = $true
    }
}
catch {
    if ($GraphState.LastStatus -eq 403) { $null = $warnings.Add('Mailbox activity was not checked because the app registration does not have the Reports.Read.All permission, so this list is based on sign-in times only.') }
    else { $null = $warnings.Add("Mailbox activity could not be read, so this list is based on sign-in times only. ($($_.Exception.Message))") }
}

# ---- find unused paid licences ----
$found = New-Object System.Collections.ArrayList
$licensedUsers = 0
foreach ($usr in $users) {
    $paid = @()
    foreach ($al in @(Get-GraphProp $usr 'assignedLicenses')) {
        $sid = ([string](Get-GraphProp $al 'skuId')).ToLowerInvariant()
        if ($sid -and $skuMap.ContainsKey($sid) -and -not $skuMap[$sid].free) { $paid += $skuMap[$sid] }
    }
    if (-not $paid.Count) { continue }
    $licensedUsers++
    $upn = [string](Get-GraphProp $usr 'userPrincipalName')
    $ae = Get-GraphProp $usr 'accountEnabled'
    $enabled = ($null -eq $ae -or [bool]$ae)
    $sia = Get-GraphProp $usr 'signInActivity'
    $lastSignIn = Get-LrLatest @((ConvertTo-LrDate (Get-GraphProp $sia 'lastSignInDateTime')), (ConvertTo-LrDate (Get-GraphProp $sia 'lastNonInteractiveSignInDateTime')), (ConvertTo-LrDate (Get-GraphProp $sia 'lastSuccessfulSignInDateTime')))
    $lastMail = $null; if ($upn -and $mailbox.ContainsKey($upn.ToLowerInvariant())) { $lastMail = $mailbox[$upn.ToLowerInvariant()] }
    $created = ConvertTo-LrDate (Get-GraphProp $usr 'createdDateTime')
    $reason = ''
    if (-not $enabled) { $reason = 'disabled' }
    else {
        if ($null -ne $created -and $created -gt $cutoff) { continue }   # too new to judge
        $lastActive = Get-LrLatest @($lastSignIn, $lastMail)
        if ($null -ne $lastActive -and $lastActive -gt $cutoff) { continue }
        $reason = $(if ($null -eq $lastActive) { 'never' } else { 'inactive' })
    }
    $known = @($paid | Where-Object { $null -ne $_.price })
    $monthly = 0.0; foreach ($k in $known) { $monthly += [double]$k.price }
    $null = $found.Add([ordered]@{
            name           = [string](Get-GraphProp $usr 'displayName')
            upn            = $upn
            enabled        = $enabled
            reason         = $reason
            lastSignIn     = $(if ($null -ne $lastSignIn) { $lastSignIn.ToString('yyyy-MM-dd') } else { '' })
            lastMailbox    = $(if ($null -ne $lastMail) { $lastMail.ToString('yyyy-MM-dd') } else { '' })
            licences       = @($paid | ForEach-Object { [ordered]@{ sku = $_.part; name = $_.name; price = $_.price; priceSource = $_.source } })
            monthly        = [Math]::Round($monthly, 2)
            unknownPrices  = ($paid.Count - $known.Count)
        })
}

$rowsOut = @($found | Sort-Object -Property @{ Expression = { $_.monthly }; Descending = $true }, @{ Expression = { $_.name }; Descending = $false })
$licenceCount = 0; $saving = 0.0; $unknownSkus = @{}; $disabled = 0
foreach ($r in $rowsOut) {
    $licenceCount += @($r.licences).Count; $saving += [double]$r.monthly
    if (-not $r.enabled) { $disabled++ }
    foreach ($l in @($r.licences)) { if ($null -eq $l.price) { $unknownSkus[$l.sku] = 1 } }
}

Set-NodeOutput ([ordered]@{
        status          = 'ok'
        days            = $days
        company_id      = [int](Get-GraphProp $in 'company_id')
        preview         = [bool](Get-GraphProp $in 'preview')
        tenantId        = $tenantId
        checkedOn       = $now.ToString('yyyy-MM-dd')
        licensedUsers   = $licensedUsers
        mailboxChecked  = $mailboxChecked
        userCount       = $rowsOut.Count
        disabledCount   = $disabled
        licenceCount    = $licenceCount
        monthlySaving   = [Math]::Round($saving, 2)
        unknownPriceSkus = @($unknownSkus.Keys | Sort-Object)
        overridesUsed   = @($overrides.Keys | Sort-Object)
        users           = $rowsOut
        warnings        = @($warnings)
    })
