// Builds ../qbr-data-pack.yml from the step sources in this folder, then pastes the shared
// libraries into it with ../../_shared/inject.js.
// Usage: node build.js          rewrite the .yml
//        node build.js --check  exit 1 if the .yml is out of date
// Edit the .ps1 files here, never the scripts inside the .yml.
// Needs js-yaml: npm install in ../../_shared, or set JS_YAML_PATH to an existing copy.
const fs = require('fs');
const path = require('path');
let y;
try { y = require('js-yaml'); } catch {
  try { y = require(path.join(__dirname, '..', '..', '_shared', 'node_modules', 'js-yaml')); } catch { y = require(process.env.JS_YAML_PATH); }
}
const { injectText } = require(path.join(__dirname, '..', '..', '_shared', 'inject.js'));

const here = __dirname;
const target = path.join(here, '..', 'qbr-data-pack.yml');
const read = (f) => fs.readFileSync(path.join(here, f), 'utf8').replace(/\r\n/g, '\n').trimEnd() + '\n';

const step = (id, name, x, file, extra = {}) => ({
  id, name, type: 'powershell-script', position: { x, y: 120 },
  properties: { script: read(file), timeoutSeconds: 900, retryCount: 0, parameters: [], aiExtensions: [], ...extra },
});

const wf = {
  automationsWorkflow: 1,
  name: 'QBR Data Pack',
  definition: {
    schemaVersion: 1,
    activities: [
      { id: 'start', name: 'Start', type: 'start', position: { x: 100, y: 120 }, properties: { webhookEnabled: false } },
      step('node-inputs', 'Read inputs', 300, 'inputs.ps1', {
        timeoutSeconds: 60,
        testInput: JSON.stringify({ company_id: '', quarter_days: 90, preview: true }, null, 2),
      }),
      step('node-cloudradial', 'Read CloudRadial data', 520, 'cloudradial-data.ps1'),
      step('node-psa', 'Read PSA ticket trends', 740, 'psa-tickets.ps1'),
      step('node-m365', 'Read Microsoft 365 licences', 960, 'm365-licences.ps1', { timeoutSeconds: 300 }),
      step('node-card', 'Post QBR-prep card', 1180, 'card.ps1', { timeoutSeconds: 300 }),
      { id: 'end', name: 'End', type: 'end', position: { x: 1400, y: 120 } },
    ],
    connections: [
      { source: 'start', target: 'node-inputs', sourceHandle: null },
      { source: 'node-inputs', target: 'node-cloudradial', sourceHandle: null },
      { source: 'node-cloudradial', target: 'node-psa', sourceHandle: null },
      { source: 'node-psa', target: 'node-m365', sourceHandle: null },
      { source: 'node-m365', target: 'node-card', sourceHandle: null },
      { source: 'node-card', target: 'end', sourceHandle: null },
    ],
    startActivityId: 'start',
  },
};

const header = '# Generated by src/build.js from src/*.ps1 and ../_shared. Edit the sources, not this file.\n';
const dumped = header + y.dump(wf, { lineWidth: -1, noRefs: true });
const { text } = injectText(dumped, 'qbr-data-pack.yml', new Map());
const parsed = y.load(text);
for (const a of parsed.definition.activities) {
  const s = a.properties && a.properties.script;
  if (s && /# >>> _shared\/\S+[^\n]*\n\s*# <<< _shared/.test(s)) throw new Error(`${a.id}: a shared block is empty after injecting`);
}
const check = process.argv.includes('--check');
const was = fs.existsSync(target) ? fs.readFileSync(target, 'utf8').replace(/\r\n/g, '\n') : '';
if (text === was) { console.log('qbr-data-pack.yml: current'); process.exit(0); }
if (check) { console.log('qbr-data-pack.yml: OUT OF DATE (run node src/build.js)'); process.exit(1); }
fs.writeFileSync(target, text);
console.log(`qbr-data-pack.yml: written (${text.length} bytes)`);
