# === STEP: Read PSA ticket trends ===
# Edit this file, then run: node automationai/qbr-data-pack/src/build.js
# Read-only (GET calls only). Counts this client's tickets opened and closed in the last <quarter_days> days and
# in the same span before it, the tickets open now, and the top 5 categories of the tickets opened this period.
# Works with ConnectWise PSA, Autotask, HaloPSA, Kaseya BMS, Syncro and Zendesk through _shared/psa.ps1.
# If no PSA is set up, or the client can't be matched in the PSA, this section says "not available" and the run continues.
# Every call is filtered to this one client's PSA company id.
# Secrets: PSA-Type plus that PSA's own secrets (CW-*, Autotask-*, Halo-*, KaseyaBMS-*, Syncro-*, Zendesk-*).
# >>> _shared/psa.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/psa.ps1

$in = Get-NodeInput
function Get-QbrProp { param($o, [string]$n) if ($null -eq $o) { return $null }; if ($o -is [System.Collections.IDictionary]) { if ($o.Contains($n)) { return $o[$n] }; return $null }; $p = $o.PSObject.Properties[$n]; if ($p) { return $p.Value }; return $null }
function Copy-QbrInput { param($o) $h = [ordered]@{}; if ($o -is [System.Collections.IDictionary]) { foreach ($k in $o.Keys) { $h[[string]$k] = $o[$k] } } elseif ($null -ne $o) { foreach ($p in $o.PSObject.Properties) { $h[$p.Name] = $p.Value } }; return $h }
$out = Copy-QbrInput $in
$warnings = New-Object System.Collections.ArrayList
foreach ($w in @(Get-QbrProp $in 'warnings')) { if ($w) { $null = $warnings.Add([string]$w) } }

$ci = [System.Globalization.CultureInfo]::InvariantCulture
$now = (Get-Date).ToUniversalTime()
function ConvertTo-QbrUtc { param($v) if ($null -eq $v) { return $null }; if ($v -is [datetime]) { if ($v.Kind -eq [DateTimeKind]::Unspecified) { return [datetime]::SpecifyKind($v, [DateTimeKind]::Utc) }; return $v.ToUniversalTime() }; if ($v -is [datetimeoffset]) { return $v.UtcDateTime }; $d = [datetime]::MinValue; if ([string]$v -and [datetime]::TryParse([string]$v, [System.Globalization.CultureInfo]::InvariantCulture, [System.Globalization.DateTimeStyles]'AdjustToUniversal,AssumeUniversal', [ref]$d)) { return $d }; return $null }
$tmp = ConvertTo-QbrUtc (Get-QbrProp $in 'runAt'); if ($null -ne $tmp) { $now = $tmp }
$days = [int](Get-QbrProp $in 'quarter_days'); if ($days -le 0) { $days = 90 }
$curStart = $now.AddDays(-$days); $prevStart = $now.AddDays(-2 * $days)
function Get-QbrIso { param([datetime]$d) return $d.ToString('yyyy-MM-ddTHH:mm:ssZ', $ci) }
function ConvertTo-QbrDate { param($v) $d = [datetime]::MinValue; if ($null -ne $v -and [string]$v -and [datetime]::TryParse([string]$v, $ci, [System.Globalization.DateTimeStyles]'AdjustToUniversal,AssumeUniversal', [ref]$d)) { if ($d.Year -gt 1900) { return $d } }; return $null }
$MaxPages = 10

$t = [ordered]@{
    available = $false; reason = ''; psa = ''; psaName = ''; psaCompanyId = ''; matchedBy = ''; days = $days
    currentFrom = (Get-QbrIso $curStart); previousFrom = (Get-QbrIso $prevStart); to = (Get-QbrIso $now)
    openedCurrent = $null; openedPrevious = $null; closedCurrent = $null; closedPrevious = $null; openNow = $null
    categories = @(); categoryLabel = 'category'; categoriesFrom = 0; notes = @()
}
$notes = New-Object System.Collections.ArrayList
function Close-QbrStep {
    $t.notes = @($notes)
    $out.tickets = $t
    $out.warnings = @($warnings)
    Set-NodeOutput $out
}

# ---- which PSA ----
$psa = ''
try { $psa = Get-PsaType ([string](Get-QbrProp $in 'psa')) } catch { $t.reason = "Ticket trends are not available: $($_.Exception.Message)" }
if (-not $psa) {
    if (-not $t.reason) { $t.reason = 'No PSA is set up on this runner, so ticket trends are not available. Add the PSA-Type secret and that PSA''s secrets to include them.' }
    $null = $warnings.Add($t.reason); Close-QbrStep; return
}
$t.psa = $psa; $t.psaName = $PsaState.Names[$psa]
try { $null = Connect-Psa $psa }
catch { $t.reason = "Couldn't sign in to $($t.psaName), so ticket trends are not available: $($_.Exception.Message)"; $null = $warnings.Add($t.reason); Close-QbrStep; return }

# ---- which PSA company: psa_company_id input, then CloudRadial's PSA link, then an exact name match ----
$pcid = ''
$given = [string](Get-QbrProp $in 'psa_company_id')
$psaKey = [string](Get-QbrProp $in 'psaKey')
$psaIdent = ([string](Get-QbrProp $in 'psaIdentifier')).Trim()
$coName = [string](Get-QbrProp $in 'companyName')
try {
    if ($given -match '^\d+$') { $pcid = $given; $t.matchedBy = 'psa_company_id input' }
    elseif ($psaKey -match '^\d+$' -and [long]$psaKey -gt 0) { $pcid = $psaKey; $t.matchedBy = 'the PSA link on the CloudRadial company (psaKey)' }   # Unverified: psaKey is the PSA's own company id for every PSA.
    elseif ($psaIdent -match '^\d+$') { $pcid = $psaIdent; $t.matchedBy = 'the PSA identifier on the CloudRadial company' }
    elseif ($psaIdent -and $psa -eq 'connectwise') {
        $hit = @(Invoke-Psa GET "/company/companies?conditions=$(ConvertTo-PsaQuery "identifier=`"$($psaIdent.Replace('"', '\"'))`"")&pageSize=2") | Where-Object { $null -ne $_ } | Select-Object -First 1
        if ($hit) { $pcid = [string](Get-PsaProp $hit 'id'); $t.matchedBy = "ConnectWise company identifier $psaIdent" }
    }
    if (-not $pcid) {
        foreach ($nm in @($psaIdent, $coName)) {
            if (-not $nm) { continue }
            $exact = @(Find-PsaCompany $nm | Where-Object { $_.exact })
            if ($exact.Count -eq 1) { $pcid = [string]$exact[0].id; $t.matchedBy = "an exact name match on '$nm'"; break }
        }
    }
}
catch { $null = $notes.Add("Looking up the client in $($t.psaName) failed: $($_.Exception.Message)") }
if (-not $pcid) {
    $t.reason = "Couldn't match $coName to one company in $($t.psaName), so ticket trends are not available. Set psa_company_id on the run, or link the company to the PSA in CloudRadial."
    $null = $warnings.Add($t.reason); Close-QbrStep; return
}
$t.psaCompanyId = $pcid

# ---- counting, per PSA ----
# Kind: opened (created in the span), closed (closed in the span), open (open now; From/To ignored).
function Get-QbrCount {
    param([string]$Kind, [datetime]$From, [datetime]$To)
    $f = Get-QbrIso $From; $e = Get-QbrIso $To
    switch ($psa) {
        'connectwise' {
            # Unverified: date conditions in square brackets and the closedDate field (CW swagger clients).
            $cond = switch ($Kind) { 'opened' { "company/id=$pcid and dateEntered>=[$f] and dateEntered<[$e]" } 'closed' { "company/id=$pcid and closedFlag=true and closedDate>=[$f] and closedDate<[$e]" } default { "company/id=$pcid and closedFlag=false" } }
            return [int](Get-PsaProp (Invoke-Psa GET "/service/tickets/count?conditions=$(ConvertTo-PsaQuery $cond)") 'count')
        }
        'autotask' {
            # Unverified: the queryCount field name (PSA.md), and completedDate as the closed date.
            $flt = @([ordered]@{ op = 'eq'; field = 'companyID'; value = [long]$pcid })
            switch ($Kind) {
                'opened' { $flt += [ordered]@{ op = 'gte'; field = 'createDate'; value = $f }; $flt += [ordered]@{ op = 'lt'; field = 'createDate'; value = $e } }
                'closed' { $flt += [ordered]@{ op = 'gte'; field = 'completedDate'; value = $f }; $flt += [ordered]@{ op = 'lt'; field = 'completedDate'; value = $e } }
                default { foreach ($s in @(Get-PsaAtCompleteStatuses)) { $flt += [ordered]@{ op = 'noteq'; field = 'status'; value = $s } } }
            }
            $r = Invoke-Psa GET "/Tickets/query/count?search=$(ConvertTo-PsaQuery (@{ filter = $flt } | ConvertTo-Json -Depth 6 -Compress))"
            $n = Get-PsaProp $r 'queryCount'; if ($null -eq $n) { return $null }; return [int]$n
        }
        'halopsa' {
            # Unverified: the datesearch values dateoccurred and dateclosed, and closed_only.
            $q = switch ($Kind) { 'opened' { "datesearch=dateoccurred&startdate=$(ConvertTo-PsaQuery $f)&enddate=$(ConvertTo-PsaQuery $e)" } 'closed' { "closed_only=true&datesearch=dateclosed&startdate=$(ConvertTo-PsaQuery $f)&enddate=$(ConvertTo-PsaQuery $e)" } default { 'open_only=true' } }
            $n = Get-PsaProp (Invoke-Psa GET "/Tickets?client_id=$pcid&$q&pageinate=true&page_size=1&page_no=1") 'record_count'; if ($null -eq $n) { return $null }; return [int]$n
        }
        'kaseyabms' {
            # From the public Swagger (Filter.AccountIds, Filter.OpenDate*, Filter.CompletedDate*, TotalRecords). Not yet proven live.
            $q = switch ($Kind) { 'opened' { "Filter.OpenDateFrom=$(ConvertTo-PsaQuery $f)&Filter.OpenDateTo=$(ConvertTo-PsaQuery $e)" } 'closed' { "Filter.CompletedDateFrom=$(ConvertTo-PsaQuery $f)&Filter.CompletedDateTo=$(ConvertTo-PsaQuery $e)" } default { 'Filter.ExcludeCompleted=true' } }
            $n = Get-PsaProp (Invoke-Psa GET "/servicedesk/tickets?Filter.AccountIds=$pcid&$q&PageSize=1&PageNumber=1") 'TotalRecords'; if ($null -eq $n) { return $null }; return [int]$n
        }
        'zendesk' {
            # Unverified: organization:<id> with created> / solved> ISO times in a search count.
            $q = switch ($Kind) { 'opened' { "type:ticket organization:$pcid created>$f created<$e" } 'closed' { "type:ticket organization:$pcid solved>$f solved<$e" } default { "type:ticket organization:$pcid status<solved" } }
            return [int](Get-PsaProp (Invoke-Psa GET "/search/count?query=$(ConvertTo-PsaQuery $q)") 'count')
        }
    }
    return $null
}

# Syncro can't count by date, so its tickets are listed (25 a page) and counted here.
function Get-QbrSyncroRows {
    param([string]$Query)
    $rows = New-Object System.Collections.ArrayList; $capped = $false
    for ($p = 1; $p -le 40; $p++) {
        $r = Invoke-Psa GET "/tickets?customer_id=$pcid&$Query&page=$p"
        foreach ($x in @(Get-PsaProp $r 'tickets' | Where-Object { $null -ne $_ })) { $null = $rows.Add($x) }
        $pages = Get-PsaPath $r 'meta.total_pages'
        if ($null -eq $pages -or $p -ge [int]$pages) { break }
        if ($p -eq 40) { $capped = $true }
    }
    return @{ rows = @($rows); capped = $capped }
}
function Get-QbrSpan { param($Rows, [string]$Field, [datetime]$From, [datetime]$To) return @($Rows | Where-Object { $d = ConvertTo-QbrDate (Get-PsaProp $_ $Field); $null -ne $d -and $d -ge $From -and $d -lt $To }) }

# Category names of the tickets opened this period (up to $MaxPages pages).
function Get-QbrCategoryNames {
    $f = Get-QbrIso $curStart; $e = Get-QbrIso $now
    $names = New-Object System.Collections.ArrayList
    switch ($psa) {
        'connectwise' {
            $t.categoryLabel = 'ticket type'
            $cond = "company/id=$pcid and dateEntered>=[$f] and dateEntered<[$e]"
            for ($p = 1; $p -le $MaxPages; $p++) {
                $rows = @(Invoke-Psa GET "/service/tickets?conditions=$(ConvertTo-PsaQuery $cond)&fields=id,type,board&pageSize=1000&page=$p" | Where-Object { $null -ne $_ })
                foreach ($r in $rows) { $n = [string](Get-PsaPath $r 'type.name'); $null = $names.Add($n) }
                if ($rows.Count -lt 1000) { break }
            }
        }
        'autotask' {
            # Unverified: IncludeFields in a query, and paging through pageDetails.nextPageUrl.
            $t.categoryLabel = 'issue type'
            $labels = @{}; foreach ($v in @(Get-PsaAtPicklist 'Tickets' 'issueType')) { $labels[[string](Get-PsaProp $v 'value')] = [string](Get-PsaProp $v 'label') }
            $flt = @([ordered]@{ op = 'eq'; field = 'companyID'; value = [long]$pcid }, [ordered]@{ op = 'gte'; field = 'createDate'; value = $f }, [ordered]@{ op = 'lt'; field = 'createDate'; value = $e })
            $next = "/Tickets/query?search=$(ConvertTo-PsaQuery (([ordered]@{ IncludeFields = @('id', 'issueType'); filter = $flt }) | ConvertTo-Json -Depth 6 -Compress))"
            for ($p = 1; $p -le $MaxPages -and $next; $p++) {
                $r = Invoke-Psa GET $next
                foreach ($x in @(Get-PsaProp $r 'items' | Where-Object { $null -ne $_ })) { $it = [string](Get-PsaProp $x 'issueType'); $null = $names.Add($(if ($it -and $labels.ContainsKey($it)) { $labels[$it] } else { '' })) }
                $next = [string](Get-PsaPath $r 'pageDetails.nextPageUrl')
            }
        }
        'halopsa' {
            # Unverified: category_1 on the ticket list.
            for ($p = 1; $p -le $MaxPages; $p++) {
                $r = Invoke-Psa GET "/Tickets?client_id=$pcid&datesearch=dateoccurred&startdate=$(ConvertTo-PsaQuery $f)&enddate=$(ConvertTo-PsaQuery $e)&pageinate=true&page_size=100&page_no=$p"
                $rows = @(Get-PsaProp $r 'tickets' | Where-Object { $null -ne $_ })
                foreach ($x in $rows) { $null = $names.Add([string](Get-PsaProp $x 'category_1')) }
                if ($rows.Count -lt 100) { break }
            }
        }
        'kaseyabms' {
            $t.categoryLabel = 'issue type'
            for ($p = 1; $p -le $MaxPages; $p++) {
                $r = Invoke-Psa GET "/servicedesk/tickets?Filter.AccountIds=$pcid&Filter.OpenDateFrom=$(ConvertTo-PsaQuery $f)&Filter.OpenDateTo=$(ConvertTo-PsaQuery $e)&PageSize=100&PageNumber=$p"
                $rows = @(Get-PsaProp $r 'Result' | Where-Object { $null -ne $_ })
                foreach ($x in $rows) { $null = $names.Add([string](Get-PsaProp $x 'IssueTypeName')) }
                if ($rows.Count -lt 100) { break }
            }
        }
        'zendesk' {
            $t.categoryLabel = 'ticket type'
            $q = "type:ticket organization:$pcid created>$f created<$e"
            for ($p = 1; $p -le $MaxPages; $p++) {
                $r = Invoke-Psa GET "/search?query=$(ConvertTo-PsaQuery $q)&per_page=100&page=$p"
                $rows = @(Get-PsaProp $r 'results' | Where-Object { $null -ne $_ })
                foreach ($x in $rows) { $null = $names.Add([string](Get-PsaProp $x 'type')) }
                if (-not (Get-PsaProp $r 'next_page')) { break }
            }
        }
    }
    return @($names)
}

try {
    if ($psa -eq 'syncro') {
        # From the Syncro Swagger (customer_id, created_after, resolved_after, 25 a page). Not yet proven live.
        $since = $prevStart.ToString('yyyy-MM-dd', $ci)
        $made = Get-QbrSyncroRows "created_after=$since"
        $t.openedCurrent = @(Get-QbrSpan $made.rows 'created_at' $curStart $now).Count
        $t.openedPrevious = @(Get-QbrSpan $made.rows 'created_at' $prevStart $curStart).Count
        $done = Get-QbrSyncroRows "resolved_after=$since"
        $t.closedCurrent = @(Get-QbrSpan $done.rows 'resolved_at' $curStart $now).Count
        $t.closedPrevious = @(Get-QbrSpan $done.rows 'resolved_at' $prevStart $curStart).Count
        $open = Get-QbrSyncroRows "status=$(ConvertTo-PsaQuery 'Not Closed')"
        $t.openNow = @($open.rows).Count
        if ($made.capped -or $done.capped -or $open.capped) { $null = $notes.Add('Syncro returned more than 1,000 tickets for one count, so the counts are lower bounds.') }
        $t.categoryLabel = 'issue type'
        $catNames = @(Get-QbrSpan $made.rows 'created_at' $curStart $now | ForEach-Object { [string](Get-PsaProp $_ 'problem_type') })
    }
    else {
        $t.openedCurrent = Get-QbrCount 'opened' $curStart $now
        $t.openedPrevious = Get-QbrCount 'opened' $prevStart $curStart
        $t.closedCurrent = Get-QbrCount 'closed' $curStart $now
        $t.closedPrevious = Get-QbrCount 'closed' $prevStart $curStart
        $t.openNow = Get-QbrCount 'open' $now $now
        $catNames = @()
        try { $catNames = @(Get-QbrCategoryNames) }
        catch { $null = $notes.Add("Ticket categories weren't available: $($_.Exception.Message)") }
    }
    $t.available = $true
    $t.categoriesFrom = @($catNames).Count
    $named = @($catNames | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
    if ($named.Count) {
        $t.categories = @($named | Group-Object | Sort-Object @{ Expression = 'Count'; Descending = $true }, @{ Expression = 'Name'; Descending = $false } | Select-Object -First 5 | ForEach-Object { [ordered]@{ name = $_.Name; count = $_.Count } })
        $blank = @($catNames).Count - $named.Count
        if ($blank -eq 1) { $null = $notes.Add("1 ticket opened this period has no $($t.categoryLabel).") }
        elseif ($blank -gt 1) { $null = $notes.Add("$blank tickets opened this period have no $($t.categoryLabel).") }
    }
    if ($null -ne $t.openedCurrent -and $t.categoriesFrom -lt [int]$t.openedCurrent -and $t.categoriesFrom -gt 0) { $null = $notes.Add("The top categories are based on the first $($t.categoriesFrom) of $($t.openedCurrent) tickets opened this period.") }
}
catch {
    $t.available = $false
    $t.reason = "Couldn't read tickets from $($t.psaName), so ticket trends are not available: $($_.Exception.Message)"
    $null = $warnings.Add($t.reason)
}
Close-QbrStep
