# === NODE: Find the affected companies ===
# Reads CloudRadial only; changes nothing. Picks the affected companies from, in this order:
#   1. companies: names or CloudRadial company ids sent in the request
#   2. companyGroup: a CloudRadial company group name
#   3. broadcast mode: every company with an endpoint that has a service matching affectedService
#      installed (CloudRadial service and serviceinstall). Resolved mode: every company whose banner
#      token or Service Status article still shows this service.
# Then reads each company's current banner token and Service Status article, so the next step can
# say exactly what it would create, update or clear. Stops (incomplete) when more companies match
# than maxCompanies allows.
# >>> _shared/cloudradial.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/cloudradial.ps1
$ErrorActionPreference = 'Stop'

function Get-ObState { $in = Get-NodeInput; $s = [ordered]@{}; if ($null -ne $in) { if ($in -is [System.Collections.IDictionary]) { foreach ($k in @($in.Keys)) { $s[[string]$k] = $in[$k] } } else { foreach ($p in $in.PSObject.Properties) { $s[$p.Name] = $p.Value } } }; return $s }
function Get-ObList { param($S, [string]$Key) if (-not $S.Contains($Key)) { return @() }; return @(@($S[$Key]) | Where-Object { $null -ne $_ -and [string]$_ -ne '' }) }
function ConvertTo-ObOData { param([string]$s) return $s.Replace("'", "''") }
function ConvertTo-ObFilter { param([string]$f) return [uri]::EscapeDataString($f) }

$st = Get-ObState
if ([string]$st['status'] -ne 'ok') { Set-NodeOutput $st; return }
$warnings = New-Object System.Collections.ArrayList; foreach ($w in @(Get-ObList $st 'warnings')) { $null = $warnings.Add([string]$w) }
$mode = [string]$st['mode']
$service = [string]$st['affectedService']
$tokenName = [string]$st['bannerToken']
$category = [string]$st['articleCategory']
$subjectBase = "Service status: $service"

function Stop-Ob {
    param([string]$Status, [string]$Why, [string]$Chat = '')
    $st['status'] = $Status; $st['message'] = $Why
    $st['chatReply'] = $(if ($Chat) { $Chat } else { $Why })
    $st['internal_note'] = "Outage broadcast for $service ($mode) stopped before any change: $Why"
    $st['warnings'] = @($warnings)
    $st['targets'] = @(); $st['counts'] = @{ companies = 0 }
    Set-NodeOutput $st
}

$null = Connect-Cr
$all = @(Get-CrAll "/v2/odata/company?`$select=companyId,name,psaKey")
$byId = @{}; foreach ($c in $all) { $cid = [int](Get-CrProp $c 'companyId'); if ($cid -gt 0) { $byId[$cid] = $c } }

$picked = [ordered]@{}   # "companyId" -> reason (string keys: an int would index an ordered dictionary by position)
$source = ''
$wanted = @(Get-ObList $st 'companies')
$group = [string]$st['companyGroup']
if ($wanted.Count) {
    $source = 'the company list in the request'
    foreach ($w in $wanted) {
        $hit = $null
        if ($w -match '^\d+$') { if ($byId.ContainsKey([int]$w)) { $hit = $byId[[int]$w] } }
        else { $hit = @($all | Where-Object { ([string](Get-CrProp $_ 'name')).Trim() -ieq $w.Trim() }) | Select-Object -First 1 }
        if ($null -eq $hit) { $null = $warnings.Add("No CloudRadial company matches '$w', so it was skipped."); continue }
        $picked[[string][int](Get-CrProp $hit 'companyId')] = 'named in the request'
    }
    if (-not $picked.Count) { Stop-Ob 'incomplete' "None of the companies named in the request ($($wanted -join ', ')) exist in CloudRadial."; return }
}
elseif ($group) {
    $source = "the company group '$group'"
    $g = @(Get-CrAll "/v2/odata/companygroup?`$filter=$(ConvertTo-ObFilter "group eq '$(ConvertTo-ObOData $group)'")" | Where-Object { (Get-CrProp $_ 'isDeleted') -ne $true }) | Select-Object -First 1
    if ($null -eq $g) { Stop-Ob 'incomplete' "There is no CloudRadial company group named '$group'."; return }
    $gid = [int](Get-CrProp $g 'companyGroupId')
    foreach ($m in @(Get-CrAll "/v2/odata/companygroupcompany?`$filter=$(ConvertTo-ObFilter "companyGroupId eq $gid")")) {
        if ((Get-CrProp $m 'isDeleted') -eq $true) { continue }
        $cid = [int](Get-CrProp $m 'companyId'); if ($byId.ContainsKey($cid)) { $picked["$cid"] = "member of the '$group' group" }
    }
}

# Current banner tokens and Service Status articles (read for every mode, for the preview and for resolved-mode targeting).
$tokens = @{}; $partnerToken = $false
foreach ($t in @(Get-CrAll "/v2/odata/token?`$filter=$(ConvertTo-ObFilter "name eq '$(ConvertTo-ObOData $tokenName)'")")) {
    if ([string](Get-CrProp $t 'name') -ne $tokenName) { continue }
    $cid = [int](Get-CrProp $t 'companyId')
    if ($cid -eq 0) { $partnerToken = $true; continue }
    $tokens[$cid] = [string](Get-CrProp $t 'value')
}
$articles = @{}
foreach ($a in @(Get-CrAll "/v2/odata/article?`$filter=$(ConvertTo-ObFilter "category eq '$(ConvertTo-ObOData $category)'")&`$select=articleId,companyId,subject,isFrontPage,datePublished")) {
    $subj = ([string](Get-CrProp $a 'subject')).Trim()
    if ($subj -ine $subjectBase -and $subj -ine "$subjectBase (resolved)") { continue }
    $cid = [int](Get-CrProp $a 'companyId')
    if (-not $articles.ContainsKey($cid)) { $articles[$cid] = $a }
}
function Test-ObMentions { param([string]$v) return ($v -and $v.IndexOf($service, [StringComparison]::OrdinalIgnoreCase) -ge 0) }

if (-not $source) {
    if ($mode -eq 'broadcast') {
        $source = "endpoints with a service matching '$service' installed"
        $svcFilter = ConvertTo-ObFilter "contains(tolower(name),'$(ConvertTo-ObOData $service.ToLowerInvariant())')"
        $services = @(Get-CrAll "/v2/odata/service?`$filter=$svcFilter&`$select=serviceId,companyId,name" | Where-Object { ([string](Get-CrProp $_ 'name')).IndexOf($service, [StringComparison]::OrdinalIgnoreCase) -ge 0 })
        foreach ($s in $services) {
            $sid = [int](Get-CrProp $s 'serviceId')
            # Unverified: whether a service row's companyId is always set; the installing endpoint's company is the fallback.
            $inst = @(Get-CrProp (Invoke-CrApi "/v2/odata/serviceinstall?`$filter=$(ConvertTo-ObFilter "serviceId eq $sid")&`$top=1&`$expand=endpoint(`$select=companyId)") 'value' | Where-Object { $null -ne $_ })
            if (-not $inst.Count) { continue }
            $cid = [int](Get-CrProp $s 'companyId')
            if ($cid -le 0) { $ep = Get-CrProp $inst[0] 'endpoint'; $cid = [int](Get-CrProp $ep 'companyId') }
            if ($cid -gt 0 -and $byId.ContainsKey($cid) -and -not $picked.Contains("$cid")) { $picked["$cid"] = "has $([string](Get-CrProp $s 'name')) installed" }
        }
    }
    else {
        $source = "companies whose banner or Service Status article still shows $service"
        foreach ($cid in @($tokens.Keys)) { if ((Test-ObMentions $tokens[$cid]) -and $byId.ContainsKey($cid)) { $picked["$cid"] = 'banner shows this outage' } }
        foreach ($cid in @($articles.Keys)) {
            $a = $articles[$cid]
            if ((Get-CrProp $a 'isFrontPage') -eq $true -and ([string](Get-CrProp $a 'subject')).Trim() -ieq $subjectBase -and $byId.ContainsKey($cid) -and -not $picked.Contains("$cid")) { $picked["$cid"] = 'Service Status article still open' }
        }
    }
}

if (-not $picked.Count) {
    $why = if ($mode -eq 'broadcast') { "No company matched $source, so there is nothing to post." } else { "No company's banner or Service Status article shows $service, so there is nothing to clear." }
    $st['status'] = 'success'; $st['message'] = $why; $st['chatReply'] = $why
    $st['internal_note'] = "Outage broadcast for $service ($mode): $why Nothing was changed."
    $st['targets'] = @(); $st['counts'] = @{ companies = 0 }; $st['warnings'] = @($warnings)
    Set-NodeOutput $st; return
}
$max = [int]$st['maxCompanies']
if ($picked.Count -gt $max) {
    Stop-Ob 'incomplete' "This would reach $($picked.Count) companies, which is over the limit of $max. Check the service name, or rerun with maxCompanies set to $($picked.Count) to go ahead."
    return
}

$targets = @(foreach ($key in @($picked.Keys)) {
        $cid = [int]$key
        $c = $byId[$cid]
        $a = $(if ($articles.ContainsKey($cid)) { $articles[$cid] } else { $null })
        [ordered]@{
            companyId = $cid; name = [string](Get-CrProp $c 'name'); psaKey = [string](Get-CrProp $c 'psaKey'); reason = $picked[$key]
            tokenExists = $tokens.ContainsKey($cid); tokenValue = $(if ($tokens.ContainsKey($cid)) { $tokens[$cid] } else { '' })
            articleId = $(if ($a) { [int](Get-CrProp $a 'articleId') } else { 0 })
            articleSubject = $(if ($a) { [string](Get-CrProp $a 'subject') } else { '' })
            articleDatePublished = $(if ($a) { [string](Get-CrProp $a 'datePublished') } else { '' })
        }
    })
$st['targets'] = @($targets)
$st['targetSource'] = $source
$st['partnerTokenExists'] = $partnerToken
$st['counts'] = @{ companies = $targets.Count }
$st['warnings'] = @($warnings)
Set-NodeOutput $st
