// Builds status-change-updates.yml from the step sources in this folder, then pastes the shared
// libraries into it (automationai/_shared/inject.js).
// Usage: node build.js          rewrite the .yml
//        node build.js --check  exit 1 if the .yml is out of date
// Edit detect.ps1, post.ps1, step.ps1 and the write.*.txt prompts (or the shared files in automationai/_shared), never the .yml.
// Needs js-yaml: set JS_YAML_PATH (or NODE_PATH) to an existing copy, or npm install in automationai/_shared.
const fs = require('fs');
const path = require('path');
const { injectText } = require('../../_shared/inject.js');

function loadYaml() {
  try { return require('js-yaml'); } catch { /* fall through */ }
  if (process.env.JS_YAML_PATH) return require(process.env.JS_YAML_PATH);
  throw new Error('js-yaml not found. Set JS_YAML_PATH, or npm install in automationai/_shared.');
}

const here = __dirname;
const name = 'status-change-updates';
const out = path.join(here, '..', `${name}.yml`);
const read = (f) => fs.readFileSync(path.join(here, f), 'utf8').replace(/\r\n/g, '\n').trimEnd();
const block = (text, indent) => text.split('\n').map((l) => (l ? indent + l : '')).join('\n');
const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
// Shared libraries are marked for inject.js; this folder's own helpers are pasted here with the same marker pattern.
const shared = (lib) => `# >>> _shared/${lib} (generated by _shared/inject.js; edit the source, not this block)\n# <<< _shared/${lib}`;
const local = (f) => `# >>> src/${f} (generated by src/build.js; edit the source, not this block)\n${read(f)}\n# <<< src/${f}`;
const script = (libs, locals, body) => [...libs.map(shared), ...locals.map(local), read(body)].join('\n');

const testInput = JSON.stringify({
  ticketId: '1001',
  oldStatus: 'New',
  newStatus: 'Waiting on Client',
  contactEmail: 'megan.bowen@contoso.com',
  ignore_statuses: '',
  psa: '',
  preview: true,
}, null, 2);

// One AI call, no tools. The ai-prompt property names follow the Phishing Report Triage workflow and are
// unverified (PLATFORM.md). model is blank so the tenant's own provider is used.
function aiStep({ id, name: n, x, prompt, system }) {
  return `  - id: ${id}
    name: ${n}
    type: ai-prompt
    position:
      x: ${x}
      y: 80
    properties:
      model: ''
      promptTemplate: |-
${block(read(prompt), '        ')}
      systemMessage: |-
${block(read(system), '        ')}
      maxTokens: 400
      outputKey: update
      parameters: []
`;
}

function psStep({ id, name: n, x, body, params, test }) {
  let s = `  - id: ${id}
    name: ${n}
    type: powershell-script
    position:
      x: ${x}
      y: 80
    properties:
      script: |-
${block(body, '        ')}
      timeoutSeconds: 300
      retryCount: 0
`;
  if (params && params.length) s += '      parameters:\n' + params.map(([p, e]) => `      - name: ${p}\n        expression: ${q(e)}\n`).join('');
  else s += '      parameters: []\n';
  s += '      aiExtensions: []\n';
  if (test) s += `      testInput: |-\n${block(test, '        ')}\n`;
  return s;
}

const steps = [
  { id: 'detect', name: 'Detect the status change', body: script(['psa.ps1'], ['step.ps1'], 'detect.ps1'), params: [['trigger', '{{ nodes.trigger.output }}']], test: testInput },
  { id: 'write', name: 'Write the update', ai: true, prompt: 'write.prompt.txt', system: 'write.system.txt' },
  { id: 'post', name: 'Post the update to the requester', body: script(['psa.ps1'], ['step.ps1'], 'post.ps1'),
    params: [['ctx', '{{ nodes.detect.output.ctx_json }}'], ['ai', '{{ nodes.write.output }}']] },
];

let x = 280;
const chain = ['start', ...steps.map((s) => s.id), 'end'];
const yml = `automationsWorkflow: 1
name: Status Change Updates
description: When a ticket changes status, write a short plain-language update for the requester from the
  ticket summary, the original request and the latest public notes, and post it as a public note so the PSA
  emails them. Skips internal-only statuses and unchanged statuses. Falls back to a fixed template per status.
definition:
  schemaVersion: 1
  activities:
  - id: start
    name: Start
    type: start
    position:
      x: 100
      y: 80
    properties:
      # Enable the webhook in Properties after import; AutomationAI issues the URL and secret.
      webhookEnabled: false
${steps.map((s) => { const r = s.ai ? aiStep({ ...s, x }) : psStep({ ...s, x }); x += 180; return r; }).join('')}  - id: end
    name: End
    type: end
    position:
      x: ${x}
      y: 80
  connections:
${chain.slice(0, -1).map((src, i) => `  - source: ${src}\n    target: ${chain[i + 1]}\n    sourceHandle: null\n`).join('')}  startActivityId: start
`;

const y = loadYaml();
const { text } = injectText(yml, `${name}.yml`, new Map());
const doc = y.load(text);
// Guard rails: the shape every workflow must have.
if (doc.automationsWorkflow !== 1) throw new Error('automationsWorkflow marker missing');
const acts = doc.definition.activities;
if (acts.find((a) => a.id === 'start').properties.webhookEnabled !== false) throw new Error('webhook must ship disabled');
if (acts.some((a) => a.properties && a.properties.model)) throw new Error('model must be blank');
if (!/{{ nodes.detect.output.facts_json }}/.test(acts.find((a) => a.id === 'write').properties.promptTemplate)) throw new Error('the prompt must read the detect facts');
if (/\{\{\s*input\./.test(text)) throw new Error('use nodes.<id>.output bindings, never input.*');
if (/—/.test(text)) throw new Error('no em dashes');
const ids = new Set(acts.map((a) => a.id));
for (const c of doc.definition.connections) if (!ids.has(c.source) || !ids.has(c.target)) throw new Error(`bad connection ${c.source} -> ${c.target}`);

const check = process.argv.includes('--check');
const was = fs.existsSync(out) ? fs.readFileSync(out, 'utf8').replace(/\r\n/g, '\n') : '';
if (text === was) { console.log(`${name}.yml: current`); process.exit(0); }
if (check) { console.log(`${name}.yml: OUT OF DATE (run node src/build.js)`); process.exit(1); }
fs.writeFileSync(out, text);
console.log(`${name}.yml: written`);
