# === Step 1: Find at-risk tickets (Auto-Escalation) ===
# Finds open tickets with no update for longer than minutes_untouched_by_priority, or whose SLA target is
# sla_risk_percent (default 80) used or already passed, and plans one escalation per ticket:
#   - its queue has an escalation_map entry, and nobody is actively working it: move it up one tier
#     (to the mapped queue, board, team or group, and/or the mapped user), then note and notify;
#   - otherwise: note and notify only.
# A ticket that already has an "[Auto-Escalation]" note is never escalated again (the next step writes that
# note before it moves anything, so a retried run can't move a ticket twice).
# This step only reads. A Routine runs it with no input, so every input has a default.
# >>> _shared/psa.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/psa.ps1
# >>> _shared/psa-tickets.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/psa-tickets.ps1

$escMarker = '[Auto-Escalation]'
$run = @{ warnings = (New-Object System.Collections.ArrayList); actions = (New-Object System.Collections.ArrayList) }
# The step's own warnings first, then the ones _shared/psa.ps1 recorded in $PsaState.Warnings (a priority it
# couldn't set, a write answered with a redirect), each once and in its own words.
function Get-EscWarnings {
    param($Own)
    $all = New-Object System.Collections.ArrayList
    foreach ($w in @(@($Own) + @($PsaState.Warnings))) { $t = [string]$w; if ($t -and -not $all.Contains($t)) { $null = $all.Add($t) } }
    return @($all)
}
function Stop-EscRun {
    param([string]$Status, [string]$Message)
    Set-NodeOutput ([ordered]@{ status = $Status; message = $Message; public_note = ''; internal_note = $Message; ticket_id = ''; preview = $false; escalations = @(); counts = @{}; settings = @{}; actions = @($run.actions); warnings = @(Get-EscWarnings $run.warnings) })
    throw $Message
}

# ---- inputs ----
$escIn = Get-NodeInput
if ($escIn -is [string]) { $escIn = $(if ($escIn.Trim()) { try { $escIn | ConvertFrom-Json } catch { $null } } else { $null }) }
$escWrap = Get-PsaProp $escIn 'trigger'; if ($null -ne $escWrap) { $escIn = $escWrap }
function Get-EscInput {
    param([string]$Name, $Default)
    $v = Get-PsaProp $escIn $Name
    if ($null -eq $v) { return $Default }
    if ($v -is [string] -and ([string]::IsNullOrWhiteSpace($v) -or $v.Trim().StartsWith('@'))) { return $Default }
    return $v
}
function ConvertTo-EscBool { param($v) if ($v -is [bool]) { return $v }; return ([string]$v).Trim() -match '^(?i)(true|yes|1|on)$' }
function ConvertTo-EscInt {
    param($v, [string]$Name, [int]$Min, [int]$Max)
    $n = 0; if (-not [int]::TryParse(([string]$v).Trim(), [ref]$n) -or $n -lt $Min -or $n -gt $Max) { throw "$Name must be a whole number from $Min to $Max." }
    return $n
}
# The "," keeps a one-item JSON list a list: a function return unrolls arrays.
function ConvertFrom-EscJson { param($v, [string]$Name) if ($v -is [string]) { try { return , ($v | ConvertFrom-Json -NoEnumerate) } catch { throw "$Name isn't valid JSON." } }; return , $v }
# A list of name/value pairs from a JSON object, hashtable or pscustomobject.
function Get-EscPairs {
    param($o)
    $pairs = New-Object System.Collections.ArrayList
    if ($null -eq $o) { return , $pairs }
    if ($o -is [System.Collections.IDictionary]) { foreach ($k in @($o.Keys)) { $null = $pairs.Add(@([string]$k, $o[$k])) } }
    else { foreach ($pp in @($o.PSObject.Properties)) { $null = $pairs.Add(@($pp.Name, $pp.Value)) } }
    return , $pairs
}
function ConvertTo-EscMinutes {
    param($Value)
    $m = @{ critical = 15; high = 60; medium = 240; low = 480 }
    if ($null -eq $Value) { return $m }
    foreach ($p in (Get-EscPairs (ConvertFrom-EscJson $Value 'minutes_untouched_by_priority'))) {
        $k = Get-PsaPriorityHint ([string]$p[0])
        $n = 0; if (-not $k -or -not [int]::TryParse([string]$p[1], [ref]$n) -or $n -lt 1) { throw "minutes_untouched_by_priority needs a whole number of minutes (1 or more) for each of critical, high, medium and low. '$($p[0])' was '$($p[1])'." }
        $m[$k] = $n
    }
    return $m
}
# escalation_map: {"<from queue name or id>": "<to queue>"} or {"<from>": {"queue": "...", "assignee": "...", "role": "..."}},
# or a list [{"from": "...", "queue": "...", "assignee": "...", "role": "..."}]. "*" matches any queue without its own entry.
function ConvertTo-EscMap {
    param($Value)
    $out = New-Object System.Collections.ArrayList
    if ($null -eq $Value) { return , $out }
    $v = ConvertFrom-EscJson $Value 'escalation_map'
    $items = New-Object System.Collections.ArrayList
    if ($v -is [array]) { foreach ($e in $v) { $null = $items.Add(@([string](Get-PsaProp $e 'from'), $e)) } }
    else { foreach ($p in (Get-EscPairs $v)) { $null = $items.Add($p) } }
    foreach ($it in $items) {
        $from = ([string]$it[0]).Trim(); $e = $it[1]
        if (-not $from) { throw 'Every escalation_map entry needs a "from" queue name or id (or "*").' }
        $q = ''; $a = ''; $r = ''
        if ($e -is [string] -or $e -is [ValueType]) { $q = [string]$e }
        else {
            foreach ($n in @('queue', 'to', 'board', 'team', 'group')) { $x = Get-PsaProp $e $n; if (-not (Test-PsaBlank $x)) { $q = [string]$x; break } }
            foreach ($n in @('assignee', 'user', 'user_id', 'dispatcher_user_id')) { $x = Get-PsaProp $e $n; if (-not (Test-PsaBlank $x)) { $a = [string]$x; break } }
            $x = Get-PsaProp $e 'role'; if (-not (Test-PsaBlank $x)) { $r = [string]$x }
        }
        if (-not $q.Trim() -and -not $a.Trim()) { throw "The escalation_map entry for '$from' names no queue and no assignee." }
        $null = $out.Add(@{ from = $from.ToLowerInvariant(); fromLabel = $from; queue = $q.Trim(); assignee = $a.Trim(); role = $r.Trim() })
    }
    return , $out
}
function Format-EscSpan {
    param([double]$Minutes)
    $m = [int][Math]::Round([Math]::Abs($Minutes))
    if ($m -ge 2880) { return "$([int][Math]::Floor($m / 1440)) days" }
    if ($m -ge 120) { $hrs = "$([int][Math]::Floor($m / 60)) hours"; if ($m % 60) { $hrs += " $($m % 60) minutes" }; return $hrs }
    return "$m minutes"
}

try {
    $preview = ConvertTo-EscBool (Get-EscInput 'preview' $false)
    $maxT = ConvertTo-EscInt (Get-EscInput 'max_tickets' 10) 'max_tickets' 1 100
    $maxScan = ConvertTo-EscInt (Get-EscInput 'max_scan' 500) 'max_scan' 1 5000
    $limits = ConvertTo-EscMinutes (Get-EscInput 'minutes_untouched_by_priority' $null)
    $riskPct = ConvertTo-EscInt (Get-EscInput 'sla_risk_percent' 80) 'sla_risk_percent' 1 100
    $checkSla = ConvertTo-EscBool (Get-EscInput 'check_sla' $true)
    # A Routine sends no input, so the AutoEscalation-Map secret (the same JSON) is the default map.
    $mapRaw = Get-EscInput 'escalation_map' $null; if ($null -eq $mapRaw) { $ms = Get-PsaSecret 'AutoEscalation-Map'; if (-not [string]::IsNullOrWhiteSpace($ms)) { $mapRaw = $ms } }
    $map = ConvertTo-EscMap $mapRaw
    # A Routine sends no input, so the Dispatcher-Email secret is the default recipient.
    $dRaw = Get-EscInput 'dispatcher_email' ''; if (-not ([string]$dRaw).Trim()) { $dRaw = [string](Get-PsaSecret 'Dispatcher-Email') }
    $dispatch = @(@($dRaw) | ForEach-Object { ([string]$_) -split '[,;]' } | ForEach-Object { $_.Trim() } | Where-Object { $_ })
    foreach ($a in $dispatch) { if ($a -notmatch '^[^@\s]+@[^@\s]+\.[^@\s]+$') { throw "'$a' in dispatcher_email isn't an email address." } }
    $skip = @(@(Get-EscInput 'skip_statuses' 'waiting,pending,on hold,scheduled') | ForEach-Object { ([string]$_) -split '[,;]' } | ForEach-Object { $_.Trim().ToLowerInvariant() } | Where-Object { $_ })
    $settings = [ordered]@{
        psa = [string](Get-EscInput 'psa' ''); preview = $preview; max_tickets = $maxT; minutes_untouched_by_priority = $limits; sla_risk_percent = $riskPct
        check_sla = $checkSla; dispatcher_email = @($dispatch); skip_statuses = $skip; marker = $escMarker
        from = [string](Get-EscInput 'from' ''); message_stream = [string](Get-EscInput 'message_stream' 'outbound')
        company = [string](@(@('company', 'company_id', 'companyId') | ForEach-Object { Get-EscInput $_ '' } | Where-Object { ([string]$_).Trim() }) | Select-Object -First 1)
        companyId = ''; companyName = ''
    }
}
catch { Stop-EscRun 'rejected' "Auto-Escalation didn't run because an input is invalid: $($_.Exception.Message)" }

# ---- read the PSA ----
try { $conn = Connect-Psa (Get-PsaType $settings.psa) }
catch { Stop-EscRun 'error' "Auto-Escalation couldn't connect to the PSA. $($_.Exception.Message)" }
$psaName = Get-PsaName
# Optional company input: a PSA company id or exact name. Only that company's tickets are read, moved or noted.
try { $co = Resolve-PsaCompanyId $settings.company; $settings.companyId = $co.id; $settings.companyName = $co.name }
catch { Stop-EscRun 'rejected' "Auto-Escalation didn't run because the company input couldn't be matched: $($_.Exception.Message)" }
$scope = if ($settings.companyName) { " for $($settings.companyName)" } elseif ($settings.companyId) { " for company $($settings.companyId)" } else { '' }
$now = [datetime]::UtcNow
try { $open = @(Find-PsaTickets -Open -CompanyId $settings.companyId -Max $maxScan -IncludeSla) }
catch { Stop-EscRun 'error' "Auto-Escalation couldn't read open tickets from $psaName. $($_.Exception.Message)" }
$null = $run.actions.Add("Read $($open.Count) open tickets$scope from $psaName.")
if ($PsaState.FindTruncated) { $null = $run.warnings.Add("Stopped reading at max_scan ($maxScan) open tickets, so some weren't checked.") }

$counts = [ordered]@{ open = $open.Count; skipped = 0; atRisk = 0; alreadyEscalated = 0; notesUnreadable = 0; selected = 0; toReassign = 0; noteOnly = 0; overLimit = 0 }
$cands = New-Object System.Collections.ArrayList
$slaWarned = @{ done = $false }
foreach ($t in $open) {
    $st = $t.status.ToLowerInvariant()
    if (@($skip | Where-Object { $st.Contains($_) }).Count) { $counts.skipped++; continue }
    $prio = if ($t.priorityLevel) { $t.priorityLevel } else { 'medium' }
    $limit = [int]$limits[$prio]
    $idle = if ($null -ne $t.updated) { ($now - $t.updated).TotalMinutes } else { 0 }
    $untouched = $idle -ge $limit
    $slaRisk = $false; $slaText = ''; $pct = 0
    if ($checkSla) {
        $sla = $null
        try { $sla = Get-PsaTicketSla $t }
        catch { if (-not $slaWarned.done) { $slaWarned.done = $true; $null = $run.warnings.Add("Couldn't read $psaName SLA details for some tickets, so only the untouched time was checked for them. First error: $($_.Exception.Message)") } }
        if ($null -ne $sla -and $sla.source -eq 'psa') {
            $what = switch ($sla.kind) { 'respond' { 'respond-by' } 'resolve' { 'resolve-by' } default { 'due' } }
            if ($null -ne $sla.target) {
                $total = ($sla.target - $sla.start).TotalMinutes
                $pct = if ($total -gt 0) { [int][Math]::Round(100 * ($now - $sla.start).TotalMinutes / $total) } else { 100 }
                $when = $sla.target.ToString('ddd d MMM HH:mm', [Globalization.CultureInfo]::InvariantCulture) + ' UTC'
                if ($now -ge $sla.target) { $slaRisk = $true; $slaText = "Its SLA $what time ($when) has passed." }
                elseif ($pct -ge $riskPct) { $slaRisk = $true; $slaText = "It has used $pct% of the time to its SLA $what time ($when)." }
            }
            elseif ($sla.breached -eq $true) { $slaRisk = $true; $slaText = "$psaName marks it as out of SLA." }
        }
    }
    if (-not $untouched -and -not $slaRisk) { continue }
    $counts.atRisk++
    $score = [Math]::Max($(if ($limit -gt 0) { $idle / $limit } else { 0 }), $pct / 100.0)
    $null = $cands.Add(@{ t = $t; prio = $prio; limit = $limit; idle = $idle; untouched = $untouched; slaRisk = $slaRisk; slaText = $slaText; score = $score })
}

# Most overdue first; skip tickets already escalated (marker note); stop at max_tickets.
$picked = New-Object System.Collections.ArrayList
$noteReads = 0
foreach ($cd in @($cands | Sort-Object { $_.score } -Descending)) {
    if ($picked.Count -ge $maxT) { $counts.overLimit++; continue }
    if ($noteReads -ge ($maxT * 5 + 20)) { $counts.overLimit++; continue }
    $noteReads++
    $notes = $null
    try { $notes = @(Get-PsaTicketNotes -Id $cd.t.id -TextOnly) }
    catch {
        # Fail closed: without the notes we can't tell whether it was already escalated.
        $counts.notesUnreadable++
        $null = $run.warnings.Add("Skipped ticket $($cd.t.number) because its notes couldn't be read to check for an earlier escalation: $($_.Exception.Message)")
        continue
    }
    if (Test-PsaNoteMarker -Id $cd.t.id -Marker $escMarker -Notes $notes) { $counts.alreadyEscalated++; continue }
    $null = $picked.Add($cd)
}
if ($counts.overLimit) { $null = $run.warnings.Add("$($counts.overLimit) more at-risk tickets were left for the next run because of max_tickets ($maxT).") }
try { Resolve-PsaTicketNames @($picked | ForEach-Object { $_.t }) }
catch { $null = $run.warnings.Add("Couldn't look up some company or technician names: $($_.Exception.Message)") }

# ---- plan each escalation ----
$escalations = @(foreach ($cd in $picked) {
        $t = $cd.t
        $qid = $t.queueId.ToLowerInvariant(); $qname = $t.queueName.Trim().ToLowerInvariant()
        $entry = @($map | Where-Object { $_.from -ne '*' -and (($qid -and $_.from -eq $qid) -or ($qname -and $_.from -eq $qname)) }) | Select-Object -First 1
        if (-not $entry) { $entry = @($map | Where-Object { $_.from -eq '*' }) | Select-Object -First 1 }
        $reasons = @()
        if ($cd.untouched) { $reasons += "It has had no update for $(Format-EscSpan $cd.idle), past the $($cd.limit)-minute limit for $($cd.prio) priority tickets." }
        if ($cd.slaRisk) { $reasons += $cd.slaText }
        $qLabel = if ($t.queueName) { $t.queueName } elseif ($t.queueId) { "queue $($t.queueId)" } else { 'no queue' }
        $active = (-not $cd.untouched) -and [bool]$t.assigneeId
        $action = 'note-only'; $why = ''; $toQ = ''; $toA = ''; $toR = ''
        if ($active) { $why = "It was updated recently and is assigned to $($t.assigneeName), so it stays with them." }
        elseif (-not $entry) { $why = "There is no escalation_map entry for $qLabel, so it wasn't moved." }
        else {
            $toQ = $entry.queue; $toA = $entry.assignee; $toR = $entry.role
            $sameQ = $toQ -and ($toQ.ToLowerInvariant() -eq $qid -or $toQ.ToLowerInvariant() -eq $qname)
            if ($sameQ) { $toQ = '' }
            $sameA = $toA -and ($toA -eq $t.assigneeId)
            if ($sameA) { $toA = '' }
            if ($toQ -or $toA) { $action = 'reassign' }
            else { $why = "It is already where the escalation_map sends $qLabel tickets, so it wasn't moved again." }
        }
        if ($action -eq 'reassign') { $counts.toReassign++ } else { $counts.noteOnly++ }
        [ordered]@{
            id = $t.id; number = $t.number; summary = $t.summary; company = $t.companyName; technician = $t.assigneeName; assigneeId = $t.assigneeId
            queue = $qLabel; queueId = $t.queueId; priority = $cd.prio; priorityLabel = $t.priority; status = $t.status
            minutesUntouched = [int][Math]::Round($cd.idle); untouched = $cd.untouched; slaAtRisk = $cd.slaRisk
            reason = ($reasons -join ' '); action = $action; whyNotMoved = $why; toQueue = $toQ; toAssignee = $toA; toRole = $toR
            result = $(if ($preview) { 'preview' } else { 'planned' }); outcome = ''; error = ''; noted = $false
        }
    })
$counts.selected = $escalations.Count

$checked = $open.Count - $counts.skipped
if (-not $escalations.Count) {
    $msg = "No open tickets$scope need escalating. $checked open tickets were checked."
    if ($counts.alreadyEscalated) { $msg += " $($counts.alreadyEscalated) at-risk tickets were already escalated earlier." }
}
elseif ($preview) { $msg = "Preview: $($escalations.Count) ticket$(if ($escalations.Count -ne 1) { 's' }) would be escalated$scope ($($counts.toReassign) moved up a tier, $($counts.noteOnly) noted and flagged only). Nothing was changed. Run again with preview set to false to make the changes." }
else { $msg = "$($escalations.Count) ticket$(if ($escalations.Count -ne 1) { 's' }) to escalate: $($counts.toReassign) to move up a tier and $($counts.noteOnly) to note and flag only." }

Set-NodeOutput ([ordered]@{
        status = $(if ($preview -and $escalations.Count) { 'pending_confirmation' } else { 'success' }); message = $msg; public_note = ''; internal_note = $msg; ticket_id = ''
        preview = $preview; psa = $conn.Psa; psaName = $psaName; companyId = $settings.companyId; companyName = $settings.companyName; generatedAt = $now.ToString('yyyy-MM-ddTHH:mm:ssZ')
        escalations = @($escalations); counts = $counts; settings = $settings
        actions = @($run.actions); warnings = @(Get-EscWarnings $run.warnings)
    })
