# === Step 4: Follow-up note and run summary (Auto-Escalation) ===
# The "[Auto-Escalation]" note was written before the move (step 2). This step adds a second internal note
# only where something didn't go to plan after that: the move failed, or the dispatcher email that note
# mentioned couldn't be sent. The follow-up uses its own marker ("[Auto-Escalation: follow-up]") through
# Add-PsaNote -Marker, so a retry never writes it twice. Then it returns the workflow's output contract.
# Does nothing in preview.
# >>> _shared/psa.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/psa.ps1

function ConvertTo-EscHash {
    param($o)
    $h = [ordered]@{}
    if ($o -is [System.Collections.IDictionary]) { foreach ($k in @($o.Keys)) { $h[[string]$k] = $o[$k] } }
    elseif ($null -ne $o) { foreach ($p in @($o.PSObject.Properties)) { $h[$p.Name] = $p.Value } }
    return $h
}

# The step's own warnings first, then the ones _shared/psa.ps1 recorded in $PsaState.Warnings (a priority it
# couldn't set, a write answered with a redirect), each once and in its own words.
function Get-EscWarnings {
    param($Own)
    $all = New-Object System.Collections.ArrayList
    foreach ($w in @(@($Own) + @($PsaState.Warnings))) { $t = [string]$w; if ($t -and -not $all.Contains($t)) { $null = $all.Add($t) } }
    return @($all)
}

$prev = ConvertTo-EscHash (Get-NodeInput)
$st = [string](Get-PsaProp $prev 'status')
if ($st -notin @('success', 'pending_confirmation')) { $prev.warnings = @(Get-EscWarnings (Get-PsaProp $prev 'warnings')); Set-NodeOutput $prev; throw "The previous step didn't finish: $(Get-PsaProp $prev 'message')" }
$settings = Get-PsaProp $prev 'settings'
$followMarker = '[Auto-Escalation: follow-up]'
$escalations = @(@(Get-PsaProp $prev 'escalations') | Where-Object { $null -ne $_ } | ForEach-Object { ConvertTo-EscHash $_ })
$actions = @(@(Get-PsaProp $prev 'actions') | Where-Object { $_ })
$warnings = @(@(Get-PsaProp $prev 'warnings') | Where-Object { $_ })
$preview = (Get-PsaProp $prev 'preview') -eq $true
$emailed = (Get-PsaProp $prev 'dispatcher_emailed') -eq $true
$emailPlanned = (Get-PsaProp $prev 'email_planned') -eq $true
$delivery = [string](Get-PsaProp $prev 'delivery')
$counts = ConvertTo-EscHash (Get-PsaProp $prev 'counts')
$coName = [string](Get-PsaProp $prev 'companyName'); $coId = [string](Get-PsaProp $prev 'companyId')
$scope = if ($coName) { " for $coName" } elseif ($coId) { " for company $coId" } else { '' }
$noteFails = @($escalations | Where-Object { -not $_.noted -and $_.result -eq 'failed' }).Count

# ---- follow-up notes ----
$follow = @($escalations | Where-Object { $_.noted -and ($_.result -in @('failed', 'partial') -or ($emailPlanned -and -not $emailed)) })
if (-not $preview -and $follow.Count) {
    $connected = $false
    try { $null = Connect-Psa (Get-PsaType ([string](Get-PsaProp $settings 'psa'))); $connected = $true }
    catch { $warnings += "Couldn't connect to the PSA to add the follow-up notes: $($_.Exception.Message)" }
    foreach ($e in $follow) {
        if (-not $connected) { continue }
        $parts = @()
        if ($e.result -in @('failed', 'partial')) { $parts += "$($e.outcome) A technician needs to finish the escalation by hand." }
        if ($emailPlanned -and -not $emailed) { $parts += 'The dispatcher email could not be sent, so these notes are the notification.' }
        try {
            $r = Add-PsaNote -Id $e.id -Text "$followMarker $($parts -join ' ')" -Title 'Auto-Escalation' -Marker $followMarker
            if ($r -eq 'written') { $actions += "Ticket $($e.number): added a follow-up note." }
        }
        catch { $warnings += "Ticket $($e.number): the follow-up note couldn't be added: $($_.Exception.Message)" }
    }
}

# ---- summary ----
$done = @($escalations | Where-Object { $_.result -ne 'already-escalated' })
$already = $escalations.Count - $done.Count
$n = $done.Count
$moved = @($done | Where-Object { $_.result -in @('reassigned', 'partial') }).Count
$moveFails = @($done | Where-Object { $_.noted -and $_.result -in @('failed', 'partial') }).Count
if ($preview -or -not $escalations.Count) {
    $status = [string](Get-PsaProp $prev 'status')
    $message = [string](Get-PsaProp $prev 'message')
}
else {
    $status = if ($moveFails -or $noteFails) { 'incomplete' } else { 'success' }
    $message = if ($n) { "Escalated $n ticket$(if ($n -ne 1) { 's' })$($scope): $moved moved up a tier and $($n - $moved) flagged without moving. $delivery" } else { "Nothing new was escalated$scope." }
    if ($already) { $message += " $already ticket$(if ($already -ne 1) { 's were' } else { ' was' }) already escalated by another run and left alone." }
    if ($moveFails) { $message += " $moveFails could not be moved; see warnings." }
    if ($noteFails) { $message += " $noteFails escalation note$(if ($noteFails -ne 1) { 's' }) could not be added, so $(if ($noteFails -ne 1) { 'those tickets were' } else { 'that ticket was' }) not moved; see warnings." }
}
$lines = @($escalations | ForEach-Object { "Ticket $($_.number) ($($_.company)): $($_.reason) $($_.outcome)".Trim() })
$internal = (@("Auto-Escalation ran against $(Get-PsaProp $prev 'psaName'). $message") + $lines) -join "`n"

Set-NodeOutput ([ordered]@{
        status = $status; message = $message.Trim(); public_note = ''; internal_note = $internal; ticket_id = $(if ($escalations.Count -eq 1) { [string]$escalations[0].id } else { '' })
        preview = $preview; dispatcher_emailed = $emailed; counts = $counts; escalations = @($escalations)
        actions = @($actions); warnings = @(Get-EscWarnings $warnings)
    })
