# === NODE: Look up the email ===
# Finds the reported email in the reporter's own mailbox through Microsoft Graph and gathers the facts
# a technician would check: authentication results (SPF, DKIM, DMARC, composite auth), display name and
# reply-to mismatches, look-alike sender domains, link domains (Safe Links unwrapped), and attachment
# names and types. No AI here. The body text is never copied out; only link domains and defanged URLs are.
# It also works out a rules score, which the ticket step uses when the AI classification is missing.
# Graph can't count how many other mailboxes received the same message (that needs Exchange or
# Defender), so this step doesn't try, and says so.
# >>> _shared/graph.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/graph.ps1
$ErrorActionPreference = 'Stop'

function Get-Prop { param($o, [string]$n) if ($null -eq $o) { return $null }; if ($o -is [System.Collections.IDictionary]) { if ($o.Contains($n)) { return $o[$n] }; return $null }; $p = $o.PSObject.Properties[$n]; if ($p) { return $p.Value }; return $null }
$stopState = @{ done = $false }
function Stop-Lookup {
    param([string]$Status, [string]$Why, [string]$TicketId = '')
    $stopState.done = $true
    Set-NodeOutput ([ordered]@{
            status = $Status; message = $Why
            public_note = 'Thanks for reporting this email. We could not check it automatically, so a technician will follow up.'
            internal_note = "Phishing report triage stopped during the mailbox lookup: $Why"
            ticket_id = $TicketId; actions = @(); warnings = @()
        })
    throw $Why
}
# Any other failure (for example a missing Graph permission) still leaves a plain output, then fails the step.
trap { if (-not $stopState.done) { $stopState.done = $true; Set-NodeOutput ([ordered]@{ status = 'error'; message = [string]$_.Exception.Message; public_note = 'Thanks for reporting this email. We could not check it automatically, so a technician will follow up.'; internal_note = "Phishing report triage failed during the mailbox lookup: $($_.Exception.Message)"; ticket_id = ''; actions = @(); warnings = @() }) }; break }
function Get-Domain { param([string]$Address) if ($Address -match '@([^@\s>]+)$') { return $Matches[1].ToLowerInvariant().TrimEnd('.') }; return '' }
function Get-HostOf { param([string]$Url) try { $u = [uri]$Url; if ($u.IsAbsoluteUri -and $u.Host) { return $u.Host.ToLowerInvariant().TrimEnd('.') } } catch { }; return '' }
# The registrable part of a host, good enough to compare (last two labels; three for co.uk style).
function Get-BaseDomain {
    param([string]$HostName)
    $h = $HostName.ToLowerInvariant().TrimEnd('.')
    if ($h -match '^\d{1,3}(\.\d{1,3}){3}$' -or $h -match ':') { return $h }
    $parts = @($h.Split('.') | Where-Object { $_ })
    if ($parts.Count -le 2) { return $h }
    $n = 2
    if ($parts[-2] -match '^(co|com|net|org|gov|ac|edu)$' -and $parts[-1].Length -eq 2) { $n = 3 }
    return ($parts[($parts.Count - $n)..($parts.Count - 1)] -join '.')
}
# Safe Links (and the older urldefense wrapper is left alone): the real target is the url= parameter.
function Expand-SafeLink {
    param([string]$Url)
    $h = Get-HostOf $Url
    if ($h -like '*.safelinks.protection.outlook.com' -or $h -eq 'safelinks.protection.outlook.com') {
        if ($Url -match '[?&]url=([^&]+)') { return [uri]::UnescapeDataString($Matches[1]) }
    }
    return $Url
}
function Get-Defanged { param([string]$s) return (($s -replace '^http', 'hxxp') -replace '\.', '[.]') }
function Get-EditDistance {
    param([string]$a, [string]$b)
    $d = New-Object 'int[,]' ($a.Length + 1), ($b.Length + 1)
    for ($i = 0; $i -le $a.Length; $i++) { $d[$i, 0] = $i }
    for ($j = 0; $j -le $b.Length; $j++) { $d[0, $j] = $j }
    for ($i = 1; $i -le $a.Length; $i++) {
        for ($j = 1; $j -le $b.Length; $j++) {
            $cost = if ($a[$i - 1] -eq $b[$j - 1]) { 0 } else { 1 }
            $d[$i, $j] = [Math]::Min([Math]::Min($d[($i - 1), $j] + 1, $d[$i, ($j - 1)] + 1), $d[($i - 1), ($j - 1)] + $cost)
        }
    }
    return $d[$a.Length, $b.Length]
}
function ConvertTo-ODataString { param([string]$s) return $s.Replace("'", "''") }

# ---- input ----
$in = Get-NodeInput
$req = $null
$rj = Get-Prop $in 'request_json'
if ($rj -is [string] -and $rj) { $req = $rj | ConvertFrom-Json }
if ($null -eq $req) { $req = Get-Prop $in 'request' }
if ($null -eq $req) { Stop-Lookup 'error' 'The previous step passed no request. Run the workflow from the start.' }
$reporter = [string](Get-Prop $req 'reporter_upn')
$ticketId = [string](Get-Prop $req 'ticket_id')
$warnings = New-Object System.Collections.ArrayList
$actions = New-Object System.Collections.ArrayList
foreach ($w in @(Get-Prop $in 'warnings')) { if ($w) { $null = $warnings.Add([string]$w) } }

# ---- sign in, and keep to this company's tenant ----
$g = Connect-Graph
$tenantWanted = [string](Get-Prop $req 'company_tenant_id')
if ($tenantWanted -match '^[0-9a-fA-F-]{36}$') {
    if ($tenantWanted.ToLowerInvariant() -ne $g.TenantId.ToLowerInvariant()) { Stop-Lookup 'rejected' "The report came from tenant $tenantWanted, but this runner's Microsoft 365 app is for tenant $($g.TenantId). Nothing was looked up, to keep one client's mail out of another client's ticket." $ticketId }
}
else { $null = $warnings.Add('No company tenant id was sent, so the tenant check was skipped. Map company_tenant_id to @CompanyTenantId.') }

$user = Get-GraphUser -Id $reporter -Select 'id,userPrincipalName,displayName,mail'
if ($null -eq $user) { Stop-Lookup 'rejected' "The reporter $reporter isn't a user in this Microsoft 365 tenant. Nothing was looked up." $ticketId }
$uid = [string](Get-Prop $user 'id')
$reporterDomain = Get-Domain ([string](Get-Prop $user 'userPrincipalName'))
$orgDomains = New-Object System.Collections.ArrayList
foreach ($d in @($reporterDomain, (Get-Domain ([string](Get-Prop $user 'mail'))))) { if ($d -and -not $orgDomains.Contains($d)) { $null = $orgDomains.Add($d) } }
$null = $actions.Add("Found the reporter $reporter in Microsoft 365.")

# ---- find the message ----
$sel = 'id,internetMessageId,subject,from,sender,replyTo,receivedDateTime,hasAttachments,parentFolderId'
$base = "/v1.0/users/$uid/messages"
$perm = 'Mail.Read'
$msgId = [string](Get-Prop $req 'message_id')
$subject = [string](Get-Prop $req 'subject')
$senderIn = [string](Get-Prop $req 'sender')
$hits = @()
$how = ''
if ($msgId) {
    $flt = [uri]::EscapeDataString("internetMessageId eq '$(ConvertTo-ODataString $msgId)'")
    $hits = @(Get-Prop (Invoke-Graph GET "$($base)?`$filter=$flt&`$select=$sel&`$top=5" -Permission $perm) 'value' | Where-Object { $null -ne $_ })
    $how = 'its Internet Message-ID'
}
if (-not $hits.Count -and $senderIn) {
    $since = (Get-Date).ToUniversalTime().AddDays(-30).ToString('yyyy-MM-ddTHH:mm:ssZ')
    $flt = [uri]::EscapeDataString("from/emailAddress/address eq '$(ConvertTo-ODataString $senderIn)' and receivedDateTime ge $since")
    $hits = @(Get-Prop (Invoke-Graph GET "$($base)?`$filter=$flt&`$select=$sel&`$top=50" -Permission $perm) 'value' | Where-Object { $null -ne $_ })
    if ($subject) { $hits = @($hits | Where-Object { ([string](Get-Prop $_ 'subject')).IndexOf($subject, [StringComparison]::OrdinalIgnoreCase) -ge 0 }) }
    $how = 'its sender' + $(if ($subject) { ' and subject' } else { '' })
}
if (-not $hits.Count -and $subject -and -not $senderIn) {
    $q = [uri]::EscapeDataString("`"subject:$($subject.Replace('"', ''))`"")
    $hits = @(Get-Prop (Invoke-Graph GET "$($base)?`$search=$q&`$select=$sel&`$top=25" -Permission $perm) 'value' | Where-Object { $null -ne $_ })
    $how = 'its subject'
}
# Leave out the reporter's own copies (a forward to the help desk sits in Sent Items).
$hits = @($hits | Where-Object { ([string](Get-Prop (Get-Prop (Get-Prop $_ 'from') 'emailAddress') 'address')).ToLowerInvariant() -ne $reporter.ToLowerInvariant() })
$hits = @($hits | Sort-Object { $v = Get-Prop $_ 'receivedDateTime'; if ($v -is [datetime]) { $v } else { try { [datetime]$v } catch { [datetime]::MinValue } } } -Descending)

$e = [ordered]@{
    found = $false; located_by = $how; matches = $hits.Count
    reporter = $reporter; reporter_domain = $reporterDomain
    subject = $subject; received = ''; internet_message_id = $msgId
    from_name = ''; from_address = $senderIn; from_domain = (Get-Domain $senderIn)
    sender_address = ''; reply_to = @(); return_path = ''
    auth = [ordered]@{ spf = 'none'; dkim = 'none'; dmarc = 'none'; compauth = 'none'; compauth_reason = ''; header_present = $false }
    flags = @(); links = [ordered]@{ count = 0; domains = @(); external_domains = @(); samples = @() }
    attachments = @(); org_domains = @($orgDomains)
    other_recipients = 'Other mailboxes were not checked: Microsoft Graph cannot count how many mailboxes received this email. The draft compliance search (when there is one) or Defender Threat Explorer shows that.'
}
$flags = New-Object System.Collections.ArrayList
$score = 0

if (-not $hits.Count) {
    $null = $warnings.Add("The email was not found in $reporter's mailbox$(if ($how) { " by $how" }). It may have been deleted permanently, or the details sent don't match.")
}
else {
    if ($hits.Count -gt 1) { $null = $warnings.Add("$($hits.Count) emails matched; the newest was used.") }
    $m = $hits[0]
    $mid = [string](Get-Prop $m 'id')
    $full = Invoke-Graph GET "$base/$mid`?`$select=$sel,internetMessageHeaders,body" -Permission $perm -Headers @{ Prefer = 'outlook.body-content-type="html"' }
    $e.found = $true
    $e.subject = [string](Get-Prop $full 'subject')
    $rcv = Get-Prop $full 'receivedDateTime'
    $e.received = if ($rcv -is [datetime]) { $rcv.ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ') } else { [string]$rcv }
    $e.internet_message_id = [string](Get-Prop $full 'internetMessageId')
    $fromEa = Get-Prop (Get-Prop $full 'from') 'emailAddress'
    $e.from_name = [string](Get-Prop $fromEa 'name')
    $e.from_address = ([string](Get-Prop $fromEa 'address')).ToLowerInvariant()
    $e.from_domain = Get-Domain $e.from_address
    $e.sender_address = ([string](Get-Prop (Get-Prop (Get-Prop $full 'sender') 'emailAddress') 'address')).ToLowerInvariant()
    $e.reply_to = @(@(Get-Prop $full 'replyTo') | Where-Object { $null -ne $_ } | ForEach-Object { ([string](Get-Prop (Get-Prop $_ 'emailAddress') 'address')).ToLowerInvariant() } | Where-Object { $_ })
    $null = $actions.Add("Found the email in $reporter's mailbox by $how.")

    # -- headers --
    $headers = @(Get-Prop $full 'internetMessageHeaders' | Where-Object { $null -ne $_ })
    $ar = @($headers | Where-Object { [string](Get-Prop $_ 'name') -ieq 'Authentication-Results' } | ForEach-Object { [string](Get-Prop $_ 'value') })
    $rp = @($headers | Where-Object { [string](Get-Prop $_ 'name') -ieq 'Return-Path' } | ForEach-Object { [string](Get-Prop $_ 'value') })
    if ($rp.Count) { $e.return_path = ($rp[0].Trim('<', '>', ' ')).ToLowerInvariant() }
    if ($ar.Count) {
        $a = $ar[0]
        $e.auth.header_present = $true
        foreach ($k in @('spf', 'dkim', 'dmarc', 'compauth')) { if ($a -match "(?i)\b$k=([a-z]+)") { $e.auth[$k] = $Matches[1].ToLowerInvariant() } }
        if ($a -match '(?i)compauth=[a-z]+\s+reason=(\d+)') { $e.auth.compauth_reason = $Matches[1] }
    }
    else { $null = $warnings.Add('The email has no Authentication-Results header, so SPF, DKIM and DMARC could not be read.') }
    if ($e.auth.dmarc -match '^(fail|permerror)$') { $null = $flags.Add('DMARC failed.'); $score += 3 }
    if ($e.auth.spf -match '^(fail|softfail|permerror)$') { $null = $flags.Add("SPF result was $($e.auth.spf)."); $score += 2 }
    if ($e.auth.dkim -match '^(fail|permerror)$') { $null = $flags.Add('DKIM failed.'); $score += 1 }
    if ($e.auth.compauth -eq 'fail') { $null = $flags.Add("Microsoft composite authentication failed (reason $($e.auth.compauth_reason))."); $score += 2 }

    # -- sender identity --
    $fromDom = $e.from_domain
    if ($e.from_name -match '([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,})') {
        $nameDom = Get-Domain $Matches[1]
        if ($nameDom -and $nameDom -ne $fromDom) { $null = $flags.Add("The display name shows the address $($Matches[1]), but the email came from $($e.from_address)."); $score += 2 }
    }
    elseif ($e.from_name -match '(?i)\b([a-z0-9-]+\.(com|net|org|io|co|us|uk|gov|edu))\b') {
        if ((Get-BaseDomain $Matches[1]) -ne (Get-BaseDomain $fromDom)) { $null = $flags.Add("The display name mentions $($Matches[1]), but the email came from $fromDom."); $score += 2 }
    }
    $badReply = @($e.reply_to | Where-Object { (Get-BaseDomain (Get-Domain $_)) -ne (Get-BaseDomain $fromDom) })
    if ($badReply.Count) { $null = $flags.Add("Replies go to $($badReply -join ', '), a different domain from the sender."); $score += 2 }
    if ($e.return_path -and $fromDom -and (Get-BaseDomain (Get-Domain $e.return_path)) -ne (Get-BaseDomain $fromDom)) { $null = $flags.Add("The bounce address ($($e.return_path)) is on a different domain from the sender. This is common for mailing services, so it counts for little on its own.") }
    foreach ($od in @($orgDomains)) {
        $fb = Get-BaseDomain $fromDom; $ob = Get-BaseDomain $od
        if ($fb -and $ob -and $fb -ne $ob) {
            $dist = Get-EditDistance ($fb.Split('.')[0]) ($ob.Split('.')[0])
            if ($dist -gt 0 -and $dist -le 2) { $null = $flags.Add("The sender domain $fromDom looks like the organization's own domain $od."); $score += 3 }
        }
        if ($fb -eq $ob -and $e.auth.dmarc -match '^(fail|permerror)$') { $null = $flags.Add("The email claims to come from the organization's own domain $od but failed DMARC."); $score += 2 }
    }
    if ($fromDom -match '^xn--|\.xn--') { $null = $flags.Add("The sender domain $fromDom uses look-alike (punycode) characters."); $score += 2 }

    # -- links --
    $html = [string](Get-Prop (Get-Prop $full 'body') 'content')
    $urls = New-Object System.Collections.ArrayList
    $textMismatch = New-Object System.Collections.ArrayList
    foreach ($am in [regex]::Matches($html, '(?is)<a\b[^>]*?href\s*=\s*["'']([^"'']+)["''][^>]*>(.*?)</a>')) {
        $href = Expand-SafeLink ([System.Net.WebUtility]::HtmlDecode($am.Groups[1].Value))
        if ($href -notmatch '^(?i)https?://') { continue }
        $null = $urls.Add($href)
        $txt = ([System.Net.WebUtility]::HtmlDecode(($am.Groups[2].Value -replace '<[^>]+>', ''))).Trim()
        if ($txt -match '^(?i)(https?://)?([a-z0-9-]+\.)+[a-z]{2,}(/\S*)?$') {
            $tUrl = Expand-SafeLink $(if ($txt -match '^(?i)https?://') { $txt } else { "http://$txt" })
            $th = Get-HostOf $tUrl; $hh = Get-HostOf $href
            if ($th -and $hh -and (Get-BaseDomain $th) -ne (Get-BaseDomain $hh)) { $null = $textMismatch.Add("$th shown, $hh behind it") }
        }
    }
    $plain = $html -replace '(?is)<a\b[^>]*>.*?</a>', ' ' -replace '<[^>]+>', ' '
    foreach ($um in [regex]::Matches($plain, '(?i)\bhttps?://[^\s"''<>]+')) { $null = $urls.Add((Expand-SafeLink $um.Value)) }
    $hosts = @($urls | ForEach-Object { Get-HostOf $_ } | Where-Object { $_ } | Sort-Object -Unique)
    $ext = @($hosts | Where-Object { $h = $_; -not @($orgDomains | Where-Object { (Get-BaseDomain $h) -eq (Get-BaseDomain $_) }).Count -and (Get-BaseDomain $h) -ne (Get-BaseDomain $fromDom) })
    $e.links.count = $urls.Count
    $e.links.domains = @($hosts | Select-Object -First 25)
    $e.links.external_domains = @($ext | Select-Object -First 25)
    $e.links.samples = @($urls | Select-Object -Unique -First 10 | ForEach-Object { $s = [string]$_; if ($s.Length -gt 200) { $s = $s.Substring(0, 200) + '...' }; Get-Defanged $s })
    $ipHosts = @($hosts | Where-Object { $_ -match '^\d{1,3}(\.\d{1,3}){3}$' })
    if ($ipHosts.Count) { $null = $flags.Add("Links go straight to an IP address ($($ipHosts -join ', '))."); $score += 2 }
    $puny = @($hosts | Where-Object { $_ -match '(^|\.)xn--' })
    if ($puny.Count) { $null = $flags.Add("Links use look-alike (punycode) domains ($($puny -join ', '))."); $score += 2 }
    $shorteners = @('bit.ly', 'tinyurl.com', 't.co', 'goo.gl', 'ow.ly', 'is.gd', 'buff.ly', 'rebrand.ly', 'cutt.ly', 'shorturl.at', 'rb.gy', 't.ly')
    $short = @($hosts | Where-Object { $shorteners -contains $_ })
    if ($short.Count) { $null = $flags.Add("Links use URL shorteners that hide the real address ($($short -join ', '))."); $score += 1 }
    if ($textMismatch.Count) { $null = $flags.Add("Link text shows one site but points to another ($(@($textMismatch | Select-Object -First 3) -join '; '))."); $score += 2 }

    # -- attachments (names and types only; content is never downloaded) --
    if ((Get-Prop $full 'hasAttachments') -eq $true -or (Get-Prop $m 'hasAttachments') -eq $true -or $html -match '(?i)cid:') {
        $atts = @(Get-Prop (Invoke-Graph GET "$base/$mid/attachments?`$select=name,contentType,size,isInline" -Permission $perm) 'value' | Where-Object { $null -ne $_ })
        $risk = @{
            executable = @('exe', 'scr', 'msi', 'bat', 'cmd', 'com', 'cpl', 'pif', 'js', 'jse', 'vbs', 'vbe', 'wsf', 'wsh', 'ps1', 'hta', 'lnk', 'jar', 'reg', 'dll', 'appx', 'msix')
            macro      = @('docm', 'dotm', 'xlsm', 'xltm', 'xlam', 'xlsb', 'pptm', 'potm', 'ppam', 'sldm')
            legacy     = @('doc', 'xls', 'ppt', 'rtf')
            html       = @('html', 'htm', 'shtml', 'xhtml', 'svg', 'mht', 'mhtml')
            disk       = @('iso', 'img', 'vhd', 'vhdx')
            archive    = @('zip', 'rar', '7z', 'gz', 'tar', 'cab', 'ace', 'arj', 'xz')
            onenote    = @('one', 'onepkg')
        }
        $weights = @{ executable = 4; macro = 3; legacy = 1; html = 3; disk = 4; archive = 1; onenote = 3 }
        $labels = @{ executable = 'a program or script'; macro = 'an Office file with macros'; legacy = 'an older Office format that can carry macros'; html = 'a web page or SVG file (often a fake sign-in page)'; disk = 'a disk image'; archive = 'a compressed archive'; onenote = 'a OneNote file' }
        $list = New-Object System.Collections.ArrayList
        foreach ($at in $atts) {
            $name = [string](Get-Prop $at 'name')
            $type = [string](Get-Prop $at '@odata.type')
            $extn = if ($name -match '\.([A-Za-z0-9]{1,6})$') { $Matches[1].ToLowerInvariant() } else { '' }
            $kind = ''
            foreach ($k in @('executable', 'disk', 'macro', 'html', 'onenote', 'archive', 'legacy')) { if ($risk[$k] -contains $extn) { $kind = $k; break } }
            $double = ($name -match '\.(pdf|docx?|xlsx?|jpe?g|png|txt)\.[A-Za-z0-9]{2,5}$' -and $kind)
            $isItem = $type -match 'itemAttachment'
            $inline = (Get-Prop $at 'isInline') -eq $true
            $null = $list.Add([ordered]@{ name = $name; content_type = [string](Get-Prop $at 'contentType'); size = (Get-Prop $at 'size'); inline = $inline; risk = $(if ($kind) { $kind } elseif ($isItem) { 'attached-email' } else { '' }) })
            if ($kind) { $null = $flags.Add("Attachment $name is $($labels[$kind])."); $score += $weights[$kind] }
            if ($double) { $null = $flags.Add("Attachment $name hides its real type behind a double extension."); $score += 2 }
            if ($isItem) { $null = $flags.Add("Attachment $name is another email attached inside this one; check it too.") }
        }
        $e.attachments = @($list)
    }
}
$e.flags = @($flags)

# Rules verdict, used when the AI classification is missing or unreadable.
$rulesVerdict = if (-not $e.found) { 'unknown' } elseif ($score -ge 6) { 'malicious' } elseif ($score -ge 3) { 'suspicious' } else { 'likely-safe' }
$rulesConf = if (-not $e.found) { 0 } else { [Math]::Round([Math]::Min(0.85, 0.5 + 0.05 * $score), 2) }
$null = $actions.Add("Checked $($e.flags.Count) warning sign(s); the rules score is $score ($rulesVerdict).")

Set-NodeOutput ([ordered]@{
        status = 'ok'
        message = $(if ($e.found) { "Found the reported email from $($e.from_address) and checked it." } else { "Could not find the reported email in $reporter's mailbox." })
        request_json = ($req | ConvertTo-Json -Compress)
        enrichment = $e
        enrichment_json = ($e | ConvertTo-Json -Depth 6 -Compress)
        rules = [ordered]@{ score = $score; verdict = $rulesVerdict; confidence = $rulesConf }
        rules_json = ([ordered]@{ score = $score; verdict = $rulesVerdict; confidence = $rulesConf } | ConvertTo-Json -Compress)
        actions = @($actions); warnings = @($warnings)
        warnings_json = (ConvertTo-Json -InputObject @($warnings) -Compress)
    })
