# === NODE: Read the report ===
# Reads who reported the email and how to find it. Accepts a flat {key:value} body (portal form
# webhook, ServiceAI Action, or a manual run), the CloudRadial {Ticket:{Questions:[...]},Company:{...}}
# shape, or either one wrapped in {trigger:...}. A value CloudRadial left as a literal @token
# (for example "@messageId") counts as not given.
# When only a ticket id is given, the ticket's subject and text are read from the PSA and searched
# for the forwarded email's From, Subject and Message-ID lines.
# >>> _shared/psa.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/psa.ps1
$ErrorActionPreference = 'Stop'

function Get-Prop { param($o, [string]$n) if ($null -eq $o) { return $null }; if ($o -is [System.Collections.IDictionary]) { if ($o.Contains($n)) { return $o[$n] }; return $null }; $p = $o.PSObject.Properties[$n]; if ($p) { return $p.Value }; return $null }
function Stop-Report {
    param([string]$Status, [string]$Why, [string]$TicketId = '')
    Set-NodeOutput ([ordered]@{
            status = $Status; message = $Why
            public_note = 'Thanks for reporting this email. We could not process the report automatically, so a technician will follow up.'
            internal_note = "Phishing report triage stopped before any lookup: $Why"
            ticket_id = $TicketId; actions = @(); warnings = @()
        })
    throw $Why
}

$raw = Get-NodeInput
if ($null -eq $raw) { Stop-Report 'incomplete' 'No input was received. Send reporter_upn plus message_id, or subject and sender.' }
if ($raw -is [string]) { try { $raw = $raw | ConvertFrom-Json } catch { Stop-Report 'incomplete' 'The input was text that is not valid JSON.' } }
$wrap = Get-Prop $raw 'trigger'; if ($null -ne $wrap) { $raw = $wrap; if ($raw -is [string]) { try { $raw = $raw | ConvertFrom-Json } catch { Stop-Report 'incomplete' 'The trigger body was text that is not valid JSON.' } } }

# Collect every simple value, then the CloudRadial nested answers on top.
$answers = @{}
if ($raw -is [System.Collections.IDictionary]) { foreach ($k in @($raw.Keys)) { $answers[[string]$k] = $raw[$k] } }
else { foreach ($p in $raw.PSObject.Properties) { $answers[$p.Name] = $p.Value } }
$crTicket = Get-Prop $raw 'Ticket'
if ($null -ne $crTicket) {
    foreach ($q in @(Get-Prop $crTicket 'Questions')) { $qid = [string](Get-Prop $q 'Id'); if ($qid) { $answers[$qid] = Get-Prop $q 'Value' } }
    $tid = Get-Prop $crTicket 'TicketId'; if ($null -ne $tid) { $answers['ticket_id'] = $tid }
}
$crCompany = Get-Prop $raw 'Company'
if ($null -ne $crCompany) {
    foreach ($pair in @(@('CompanyTenantId', 'company_tenant_id'), @('CompanyName', 'company_name'), @('CompanyPsaId', 'psa_company_id'))) { $v = Get-Prop $crCompany $pair[0]; if ($null -ne $v) { $answers[$pair[1]] = $v } }
}
function Get-Field {
    param([string[]]$Names)
    foreach ($n in $Names) {
        if (-not $answers.ContainsKey($n)) { continue }
        $v = $answers[$n]
        if ($null -eq $v -or $v -is [System.Management.Automation.PSCustomObject] -or $v -is [System.Collections.IDictionary]) { continue }
        $s = ([string]$v).Trim()
        if (-not $s -or $s.StartsWith('@') -or $s -match '^\{\{.*\}\}$') { continue }
        return $s
    }
    return ''
}

$f = [ordered]@{
    reporter_upn      = (Get-Field @('reporter_upn', 'reporterUpn', 'UserEmail', 'userEmail', 'submittedByUpn'))
    message_id        = (Get-Field @('message_id', 'internetMessageId', 'internet_message_id', 'messageId'))
    subject           = (Get-Field @('subject', 'email_subject', 'emailSubject'))
    sender            = (Get-Field @('sender', 'from', 'sender_address', 'senderAddress'))
    ticket_id         = (Get-Field @('ticket_id', 'ticketId', 'TicketId'))
    psa               = (Get-Field @('psa'))
    company_name      = (Get-Field @('company_name', 'companyName'))
    psa_company_id    = (Get-Field @('psa_company_id', 'psaCompanyId', 'companyPsaId'))
    company_tenant_id = (Get-Field @('company_tenant_id', 'companyTenantId'))
    psa_queue         = (Get-Field @('psa_queue', 'queue', 'board'))
    confirm           = $false
}
$confirmRaw = (Get-Field @('confirm')).ToLowerInvariant()
$f.confirm = @('true', 'yes', '1', 'y') -contains $confirmRaw
$warnings = New-Object System.Collections.ArrayList
$actions = New-Object System.Collections.ArrayList

# A sender typed as "Name <address>" keeps the address only.
if ($f.sender -match '<([^<>\s]+@[^<>\s]+)>') { $f.sender = $Matches[1] }
if ($f.sender -and $f.sender -notmatch '^[^@\s]+@[^@\s]+\.[^@\s]+$') { $null = $warnings.Add("The sender '$($f.sender)' is not an email address, so it was ignored."); $f.sender = '' }
# Message-IDs are written with angle brackets; add them when missing.
if ($f.message_id -and $f.message_id -notmatch '^<.*>$') { $f.message_id = "<$($f.message_id.Trim('<', '>'))>" }

if (-not $f.reporter_upn) { Stop-Report 'incomplete' 'The reporter was not identified. Map reporter_upn to @UserEmail (portal form) or the ticket contact''s email (ServiceAI). Nothing was looked up.' $f.ticket_id }
if ($f.reporter_upn -notmatch '^[^@\s]+@[^@\s]+\.[^@\s]+$') { Stop-Report 'incomplete' "The reporter '$($f.reporter_upn)' is not an email address. Nothing was looked up." $f.ticket_id }
if ($f.ticket_id -and $f.ticket_id -notmatch '^\d+$') { Stop-Report 'incomplete' "The ticket id '$($f.ticket_id)' is not a number. Nothing was looked up." $f.ticket_id }

# Only a ticket id: read the forwarded email's details from the ticket.
if (-not $f.message_id -and -not $f.subject -and -not $f.sender -and $f.ticket_id) {
    $null = Connect-Psa -Psa (Get-PsaType $f.psa)
    $t = Get-PsaTicket -Id $f.ticket_id
    $text = "$($t.summary)`n$($t.description)"
    if ($text -match '(?im)^\s*Message-ID:\s*(<[^>\s]+>)') { $f.message_id = $Matches[1] }
    if ($text -match '(?im)^\s*From:\s*[^\r\n]*?<?([^<>\s:]+@[^<>\s]+?)>?\s*$') { $f.sender = $Matches[1] }
    if ($text -match '(?im)^\s*Subject:\s*(.+?)\s*$') { $f.subject = $Matches[1] }
    if (-not $f.subject -and $t.summary) { $f.subject = ($t.summary -replace '^(?i)\s*((fw|fwd|re)\s*:\s*)+', '').Trim() }
    $null = $actions.Add("Read ticket $($f.ticket_id) to find the reported email.")
}
if (-not $f.message_id -and -not $f.subject -and -not $f.sender) { Stop-Report 'incomplete' 'There is nothing to find the email by. Send message_id (the Internet Message-ID), or subject and sender.' $f.ticket_id }

$null = $actions.Add("Read the report from $($f.reporter_upn).")
Set-NodeOutput ([ordered]@{
        status = 'ok'; request = $f; request_json = ($f | ConvertTo-Json -Compress)
        message = "Report read from $($f.reporter_upn)$(if (-not $f.confirm) { ' (preview only: confirm is false)' })."
        actions = @($actions); warnings = @($warnings)
    })
