# === NODE: Open or update the ticket ===
# Takes the email facts, the AI classification (or the rules score when the AI answer is missing or
# unreadable) and writes the findings to the PSA as an internal note: on a new categorized ticket, or on
# the ticket the report came with. Six PSAs through _shared/psa.ps1.
# When the email looks malicious, the note carries a DRAFT tenant-wide search-and-purge for a technician
# to review and run. This workflow never runs it, and never deletes or moves any email.
# confirm=false (the default) returns a preview and writes nothing.
# >>> _shared/plan.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/plan.ps1
# >>> _shared/psa.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/psa.ps1
# >>> _shared/psa-tickets.ps1 (generated by _shared/inject.js; edit the source, not this block)
# <<< _shared/psa-tickets.ps1
$ErrorActionPreference = 'Stop'

function Read-Json { param($v) if ($null -eq $v) { return $null }; if ($v -is [string]) { if (-not $v.Trim()) { return $null }; try { return ($v | ConvertFrom-Json) } catch { return $null } }; return $v }
$stopState = @{ done = $false }
function Stop-Ticket {
    param([string]$Status, [string]$Why, [string]$TicketId = '')
    $stopState.done = $true
    Set-NodeOutput ([ordered]@{
            status = $Status; message = $Why
            public_note = 'Thanks for reporting this email. A technician will follow up.'
            internal_note = "Phishing report triage did not write to the PSA: $Why"
            ticket_id = $TicketId; actions = @(); warnings = @()
        })
    throw $Why
}
trap { if (-not $stopState.done) { $stopState.done = $true; Set-NodeOutput ([ordered]@{ status = 'error'; message = [string]$_.Exception.Message; public_note = 'Thanks for reporting this email. A technician will follow up.'; internal_note = "Phishing report triage failed while writing to the PSA: $($_.Exception.Message)"; ticket_id = ''; actions = @(); warnings = @() }) }; break }

# Inputs come through the step's parameters (bound to the enrich and classify outputs).
$e = Read-Json (Get-NodeInput -Name 'enrichment')
$req = Read-Json (Get-NodeInput -Name 'request')
$rules = Read-Json (Get-NodeInput -Name 'rules')
$aiRaw = Get-NodeInput -Name 'classification'
if ($null -eq $e -or $null -eq $req) { Stop-Ticket 'error' 'The email facts from the lookup step are missing. Run the workflow from the start.' }
$warnings = New-Object System.Collections.ArrayList
$actions = New-Object System.Collections.ArrayList
foreach ($w in @(Read-Json (Get-NodeInput -Name 'warnings_json'))) { if ($w) { $null = $warnings.Add([string]$w) } }

$confirm = (Get-PsaProp $req 'confirm') -eq $true -or @('true', 'yes', '1') -contains ([string](Get-PsaProp $req 'confirm')).ToLowerInvariant()
$ticketId = [string](Get-PsaProp $req 'ticket_id')
$found = (Get-PsaProp $e 'found') -eq $true

# ---- the verdict: AI first, rules when the AI answer is missing or unreadable ----
$sev = @{ 'likely-safe' = 0; 'suspicious' = 1; 'malicious' = 2 }
$rulesVerdict = [string](Get-PsaProp $rules 'verdict'); if (-not $rulesVerdict) { $rulesVerdict = $(if ($found) { 'suspicious' } else { 'unknown' }) }
$rulesConf = 0.0; try { $rulesConf = [double](Get-PsaProp $rules 'confidence') } catch { }
$ai = $null
$aiText = [string]$aiRaw
if ($aiRaw -and $aiRaw -isnot [string]) { $ai = $aiRaw }
elseif ($aiText -match '(?s)\{.*\}') { try { $ai = $Matches[0] | ConvertFrom-Json } catch { $ai = $null } }
$verdict = ''; $confidence = 0.0; $reasons = @(); $by = 'rules'
if ($null -ne $ai) {
    $v = ([string](Get-PsaProp $ai 'verdict')).Trim().ToLowerInvariant()
    $cRaw = Get-PsaProp $ai 'confidence'; $cOk = $false; $cVal = 0.0
    try { $cVal = [double]$cRaw; $cOk = ($null -ne $cRaw -and $cVal -ge 0 -and $cVal -le 1) } catch { }
    if ($sev.ContainsKey($v) -and $cOk) {
        $verdict = $v; $confidence = [Math]::Round($cVal, 2); $by = 'ai'
        $reasons = @(@(Get-PsaProp $ai 'reasons') | Where-Object { $_ } | ForEach-Object { ([string]$_).Trim() } | Select-Object -First 8)
    }
}
if (-not $verdict) {
    if ($aiText.Trim()) { $null = $warnings.Add('The AI classification could not be read, so the rules score was used.') } else { $null = $warnings.Add('The AI classification was empty, so the rules score was used.') }
    $verdict = $rulesVerdict; $confidence = $rulesConf
    $reasons = @(@(Get-PsaProp $e 'flags') | Where-Object { $_ } | Select-Object -First 8)
}
elseif ($found -and $sev.ContainsKey($rulesVerdict) -and [Math]::Abs($sev[$verdict] - $sev[$rulesVerdict]) -eq 2) {
    $null = $warnings.Add("The AI said $verdict but the rules said $rulesVerdict, so it was marked suspicious for a person to decide.")
    $verdict = 'suspicious'
}
if (-not $found) { $verdict = 'unknown'; $confidence = 0.0; $by = 'not-found'; $reasons = @('The email could not be found in the reporter''s mailbox, so it was not checked.') }

$priority = switch ($verdict) { 'malicious' { 'high' } 'likely-safe' { 'low' } default { 'medium' } }
$label = switch ($verdict) { 'malicious' { 'Malicious' } 'suspicious' { 'Suspicious' } 'likely-safe' { 'Likely safe' } default { 'Not found' } }

# ---- the draft purge (never run here) ----
$from = [string](Get-PsaProp $e 'from_address')
$subject = [string](Get-PsaProp $e 'subject')
$imid = [string](Get-PsaProp $e 'internet_message_id')
# Dates can come back from JSON as DateTime values; keep one UTC date and show it plainly.
$rcvRaw = Get-PsaProp $e 'received'
$rcvAt = $null
if ($rcvRaw -is [datetime]) { $rcvAt = $rcvRaw.ToUniversalTime() }
elseif ($rcvRaw) { try { $rcvAt = [datetime]::Parse([string]$rcvRaw, [Globalization.CultureInfo]::InvariantCulture, [Globalization.DateTimeStyles]::AdjustToUniversal) } catch { } }
$received = if ($rcvAt) { $rcvAt.ToString('yyyy-MM-dd HH:mm') + ' UTC' } else { [string]$rcvRaw }
$purge = ''
if ($verdict -eq 'malicious' -and $from) {
    # KQL and PowerShell quoting: drop double quotes from the subject, double the single quotes.
    $kqlSubject = ($subject -replace '["\r\n\t]', ' ' -replace '\s+', ' ').Trim()
    if ($kqlSubject.Length -gt 120) { $kqlSubject = $kqlSubject.Substring(0, 120) }
    $day = (Get-Date).ToUniversalTime()
    if ($rcvAt) { $day = $rcvAt }
    $kql = "(From:$from)"
    if ($kqlSubject) { $kql += " AND (Subject:`"$kqlSubject`")" }
    $kql += " AND (Received:$($day.AddDays(-2).ToString('yyyy-MM-dd'))..$($day.AddDays(2).ToString('yyyy-MM-dd')))"
    $kqlPs = $kql.Replace("'", "''")
    $name = "Phish-$($day.ToString('yyyyMMdd'))-$(([guid]::NewGuid().ToString('N')).Substring(0, 6))"
    $purge = @"
DRAFT ONLY. This was not run. Review the search results before purging.
Run in Exchange Online PowerShell as someone with the Compliance Search and Search And Purge roles:

Connect-IPPSSession
New-ComplianceSearch -Name '$name' -ExchangeLocation All -ContentMatchQuery '$kqlPs'
Start-ComplianceSearch -Identity '$name'
Get-ComplianceSearch -Identity '$name' | Format-List Name,Status,Items,SuccessResults
# Check the item count and the mailboxes in SuccessResults. If they look right:
New-ComplianceSearchAction -SearchName '$name' -Purge -PurgeType SoftDelete
Get-ComplianceSearchAction -Identity '$($name)_Purge' | Format-List Status,Results

The query matches the sender, the subject and two days either side of when it arrived. To narrow it to this one message, its Internet Message-ID is $imid. A purge removes at most 10 items per mailbox per run; SoftDelete moves them to Recoverable Items, so they can still be restored during the retention period.
"@
}

# ---- the note, in plain sentences ----
$auth = Get-PsaProp $e 'auth'
$links = Get-PsaProp $e 'links'
$atts = @(Get-PsaProp $e 'attachments' | Where-Object { $null -ne $_ })
$reporter = [string](Get-PsaProp $e 'reporter')
$lines = New-Object System.Collections.ArrayList
$null = $lines.Add("Phishing report from $reporter. Verdict: $label$(if ($verdict -ne 'unknown') { " ($([int]($confidence * 100))% confidence, decided by $(if ($by -eq 'ai') { 'the AI classification' } else { 'the rules score' }))" }).")
if ($found) {
    $fromName = [string](Get-PsaProp $e 'from_name')
    $fromText = if ($fromName) { "$fromName <$from>" } else { $from }
    $null = $lines.Add("The email came from $fromText with the subject '$subject', received $received.")
    if ((Get-PsaProp $auth 'header_present') -eq $true) { $null = $lines.Add("Authentication: SPF $(Get-PsaProp $auth 'spf'), DKIM $(Get-PsaProp $auth 'dkim'), DMARC $(Get-PsaProp $auth 'dmarc'), Microsoft composite auth $(Get-PsaProp $auth 'compauth').") }
    $rt = @(Get-PsaProp $e 'reply_to'); if ($rt.Count -and $rt[0]) { $null = $lines.Add("Replies go to $($rt -join ', ').") }
    $null = $lines.Add("It has $(Get-PsaProp $links 'count') link(s)$(if (@(Get-PsaProp $links 'domains').Count) { " to $(@(Get-PsaProp $links 'domains') -join ', ')" }). Safe Links wrappers were removed before checking.")
    if ($atts.Count) { $null = $lines.Add("Attachments: $(@($atts | ForEach-Object { "$(Get-PsaProp $_ 'name')$(if (Get-PsaProp $_ 'risk') { " ($(Get-PsaProp $_ 'risk'))" })" }) -join ', ').") } else { $null = $lines.Add('It has no attachments.') }
    $fl = @(Get-PsaProp $e 'flags' | Where-Object { $_ })
    if ($fl.Count) { $null = $lines.Add("Warning signs: $($fl -join ' ')") } else { $null = $lines.Add('No warning signs were found in the headers, links or attachments.') }
    if ($reasons.Count -and $by -eq 'ai') { $null = $lines.Add("Why the AI decided this: $($reasons -join ' ')") }
    $samples = @(Get-PsaProp $links 'samples' | Where-Object { $_ })
    if ($samples.Count) { $null = $lines.Add("Links (defanged, do not click): $($samples -join ' , ')") }
}
else {
    $null = $lines.Add("The email could not be found in the reporter's mailbox, so nothing about it was checked. Ask the reporter to forward it as an attachment, or search for it in Defender.")
}
$null = $lines.Add("Rules score: $(Get-PsaProp $rules 'score') ($rulesVerdict).")
$null = $lines.Add([string](Get-PsaProp $e 'other_recipients'))
foreach ($w in $warnings) { $null = $lines.Add("Note: $w") }
switch ($verdict) {
    'malicious' { $null = $lines.Add('Next steps: confirm the verdict, run the draft search below and review it, then purge. Block the sender and the link domains, and check whether anyone clicked or replied. Nothing was deleted automatically.') }
    'suspicious' { $null = $lines.Add('Next steps: a technician should review the email before deciding. No purge was drafted because it was not judged malicious.') }
    'likely-safe' { $null = $lines.Add('Next steps: if a technician agrees it is safe, tell the reporter and close the ticket.') }
}
if ($purge) { $null = $lines.Add(''); $null = $lines.Add($purge) }
$note = ($lines -join "`n")

# ---- the PSA write, behind confirm ----
$psa = Get-PsaType ([string](Get-PsaProp $req 'psa'))
if (-not $psa) { Stop-Ticket 'incomplete' 'No PSA is set up. Add the PSA-Type secret, or send psa in the request.' $ticketId }
$null = Connect-Psa -Psa $psa
$companyId = [string](Get-PsaProp $req 'psa_company_id')
$companyName = [string](Get-PsaProp $req 'company_name')
if ($companyId -and $companyId -notmatch '^\d+$') {
    # CloudRadial's @CompanyPsaId can be a name or identifier; treat a non-number as a name.
    if (-not $companyName) { $companyName = $companyId }
    $companyId = ''
}
# Retry guard: the findings note carries a marker made from the reported email (a short hash of its
# Internet Message-ID, or of the report details when it wasn't found; never a name or address), so a
# ServiceAI Retry adds nothing twice. Without a ticket id, a confirm run first looks for a ticket an earlier
# run of this same report already opened, and reuses it instead of opening a second one.
$keySrc = if ($imid) { $imid } else { "$reporter|$([string](Get-PsaProp $req 'message_id'))|$subject|$([string](Get-PsaProp $req 'sender'))" }
$prSha = [System.Security.Cryptography.SHA256]::Create()
try { $prKey = (-join ($prSha.ComputeHash([Text.Encoding]::UTF8.GetBytes($keySrc.ToLowerInvariant())) | ForEach-Object { $_.ToString('x2') })).Substring(0, 8) } finally { $prSha.Dispose() }
$noteMarker = "phishing-report-triage: $prKey"
$reused = ''
# The new ticket id is kept here so the note step can use it (a hashtable, changed in place).
$holder = @{ id = $ticketId }
$plan = New-ChangePlan "Phishing report from $reporter"
if ($ticketId) {
    $t = Get-PsaTicket -Id $ticketId
    if ($companyId -and $t.companyId -and $t.companyId -ne $companyId) { Stop-Ticket 'rejected' "Ticket $ticketId belongs to company $($t.companyId) in $(Get-PsaName), not company $companyId. Nothing was written, to keep one client's findings off another client's ticket." $ticketId }
    Add-PlannedChange $plan "Add the findings as an internal note on ticket $ticketId" { param($id, $text, $mk) Add-PsaNote -Id $id -Text $text -Title 'Phishing report triage' -Marker $mk } -Arguments @($ticketId, $note, $noteMarker)
}
else {
    if (-not $companyId) {
        if (-not $companyName) { Stop-Ticket 'incomplete' 'There is no ticket id and no company to open a ticket for. Send psa_company_id or company_name.' }
        $co = @(Find-PsaCompany -Name $companyName)
        $exact = @($co | Where-Object { $_.exact })
        if ($exact.Count -ne 1) { Stop-Ticket 'incomplete' "$(if ($exact.Count) { "$($exact.Count) companies" } else { 'No company' }) in $(Get-PsaName) exactly match '$companyName'. Send psa_company_id instead." }
        $companyId = [string]$exact[0].id
    }
    $summarySubject = if ($subject) { $subject } else { [string](Get-PsaProp $req 'subject') }
    if ($summarySubject.Length -gt 60) { $summarySubject = $summarySubject.Substring(0, 60) + '...' }
    $summary = "Phishing report ($label): $summarySubject"
    $subjText = if ($summarySubject) { " with the subject '$summarySubject'" } else { '' }
    $desc = "$reporter reported a suspected phishing email$subjText. The findings are in the internal notes."
    $queue = [string](Get-PsaProp $req 'psa_queue')
    if ($confirm) {
        # A retry of a run that already opened the ticket: an open ticket for this company from the last 3 days,
        # titled as this workflow titles them, that holds this report's marker. A failed lookup is a warning and
        # a new ticket is opened, because a missing phishing ticket is worse than a duplicate.
        try {
            foreach ($prev in @(Find-PsaTickets -CompanyId $companyId -Open -CreatedAfter ((Get-Date).ToUniversalTime().AddDays(-3)) -Text 'Phishing report' -Max 50 -Order newest)) {
                if (Test-PsaNoteMarker -Id ([string]$prev.id) -Marker $noteMarker) { $reused = [string]$prev.id; break }
            }
        }
        catch { $null = $warnings.Add("Couldn't check for a ticket an earlier run of this report already opened, so a new one was opened: $($_.Exception.Message)") }
    }
    if ($reused) {
        $holder.id = $reused
        Add-PlannedChange $plan "Add the findings as an internal note on ticket $reused (opened by an earlier run of this report)" { param($id, $text, $mk) Add-PsaNote -Id $id -Text $text -Title 'Phishing report triage' -Marker $mk } -Arguments @($reused, $note, $noteMarker)
    }
    else {
        Add-PlannedChange $plan "Open a $priority priority ticket: $summary" { param($cid, $s, $d, $p, $q) $r = New-PsaTicket -CompanyId $cid -Summary $s -Description $d -Priority $p -Queue $q; $holder.id = $r.id; return "ticket $($r.id)" } -Arguments @($companyId, $summary, $desc, $priority, $queue)
        Add-PlannedChange $plan 'Add the findings as an internal note on the new ticket' { param($text, $mk) Add-PsaNote -Id $holder.id -Text $text -Title 'Phishing report triage' -Marker $mk } -Arguments @($note, $noteMarker)
    }
}
$result = Invoke-ChangePlan $plan -Confirm $confirm
foreach ($a in @(Get-PsaProp $result 'ran')) {
    if (-not $a) { continue }
    $ranText = [string](Get-PsaProp $a 'description')
    if ([string](Get-PsaProp $a 'output') -eq 'already-present') { $ranText += ': it was already there, so it was not added again' }
    $null = $actions.Add($ranText)
}

$outTicket = [string]$holder.id
$status = switch ([string](Get-PsaProp $result 'status')) { 'preview' { 'pending_confirmation' } 'done' { 'success' } 'failed' { 'error' } default { 'incomplete' } }
$msg = switch ($status) {
    'pending_confirmation' { "Preview: the reported email is $($label.ToLowerInvariant()). Nothing was written to $(Get-PsaName). Run again with confirm=true to $(if ($ticketId) { "note ticket $ticketId" } else { 'open the ticket' })." }
    'success' { "The reported email is $($label.ToLowerInvariant()). $(if ($ticketId) { "Ticket $outTicket has" } elseif ($reused) { "Ticket $outTicket, opened by an earlier run of this report, has" } else { "Ticket $outTicket was opened with" }) the findings$(if ($purge) { ' and a draft purge for a technician to review' })." }
    default { "Writing to $(Get-PsaName) failed: $(Get-PsaProp $result 'message')" }
}
$public = switch ($verdict) {
    'malicious' { 'Thanks for reporting this email. It looks malicious, so please delete it and do not click its links or open its attachments. Our team is handling it.' }
    'likely-safe' { 'Thanks for reporting this email. It looks safe at first check, and a technician will confirm.' }
    default { 'Thanks for reporting this email. Our team is reviewing it. Until then, please do not click its links or open its attachments.' }
}
$out = [ordered]@{
    status = $status; message = $msg; public_note = $public; internal_note = $note
    ticket_id = $outTicket; psa = $psa
    verdict = $verdict; confidence = $confidence; reasons = @($reasons); classified_by = $by
    rules_score = (Get-PsaProp $rules 'score'); purge_drafted = [bool]$purge
    planned = @(Get-PsaProp $result 'planned'); actions = @($actions); warnings = @($warnings)
    chatReply = $msg
}
Set-NodeOutput $out
if ($status -eq 'error') { $stopState.done = $true; throw $msg }
